Tau DQM code relocation from Validation/RecoTau area
cms-sw/cmssw pull request #15744
Opened 2016-09-06 12:01 UTC by amodakgit

Following the proposal from RECO group, the data certification related Tau DQM code is now moved from **Validation/RecoTau** to  **DQMOffline/PFTau** package. The idea is to separate the genuine data certification code related to Tau DQM from mc validation which is in the Validation/RecoTau package. Common part of the data & mc code are kept in the DQMOffline/PFTau and will also be used by mc validation.
These changes have been approved by TauPOG and you can see the slides here for more details,
https://indico.cern.ch/event/565857/contributions/2285741/attachments/1328124/1994864/TauDQM_29Aug16.pdf

cc: @roger-wolf

2016-09-06 12:02 UTC, cmsbuild commented
A new Pull Request was created by  @amodakgit (Atanu Modak) for CMSSW_8_1_X.

It involves the following packages:

DQMOffline/Configuration
DQMOffline/PFTau
Validation/RecoTau


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@threus, @rociovilar this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are list here cms-sw/cmssw#13028

2016-09-16 14:24 UTC, dmitrijus commented on Validation/RecoTau/src/TauTagMCValidation.cc
> +    std::cerr << " Reference collection: " << refCollection_ << " not found while running TauTagMCValidation.cc " << std::endl;
Please replace std:cerr with LogWarning. Rule of thumb: never use std:cout/cerr in CMSSW.

2016-09-16 14:25 UTC, dmitrijus requested changes

2016-09-16 15:35 UTC, amodakgit commented on Validation/RecoTau/src/TauTagMCValidation.cc
> +    std::cerr << " Reference collection: " << refCollection_ << " not found while running TauTagMCValidation.cc " << std::endl;
thanks for the suggestion. it is now corrected.

2016-09-23 12:15 UTC, dmitrijus commented
+1

2016-09-23 12:16 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-09-23 12:16 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_8_1_X IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-09-23 15:54 UTC, cmsbuild commented
-1

Tested at: b101ebff6b260833975048e5b44c9b0b1de23dbf

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15744/15362/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
5.1 step1
<pre>runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS/step1_TTbar+TTbarFS+HARVESTFS.log

</pre>135.4 step1
<pre>runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

</pre>

2016-09-27 15:20 UTC, dmitrijus commented
please test

2016-09-27 15:20 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-09-27 18:28 UTC, cmsbuild commented
-1

Tested at: b101ebff6b260833975048e5b44c9b0b1de23dbf

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15744/15401/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
5.1 step1
<pre>runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS/step1_TTbar+TTbarFS+HARVESTFS.log

</pre>135.4 step1
<pre>runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

</pre>

2016-10-27 12:36 UTC, davidlange6 commented
Hi @amodakgit - any plans to update this PR?

2016-10-27 15:35 UTC, amodakgit commented
Hi David,

Still facing some issues to validate the fix. But hopefully will converge
by next week.

thanks,
atanu


________________________________
From: David Lange [notifications@github.com]
Sent: 27 October 2016 18:06
To: cms-sw/cmssw
Cc: Atanu Modak; Mention
Subject: Re: [cms-sw/cmssw] Tau DQM code relocation from Validation/RecoTau area (#15744)


Hi @amodakgit<https://github.com/amodakgit> - any plans to update this PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/15744#issuecomment-256628848>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AFU8BcF2hpC3uLB9e4eg5_OhIxMjiE1pks5q4JrogaJpZM4J1ws8>.

2016-11-17 16:07 UTC, davidlange6 commented
lets resume this PR review in 90x once it is updated.

2016-11-17 16:07 UTC, closed without merging