SMP DQM codes updated after fixing the bug
cms-sw/cmssw pull request #15954
Opened 2016-09-22 13:39 UTC by gwalia

2016-09-22 13:39 UTC, cmsbuild commented
A new Pull Request was created by  @gwalia  for CMSSW_8_1_X.

It involves the following packages:

DQM/Physics


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@rappoccio this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are list here cms-sw/cmssw#13028

2016-09-23 11:29 UTC, dmitrijus commented on DQM/Physics/src/EwkMuDQM.cc
> +     std::cout  << ">>> Muon collection does not exist !!!" << std::endl;
std::cout is thread unsafe!
Please go back to using LogWarning.

2016-09-23 11:31 UTC, dmitrijus requested changes

2016-09-23 11:34 UTC, dmitrijus commented
Please run, `clang-format -i --style=Google` on the cpp files and review the changes you have made.
It is barely readable: lots of if-statements don't have properly matching brackets.

2016-09-23 11:37 UTC, gwalia commented
thanks for the comments, we will update the code with the changes suggested.

2016-10-05 06:38 UTC, cmsbuild commented
Pull request #15954 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2016-10-11 14:13 UTC, dmitrijus commented
It is still messy and barely readable code.
If you do a clang format - it should go as a separate commit, before applying your own changes.

2016-10-25 15:33 UTC, fabozzi commented
Hi Genius, is it possible to move on with this PR?

2016-10-25 18:46 UTC, gwalia commented
Hi,
   There were few indentation changes suggested by Dmitrijus Bugelskis and we made a new pull request (PR #16322) with the updated codes.

Thanks,
Genius
________________________________
From: fabozzi [notifications@github.com]
Sent: 25 October 2016 21:03
To: cms-sw/cmssw
Cc: Genius Walia; Mention
Subject: Re: [cms-sw/cmssw] SMP DQM codes updated after fixing the bug (#15954)


Hi Genius, is it possible to move on with this PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/15954#issuecomment-256070747>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AE8PWC_y6EOIbnrLB8aWmxVm0ABNUknbks5q3iE3gaJpZM4KD5tI>.

2016-10-28 13:45 UTC, dmitrijus commented
please close this PR

2017-03-23 09:46 UTC, closed without merging