SMP DQM codes
cms-sw/cmssw pull request #16322
Opened 2016-10-24 06:39 UTC by sasharma6

"After removing the trigger part and after indentation"

2016-10-24 06:39 UTC, cmsbuild commented
A new Pull Request was created by  @sasharma6  for CMSSW_8_1_X.

It involves the following packages:

DQM/Physics


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@rappoccio this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2016-10-28 13:47 UTC, dmitrijus commented
Please set the proper title and the detailed description.
For example, such as in this pull request: https://github.com/cms-sw/cmssw/pull/15830

2016-11-03 05:16 UTC, sasharma6 commented
Hi Dmitrijus,

I have added the information for PR#16322. Kindly have a look.

Thanks and regards
Sandeep

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Oct 28, 2016 at 7:18 PM +0530, "Dmitrijus" <notifications@github.com<mailto:notifications@github.com>> wrote:


Please set the proper title and the detailed description.
For example, such as in this pull request: #15830<https://github.com/cms-sw/cmssw/pull/15830>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/16322#issuecomment-256924359>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ATMpCvxwiCUt1RqJiBUvN_LLKajMrabGks5q4f0IgaJpZM4KecS6>.

2017-01-17 15:39 UTC, dmitrijus requested changes
Looks much better than previous pull requests.
One major issue is that thread-unsafe std::cout is used. It should be converted into LogWarning (where appropriate). 

Please make a PR to 90x with std::cout removed.
Once it is *merged*, you will be able to submit backports to other branches. However, it is much easier to keep 1 PR for all the discussions.

In general, you should edit the PR instead of making a new for every single change (there is an 'edit' button).

2017-01-17 15:39 UTC, dmitrijus commented on DQM/Physics/src/EwkElecDQM.cc
> +    LogVerbatim("") << "\n>>>>>> SELECTION SUMMARY BEGIN >>>>>>>>>>>>>>>";
Why does this use LogVerbatim? Why not LogWarning?

2017-01-17 15:39 UTC, dmitrijus commented on DQM/Physics/src/EwkElecDQM.cc
> +        std::cout << ">>> No beam spot found !!!";
No std::cout or std::cerr!

2017-01-17 15:39 UTC, dmitrijus commented on DQM/Physics/src/EwkElecDQM.cc
> +                std::cout << "\t... detain value " << detain << " (barrel), pass? " << electron_sel[3];
std::cout used again!

2017-01-17 15:39 UTC, dmitrijus commented on DQM/Physics/src/EwkMuDQM.cc
> +        std::cout << ">>> Muon collection does not exist !!!" << std::endl;
!

2017-01-17 15:39 UTC, dmitrijus commented on DQM/Physics/src/EwkMuDQM.cc
> +        std::cout << ">>> No beam spot found !!!" << std::endl;
!

2017-02-11 10:48 UTC, cmsbuild commented
Pull request #16322 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-11 10:53 UTC, cmsbuild commented
Pull request #16322 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-15 15:29 UTC, dmitrijus commented
Please close this PR. And the other one in 81x.
Your main target is the upstream branch - 90x - https://github.com/cms-sw/cmssw/pull/16630
The PR there has a merge conflict, I cannot start the tests. Fix it and I will start the tests.

2017-02-18 16:50 UTC, closed without merging