scouting code updated
cms-sw/cmssw pull request #16368
Opened 2016-10-27 12:00 UTC by swagata87

2016-10-27 12:00 UTC, cmsbuild commented
A new Pull Request was created by  @swagata87 (Swagata Mukherjee) for CMSSW_8_1_X.

It involves the following packages:

DataFormats/Scouting
HLTrigger/JetMET
HLTrigger/Muon


@perrotta, @smuzaffar, @Dr15Jones, @silviodonato, @Martin-Grunewald, @cmsbuild, @fwyzard, @davidlange6 can you please review it and eventually sign? Thanks.
@battibass, @abbiendi, @jhgoh, @Martin-Grunewald, @calderona, @HuguesBrun, @trocino this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2016-10-27 12:02 UTC, silviodonato commented
please test

2016-10-27 12:02 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-10-27 13:24 UTC, cmsbuild commented
+1
Tested at: 0c75103ee145ace84dcf6e11836d3243e2f09a19
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16368/16009/summary.html

2016-10-27 13:24 UTC, cmsbuild commented
Comparison job queued.

2016-10-27 14:01 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16368/16009/summary.html

The workflows 1003.0, 1001.0, 1000.0, 140.53, 136.731, 4.22 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

2016-10-27 16:51 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16368/16009/summary.html

2016-10-27 19:12 UTC, Dr15Jones requested changes

2016-10-27 19:12 UTC, Dr15Jones commented on DataFormats/Scouting/interface/ScoutingMuon.h
> +	      float trk_lambdaError, float trk_phiError, float trk_dsz, float trk_dszError, std::vector<int> vtxIndx):
Better to change to `std::vector<int> const& vtxIndx`

2016-10-27 19:12 UTC, Dr15Jones commented on HLTrigger/Muon/src/HLTScoutingMuonProducer.cc
> +    vtxInd.clear();
There is no need to call `clear` hear since `vtxInd` is guaranteed to be empty at this point.

2016-10-27 19:12 UTC, Dr15Jones commented on HLTrigger/Muon/src/HLTScoutingMuonProducer.cc
> +      double ecalisopf=-99.0;
Would be better to do 
```
double ecalisopf=-1.0;
if( EcalPFClusterIsoMap.isValid()) { ecalisopf = (*EcalPFClusterIsoMap)[muonRef]; }
```
this avoids setting a value to `ecalisopf` and then immediately reassigning the value.

2016-10-27 19:12 UTC, Dr15Jones commented on HLTrigger/Muon/src/HLTScoutingMuonProducer.cc
> +      else hcalisopf = (*HcalPFClusterIsoMap)[muonRef];
The same change should be made here.

2016-10-27 19:12 UTC, Dr15Jones commented on HLTrigger/Muon/src/HLTScoutingMuonProducer.cc
> +	float dr2_2 = reco::deltaR2( ((vtxMuPair.at(i)).second),muon );
There is no need to use `at()` here since you know you are within the allowed indicies. Better to use `vtxMuPair[i]` which is faster.

2016-10-27 19:12 UTC, Dr15Jones commented on HLTrigger/Muon/src/HLTScoutingMuonProducer.cc
> +    vtxMuPair.clear();
No need to call `clear` here.

2016-10-28 14:22 UTC, cmsbuild commented
Pull request #16368 was updated. @perrotta, @smuzaffar, @Dr15Jones, @silviodonato, @Martin-Grunewald, @cmsbuild, @fwyzard, @davidlange6 can you please check and sign again.

2016-10-31 13:26 UTC, Martin-Grunewald commented
please test

2016-10-31 13:27 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-10-31 18:21 UTC, cmsbuild commented
+1
Tested at: b0225a040308669f0d6d676a4571a7e7eaa1d58c
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16368/16093/summary.html

2016-10-31 18:21 UTC, cmsbuild commented
Comparison job queued.

2016-10-31 19:15 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16368/16093/summary.html

2016-11-01 16:48 UTC, Dr15Jones commented
+1

2016-11-04 12:07 UTC, Martin-Grunewald commented
+1

2016-11-04 12:08 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_8_1_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-11-05 08:18 UTC, davidlange6 commented
Hi @swagata87 is there a summary of the reason for and impact (on size per event) of this change to scouting?

2016-11-06 05:32 UTC, swagata87 commented
A search for dark-photon has been planned, where the dark-photon decays to prompt or displaced muon-pair of low pT. For this search, a primary vertex collection and displaced vertex collection is needed to be saved, along with the muons, for each event. This has motivated the changes in scouting code. Muon and vertex information are added to ScoutingCalo event content. Event size increases from ~1.5 KB to ~2.7 KB. Some more relevant information can be found in this presentation : https://indico.cern.ch/event/574632/contributions/2325114/attachments/1349671/2036802/ScoutingOct6.pdf

2016-11-06 09:06 UTC, fwyzard commented
hold

To be reviewed and approved by Trigger Coordination.

2016-11-06 09:06 UTC, cmsbuild commented
Pull request has been put on hold by  @fwyzard
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2016-11-06 20:17 UTC, swagata87 commented
Adding more to my previous comment, till now muons are only part of the PF-scouting event content, so now only the PF-scouting event size will increase. The addition of the muons to the calo-scouting event content is expected to happen later when we introduce the new dimuon scouting trigger[*] into the HLT menu. 
[*] Available in confdb under /users/swmukher/test_scouting_muon/

2016-11-10 13:47 UTC, fwyzard commented
hi @swagata87 ,
can I ask for a presentation at one of the upcoming TSG meetings, to review the impact on the HLT timing, rates, and stream size ?
I checked the talk linked above, and it's not clear to me what the actual impact is going to be.

Normally I would have no objections to presenting the request and results after the code has been integrted and made available to the studies - but the changes to the dataformats are a bit more delicate.

2016-11-16 10:09 UTC, davidlange6 commented
for 90x.

2016-11-16 10:09 UTC, closed without merging