merging PRs 16513 and 15748 & EMTF cancel tracks by LCT, as in firmware.
cms-sw/cmssw pull request #16654
Opened 2016-11-16 10:57 UTC by EsmaeelEskandari

2016-11-16 10:57 UTC, cmsbuild commented
A new Pull Request was created by  @EsmaeelEskandari  for CMSSW_8_0_X.

It involves the following packages:

DQM/L1TMonitor
DQM/L1TMonitorClient
L1Trigger/L1TMuonEndCap


@dmitrijus, @cmsbuild, @rekovic, @vanbesien, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2016-11-18 07:49 UTC, thomreis requested changes
Please consider these changes in order to avoid the ProductNotFound exception after the switch to the most up to date EMTF emulator.

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
>        muonToken(consumes<l1t::RegionalMuonCandBxCollection>(ps.getParameter<edm::InputTag>("emtfSource"))),
To fix the ProductNotFound error every token should have its own InputTag in order to choose different instance names. They should not use all `emtfSource`.

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/src/L1TdeStage2EMTF.cc
>        monitorDir(ps.getUntrackedParameter<std::string>("monitorDir", "")),
To fix the ProductNotFound error every token should have its own InputTag in order to choose different instance names. They should not use all `emtfSource` and `dataSource`.

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/python/L1TStage2EMTFData_cfi.py
> +    emtfSource = cms.InputTag("emtfStage2Digis"),
Use different InputTags for the different collections you are going to use in the module to avoid ProductNotFound exceptions

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/python/L1TStage2EMTFEmul_cfi.py
> +    emtfSource = cms.InputTag("valEmtfStage2Digis", "EMTF"),
Use different InputTags for the different collections you are going to use in the module to avoid ProductNotFound exceptions

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/python/L1TStage2EMTF_cfi.py
>      emtfSource = cms.InputTag("emtfStage2Digis"),
Use different InputTags for the different collections you are going to use in the module to avoid ProductNotFound exceptions

2016-11-18 07:49 UTC, thomreis commented on DQM/L1TMonitor/src/L1TdeStage2EMTF.cc
>        monitorDir(ps.getUntrackedParameter<std::string>("monitorDir", "")),
Of course this must be also changed in the corresponding cfi file.

2016-12-15 13:34 UTC, thomreis commented
@EsmaeelEskandari can this one be closed? If yes please reference the superseding PR when closing.

2016-12-15 15:52 UTC, EsmaeelEskandari commented
Dear Thomas,

Thanks for reminding this.
I referenced and closed it.

Cheers,
Esmaeel.

On Thu, Dec 15, 2016 at 5:04 PM, Thomas Reis <notifications@github.com>
wrote:

> @EsmaeelEskandari <https://github.com/EsmaeelEskandari> can this one be
> closed? If yes please reference the superseding PR when closing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/16654#issuecomment-267328385>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGGyuR812frFQUgGYxNtOu08GkRztJEMks5rIUH2gaJpZM4KzszV>
> .
>

2016-12-15 15:52 UTC, closed without merging