Changes to disable DDU trigger plots in DT DQM Online Trigger checks …
cms-sw/cmssw pull request #16739
Opened 2016-11-23 08:58 UTC by jfernan2

…and disable check on RPC paths for TriggerEfficiency studies in DT DQM Offline. Port to 90X of PR 16679

2016-11-23 08:59 UTC, cmsbuild commented
A new Pull Request was created by  @jfernan2  for CMSSW_9_0_X.

It involves the following packages:

DQM/DTMonitorClient
DQM/DTMonitorModule


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2016-11-28 12:38 UTC, dmitrijus commented
+1

2016-11-28 12:38 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-11-28 12:38 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-11-28 16:34 UTC, cmsbuild commented
-1

Tested at: cd59556f61e0c9186460795f6ddd3f41180cdbc0

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16627/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
4.22 step2
<pre>runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

</pre>140.53 step2
<pre>runTheMatrix-results/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/step2_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI.log

</pre>8.0 step3
<pre>runTheMatrix-results/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/step3_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS.log

</pre>1306.0 step3
<pre>runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15/step3_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>1330.0 step3
<pre>runTheMatrix-results/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/step3_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>1000.0 step2
<pre>runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step2_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT.log

</pre>9.0 step3
<pre>runTheMatrix-results/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/step3_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST.log

</pre>25.0 step3
<pre>runTheMatrix-results/25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/step3_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT.log

</pre>1001.0 step2
<pre>runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step2_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log

</pre>136.731 step3
<pre>runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log

</pre>1003.0 step2
<pre>runTheMatrix-results/1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM/step2_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM.log

</pre>10021.0 step3
<pre>runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>50202.0 step3
<pre>runTheMatrix-results/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/step3_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50.log

</pre>20034.0 step3
<pre>runTheMatrix-results/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D1_GenSimHLBeamSpotFull14+DigiFull_2023D1+RecoFullGlobal_2023D1+HARVESTFullGlobal_2023D1/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D1_GenSimHLBeamSpotFull14+DigiFull_2023D1+RecoFullGlobal_2023D1+HARVESTFullGlobal_2023D1.log

</pre>10024.0 step3
<pre>runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>25202.0 step3
<pre>runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

</pre>21234.0 step3
<pre>runTheMatrix-results/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFull_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFull_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4.log

</pre>23234.0 step3
<pre>runTheMatrix-results/23234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D5_GenSimHLBeamSpotFull14+DigiFull_2023D5+RecoFullGlobal_2023D5+HARVESTFullGlobal_2023D5/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D5_GenSimHLBeamSpotFull14+DigiFull_2023D5+RecoFullGlobal_2023D5+HARVESTFullGlobal_2023D5.log

</pre>

2016-11-28 16:34 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2016-11-28 17:39 UTC, cmsbuild commented
Pull request #16739 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2016-11-29 12:37 UTC, dmitrijus commented
+1

2016-11-29 12:37 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-11-29 12:37 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-11-29 13:54 UTC, cmsbuild commented
-1

Tested at: c134746ecef690e68c2b9fa33382c88997ef4f65

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16649/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
8.0 step3
<pre>runTheMatrix-results/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/step3_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS.log

</pre>9.0 step3
<pre>runTheMatrix-results/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/step3_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST.log

</pre>

2016-11-29 13:54 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2016-11-29 20:24 UTC, cmsbuild commented
Pull request #16739 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2016-12-06 15:20 UTC, dmitrijus commented
+1

2016-12-06 15:20 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-12-06 15:20 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-12-06 17:27 UTC, cmsbuild commented
+1
Tested at: 0adab095c7ab58c0e8216aec876558441bb80127
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16809/summary.html

2016-12-06 17:27 UTC, cmsbuild commented
Comparison job queued.

2016-12-06 18:00 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16809/summary.html

The workflows 1003.0, 1001.0, 1000.0, 140.53, 136.731, 4.22 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

2016-12-07 00:12 UTC, davidlange6 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_cff.py
> +from EventFilter.L1TXRawToDigi.twinMuxStage2Digis_cfi import *
hi @jfernan2 -all of the changes in this file need to be moved into the EventFilter package itself. (and the unpackers go into the raw2digi step not the dqm one.

2016-12-07 09:03 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2016-12-07 09:03 UTC, jfernan2 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_cff.py
> +from EventFilter.L1TXRawToDigi.twinMuxStage2Digis_cfi import *
hi @davidlange6 
Done. Should I do the same to the equivalent 80X and 81X PR too?
Thanks

2016-12-07 17:55 UTC, cvuosalo commented
@cmsbuild please test

2016-12-07 17:55 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-12-07 19:43 UTC, cmsbuild commented
+1
Tested at: e3c42fd9bf302e6a0ee479544791c2655d15d962
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16842/summary.html

2016-12-07 19:43 UTC, cmsbuild commented
Comparison job queued.

2016-12-07 20:23 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/16842/summary.html

The workflows 1003.0, 1001.0, 1000.0, 140.53, 136.731, 4.22 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

2016-12-07 21:50 UTC, cvuosalo commented
@jfernan2: Please add to the PR description which DQM plots are being changed and how they should change. The Jenkins results show DQM plot changes that are a bit difficult to interpret.

Here are a few from workflow 	25202.0_TTbar_13 that show entries disappearing from one plot, entries being added to another, and efficiency dropping in yet another. It's hard to tell if this PR is working as intended.

![eff](https://cloud.githubusercontent.com/assets/5736159/20988024/832803fe-bc94-11e6-8d21-c69d40a60a2a.png)
![denum](https://cloud.githubusercontent.com/assets/5736159/20988022/83221ef8-bc94-11e6-9d19-29c4e7ba3976.png)
![phi](https://cloud.githubusercontent.com/assets/5736159/20988023/83275df0-bc94-11e6-95b9-1e7f6b997ffa.png)

2016-12-08 08:14 UTC, jfernan2 commented
@cvuosalo thanks for checking this!
I have added the description of the changes.
I believe the plots are fine, up to now were empty due to RPC filter, now they are filled if stats allow, for example in ZMuMu sample:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-12-07-0000+16739/17415/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/DT_03-LocalTrigger-TM_Task.html

The TTbar sample should not have many muon statistics, it could be fluctuations, however I'm not able to find the plots you point out for a deeper inspection in the Jenkins comparison. I do see this with entries now where there were no entries before:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-12-07-0000+16739/17415/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/DT_03-LocalTrigger-TM_Task.html

tanks

2016-12-08 16:56 UTC, cvuosalo commented
@jfernan2: You can find the DQM plots here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-12-07-0000+16739/17415/alternative-comparisons/
The workflows that show significant differences are: 4.22, 9.0, 25, 136.731, 140.53, 1000, 1330, 10021, 10024, 20034, 21234, 23234, 25202, and 50202.

You say TM_TrigEff plots are now filled. I see some getting filled, while others become empty. Here are examples of plots getting emptied from workflow 4.22_RunCosmics2011A (left is baseline, right is PR):

![moremisseff](https://cloud.githubusercontent.com/assets/5736159/21019041/c2e23c58-bd34-11e6-81b5-c626667ac516.png)
![misseff](https://cloud.githubusercontent.com/assets/5736159/21019040/c2dd0f3a-bd34-11e6-9e1a-41c2b2f8742a.png)

2016-12-09 17:13 UTC, cvuosalo commented
If there is no progress on this PR today (Friday), it will probably miss 900pre2.

2016-12-09 17:37 UTC, jfernan2 commented
Thanks, @cvuosalo but I'm working on demonstrating that the problem in the Cosmics workflow  is due to the RAW version of the data (2011), where the DDU was used. Now this PR is disabling the DDU due to the introduction of the TwinMux boards, that's why the baseline has non-empty histograms. I would suggest moving the Cosmic workflow in Jenkins test to 2016 Cosmic data for RAW data compatibility with phase I upgrades. 

In the other workflows I believe the differences are due to statistics though.
However I will not have the proofs until next week. Thanks.

2016-12-12 11:23 UTC, jfernan2 commented
@cvuosalo As I pointed out on Friday, I have run myself the 2011 Cosmics workflow over a large statistics sample (100k events) with the PR and produced the DQM file where you can see that there are no empty histograms.
- Root file: /afs/cern.ch/user/j/jfernan/work/public/DTDQM_Cosmics2011/DQM_V0001_R000160960__Global__CMSSW_X_Y_Z__RECO.root
- Uploaded to my DQM GUI: http://fanae43.geol.uniovi.es:8080/dqm/offline/start?runnr=160960;dataset=/Cosmics/Run2011A/DQMIO;sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=DT;size=M;root=DT/03-LocalTrigger-TM;focus=;zoom=no;

As I mentioned, the reason why the baseline has non-empty histograms while the PR does, is double: 2011 RAW data format included DDU (and RPC hits in trigger from it), which made populate the histograms with the DDU and RPC filter enabled, even with stats as low as 10 events (as the Jenkins test use).

In 2016, with the introduction of the TwinMux boards, all the DT DQM Offline plots in folder  DT / 03-LocalTrigger-TM are empty due tow these two facts above. You can check in the DQM Offline Gui in any decent Cosmic or Data run, e.g.:
https://goo.gl/fG722v

I'm pretty sure the PR is doing well, but I'm willing to perform any other test or workflow you consider the differences are salient with 10 event statitics, as Jenkins test is using. Nevertheless, for the future I'd suggest moving the Cosmics Jenkin test to a recent 2016 dataset as reference to avoid this kind of problems.

Thanks

2016-12-12 13:42 UTC, slava77 commented
can we use configuration changes only to preserve pre-2016 behavior?

If so, then this PR should use era feature and keep pre-2016
functionality in place.



On 12/12/16 3:23 AM, jfernan2 wrote:
> @cvuosalo <https://github.com/cvuosalo> As I pointed out on Friday, I
> have run myself the 2011 Cosmics workflow over a large statistics sample
> (100k events) with the PR and produced the DQM file where you can see
> that there are no empty histograms.
> 
>   * Root file:
>     /afs/cern.ch/user/j/jfernan/work/public/DTDQM_Cosmics2011/DQM_V0001_R000160960__Global__CMSSW_X_Y_Z__RECO.root
>   * Uploaded to my DQM GUI:
>     http://fanae43.geol.uniovi.es:8080/dqm/offline/start?runnr=160960;dataset=/Cosmics/Run2011A/DQMIO;sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=DT;size=M;root=DT/03-LocalTrigger-TM;focus=;zoom=no;
> 
> As I mentioned, the reason why the baseline has non-empty histograms
> while the PR does, is double: 2011 RAW data format included DDU (and RPC
> hits in trigger from it), which made populate the histograms with the
> DDU and RPC filter enabled, even with stats as low as 10 events (as the
> Jenkins test use).
> 
> In 2016, with the introduction of the TwinMux boards, all the DT DQM
> Offline plots in folder DT / 03-LocalTrigger-TM are empty due tow these
> two facts above. You can check in the DQM Offline Gui in any decent
> Cosmic or Data run, e.g.:
> https://goo.gl/fG722v
> 
> I'm pretty sure the PR is doing well, but I'm willing to perform any
> other test or workflow you consider the differences are salient with 10
> event statitics, as Jenkins test is using. Nevertheless, for the future
> I'd suggest moving the Cosmics Jenkin test to a recent 2016 dataset as
> reference to avoid this kind of problems.
> 
> Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/16739#issuecomment-266404495>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEdcbrj28Me6SBlrJ9n6j9ouGNfhqCQWks5rHS6tgaJpZM4K6V0L>.
>

2016-12-12 14:27 UTC, jfernan2 commented
@slava77 Thanks. But I'm not sure if I understand your comment/request. 
Let me put this way:
The whole 2016 data taking have those DQM plots empty due to the use of new Trigger Primitives in the DT data format. We realized now the source of the problem so, only in case a pre-2016 data format is used as input (like the 2011 Cosmics used in the Jenkins test) the plots have entries in the baseline.

This change can go to 90X only if it eases the merging, though we would like to have it in 8XY too to take advantage of any data reprocessing, but I guess there will be no further data reprocessings anyway in a short-term time scale...
Thanks

2016-12-12 14:36 UTC, slava77 commented
On 12/12/16 6:27 AM, jfernan2 wrote:
> @slava77 <https://github.com/slava77> Thanks. But I'm not sure if I
> understand your comment/request.

If we can support both pre-2016 and 2016+  by just adjusting configuration,
then I think we should.
So that the plost are filled in a meaningful way in all scenarios.

Our configuration language allows this support using eras.

If code that supports pre-2016 is incompatible with that for 2016+,
then DQM decides if it's time to abandon support for pre-2016,
then we do what this PR has now (broken or descoped monitoring of
pre-2016 data)
(chances are that someone may still need to check some old data)

> Let me put this way:
> The whole 2016 data taking have those DQM plots empty due to the use of
> new Trigger Primitives in the DT data format. We realized now the source
> of the problem so, only in case a pre-2016 data format is used as input
> (like the 2011 Cosmics used in the Jenkins test) the plots have entries
> in the baseline.
> 
> This change can go to 90X only if it eases the merging, though we would
> like to have it in 8XY too to take advantage of any data reprocessing,
> but I guess there will be no further data reprocessings anyway in a
> short-term time scale...
> Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/16739#issuecomment-266444098>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEdcbtsPuKN96bCtHovl28zTtEW1mYAMks5rHVnugaJpZM4K6V0L>.
>

2016-12-13 08:06 UTC, jfernan2 commented
@slava77 Thanks, now I understand what you mean. I can add an extra configuration parameter so that the RPC filter can be enabled/disabled via python. However, I don't now how to set that this be used depending on the input Era, can you point to an example?

On the other hand, these DQM plots are used by DT expert shifter, who knows exactly this incompatibility, so I'm not sure if it may be needed or not.
Thanks

2016-12-13 13:21 UTC, slava77 commented
On 12/13/16 12:06 AM, jfernan2 wrote:
> @slava77 <https://github.com/slava77> Thanks, now I understand what you
> mean. I can add an extra configuration parameter so that the RPC filter
> can be enabled/disabled via python. However, I don't now how to set that
> this be used depending on the input Era, can you point to an example?
> 
> On the other hand, these DQM plots are used by DT expert shifter, who
> knows exactly this incompatibility, so I'm not sure if it may be needed
> or not.
> Thanks


https://github.com/cms-sw/cmssw/blob/53327033fb356b2a704464439ce79fa47a9d1678/CalibMuon/CSCCalibration/python/CSCChannelMapper_cfi.py#L15
has an example of using eras
for things installed in 2016 you can use an existing run2_25ns_specific
modifier.



> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/16739#issuecomment-266672545>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEdcbty59Buln86B3I_xQYmPWbnjU8LHks5rHlHygaJpZM4K6V0L>.
>

2016-12-14 18:02 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2016-12-14 18:03 UTC, slava77 commented
@cmsbuild please test

2016-12-14 18:04 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-12-14 20:18 UTC, cmsbuild commented
+1
Tested at: 38e35b4fede974885c318bde37fc0f2bc7c2d04a
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17038/summary.html

2016-12-14 20:18 UTC, cmsbuild commented
Comparison job queued.

2016-12-14 21:24 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17038/summary.html

2016-12-14 22:43 UTC, cvuosalo commented
@jfernan2: What is the purpose of the latest era change to this PR? I checked the new Jenkins test results, and they seem the same as I reported before the latest change (https://github.com/cms-sw/cmssw/pull/16739#issuecomment-265584289).

2016-12-19 23:09 UTC, cvuosalo commented
+1

For #16739 38e35b4fede974885c318bde37fc0f2bc7c2d04a

Changing some DT and RPC DQM trigger plots.

The Reco code change is satisfactory. Jenkins tests against baseline CMSSW_9_0_X_2016-12-14-1100 show no Reco problems, but there still might be issues of concern to DQM.
@dmitrijus: It appears that even the latest version of this PR is failing to preserve pre-2016 behavior in some of the DQM plots. Reco will defer to DQM as to how to best proceed from here.

2016-12-20 08:17 UTC, jfernan2 commented
Please hold on, I'm still working on a solution for the DQM differences, but not much time available lately. Hope to arrive to commit by today

2016-12-20 16:43 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2016-12-20 16:43 UTC, jfernan2 commented
Now it should be fine, thanks for your patience

2016-12-20 17:12 UTC, cvuosalo commented
@cmsbuild please test

2016-12-20 17:12 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-12-20 19:15 UTC, cmsbuild commented
+1
Tested at: 8f292b6e50f37996c46ae7f316beb453e7a94495
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17130/summary.html

2016-12-20 19:15 UTC, cmsbuild commented
Comparison job queued.

2016-12-20 20:55 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17130/summary.html

2016-12-20 21:32 UTC, cvuosalo commented
+1

For #16739 8f292b6e50f37996c46ae7f316beb453e7a94495

Second approval, after DQM code fixes. Jenkins test results show only TM_TrigEff DQM plots getting filled in as desired, with no plots being erroneously emptied as seen previously before the code fix. Note that DQM plots for workflows 136.731 and 1000.0 are completely wrong, but that is a long-standing Jenkins problem not related to this PR.

2017-01-09 10:22 UTC, dmitrijus requested changes
Please fix the white space issues in python configuration files. Also, https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMGithubGuide

2017-01-09 10:22 UTC, dmitrijus commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +			 twinMuxStage2Digis +
tabs, please switch to spaces!

2017-01-09 10:22 UTC, dmitrijus commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_cff.py
> +			 twinMuxStage2Digis +
tabs again!

2017-01-09 15:11 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-01-09 22:09 UTC, slava77 commented
@cmsbuild please test

2017-01-09 22:09 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-09 23:52 UTC, cmsbuild commented
+1
Tested at: 70cfcb04298257c9bf5442e911186ff32da70d25
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17222/summary.html

2017-01-09 23:52 UTC, cmsbuild commented
Comparison job queued.

2017-01-10 01:47 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17222/summary.html

2017-01-10 10:48 UTC, dmitrijus requested changes
Please just configure your editor not to emit tabs. Ever.
This as frustrating to me as it is to you.

2017-01-10 10:48 UTC, dmitrijus commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_HI_cff.py
> +			 twinMuxStage2Digis  +
Another tab!

2017-01-10 10:53 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-01-10 10:54 UTC, jfernan2 commented
Done. My apologies

2017-01-10 13:53 UTC, slava77 commented
@cmsbuild please test

2017-01-10 13:53 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-10 13:56 UTC, dmitrijus requested changes

2017-01-10 13:56 UTC, dmitrijus commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_HI_cff.py
> +	                 twinMuxStage2Digis  +
Still a tab left. Now it is even worse, tab + space + more space?
(also please check the other files...)

2017-01-10 15:50 UTC, cmsbuild commented
+1
Tested at: a0d32963b3274176ae24fddaa721c10ae7e88278
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17228/summary.html

2017-01-10 15:50 UTC, cmsbuild commented
Comparison job queued.

2017-01-10 16:21 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17228/summary.html

2017-01-10 16:30 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-01-10 16:57 UTC, slava77 commented
@cmsbuild please test

2017-01-10 16:57 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-10 18:44 UTC, cmsbuild commented
+1
Tested at: ff549f2b7a24ca9a1a17a2a317852d731769b2d9
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17235/summary.html

2017-01-10 18:44 UTC, cmsbuild commented
Comparison job queued.

2017-01-10 20:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17235/summary.html

2017-01-10 20:33 UTC, slava77 commented
+1

for https://github.com/cms-sw/cmssw/pull/16739	ff549f2
- only DQM/DT\* files were modified since the last signoff by reco https://github.com/cms-sw/cmssw/compare/38e35b4fede974885c318bde37fc0f2bc7c2d04a...ff549f2b7a24ca9a1a17a2a317852d731769b2d9
    - reco products are not changed by this PR, it has DQM changes only
- jenkins tests pass and comparisons with baseline roughly correspond to what was noticed in the last RECO signoff https://github.com/cms-sw/cmssw/pull/16739#issuecomment-268105499

2017-01-11 10:39 UTC, dmitrijus commented
+1

2017-01-11 10:39 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-01-18 10:17 UTC, davidlange6 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
Hi @jfernan2 - sorry for not re-reviewing this after your changes - also the producer(s) themselves need to be moved to a path with producers - in this case the L1 sequence I think. Maybe @rekovic  can help.

2017-01-18 11:44 UTC, jfernan2 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
Any hint where this should go instead?

2017-01-18 15:56 UTC, jfernan2 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
Hi @davidlange6 , @rekovic but, I'm not able to find where should I move the twiMuxStage2Digis in this DQM sequence. Could you please point me to the right package? 

I can trace back to see that DQMOffline/Configuration/python/DQMOffline_cff.py is calling this config file, but I ignore where all the raw2digi is being set for DQM, if so. Thanks

2017-01-25 11:01 UTC, jfernan2 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
Hi @davidlange6 , @rekovic , @dmitrijus , could any help me to understand where the unpacker should go instead? 
For DQM online, it is sourced through DQM/DTMonitorModule/python/dt_dqm_sourceclient_common_cff.py in DQM/Integration/python/clients/dt_dqm_sourceclient-live_cfg.py 
But the equivalent for DQM offline seems to be DQM/DTMonitorModule/python/dtDQMOfflineSources_*.py
Any hint is very apreciated
Thank you very much

2017-01-25 12:05 UTC, cmsbuild commented
Pull request #16739 was updated. @cvuosalo, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-01-25 13:26 UTC, dmitrijus commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
I am not sure what David meant. L1 reco sequence? To me, dtDQMOfflineSources_*.py looks a proper place for it. Ping, @davidlange6 @rekovic

2017-01-25 17:46 UTC, jfernan2 commented on DQM/DTMonitorModule/python/dtDQMOfflineSources_Cosmics_cff.py
> +                         twinMuxStage2Digis +
@dmitrijus Could you anyway trigger the Jenkins tests with the last commit which may fix the situation? I'm not able to run them in my local release in due a strange error not related to this PR: 
"plugin-poisoned-CondFormatsCTPPSReadoutObjectsPlugins.so cannot open shared object file"
Thanks

2017-01-26 09:48 UTC, dmitrijus commented
please test

2017-01-26 09:48 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-26 11:07 UTC, cmsbuild commented
+1
Tested at: d1813282ddfa9e7599f354304dca4affc55cefe5
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17452/summary.html

2017-01-26 11:07 UTC, cmsbuild commented
Comparison job queued.

2017-01-26 12:34 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16739/17452/summary.html

2017-01-27 18:35 UTC, slava77 commented
+1

for https://github.com/cms-sw/cmssw/pull/16739	d181328
- DQM-related updates since the last commit, no impact on reco; changes look reasonable (removal of the twinMuxStage2Digis  producer from purely DQM sequences)
- jenkins tests pass; comparisons with baseline look consistent with the differences observed in the past in the DT LocalTrigger monitoring plots

2017-01-31 13:44 UTC, dmitrijus commented
+1

2017-01-31 13:44 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-02-01 15:45 UTC, davidlange6 commented
+1
Thanks

2017-02-01 15:45 UTC, merged