Fix L1 fat event filters 81X
cms-sw/cmssw pull request #16766
Opened 2016-11-25 15:47 UTC by jimbrooke

81X version of #16765

Fixes for two filters used to select L1T "fat events", to use of the 64-bit event number from TCDS FED word 11 (https://twiki.cern.ch/twiki/bin/viewauth/CMS/TcdsEventRecord#TCDS_Data_Block_Definition_curre) instead of the 24-bit event number from common DAQ header.

In the case of HLTL1NumberFilter, use of the common DAQ header (ie. existing functionality) is maintained as default.

2016-11-25 15:47 UTC, cmsbuild commented
A new Pull Request was created by  @jimbrooke (Jim B) for CMSSW_8_1_X.

It involves the following packages:

EventFilter/L1TRawToDigi
HLTrigger/special


@perrotta, @cmsbuild, @silviodonato, @Martin-Grunewald, @rekovic, @fwyzard, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @kreczko this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2016-11-25 17:12 UTC, rekovic commented
please test

2016-11-25 17:12 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2016-11-25 18:34 UTC, cmsbuild commented
+1
Tested at: be986676eb3ca6c15a5ace782b6bd32efae21e05
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16766/16605/summary.html

2016-11-25 18:34 UTC, cmsbuild commented
Comparison job queued.

2016-11-25 19:09 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16766/16605/summary.html

2016-11-26 10:16 UTC, Martin-Grunewald commented
+1

2016-11-26 14:48 UTC, rekovic commented
+1

2016-11-26 14:48 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_8_1_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @slava77, @davidlange6, @smuzaffar

2016-11-26 15:48 UTC, fwyzard requested changes

2016-11-26 15:48 UTC, fwyzard commented on HLTrigger/special/interface/HLTL1NumberFilter.h
> +  bool useTCDS_;
can you make this `const` ?

2016-11-26 15:48 UTC, fwyzard commented on HLTrigger/special/src/HLTL1NumberFilter.cc
> +
can you move this into the office initialiser above ?

2016-11-26 15:48 UTC, fwyzard commented on HLTrigger/special/src/HLTL1NumberFilter.cc
> +      }
can you reword this so that there is a single check on the counter ?

2016-11-26 15:49 UTC, fwyzard commented
are my retreats for changes even visible ?

2016-11-28 07:44 UTC, davidlange6 commented
hi @jimbrooke @rekovic - please open/approve a 90x version of this pr. Thanks

2016-11-28 16:16 UTC, fwyzard commented
hold

please address the comments above

2016-11-28 16:16 UTC, cmsbuild commented
Pull request has been put on hold by  @fwyzard
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2016-11-28 17:34 UTC, jimbrooke commented
I think it would be more efficient if someone who is actually familiar with HLT coding rules fix this bug.  I certainly don't have time for this.  Please see https://github.com/cms-l1t-offline/cmssw/pull/438 for an example of the 3 line change that is required.

2016-11-28 17:43 UTC, fwyzard commented
The HLT coding rules are "do not write crappy code".
What makes you think that the HLT people have the time to fix the L1 code ?

2016-11-28 17:58 UTC, fwyzard commented
please see #16782

2016-11-28 17:59 UTC, fwyzard commented
-1

2016-11-28 21:35 UTC, rekovic commented
superseded by #16782

2016-11-29 17:01 UTC, closed without merging