Refactoring and speeding-up of the XML parser for the L1T O2O
cms-sw/cmssw pull request #17059
Opened 2016-12-16 17:27 UTC by kkotov

The original XML parser developed by Thomas and Vangelis did a good job for the rapidly developing L1T O2O in Run II 2016. Now I've revisited some of it's design, simplified the interface, and took advantage of the c++11 move semantics, that resulted in substantial speed increase. The original code
still lives in L1Trigger/L1TCommon (along with other not related code) while new classes are available in L1TriggerConfig/XmlConfigTools . The O2O online producers in L1TriggerConfig/L1TConfigProducers as well as uGMT and BMTF helper classes in L1Trigger/{L1TMuon,L1TMuonBarrel} were modified to use the new parser.

2016-12-16 17:28 UTC, cmsbuild commented
A new Pull Request was created by  @kkotov (Khristian Kotov) for CMSSW_9_0_X.

It involves the following packages:

L1Trigger/L1TCommon
L1Trigger/L1TMuon
L1Trigger/L1TMuonBarrel
L1TriggerConfig/L1TConfigProducers
L1TriggerConfig/XmlConfigTools


The following packages do not have a category, yet:

L1TriggerConfig/XmlConfigTools
Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories.py to assign category

@cmsbuild, @rekovic, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @kreczko this is something you requested to watch as well.
@slava77, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-01-04 18:31 UTC, lgray commented
@cmsbuild please test

@kkotov You need to make a pull request in cms-bot to add the new package.

2017-01-04 18:32 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-04 20:22 UTC, cmsbuild commented
+1
Tested at: d5aaacf4817ce9b9d1ecf67cdd2b2ef4219317a7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17178/summary.html

2017-01-04 20:22 UTC, cmsbuild commented
Comparison job queued.

2017-01-04 21:55 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17178/summary.html

2017-01-05 11:45 UTC, kkotov commented
@lgray , could you point me to any instructions on how to add new packages using cms-bot? Thanks!

2017-01-05 16:06 UTC, lgray commented
@kkotov You need to clone https://github.com/cms-sw/cms-bot/ and then edit https://github.com/cms-sw/cms-bot/blob/master/categories.py and make a pull request.

2017-01-05 17:25 UTC, kkotov commented
@lgray  Thanks for the hint! I've just made a new PR: https://github.com/cms-sw/cms-bot/pull/799 . A theoretical question aside: am I also allowed to introduce new categories? For example, I've added my new package L1TriggerConfig/XmlConfigTools under l1 meaning that l1 managers (Mike or Vladimir) will have to sign off every time I modify my package. On the other hand, if I introduce my own l1o2o category with the packages that are not used anywhere but in L1T O2O, I'd be a natural person to have full control over this code.

2017-01-05 17:47 UTC, lgray commented
I'd bring that up with other people, perhaps @slava77 knows? Otherwise my
best guess is to put it under L1.

On Jan 5, 2017 11:25 AM, "Khristian Kotov" <notifications@github.com> wrote:

> @lgray <https://github.com/lgray> Thanks for the hint! I've just made a
> new PR: cms-sw/cms-bot#799 <https://github.com/cms-sw/cms-bot/pull/799> .
> A theoretical question aside: am I also allowed to introduce new
> categories? For example, I've added my new package
> L1TriggerConfig/XmlConfigTools under l1 meaning that l1 managers (Mike or
> Vladimir) will have to sign off every time I modify my package. On the
> other hand, if I introduce my own l1o2o category with the packages that are
> not used anywhere but in L1T O2O, I'd be a natural person to have full
> control over this code.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/17059#issuecomment-270703320>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABBMOaXxKfCtpQfoYJUu_w2L_W0JtYKFks5rPSeggaJpZM4LPakq>
> .
>

2017-01-05 17:58 UTC, slava77 commented
On 1/5/17 9:47 AM, Lindsey Gray wrote:
> I'd bring that up with other people, perhaps @slava77 knows? Otherwise my
> best guess is to put it under L1.

bring this up in the ORP and then in the O&C weekly meeting or a
management meeting.

categories are not cast in stone. A new category should not be hard to
implement.
(more changes will be necessary than just in the categories.py file)
You can even make the current l1 managers also to be in the l1o2o
category so that the signature ability is available from more people.


> 
> On Jan 5, 2017 11:25 AM, "Khristian Kotov" <notifications@github.com> wrote:
> 
>> @lgray <https://github.com/lgray> Thanks for the hint! I've just made a
>> new PR: cms-sw/cms-bot#799 <https://github.com/cms-sw/cms-bot/pull/799> .
>> A theoretical question aside: am I also allowed to introduce new
>> categories? For example, I've added my new package
>> L1TriggerConfig/XmlConfigTools under l1 meaning that l1 managers (Mike or
>> Vladimir) will have to sign off every time I modify my package. On the
>> other hand, if I introduce my own l1o2o category with the packages that are
>> not used anywhere but in L1T O2O, I'd be a natural person to have full
>> control over this code.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cms-sw/cmssw/pull/17059#issuecomment-270703320>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/ABBMOaXxKfCtpQfoYJUu_w2L_W0JtYKFks5rPSeggaJpZM4LPakq>
>> .
>>
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/17059#issuecomment-270708658>, or
> mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEdcbr53oc4tEVLU38iWgKa2ZHHEY7yEks5rPSyygaJpZM4LPakq>.
>

2017-01-17 16:08 UTC, rekovic commented
as discussed with @kkotov, needs moving code around and putting new modules in the existing L1Trigger/L1TCommon package.

2017-01-20 17:47 UTC, davidlange6 commented
As for categories - of course the idea is for actual code review before it gets into the release for general use - so having developers "review" their own code makes little sense..

2017-01-23 14:57 UTC, cmsbuild commented
Pull request #17059 was updated. @ggovi, @cmsbuild, @rekovic, @mulhearn, @davidlange6 can you please check and sign again.

2017-01-23 15:07 UTC, cmsbuild commented
Pull request #17059 was updated. @ggovi, @cmsbuild, @rekovic, @mulhearn, @davidlange6 can you please check and sign again.

2017-01-23 15:28 UTC, ggovi commented
please test

2017-01-23 15:28 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-23 16:58 UTC, cmsbuild commented
+1
Tested at: d8103975708725d319c89da2d346325098993077
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17386/summary.html

2017-01-23 16:58 UTC, cmsbuild commented
Comparison job queued.

2017-01-23 17:30 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17386/summary.html

Alternative comparison was/were failed for workflow(s):
25202.0
5.1
1306.0
21234.0
1003.0
23234.0
140.53
136.731
1330.0
1000.0
135.4
10024.0
8.0
1001.0
10021.0
50202.0
20034.0
9.0
4.22

2017-01-23 17:32 UTC, kkotov commented
As agreed with @rekovic , the new code is placed back into L1TCommon side by side with the old files. While reviewing the code the two additional files were identified not updated to this branch:  L1Trigger/L1TMuon/plugins/BuildFile.xml and L1TriggerConfig/L1TConfigProducers/src/L1TMuonEndcapParamsOnlineProd.cc. Now a new test needs to be triggered.

2017-01-23 19:15 UTC, cmsbuild commented
Pull request #17059 was updated. @ghellwig, @ianna, @cerminar, @fabozzi, @Martin-Grunewald, @mommsen, @vanbesien, @perrotta, @civanch, @monttj, @silviodonato, @franzoni, @cmsbuild, @fwyzard, @davidlange6, @smuzaffar, @Dr15Jones, @cvuosalo, @mdhildreth, @slava77, @ggovi, @mmusich, @mulhearn, @rekovic, @arunhep, @emeschi, @dmitrijus, @srimanob, @hengne can you please check and sign again.

2017-01-23 19:17 UTC, kkotov commented
I also rebased this PR to the current branch CMSSW_9_0_X

2017-01-23 19:37 UTC, slava77 commented
-1
rebase or similar fix is needed 

https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideHATS2016Git#CMSSW_rebasing_recipe

2017-01-24 14:17 UTC, rekovic commented
please test

2017-01-24 14:17 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-24 15:33 UTC, cmsbuild commented
-1

Tested at: b5824a62c3dd6fceba14c427adc687213c52b19a

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17403/summary.html

I found follow errors while testing this PR

**Failed tests:  AddOn**

* **AddOn**:

I found errors in the following addon tests:

cmsRun /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-24-1100/src/Utilities/ReleaseScripts/scripts/read312RV_cfg.py : FAILED - time: date Tue Jan 24 16:27:09 2017-date Tue Jan 24 16:19:42 2017 s - exit: 23552

2017-01-24 15:33 UTC, cmsbuild commented
Comparison job queued.

2017-01-24 17:31 UTC, kkotov commented
Judging from the logs, I don't see anything in my code that could have cause the problem with tests above. @rekovic do you think we may want to trigger another test?

2017-01-24 17:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17403/summary.html

The workflows 1003.0, 1001.0, 1000.0, 140.53, 136.731, 4.22 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

2017-01-25 11:42 UTC, rekovic commented
please test

2017-01-25 11:42 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-25 13:14 UTC, cmsbuild commented
+1
Tested at: b5824a62c3dd6fceba14c427adc687213c52b19a
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17433/summary.html

2017-01-25 13:14 UTC, cmsbuild commented
Comparison job queued.

2017-01-25 15:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17433/summary.html

2017-01-26 11:27 UTC, rekovic commented
+1

2017-01-26 11:28 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-02-01 09:32 UTC, kkotov commented
@davidlange6 is there anything left for this PR before it is merged?

2017-02-01 10:03 UTC, ianna requested changes
Xerces string utilities guarantee proper memory management. Please, consider using them.

2017-02-01 10:03 UTC, ianna commented on L1Trigger/L1TCommon/src/XmlConfigParser.cc
> +inline std::string _toString(XMLCh const* toTranscode) {
@kkotov - please use Xerces string utilities from http://cmslxr.fnal.gov/source/Utilities/Xerces/interface/XercesStrUtils.h

2017-02-01 17:02 UTC, davidlange6 commented on L1Trigger/L1TCommon/interface/Parameter.h
> +        if( type.find("vector") != std::string::npos ||
hi @kkotov - xml is always long to review - here are some comments

2017-02-01 17:03 UTC, davidlange6 commented on L1Trigger/L1TCommon/interface/Parameter.h
> +        if( type.find("vector") != std::string::npos ||
please make the "vector" and "table" into const expr.

2017-02-01 17:05 UTC, davidlange6 commented on L1Trigger/L1TCommon/src/Parameter.cc
> +    this->id = id;
would be more nicely handled by following a naming convention. Eg, a usual one in CMS is member data ends in '_'

2017-02-01 17:08 UTC, davidlange6 commented on L1Trigger/L1TCommon/src/XmlConfigParser.cc
> +    std::cout << "No xml root element found" << std::endl;
Please use the message logger or other thread safe construct instead of cout.

2017-02-01 17:14 UTC, davidlange6 commented
and generically - it looks like this PR is intended to obsolete some set of classes, hopefully including one of the two existing L1 xml readers. Is that the case? if so what is the plan to actually delete the obsolete code?

2017-02-01 18:19 UTC, kkotov commented on L1Trigger/L1TCommon/src/XmlConfigParser.cc
> +    std::cout << "No xml root element found" << std::endl;
That'll bring a dependency on the Logging library of CMSSW. I don't know if Thomas Reis (the author of XmlConfigReader, that this class is derived from) had ever intended to use it in a standalone mode. I'll better try to clean all the std::cout's instead.

2017-02-06 11:59 UTC, kkotov commented on L1Trigger/L1TCommon/src/XmlConfigParser.cc
> +inline std::string _toString(XMLCh const* toTranscode) {
Thanks @ianna for pointing to this solution.

2017-02-06 11:59 UTC, kkotov commented on L1Trigger/L1TCommon/interface/Parameter.h
> +        if( type.find("vector") != std::string::npos ||
@davidlange6 I am not sure I understand what you mean here. Non of the l1t::Parameter objects are constructed or manipulated at compile-time. They are constructed as the xml configuration parsed in runtime. So declaring any of the trivial methods of this class as constexpr won't have any effect in the end.

2017-02-06 11:59 UTC, kkotov commented
@davidlange6 , Yes, the XmlConfigParser is depricating XmlConfigReader as well as l1t::Parameters is replacing l1t::Setting and l1t::TableRow classes. I would prefer to profit (not for a long time) of having the new and old systems side by side in the release.

2017-02-06 11:59 UTC, cmsbuild commented
Pull request #17059 was updated. @cmsbuild, @rekovic, @mulhearn, @davidlange6 can you please check and sign again.

2017-02-06 12:01 UTC, kkotov commented on L1Trigger/L1TCommon/src/Parameter.cc
> +    this->id = id;
Thanks for pointing to the naming convention. I'd stick with the 'this->' construct for the moment so as to minimize the changes.

2017-02-06 14:01 UTC, rekovic commented
please test

2017-02-06 14:01 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-06 15:12 UTC, cmsbuild commented
-1

Tested at: 2e533d86cf18174030ff539c9a42fe5475a37554

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17635/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
10021.0 step4
<pre>runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step4_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>10024.0 step4
<pre>runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step4_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>

2017-02-06 15:12 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2017-02-06 15:19 UTC, kkotov commented
The error above must be due to a problem with RelVal accessibility. But the logs seem to be incomplete.

2017-02-07 10:17 UTC, rekovic commented
please test

2017-02-07 10:17 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-07 11:48 UTC, cmsbuild commented
+1
Tested at: 2e533d86cf18174030ff539c9a42fe5475a37554
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17659/summary.html

2017-02-07 11:49 UTC, cmsbuild commented
Comparison job queued.

2017-02-07 14:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17059/17659/summary.html

2017-02-07 16:14 UTC, rekovic commented
+1

2017-02-07 16:14 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-02-08 09:05 UTC, davidlange6 commented
+1

2017-02-08 09:05 UTC, merged