Increase buffer to 20 chars (was too small)
cms-sw/cmssw pull request #17240
Opened 2017-01-20 22:20 UTC by davidlt

According to the compiler we need at least 11 bytes for string format.
Also we always should use snprintf to avoid buffer overflows.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

2017-01-20 22:20 UTC, cmsbuild commented
A new Pull Request was created by  @davidlt  for CMSSW_9_0_X.

It involves the following packages:

Geometry/TrackerCommonData


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @davidlange6 can you please review it and eventually sign? Thanks.
@makortel, @ghellwig, @venturia, @VinInn, @ghugo83 this is something you requested to watch as well.
@davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-01-20 22:20 UTC, davidlt commented
please test

2017-01-20 22:20 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-01-21 00:07 UTC, cmsbuild commented
+1
Tested at: 5f339b480fd2120658b21061ca88a029b17ec936
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17240/17357/summary.html

2017-01-21 00:07 UTC, cmsbuild commented
Comparison job queued.

2017-01-21 02:34 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17240/17357/summary.html

2017-01-21 09:03 UTC, davidlange6 commented
@ianna - would be nice to get rid of the char* completely and use a string (and corresponding stream) here.

2017-01-21 09:13 UTC, davidlt commented
That's true, there seems to be no need for char buffer.

2017-01-22 13:16 UTC, ianna commented
-1

2017-01-22 13:17 UTC, ianna requested changes

2017-01-22 13:17 UTC, ianna commented on Geometry/TrackerCommonData/plugins/DDTECModuleAlgo.cc
>      name    = idName + "SiReenforce"+buf;
@davidlt - please use:
```
+ std::to_string(i)
```
instead of 
```
+ buf
```
and remove the buffer entirely

2017-01-22 13:17 UTC, ianna commented on Geometry/TrackerCommonData/plugins/DDTECModuleAlgo.cc
>      name    = idName + "SuppliesBox"+buf;
@davidlt - please see my comment beneath

2017-01-23 17:29 UTC, davidlt commented
Replaced by https://github.com/cms-sw/cmssw/pull/17255
Closing.

2017-01-23 17:29 UTC, closed without merging