Phase1 improvements:
cms-sw/cmssw pull request #17340
Opened 2017-01-31 17:37 UTC by fioriNTU

2017-01-31 17:37 UTC, cmsbuild commented
A new Pull Request was created by  @fioriNTU  for CMSSW_9_0_X.

It involves the following packages:

DQM/Integration
DQM/SiPixelPhase1Common
DQM/SiPixelPhase1Config
DQM/SiPixelPhase1Digis
DQM/SiPixelPhase1RecHits
DQM/SiPixelPhase1TrackClusters
DQM/SiPixelPhase1TrackEfficiency
DQM/SiPixelPhase1TrackResiduals


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@idebruyn, @threus, @batinkov, @hdelanno this is something you requested to watch as well.
@davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-01-31 17:46 UTC, fioriNTU commented
@enochnotsocool @davidcarbonis  @lunik1 @leggat  you may be interested

2017-02-02 15:52 UTC, fioriNTU commented
@dmitrijus could you start he tests please?

2017-02-03 19:34 UTC, fioriNTU commented
Can someone start also this test? I see quiet some activity on github ...

2017-02-07 08:37 UTC, fioriNTU commented
@dmitrijus could you start the tests please?

2017-02-07 09:26 UTC, davidlange6 commented
please test

2017-02-07 09:27 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-07 11:27 UTC, cmsbuild commented
+1
Tested at: 767d6b2e5d694093032b0a6ed991ee47e000813a
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17340/17656/summary.html

2017-02-07 11:28 UTC, cmsbuild commented
Comparison job queued.

2017-02-07 12:09 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17340/17656/summary.html

2017-02-07 13:16 UTC, dmitrijus requested changes

2017-02-07 13:16 UTC, dmitrijus commented on DQM/Integration/python/clients/pixel_dqm_sourceclient-live_For_Timing_Scan_cfg.py
> +import FWCore.ParameterSet.Config as cms
The file name should be pixel_timing_scan_dqm_sourceclient-live_cfg.py or similar. No touching anything after "dqm_".

2017-02-07 13:16 UTC, dmitrijus commented on DQM/Integration/python/clients/pixel_dqm_sourceclient-live_For_Timing_Scan_cfg.py
> +import FWCore.ParameterSet.Config as cms
Also, if this is intended to run in online DQM, you will need to write an email to core DQM once this is merged and this code reaches the online DQM. We will need to properly link it, so the daemon picks it up and cmsRuns it.

If it is not intended to run in online DQM, please move this file elsewhere. Preferably outside DQM/Integration.

2017-02-07 13:54 UTC, cmsbuild commented
Pull request #17340 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-07 13:57 UTC, fioriNTU commented on DQM/Integration/python/clients/pixel_dqm_sourceclient-live_For_Timing_Scan_cfg.py
> +import FWCore.ParameterSet.Config as cms
@dmitrijus I have removed the file in the DQM/Integration directory and renamed it properly in our SiPixelPhase1/Config folder. In the case we will decide to use it Online I will make a separate PR. It is important to have this merged as soon as possible, in the way new contributors can play with a "quasi-final" version of the code without struggling with private branche etc ...

2017-02-07 14:05 UTC, cmsbuild commented
Pull request #17340 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-07 14:21 UTC, fioriNTU commented
@dmitrijus can you restart the tests?

2017-02-07 16:14 UTC, dmitrijus commented
+1

2017-02-07 16:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-07 16:14 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-02-07 18:18 UTC, cmsbuild commented
+1
Tested at: 66ea76a3548c41226e4d40c07e8bc627a2504b4d
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17340/17673/summary.html

2017-02-07 18:18 UTC, cmsbuild commented
Comparison job queued.

2017-02-07 20:04 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17340/17673/summary.html

2017-02-08 08:52 UTC, davidlange6 commented
+1

2017-02-08 08:52 UTC, merged