Pr90x l1t prescales from payloads
cms-sw/cmssw pull request #17512
Opened 2017-02-14 15:44 UTC by rekovic

90x PR: Updated L1TGlobalUtil to now also access L1T prescales from payloads, using GlobalTag.

Example:
<pre>
cmsRun L1Trigger/L1TGlobal/test/runGTSummary.py 
</pre>

2017-02-14 15:44 UTC, rekovic commented
please test

2017-02-14 15:45 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-14 15:45 UTC, cmsbuild commented
A new Pull Request was created by  @rekovic  for CMSSW_9_0_X.

It involves the following packages:

L1Trigger/L1TGlobal
L1Trigger/L1TMuonEndCap


@cmsbuild, @rekovic, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @kreczko this is something you requested to watch as well.
@davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-02-14 17:14 UTC, Martin-Grunewald commented
@rekovic @apana 
Can you please move the ```cout``` back to ```MessageLogger```?

2017-02-14 18:26 UTC, cmsbuild commented
-1

Tested at: e14dbd7e3e1423afe09e6baffe2de7dac10ae69d

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17512/17787/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals  AddOn**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
1306.0 step3
<pre>runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15/step3_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>136.731 step3
<pre>runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log

</pre>1330.0 step3
<pre>runTheMatrix-results/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/step3_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>135.4 step3
<pre>runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step3_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

</pre>10021.0 step3
<pre>runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>25202.0 step3
<pre>runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

</pre>10024.0 step3
<pre>runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>10824.0 step3
<pre>runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018.log

</pre>

* **AddOn**:

I found errors in the following addon tests:

cmsRun /cvmfs/cms-ib.cern.ch/nweek-02459/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-14-1100/src/HLTrigger/Configuration/test/OnLine_HLT_GRun.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Tue Feb 14 19:13:31 2017-date Tue Feb 14 19:02:21 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:GRun,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_GRun --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_GRun_MC.root --fileout file:RelVal_Raw_GRun_MC_HLT_RECO.root : FAILED - time: date Tue Feb 14 19:13:31 2017-date Tue Feb 14 19:02:21 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02459/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-14-1100/src/HLTrigger/Configuration/test/OnLine_HLT_PRef.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Tue Feb 14 19:11:37 2017-date Tue Feb 14 19:02:29 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:PRef,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_PRef --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_PRef_MC.root --fileout file:RelVal_Raw_PRef_MC_HLT_RECO.root : FAILED - time: date Tue Feb 14 19:11:37 2017-date Tue Feb 14 19:02:29 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02459/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-14-1100/src/HLTrigger/Configuration/test/OnLine_HLT_HIon.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Tue Feb 14 19:18:28 2017-date Tue Feb 14 19:09:23 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:HIon,RAW2DIGI,L1Reco,RECO --mc --scenario=HeavyIons -n 10 --conditions auto:run2_mc_HIon --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016,Run2_HI --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_HIon_MC.root --fileout file:RelVal_Raw_HIon_MC_HLT_RECO.root : FAILED - time: date Tue Feb 14 19:18:28 2017-date Tue Feb 14 19:09:23 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02459/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-14-1100/src/HLTrigger/Configuration/test/OnLine_HLT_PIon.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Tue Feb 14 19:22:15 2017-date Tue Feb 14 19:17:37 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:PIon,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_PIon --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_PIon_MC.root --fileout file:RelVal_Raw_PIon_MC_HLT_RECO.root : FAILED - time: date Tue Feb 14 19:22:15 2017-date Tue Feb 14 19:17:37 2017 s - exit: 16640

2017-02-14 18:26 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2017-02-28 13:23 UTC, cmsbuild commented
Pull request #17512 was updated. @dmitrijus, @cmsbuild, @rekovic, @vanbesien, @mulhearn, @davidlange6 can you please check and sign again.

2017-02-28 14:06 UTC, Martin-Grunewald commented
@rekovic @apana
Can you please move the ```cout``` back to ```MessageLogger```?

2017-03-01 04:39 UTC, apana commented
Hi Martin,

Sorry I forgot to followup on this request.  I will take care of the cout.

-Len

2017-03-01 12:54 UTC, cmsbuild commented
Pull request #17512 was updated. @dmitrijus, @cmsbuild, @rekovic, @vanbesien, @mulhearn, @davidlange6 can you please check and sign again.

2017-03-01 12:55 UTC, rekovic commented
@Martin-Grunewald, @apana 
> Can you please move the `cout` back to `MessageLogger`?

Done.

2017-03-02 08:22 UTC, dmitrijus requested changes

2017-03-02 08:22 UTC, dmitrijus commented on L1Trigger/L1TGlobal/plugins/L1TGlobalSummary.cc
>    gtUtil_             = new L1TGlobalUtil(iConfig, consumesCollector(), *this, algInputTag_, extInputTag_);
can this become a member? Or at least std::unique_ptr?

2017-03-02 08:23 UTC, dmitrijus commented
+1

I did request a small change, but it was there before this PR as well - the PR does not make it worse.

2017-03-02 08:23 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-03 04:20 UTC, cmsbuild commented
-1

Tested at: b246965d32a293aceea8cdb699c17eb1b5d582be

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17512/18123/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals  AddOn**

* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
1306.0 step3
<pre>runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15/step3_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>1330.0 step3
<pre>runTheMatrix-results/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/step3_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>10021.0 step3
<pre>runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>10824.0 step3
<pre>runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018.log

</pre>10024.0 step3
<pre>runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

</pre>25202.0 step3
<pre>runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

</pre>

* **AddOn**:

I found errors in the following addon tests:

cmsRun /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-03-02-2300/src/HLTrigger/Configuration/test/OnLine_HLT_GRun.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Fri Mar  3 05:13:40 2017-date Fri Mar  3 05:05:19 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:GRun,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_GRun --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_GRun_MC.root --fileout file:RelVal_Raw_GRun_MC_HLT_RECO.root : FAILED - time: date Fri Mar  3 05:13:40 2017-date Fri Mar  3 05:05:19 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-03-02-2300/src/HLTrigger/Configuration/test/OnLine_HLT_PRef.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Fri Mar  3 05:12:23 2017-date Fri Mar  3 05:05:25 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:PRef,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_PRef --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_PRef_MC.root --fileout file:RelVal_Raw_PRef_MC_HLT_RECO.root : FAILED - time: date Fri Mar  3 05:12:23 2017-date Fri Mar  3 05:05:25 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-03-02-2300/src/HLTrigger/Configuration/test/OnLine_HLT_HIon.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Fri Mar  3 05:12:22 2017-date Fri Mar  3 05:05:39 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:HIon,RAW2DIGI,L1Reco,RECO --mc --scenario=HeavyIons -n 10 --conditions auto:run2_mc_HIon --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016,Run2_HI --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_HIon_MC.root --fileout file:RelVal_Raw_HIon_MC_HLT_RECO.root : FAILED - time: date Fri Mar  3 05:12:22 2017-date Fri Mar  3 05:05:39 2017 s - exit: 16640
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-03-02-2300/src/HLTrigger/Configuration/test/OnLine_HLT_PIon.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Fri Mar  3 05:13:02 2017-date Fri Mar  3 05:05:52 2017 s - exit: 16640
cmsDriver.py RelVal -s HLT:PIon,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_PIon --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2016 --magField 38T_PostLS1 --processName=HLTRECO --filein file:RelVal_Raw_PIon_MC.root --fileout file:RelVal_Raw_PIon_MC_HLT_RECO.root : FAILED - time: date Fri Mar  3 05:13:02 2017-date Fri Mar  3 05:05:52 2017 s - exit: 16640

2017-03-03 04:20 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2017-03-13 09:07 UTC, closed without merging

2017-03-15 14:11 UTC, fwyzard commented
sorry @rekovic @davidlange6 , what happened to this PR ?
has i been integrated somewhere else ?

2017-03-16 07:27 UTC, davidlange6 commented
not that i'm aware of (don't recall seeing a version that worked)

2017-03-16 08:04 UTC, rekovic commented
@fwyzard @davidlange6 Correct - the new version is being worked on.