organize HLT trigger rate plots in directories
cms-sw/cmssw pull request #17519
Opened 2017-02-15 10:54 UTC by mtosi

as requested in JIRA [#1158](https://its.cern.ch/jira/browse/CMSHLT-1158)
this update is meant to re-organize HLT trigger paths in sub-directories
in order to speed up the displaying on the GUI

plots are created in directories depending on the PD the trigger belongs to

because the same trigger might be used in different PDs,
extra plots are created w.r.t. previous implementation

2 set of plots are dropped, instead,
they correspond to the paths HLTriggerFirstPath and HLTriggerFirstPath,
which are not needed to be monitored

the new TriggerMonitorRateClient is currently not used

2017-02-15 10:54 UTC, cmsbuild commented
A new Pull Request was created by  @mtosi (mia tosi) for CMSSW_9_0_X.

It involves the following packages:

DQM/HLTEvF


@perrotta, @cmsbuild, @silviodonato, @dmitrijus, @Martin-Grunewald, @fwyzard, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-02-15 10:55 UTC, mtosi commented
it would be useful to have this PR merged in 900pre5,
because --as far as I understood-- 900pre5 will be used in the upcoming WMGR,
and therefore it would be useful to check this new feature on the online DQM

2017-02-15 11:48 UTC, dmitrijus requested changes

2017-02-15 11:48 UTC, dmitrijus commented on DQM/HLTEvF/plugins/TriggerRatesMonitorClient.cc
> +      std::cout << "me: " << me << std::endl;
std::cout!

2017-02-15 13:07 UTC, cmsbuild commented
Pull request #17519 was updated. @perrotta, @cmsbuild, @silviodonato, @dmitrijus, @Martin-Grunewald, @fwyzard, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-15 13:12 UTC, cmsbuild commented
Pull request #17519 was updated. @perrotta, @cmsbuild, @silviodonato, @dmitrijus, @Martin-Grunewald, @fwyzard, @vanbesien, @davidlange6 can you please check and sign again.

2017-02-15 13:13 UTC, dmitrijus commented
+1

2017-02-15 13:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-02-15 15:38 UTC, cmsbuild commented
+1
Tested at: dadadb0f5a682bd5ec05b4fd10e04719d534565a
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17519/17798/summary.html

2017-02-15 15:38 UTC, cmsbuild commented
Comparison job queued.

2017-02-15 19:30 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17519/17798/summary.html

2017-02-17 09:27 UTC, Martin-Grunewald commented
+1

2017-02-17 09:27 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-02-17 13:09 UTC, davidlange6 commented on DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
> +      for (unsigned int i = 0; i < m_datasets[d].size(); ++i) {
this looks like a bug - i is used in two loops at once. Is it really correct?
@mtosi

2017-02-20 16:44 UTC, mtosi commented
ciao
are there pending issue w/ this PR ?
thanks a lot !
@davidlange6 @fwyzard @silviodonato @Martin-Grunewald

2017-02-20 17:06 UTC, Martin-Grunewald commented
@mtosi 
Have you seen @davidlange6 comments (see above)?

2017-02-20 17:17 UTC, mtosi commented
yes, last week, but I replied to them, didn't I ?

2017-02-20 17:21 UTC, Martin-Grunewald commented
@mtosi 
Look again at the PR, there a new comments on some loop index i.

2017-02-24 18:11 UTC, davidlange6 commented
-1
while waiting for comments from @mtosi

2017-02-27 13:15 UTC, mtosi commented on DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
> +      for (unsigned int i = 0; i < m_datasets[d].size(); ++i) {
apparently the comment I wrote 10 days ago was not committed .. it seemed to me so, but it was not !

the comment was
loop opened in line 361 gets closed in 366, 
not that the for instance does not have the `for (unsigned int i: m_datasets[d])`

in addition, the compiler does not complain, above all in this case where the variable `i` gets different types

2017-02-27 13:21 UTC, davidlange6 commented on DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
> +      for (unsigned int i = 0; i < m_datasets[d].size(); ++i) {
ah - ok, I missed the lack of a {} for the loop starting on line 361 (the } on line 366 closes the if statement started on 362)

2017-02-27 13:21 UTC, davidlange6 commented
+1

2017-02-27 13:21 UTC, merged

2017-02-27 13:30 UTC, mtosi commented on DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
> +      for (unsigned int i = 0; i < m_datasets[d].size(); ++i) {
right
is it ok ?
thanks

2017-02-27 13:36 UTC, mtosi commented
thanks !
and sorry again for the delay, but from my window it seemed my comment was
posted ...
  mia

On Mon, Feb 27, 2017 at 1:21 PM, cmsbuild <notifications@github.com> wrote:

> Merged #17519 <https://github.com/cms-sw/cmssw/pull/17519>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/17519#event-978322991>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AEt58-2MuFtgB3NodflxIrI1QrSwnyycks5rgs3xgaJpZM4MBkYQ>
> .
>

2017-02-27 15:02 UTC, fwyzard commented
@mtosi 

> in addition, the compiler does not complain, above all in this case where the variable i gets different types

The compiler does not necessarily complain if you reuse the same variable in a nested loop.
This is valid C++
```c++
  for (unsigned int i = 0; i < 3; ++i)
    for (double i = 0.; i < 3.; ++i)
      for (auto const & i: std::vector<std::string>{ "Hello", " ", "world", "\n" })
        std::cout << i;
```
that will print 9 times `Hello world`.