Fix BranchChildren/Parentage problems that occur with SubProcess and EDAlias
cms-sw/cmssw pull request #17950
Opened 2017-03-15 22:04 UTC by wddgit

Also adds unit tests to cover these cases.

2017-03-15 22:04 UTC, cmsbuild commented
A new Pull Request was created by  @wddgit (W. David Dagenhart) for master.

It involves the following packages:

DataFormats/Provenance
FWCore/Framework
FWCore/Integration
IOPool/Input
IOPool/Output


@cmsbuild, @smuzaffar, @Dr15Jones, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @wmtan this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-03-15 23:46 UTC, Dr15Jones commented
please test

2017-03-15 23:46 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-16 08:30 UTC, cmsbuild commented
-1

Tested at: 6cb2b7814afdfaca4ffe51c1361504c9cfd7d169

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18470/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test TestSubProcess had ERRORS

2017-03-16 08:30 UTC, cmsbuild commented
Comparison job queued.

2017-03-16 11:16 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18470/summary.html

There are some workflows for which there are errors in the baseline:
 25.0 step 5
 The results for the comparisons for these workflows could be incomplete 
This means most likely that the IB is having errors in the relvals.The error does NOT come from this pull request

2017-03-16 12:54 UTC, Dr15Jones commented
Please test

2017-03-16 12:54 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-16 13:59 UTC, Dr15Jones requested changes
Done with my review.

2017-03-16 13:59 UTC, Dr15Jones commented on DataFormats/Provenance/interface/Provenance.h
> +    BranchID const& originalBranchID() const {return stable().originalBranchID();}
Please add a comment explaining the difference between `branchID` and `originalBranchID`

2017-03-16 13:59 UTC, Dr15Jones commented on FWCore/Framework/src/ScheduleItems.cc
> +      subProcessParentageHelper_(new SubProcessParentageHelper),
How about switching to `std::make_shared<>()`? That is actually more memory efficient

2017-03-16 13:59 UTC, Dr15Jones commented on FWCore/Framework/src/ScheduleItems.cc
> +                     subProcessParentageHelper_ ? &*subProcessParentageHelper_ : nullptr,
probably simpler to do `subProcessParentageHelper_ ? subProcessParentageHelper_.get() : nullptr`

2017-03-16 13:59 UTC, Dr15Jones commented on IOPool/Input/src/RootFile.h
> +    void markBranchToBeDropped(bool dropDescendants, BranchDescription const& branchy, std::set<BranchID>& branchesToDrop, std::map<BranchID, BranchID> const& droppedToKeptAlias) const;
`branchy` seems like an odd name

2017-03-16 17:01 UTC, cmsbuild commented
Pull request #17950 was updated. @cmsbuild, @smuzaffar, @Dr15Jones, @davidlange6 can you please check and sign again.

2017-03-16 17:01 UTC, wddgit commented
@Dr15Jones I agree with all your comments and submitted the appropriate modifications in the last commit I pushed.

2017-03-16 17:20 UTC, Dr15Jones commented
please test

2017-03-16 17:20 UTC, Dr15Jones commented
+1

2017-03-16 17:20 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-16 17:20 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-03-16 22:08 UTC, cmsbuild commented
-1

Tested at: 33148b9dd8e43044f621092ffdb87be5d32ae546

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18500/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test TestSubProcess had ERRORS

2017-03-16 22:08 UTC, cmsbuild commented
Comparison job queued.

2017-03-17 00:28 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18500/summary.html

2017-03-20 09:26 UTC, davidlange6 commented
-1
test failure looks related.

2017-03-20 14:21 UTC, Dr15Jones commented
please test

2017-03-20 14:21 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-20 14:22 UTC, Dr15Jones commented
@davidlange6 as far as David Dagenhart and I can tell, the unit test failure is from the problem fixed by #17946 and not from this pull request.

2017-03-20 14:35 UTC, davidlange6 commented
please test

ok, lets test again

> On Mar 20, 2017, at 3:22 PM, Chris Jones <notifications@github.com> wrote:
> 
> @davidlange6 as far as David Dagenhart and I can tell, the unit test failure is from the problem fixed by #17946 and not from this pull request.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-20 14:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-20 19:42 UTC, cmsbuild commented
+1
Tested at: 33148b9dd8e43044f621092ffdb87be5d32ae546
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18562/summary.html

2017-03-20 19:42 UTC, cmsbuild commented
Comparison job queued.

2017-03-20 20:32 UTC, davidlange6 commented
+1

2017-03-20 20:32 UTC, merged

2017-03-20 23:08 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17950/18562/summary.html

2017-03-24 10:39 UTC, dmitrijus commented
Hi @wddgit, can this be backported to 90x?

This problem causes a segfault in IOPool/Streamer modules, this PR fixes it.

2017-03-24 15:47 UTC, wddgit commented
@dmitrijus We can probably backport the change, but we are interested in understanding how and why the seg fault is occurring. Can you tell me how to reproduce it so I can investigate this? If you already know exactly how the seg fault is occurring, can you explain it? Thanks.

2017-03-24 19:29 UTC, dmitrijus commented
@wddgit 
To reproduce merge https://github.com/cms-sw/cmssw/pull/18066 and use 
cmsRun DQMStreamerOutputRepackerTest_cfg.py <any_root_with_mc_data>.root 

The crash is a (double) null-pointer dereference in this line,
https://github.com/cms-sw/cmssw/blob/master/IOPool/Streamer/src/StreamSerializer.cc#L149

2017-03-24 21:13 UTC, wddgit commented
@Dr15Jones I reproduced the problem. If you write a file containing an EDAlias to a ROOT format output file and then in a subsequent process you read that file and try to run the streamer output module, then a seg fault occurs. The problem is indeed in the line he pointed to in StreamSerializer.cc. It successfully get the product using the EDAlias, then using the EDAlias BranchID tries to get the ProductProvenance, but that is stored keyed on the original BranchID not the EDAlias BranchID so it fails and returns a nullptr. The streamer output module does not check the pointer and dereferences and there is a seg fault. This was fixed by this PR in 9_1_X, but not backported to 9_0_X

I reproduced the error running a Framework unit test to make the file with the EDAlias
(cmsRun FWCore/Integration/test/testGetBy1_cfg.py)

and the following to read it and seg fault. It has nothing to do with the DQM PR.

```
import FWCore.ParameterSet.Config as cms

process = cms.Process("PROD2")

process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
        'file:testGetBy1.root'
    )
)

process.out = cms.OutputModule("EventStreamFileWriter",
    fileName = cms.untracked.string('testSeriesOfProcessesHLT.dat'),
    compression_level = cms.untracked.int32(1),
    use_compression = cms.untracked.bool(True),
    max_event_size = cms.untracked.int32(7000000)
)

process.e = cms.EndPath(process.out)
```
Should I backport the entire PR (and the other related PR that followed) to 9_0_X? This has probably been there for a while. It is somewhat unusual to run streamer output on a file containing an EDAlias and that is probably why no one noticed before.

2017-03-24 21:15 UTC, wddgit commented
I did not try it but this might also fail if you dropped the parentage and tried to run streamer output. So it could be looked at as also a bug in streamer output.

2017-03-24 21:24 UTC, Dr15Jones commented
Let's start with a fix to the Streamer. Both in 9_1 and 9_0.

2017-03-27 15:53 UTC, wddgit commented
I'm working on fixing the Streamer IO. It actually is not built to handle a nullptr for the ProductProvenance at all so this is more than a one or two line fix. I'll need to trace this all the way through streamer input and output and then make several little fixes in the entire streamer input and output chain to make it work.

2017-03-28 12:05 UTC, dmitrijus commented
@wddgit Thanks!

2017-03-30 17:32 UTC, wddgit commented
@dmitrijus I submitted pull requests for the Streamer Output Module problem. PR #18126 was already merged into 9_1_X and PR #18135 is the back port to 9_0_X which was just submitted (not merged yet). These should be sufficient to avoid the seg fault you saw.
@Dr15Jones My understanding is that we are not backporting this PR because we want to maintain stability in 9_0_X, avoid the effort to resolve conflicts, and the risk associated with it. Let me know if you want me to backport this also.