PhysicsTools/KinFitter: fix gcc5 strict-overflow warning.
cms-sw/cmssw pull request #17974
Opened 2017-03-17 16:43 UTC by gartung

Move conditional out of for statement so that compiler does not attempt to optimize out for loop.

This fixes the gcc5 warning:

  /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/7339d4514f5638002b3a1b1f515c3f0b/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_1_X_2017-03-16-1100/src/PhysicsTools/KinFitter/src/TKinFitter.cc:1256:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
  void TKinFitter::printMatrix(const TMatrixD &matrix, const TString& name) {
      ^

2017-03-17 16:44 UTC, cmsbuild commented
A new Pull Request was created by  @gartung (Patrick Gartung) for master.

It involves the following packages:

PhysicsTools/KinFitter


@cmsbuild, @monttj, @davidlange6 can you please review it and eventually sign? Thanks.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-03-20 16:41 UTC, gartung commented
@Dr15Jones test please

2017-03-20 18:09 UTC, Dr15Jones commented
Please add `{}` to aid in understanding the structure.

2017-03-20 18:18 UTC, cmsbuild commented
Pull request #17974 was updated. @cmsbuild, @monttj, @davidlange6 can you please check and sign again.

2017-03-20 18:18 UTC, gartung commented
Done

2017-03-20 18:20 UTC, Dr15Jones commented on PhysicsTools/KinFitter/src/TKinFitter.cc
> +      }
This brace does not appear to line up with the `for`.

2017-03-20 18:22 UTC, cmsbuild commented
Pull request #17974 was updated. @cmsbuild, @monttj, @davidlange6 can you please check and sign again.

2017-03-20 18:22 UTC, gartung commented
Done

2017-03-20 18:28 UTC, Dr15Jones requested changes

2017-03-20 18:28 UTC, Dr15Jones commented on PhysicsTools/KinFitter/src/TKinFitter.cc
> +          log << "\n";
This should be outside the for loop to match the previous logic.

2017-03-20 18:28 UTC, Dr15Jones commented on PhysicsTools/KinFitter/src/TKinFitter.cc
> +      log << "\n"
The curly brace for the `for` loop should be before this line to match the previous logic.

2017-03-20 18:42 UTC, cmsbuild commented
Pull request #17974 was updated. @cmsbuild, @monttj, @davidlange6 can you please check and sign again.

2017-03-20 18:42 UTC, gartung commented
I think I have it right this time.

2017-03-20 18:54 UTC, Dr15Jones commented
please test

2017-03-20 18:54 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-20 21:20 UTC, cmsbuild commented
+1
Tested at: c361c9e6825337764ccc563631d84ef947fc4cea
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17974/18571/summary.html

2017-03-20 21:20 UTC, cmsbuild commented
Comparison job queued.

2017-03-20 23:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17974/18571/summary.html

2017-03-23 08:32 UTC, merged