BD hadron track monitoring in standard validation sequence 91X (master)
cms-sw/cmssw pull request #18053
Opened 2017-03-23 17:07 UTC by smoortga

same PR as https://github.com/cms-sw/cmssw/pull/18011 but in the master branch (91X)

2017-03-23 17:07 UTC, cmsbuild commented
A new Pull Request was created by  @smoortga  for master.

It involves the following packages:

Validation/Configuration
Validation/RecoB


@perrotta, @civanch, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@imarches, @acaudron, @JyothsnaKomaragiri, @mverzett, @ferencek, @pvmulder this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-03-23 17:17 UTC, slava77 commented
@cmsbuild please test

2017-03-23 17:18 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-23 19:06 UTC, cmsbuild commented
+1
Tested at: 8b19e5cc5c2df304e35edb0899a18338cc2297bb
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18053/18650/summary.html

2017-03-23 19:06 UTC, cmsbuild commented
Comparison job queued.

2017-03-23 21:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18053/18650/summary.html

2017-03-24 08:09 UTC, dmitrijus requested changes

2017-03-24 08:09 UTC, dmitrijus commented on Validation/Configuration/python/globalValidation_cff.py
> +				 + bdHadronTrackValidationSeq
do not introduce tab  characters in python files, please.

2017-03-24 08:09 UTC, dmitrijus commented on Validation/RecoB/python/BDHadronTrackValidation_cff.py
> +					* patJetCharge*patJetPartonMatch
tabs again.

2017-03-24 08:43 UTC, smoortga commented
@dmitrijus , fixed

2017-03-24 08:59 UTC, dmitrijus commented
thanks

2017-03-24 08:59 UTC, dmitrijus commented
+1

2017-03-24 09:02 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-24 10:54 UTC, cmsbuild commented
+1
Tested at: 3894b8976a10875fb28e3b1757af88e7f5d41db5
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18053/18664/summary.html

2017-03-24 10:54 UTC, cmsbuild commented
Comparison job queued.

2017-03-24 11:26 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18053/18664/summary.html

2017-03-24 19:29 UTC, civanch commented
+1

2017-03-29 11:47 UTC, smoortga commented
Hi all,

Thanks for putting effort in reviewing this PR with me. Which approval-flags do we still need set to get this PR merged? (and who is responsible for that?)

Cheers,
Seth

2017-03-30 10:42 UTC, perrotta commented
+1
Validation stuff
Code looks reasonable

2017-03-30 10:42 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-03-30 12:47 UTC, perrotta commented
hold
(while checking whether, and to what extent, the producers run in the newly added sequence add  up to the saved output)

2017-03-30 12:48 UTC, cmsbuild commented
Pull request has been put on hold by  @perrotta
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2017-03-30 15:29 UTC, perrotta commented
unhold
(explicitely verified that the new products are never saved with the usual reco-related event contents)

2017-03-30 15:30 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-03-30 15:42 UTC, davidlange6 commented
+1

2017-03-30 15:42 UTC, merged