Update legacy modules in CommonTools, RecoMET, RecoJets
cms-sw/cmssw pull request #18153
Opened 2017-03-31 15:56 UTC by kpedro88

In the course of testing Phase2 workflows on Knights Landing machines (with 64 threads), @Dr15Jones and @gartung found a number of legacy modules causing stalls.

In this PR, I fixed several of them. Modules were updated to global where possible (no mutable state required, or mutable state could be avoided with straightforward code changes) and stream otherwise (when a mutable state of the class was unavoidable). In some cases, code edits were necessary to remove thread-unsafe practices.

2017-03-31 15:56 UTC, cmsbuild commented
A new Pull Request was created by  @kpedro88 (Kevin Pedro) for master.

It involves the following packages:

CommonTools/CandAlgos
CommonTools/CandUtils
CommonTools/RecoAlgos
RecoJets/JetAlgorithms
RecoJets/JetProducers
RecoMET/METFilters


@perrotta, @cmsbuild, @slava77, @monttj, @davidlange6 can you please review it and eventually sign? Thanks.
@rappoccio, @gouskos, @jdolen, @yslai, @abbiendi, @TaiSakuma, @jhgoh, @makortel, @nhanvtran, @mmarionncern, @ahinzmann, @gkasieczka, @mariadalfonso, @schoef this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-03-31 15:57 UTC, kpedro88 commented
@cmsbuild please test

2017-03-31 15:57 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-03-31 18:02 UTC, cmsbuild commented
+1
Tested at: e7748eeff24322177a081fc031fa29eb51163d4d
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18153/18841/summary.html

2017-03-31 18:02 UTC, cmsbuild commented
Comparison job queued.

2017-03-31 20:09 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18153/18841/summary.html

2017-04-01 12:25 UTC, Dr15Jones commented on RecoMET/METFilters/interface/EcalBoundaryInfoCalculator.h
> +    CaloNavigator<EcalDetId> * initializeEcalNavigator(DetId startE, const edm::ESHandle<CaloTopology> theCaloTopology,
How about changing this to return a `std::unique_ptr<CaloNavigator<EcalDetId>`. That would simplify the logic in the routine which uses it.

2017-04-01 12:28 UTC, Dr15Jones commented on RecoMET/METFilters/plugins/EcalDeadCellBoundaryEnergyFilter.cc
> +      std::cout << "Constructor EcalAnomalousEvent" << std::endl;
Please change to MessageLogger to avoid thread safety issues.

2017-04-01 12:31 UTC, Dr15Jones commented on RecoMET/METFilters/plugins/EcalDeadCellTriggerPrimitiveFilter.cc
> -#include "TFile.h"
I think you can remove the `#include "TTree.h"` as well.

2017-04-01 12:33 UTC, Dr15Jones commented on RecoMET/METFilters/plugins/EcalLaserCorrFilter.cc
> +    virtual bool filter(edm::StreamID, edm::Event & iEvent, const edm::EventSetup & iSetup) const override;
NOTE: the `EDGetTokenT`s can also be made `const`.

2017-04-01 12:35 UTC, Dr15Jones commented on RecoMET/METFilters/plugins/HcalLaserEventFilter.cc
> +	       if (debug_) std::cout <<"<HcalLaserEventFilter::Error> No valid HBHERecHitCollection with label '"<<hbheInputLabel_<<"' found"<<std::endl;
Please replace with the MessageLogger.

2017-04-01 12:36 UTC, Dr15Jones requested changes
Finished with my comments.

2017-04-03 08:13 UTC, cmsbuild commented
Pull request #18153 was updated. @perrotta, @cmsbuild, @slava77, @monttj, @davidlange6 can you please check and sign again.

2017-04-03 08:13 UTC, kpedro88 commented
@Dr15Jones all done (there were a lot of couts...)

2017-04-03 08:13 UTC, kpedro88 commented
@cmsbuild please test

2017-04-03 08:13 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-03 09:37 UTC, cmsbuild commented
+1
Tested at: 94557af01246835e1e794586a9fa3e94f3d1a9b1
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18153/18866/summary.html

2017-04-03 09:37 UTC, cmsbuild commented
Comparison job queued.

2017-04-03 11:27 UTC, kpedro88 commented
@knoepfel FYI, since I noticed you've also been updating some of the legacy modules

2017-04-03 11:49 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18153/18866/summary.html

2017-04-05 17:26 UTC, perrotta commented
+1
Updates look fine after visual inspection
No changes in jenkins test

2017-04-06 08:03 UTC, merged