bsunanda:Run2-hcx122 Testing Reconstruction geometry for Plan1 option
cms-sw/cmssw pull request #18166
Opened 2017-04-02 08:33 UTC by bsunanda

2017-04-02 08:34 UTC, bsunanda commented
@cmsbuild Please test

2017-04-02 08:34 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HcalCommonData
Geometry/HcalTowerAlgo


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-04-02 08:34 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-02 11:10 UTC, cmsbuild commented
-1

Tested at: 3b3c1c20403e4a6379e3757344c782c55b2466ea

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18854/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test testRecoMETMETProducers had ERRORS

2017-04-02 13:08 UTC, bsunanda commented
@cmsbuild Please test

2017-04-02 13:08 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-02 13:09 UTC, bsunanda commented
@smuzaffar @davidlange6 The failure has nothing to do with this PR.

2017-04-02 16:41 UTC, cmsbuild commented
-1

Tested at: 3b3c1c20403e4a6379e3757344c782c55b2466ea

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18857/summary.html

I found follow errors while testing this PR

**Failed tests:  Build**

* **Build**:

I found an error when building: 
 
 <pre>In file included from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/boost/1.63.0-mlhled/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/boost/1.63.0-mlhled/include/boost/lexical_cast/detail/inf_nan.hpp:34:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/boost/1.63.0-mlhled/include/boost/math/special_functions/sign.hpp:16:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/boost/1.63.0-mlhled/include/boost/math/tools/config.hpp:388:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/boost/1.63.0-mlhled/include/boost/detail/fenv.hpp:97:
/cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/gcc/5.3.0/include/c++/5.3.0/fenv.h:58:11: error: no member named 'fenv_t' in the global namespace
  using ::fenv_t;
        ~~^
/cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/external/gcc/5.3.0/include/c++/5.3.0/fenv.h:59:11: error: no member named 'fexcept_t' in the global namespace
  using ::fexcept_t;
        ~~^
</pre>

2017-04-02 16:41 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2017-04-04 07:10 UTC, bsunanda commented
@cmsbuild Please test

2017-04-04 07:10 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-04 09:17 UTC, cmsbuild commented
+1
Tested at: 3b3c1c20403e4a6379e3757344c782c55b2466ea
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18894/summary.html

2017-04-04 09:17 UTC, cmsbuild commented
Comparison job queued.

2017-04-04 10:16 UTC, ianna requested changes

2017-04-04 10:16 UTC, ianna commented on Geometry/HcalCommonData/src/HcalDDDRecConstants.cc
> +  ids.clear();
@bsunanda - why do you need to clear the vector here? You fill an empty newly created vector from the way it is used in the test. Note, that the capacity (memory usage) of a vector will never decrease, even if you call the clear method, unless you use the swap method.

2017-04-04 10:17 UTC, ianna commented
@bsunanda - please, provide description

2017-04-04 11:03 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18894/summary.html

2017-04-05 08:05 UTC, cmsbuild commented
Pull request #18166 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @davidlange6 can you please check and sign again.

2017-04-05 08:06 UTC, bsunanda commented
@cmsbuild Please test

2017-04-05 08:06 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-05 10:08 UTC, cmsbuild commented
+1
Tested at: 9d2047bfb3b45242cc160a66fdd70d202bfbfa8c
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18930/summary.html

2017-04-05 10:08 UTC, cmsbuild commented
Comparison job queued.

2017-04-05 10:36 UTC, ianna requested changes

2017-04-05 10:36 UTC, ianna commented on Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
> +  if (geomDB_) {
@bsunanda - the geometry will not necessarily come from DB, but from an EventSetup. The python configuration will define if it is coming from DB.

2017-04-05 10:36 UTC, ianna commented on Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
> +    HcalFlexiHardcodeGeometryLoader m_loader(ps0_);
@bsunanda - a possibility of an HcalGeometry creation outside of an EventSetup is a bad practice. I hope, it is limited to the test only.

2017-04-05 10:36 UTC, ianna commented on Geometry/HcalTowerAlgo/test/runHcalGeometryPlan1Tester_cfg.py
> +process.load("Geometry.HcalCommonData.testGeometry17bXML_cfi")
@bsunanda - here is where the geometry choice is made and it is from XML, not DB

2017-04-05 10:36 UTC, ianna commented on Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
> +  for (unsigned int k=0; k<idsp.size(); ++k) {
@bsunanda - please, use a range-based for loop

2017-04-05 10:36 UTC, ianna commented on Geometry/HcalCommonData/src/HcalDDDRecConstants.cc
> +    std::map<HcalDetId,HcalDetId>::const_iterator itr;
@bsunanda - please, consider using range-based for loops

2017-04-05 10:45 UTC, ianna commented
@bsunanda - please, do not put neither branch name nor a PR number in the a PR title. The title is used in release notes, for example:
You can have a look https://github.com/cms-sw/cmssw/releases/CMSSW_9_0_0
If you need to refer to another PR, it is better to do it in the PR description - a link to it will be automatically added.

2017-04-05 12:11 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18930/summary.html

2017-04-05 12:26 UTC, bsunanda commented
@cmsbuild Please test

2017-04-05 12:26 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-05 12:28 UTC, cmsbuild commented
Pull request #18166 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @davidlange6 can you please check and sign again.

2017-04-05 14:01 UTC, ianna commented on Geometry/HcalTowerAlgo/test/HcalGeometryPlan1Tester.cc
> +  for (std::vector<HcalDetId>::const_iterator itr=idsp.begin();
@bsunanda - the following would be shorter. Please, have a look at http://en.cppreference.com/w/cpp/language/range-for
```
for( const auto& itr : idsp )
{
 ...
} 
```

2017-04-05 14:25 UTC, cmsbuild commented
+1
Tested at: 8b3ce054607895c04cc640f45da804ed6134cd22
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18940/summary.html

2017-04-05 14:25 UTC, cmsbuild commented
Comparison job queued.

2017-04-05 14:49 UTC, ianna commented
+1

2017-04-05 14:49 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-04-05 19:45 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18166/18940/summary.html

2017-04-06 07:55 UTC, davidlange6 commented
+1

2017-04-06 07:56 UTC, merged