Final Tracker Geometry for tracker TDR + Cleaning old Phase1
cms-sw/cmssw pull request #18253
Opened 2017-04-07 09:18 UTC by boudoul

Greetings 
This pull request aim for 
- Describing the final Tracker for the TDR (in D11) described here : 
http://ghugo.web.cern.ch/ghugo/layouts/2016/OT613_200_IT4025/

- Fix the important thing which was a (non desired and problematic) dependencies of the phase2 Geometry with Phase1 Geometry (for the inner pixel part ) 
--> the Inner Tracker is now defined as P2PXBBarrel and no more as P1PXBBarrel which could cause severe bugs for any changes in 2017 geometry 

- The usage of  P1PXBBarrel eleswhere in cmssw has been tracked down and fixed accordingly 

- Note that the D11 is no more running the track trigger sequence, as it should be fix ot deal with the new geometries (new rings) to be fix in a subsequent PR 

- I have added a protection in the phase2 DQM in case of no valid collections are found 

- PLease note that this PR (in particular D11 sceanrio ) should be tested with this PR :+1: https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/pull/6

2017-04-07 09:18 UTC, cmsbuild commented
A new Pull Request was created by  @boudoul (boudoul) for master.

It involves the following packages:

Alignment/CommonAlignment
Alignment/TrackerAlignment
Configuration/PyReleaseValidation
DPGAnalysis/SiStripTools
DQM/Phase2OuterTracker
Geometry/CommonDetUnit
Geometry/TrackerCommonData
Geometry/TrackerGeometryBuilder
Geometry/TrackerNumberingBuilder
Geometry/TrackerRecoData
Geometry/TrackerSimData
RecoPixelVertexing/PixelLowPtUtilities
RecoTracker/TkDetLayers
SLHCUpgradeSimulations/Geometry
SimGeneral/DataMixingModule
Validation/Geometry


@perrotta, @ghellwig, @civanch, @Dr15Jones, @dmitrijus, @arunhep, @ianna, @kpedro88, @fabozzi, @cmsbuild, @franzoni, @mdhildreth, @cerminar, @slava77, @GurpreetSinghChahal, @mmusich, @vanbesien, @monttj, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig, @pakhotin, @makortel, @felicepantaleo, @GiacomoSguazzoni, @tocheng, @VinInn, @Martin-Grunewald, @mschrode, @ebrondol, @rovere, @tlampen, @gpetruc, @mmusich, @ghugo83, @threus, @dgulhan, @venturia this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-04-07 09:19 UTC, boudoul commented
I have tested locally but i'm planning to provide with more stats some relevant
tracking plots in a couple of days , but it doesn't prevent the review to start
- thanks !

2017-04-07 09:19 UTC, boudoul commented
adding @delaere , @atricomi

2017-04-07 09:24 UTC, kpedro88 commented
@boudoul can you summarize the "real" changes in the T5/D11 geometry (as opposed to technical reorganizations)?

2017-04-07 09:32 UTC, ianna commented on Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml
> +   <ZSection z="95.90*cm" rMin="2.8*cm" rMax="116.0*cm"/>
@boudoul - Have you checked that this move in Z by 3.1 cm does not introduce an overlap? Or shall I do it? Thanks.

2017-04-07 09:33 UTC, boudoul commented on Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml
> +   <ZSection z="95.90*cm" rMin="2.8*cm" rMax="116.0*cm"/>
@ianna ,   @ghugo should have checked that, maybe she can confirm

2017-04-07 09:33 UTC, boudoul commented
@kpedro88 Sure, I was exacly preapring this, comments in github will be there in a few minutes

2017-04-07 09:38 UTC, iahmad-khan commented
please test with cms-sw/cmsdist#2942

2017-04-07 09:38 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Using externals from cms-sw/cmsdist#2942

2017-04-07 09:39 UTC, ebrondol commented
Hi @boudoul and @atricomi, the cluster shape filter is not been updated. Am I correct? I suppose this is the best way to have it now, then if we see that we need to update it, it can be done in a future PR.

2017-04-07 09:46 UTC, ghellwig requested changes
@boudoul Except for the re-introduced bug, I am fine with the changes.

2017-04-07 09:46 UTC, ghellwig commented on Alignment/CommonAlignment/src/AlignableObjectId.cc
> -  if (!geometry) return Geometry::General;
@boudoul here you re-introduce I bug I fixed in #18097

2017-04-07 09:49 UTC, boudoul commented on Alignment/CommonAlignment/src/AlignableObjectId.cc
> -  if (!geometry) return Geometry::General;
whoops will fix in the next commit - thanks for noticing !

2017-04-07 09:51 UTC, boudoul commented
Description : of the changes in T5 : 
1) Outer Tracker PS modules:
PS-p active length: 32 x 1467 = 46944 mu. Used to be 32 x 1446.

2) Outer Tracker Barrel PS layers : 
+ 1 ring in TBPS Layer 1.
Now, all TBPS layers have 12 rings.
Minor adjustments in coordinates in TBPS.

3) Outer Tracker EndCaps: 
Disk 1 has a much lower Z.
PS instead of 2S in Ring 10 (disks 1 to 5).
- 1 ring in TEDD (disks 3 to 5).
Now, in TEDD, disks 3 to 5 have 12 rings each. 

4) Minor update in pixel IT MB 

I let @ghugo check if my list is complete

2017-04-07 09:56 UTC, cmsbuild commented
Pull request #18253 was updated. @perrotta, @ghellwig, @civanch, @Dr15Jones, @dmitrijus, @arunhep, @ianna, @kpedro88, @fabozzi, @cmsbuild, @franzoni, @mdhildreth, @cerminar, @slava77, @GurpreetSinghChahal, @mmusich, @vanbesien, @monttj, @davidlange6 can you please check and sign again.

2017-04-07 10:05 UTC, boudoul commented
@ebrondol , you are correct and +1 to your comments, thanks !
Le 7 avr. 2017 à 11:39, ebrondol <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @boudoul<https://github.com/boudoul> and @atricomi<https://github.com/atricomi>, the cluster shape filter is not been updated. Am I correct? I suppose this is the best way to have it now, then if we see that we need to update it, it can be done in a future PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/18253#issuecomment-292490668>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AE5NyNgXYjUm95n8HE4dcCvCkeKEhMU5ks5rtgRvgaJpZM4M2p6H>.

2017-04-07 10:28 UTC, boudoul commented
Informing @lmoreels for the changes i'm introducing here in the DQM phase2 since she's the original developer

2017-04-07 10:37 UTC, kpedro88 commented
@boudoul thanks

@ebrondol can you or someone else do a 200PU igprof run to see if the possibly non-ideal cluster shape filter impacts CPU performance?

2017-04-07 11:21 UTC, ghugo83 commented on Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml
> +   <ZSection z="95.90*cm" rMin="2.8*cm" rMax="116.0*cm"/>
Hi, yes i modifed to solve extrusions (first disk in TEDD moved inwards).

2017-04-07 12:31 UTC, ghellwig commented
@ianna there should be a corresponding GT with the updated geometry payloads, right?
Can you take care of this?

2017-04-07 12:32 UTC, kpedro88 commented
@ghellwig for phase2 we're just using XML geometries right now

If any of the changes affect phase1 then the 2017 tag should be updated

2017-04-07 12:50 UTC, ianna commented
@kpedro88 - yes, but @ghellwig is right - there is a GT and it should be updated (IMHO). I'll take care of it.

2017-04-07 12:51 UTC, ghugo83 commented on Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4025/pixfwd.xml
> +   <ZSection z="95.90*cm" rMin="2.8*cm" rMax="116.0*cm"/>
On a more general note, once I finished these TDR XMLs, I did a first-glance validation in CMSSW to solve all extrusions / overlaps with the following tools : 
- Fireworks;
- Geant4 overlap checking tool.
Any cross-check is welcome though :)

2017-04-07 13:07 UTC, ghugo83 commented
@boudoul Yes I confirm these are the changes in the geometry that correspond to these XMLs.

As regards the point on the ring in TEDD, in disks 3 to 5 : we have one ring less (12 rings instead of 13).
TEDD disks 1 and 2 still have 15 rings each.
Geometric coverage was improved in TBPS and TEDD.

2017-04-07 13:08 UTC, ghugo83 commented
I did a MB comparison between CMSSW Sim and tkLayout for this layout, will post it on Monday ;)

2017-04-07 13:12 UTC, ghellwig commented
thanks @ianna for taking care of it!

2017-04-07 13:16 UTC, cmsbuild commented
+1
Tested at: 1960e31840754b58c221be2f3a3ded9fb2af213e
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18253/18990/summary.html

2017-04-07 13:16 UTC, cmsbuild commented
Comparison job queued.

2017-04-07 16:20 UTC, ghellwig commented
+1

2017-04-07 16:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18253/18990/summary.html

Comparison Summary:
 - You potentially added 157 lines to the logs
 - Reco comparison results: 6525 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1917243
 - DQMHistoTests: Total failures: 44161
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1872909
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-10 05:27 UTC, ianna commented
+1

2017-04-10 13:14 UTC, ghugo83 commented
Material Budget comparison between CMSSW Sim and tkLayout is enclosed (for D11).
This is within Full Tracker volume, Beam Pipe excluded. 10000 tracks.
materials:Air is not taken into account here.

![ratio](https://cloud.githubusercontent.com/assets/11192654/24863073/9ff5b11c-1dff-11e7-8667-43d73d51f68b.png)

2017-04-10 16:12 UTC, kpedro88 commented
+1
2023 workflows show differences in the comparisons, primarily for tracker/tracking and related quantities, due to geometry changes. Other workflow results are unchanged.

2017-04-10 21:24 UTC, civanch commented
+1

2017-04-11 13:31 UTC, dmitrijus commented
+1

2017-04-11 14:20 UTC, ianna commented
@ghellwig - the following tags are available in DB for 2023 D11 tracker:
```
XMLFILE_Geometry_91YV5_Extended2023D11_mc
TKRECO_Geometry_91YV5
TKExtra_Geometry_91YV5
TKParameters_Geometry_91YV5
```
@kpedro88 - BTW, I noticed that HCal RECO geometry size is much bigger then it used to be. Is it really so detailed? Here is a comparison with other payloads:
```
-rw-r--r--. 1 yana zh    61440 Apr 11 16:07 CASTORRECO_Geometry.db
-rw-r--r--. 1 yana zh    57344 Apr 11 16:07 CSCRECODIGI_Geometry.db
-rw-r--r--. 1 yana zh   151552 Apr 11 16:07 CSCRECO_Geometry.db
-rw-r--r--. 1 yana zh   163840 Apr 11 16:07 CTRECO_Geometry.db
-rw-r--r--. 1 yana zh   688128 Apr 11 16:07 DTRECO_Geometry.db
-rw-r--r--. 1 yana zh  2015232 Apr 11 16:07 EBRECO_Geometry.db
-rw-r--r--. 1 yana zh   425984 Apr 11 16:07 GEMRECO_Geometry.db
-rw-r--r--. 1 yana zh  2289664 Apr 11 16:07 GeometryFileExtended2023D11.db
-rw-r--r--. 1 yana zh    61440 Apr 11 16:07 HCALParameters_Geometry.db
-rw-r--r--. 1 yana zh 27328512 Apr 11 16:07 HCALRECO_Geometry.db
-rw-r--r--. 1 yana zh   598016 Apr 11 16:07 RPCRECO_Geometry.db
-rw-r--r--. 1 yana zh  2535424 Apr 11 16:07 TKExtra_Geometry.db
-rw-r--r--. 1 yana zh    57344 Apr 11 16:07 TKParameters_Geometry.db
-rw-r--r--. 1 yana zh 12500992 Apr 11 16:07 TKRECO_Geometry.db
-rw-r--r--. 1 yana zh    57344 Apr 11 16:07 ZDCRECO_Geometry.db
```

2017-04-11 14:22 UTC, kpedro88 commented
@ianna better to ask @bsunanda about HCAL RECO geometry tag size

2017-04-11 14:31 UTC, ianna commented
@kpedro88 and @bsunanda - the tag size is proportional to the number of DetIds in Hcal reco geometry. My question is how many DetIds are there in 2023 D11 Hcal - I presume HB only?

2017-04-11 14:33 UTC, kpedro88 commented
@ianna ah, I think the Hcal DetIds are also used for HE = BH, even though the digi/reco is done in HGCal code

2017-04-11 15:10 UTC, ianna commented
@kpedro88 and @bsunanda - How much has HCal reco geometry changed since 810? The HCal reco payload size in 810 is 376832 (compared to 27328512 now).

2017-04-11 15:13 UTC, kpedro88 commented
@ianna do you mean specifically for Phase2? I don't really remember what was in 810 for Phase2.

2017-04-11 15:15 UTC, ianna commented
@kpedro88 - D1 - D6

2017-04-11 15:16 UTC, kpedro88 commented
hm, I would think C2 hasn't changed since then.

2017-04-11 16:00 UTC, ianna commented
@ghellwig - Please use a candidate GT: 91X_upgrade2023_realistic_Candidate_2017_04_11_15_56_35, D11 scenario is set a default geometry (e.g. label Extended).
Alignments need to be updated:
```
Exception Message:
Size mismatch between geometry (size=44240) and alignments (size=19876)
```

2017-04-11 16:06 UTC, boudoul commented
Hi @ghellwig , @ianna , I'm not sure what we are trying to achive here  - As pointed by @kpedro88 , we are not using the geometry GT but xmls for any phae2 scenario . There's no alignement to be applied (this is exactly why there is this line  : https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/GeometryExtended2023D11Reco_cff.py#L14 ) -

2017-04-11 16:11 UTC, boudoul commented
and for a previous comment from @kpedro88 : 
" If any of the changes affect phase1 then the 2017 tag should be updated "
the changes proposed here are NOT affecting 2017

2017-04-11 18:35 UTC, ianna commented
@boudoul - there is an upgrade2023 GT queue and even if it's not used, it should not diverge too much from a transient geometry.

2017-04-12 09:00 UTC, ianna commented
@kpedro88 and @bsunanda - I've moved the question about HCal reco geometry payload to https://github.com/cms-sw/cmssw/issues/18326

2017-04-13 14:48 UTC, perrotta commented
+1
Mostly geometry: reco updates are kind of simple
Changes are only for phase2 wfs, as expected

2017-04-13 14:52 UTC, boudoul commented
Thanks to all reviewers ! Can PdmV take a look @fabozzi , @GurpreetSinghChahal, ? Thanks

2017-04-13 15:10 UTC, merged