Run2-TB26 Add possible scenario for 2017 HGCAL TB
cms-sw/cmssw pull request #18256
Opened 2017-04-07 11:12 UTC by bsunanda

The default scenario is updated and 3 other scenario's added for 2017 TB which are foreseen as of now.

2017-04-07 11:13 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HGCalCommonData
SimG4CMS/HGCalTestBeam


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig, @makortel this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-04-07 12:26 UTC, bsunanda commented
@cmsbuild Please test

2017-04-07 12:26 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-07 12:55 UTC, ianna requested changes

2017-04-07 12:55 UTC, ianna commented on SimG4CMS/HGCalTestBeam/test/waferGeom.C
> +#include <algorithm>
@bsunanda - why is the file extension .C and not .cc?

2017-04-07 13:45 UTC, cmsbuild commented
+1
Tested at: c68a0f38279faf89e71841db2c5e58b91471f243
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/18997/summary.html

2017-04-07 13:45 UTC, cmsbuild commented
Comparison job queued.

2017-04-07 13:48 UTC, bsunanda commented on SimG4CMS/HGCalTestBeam/test/waferGeom.C
> +#include <algorithm>
This is used for analyzing the MC data and used within ROOT. I made these functions and the analyzers of TB data use them and asked me to put it in the repository

2017-04-07 15:21 UTC, ianna commented on SimG4CMS/HGCalTestBeam/test/waferGeom.C
> +#include <algorithm>
@bsunanda - I'd suggest to add a macros directory and put it there. For example: http://cmslxr.fnal.gov/source/Fireworks/Geometry/macros/

2017-04-07 15:33 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/18997/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 72 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1917243
 - DQMHistoTests: Total failures: 14994
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1902076
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-09 12:02 UTC, cmsbuild commented
Pull request #18256 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please check and sign again.

2017-04-09 12:02 UTC, bsunanda commented
@cmsbuild Please test

2017-04-09 12:03 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-09 13:18 UTC, cmsbuild commented
+1
Tested at: dfa8e7fb4f1b44ce3a3a97c88ac179eafafaf92b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/19034/summary.html

2017-04-09 13:18 UTC, cmsbuild commented
Comparison job queued.

2017-04-09 15:47 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/19034/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 1630 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1917175
 - DQMHistoTests: Total failures: 53643
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1863359
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-10 05:26 UTC, ianna commented
+1

2017-04-10 06:29 UTC, cmsbuild commented
Pull request #18256 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please check and sign again.

2017-04-10 06:29 UTC, bsunanda commented
@cmsbuild Please test

2017-04-10 06:30 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-10 07:52 UTC, cmsbuild commented
+1
Tested at: fed14149d0bc5584c0603c9f46a5f9368b055e0b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/19042/summary.html

2017-04-10 07:52 UTC, cmsbuild commented
Comparison job queued.

2017-04-10 08:34 UTC, ianna commented
+1

2017-04-10 09:56 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18256/19042/summary.html

Comparison Summary:
 - You potentially added 26 lines to the logs
 - Reco comparison results: 1682 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1917175
 - DQMHistoTests: Total failures: 21175
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1895827
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-10 10:03 UTC, civanch commented
+1

2017-04-10 12:35 UTC, bsunanda commented
@kpedro88 Please approve

2017-04-10 14:40 UTC, kpedro88 commented
+1

2017-04-10 14:40 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-04-11 13:37 UTC, davidlange6 commented
+1

2017-04-11 13:38 UTC, merged