Restore HCAL DQM to offline workflow
cms-sw/cmssw pull request #18353
Opened 2017-04-13 15:46 UTC by DryRun

Fix for non-backwards-compatible FED-to-crate tables, as discussed in https://github.com/cms-sw/cmssw/pull/17657: offline workflows have been modified to use crateId instead of FED number. 

FEDs are still used for online workflows. 

This PR contains most of the other commits from this year, which were not merged pending a fix for the fed2crate issue.

2017-04-13 15:46 UTC, cmsbuild commented
A new Pull Request was created by  @DryRun (David Yu) for master.

It involves the following packages:

DQM/HcalCommon
DQM/HcalTasks
DQM/Integration
DQMOffline/Configuration


@cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@threus, @batinkov, @deguio, @rociovilar this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-04-13 17:01 UTC, kpedro88 commented
@cmsbuild please test

2017-04-13 17:01 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-18 14:47 UTC, kpedro88 commented
I guess these tests got stuck...

2017-04-18 14:47 UTC, kpedro88 commented
@cmsbuild please test

2017-04-18 14:48 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-18 18:01 UTC, cmsbuild commented
+1
Tested at: bac262ebf06f7f44d7341dfe12c8677b0340259e
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18353/19218/summary.html

2017-04-18 18:01 UTC, cmsbuild commented
Comparison job queued.

2017-04-18 21:38 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18353/19218/summary.html

Comparison Summary:
 - You potentially added 74 lines to the logs
 - Reco comparison results: 1690 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1819408
 - DQMHistoTests: Total failures: 39063
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1780172
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-20 07:43 UTC, dmitrijus requested changes

2017-04-20 07:43 UTC, dmitrijus commented on DQM/HcalCommon/interface/ElectronicsQuantity.h
> +				std::cout << "[debug] CrateQuantity: returning nbins = " << _crates.size() << std::endl;
You probably did this for debugging purposes and forgot to disable afterwards.
Either way, cout should not be used.

2017-04-20 09:34 UTC, cmsbuild commented
Pull request #18353 was updated. @cmsbuild, @dmitrijus, @vanbesien, @davidlange6 can you please check and sign again.

2017-04-20 09:36 UTC, DryRun commented on DQM/HcalCommon/interface/ElectronicsQuantity.h
> +				std::cout << "[debug] CrateQuantity: returning nbins = " << _crates.size() << std::endl;
Thanks for spotting this. I committed a fix removing this line.

2017-04-20 09:37 UTC, dmitrijus commented
+1

2017-04-20 09:37 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-20 09:37 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-04-20 11:25 UTC, cmsbuild commented
+1
Tested at: c6bc9ce20c77f4fca0c8b9c10233058f75fef83b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18353/19288/summary.html

2017-04-20 11:25 UTC, cmsbuild commented
Comparison job queued.

2017-04-20 14:06 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18353/19288/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 3308 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1826205
 - DQMHistoTests: Total failures: 45133
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1780899
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-25 19:52 UTC, davidlange6 commented
+1
from various conversations I believe there is some consensus that splitting the "offline", "online" and "common" parts of this into separate analyzers would greatly simplify and clarify the code. Hopefully that can be done in the near future..

2017-04-25 19:53 UTC, merged