Phase2-gem27 Move GEM related geometry files in the style suggested by David
cms-sw/cmssw pull request #18437
Opened 2017-04-21 12:25 UTC by bsunanda

Correct the scenario defining files as well

2017-04-21 12:25 UTC, bsunanda commented
@cmsbuild Please test

2017-04-21 12:25 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-21 12:25 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Configuration/Geometry
Geometry/CMSCommonData
Geometry/HGCalCommonData
Geometry/HcalCommonData
Geometry/MuonCommonData


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig, @ptcox, @Martin-Grunewald this is something you requested to watch as well.
@muzaffar, @davidlange6, @smuzaffar you are the release manager for this.

cms-bot commands are listed here cms-sw/cmssw#13028

2017-04-21 14:18 UTC, cmsbuild commented
+1
Tested at: ea888f6b9a7867a539ab4244c95e2a2613fb7c89
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19318/summary.html

2017-04-21 14:18 UTC, cmsbuild commented
Comparison job queued.

2017-04-21 16:16 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19318/summary.html

Comparison Summary:
 - You potentially added 31 lines to the logs
 - Reco comparison results: 1660 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1826205
 - DQMHistoTests: Total failures: 38850
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1787182
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-23 21:25 UTC, kpedro88 commented
+1

2017-04-24 09:46 UTC, ianna requested changes

2017-04-24 09:46 UTC, ianna commented on Geometry/HcalCommonData/python/testPhase0GeometryXML_cfi.py
> +        'Geometry/CMSCommonData/data/beampipe.xml',
@bsunanda - I think, you need 2015 beampipe. The other may have overlaps.

2017-04-24 09:46 UTC, ianna commented on Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_cfi.py
> +        'Geometry/MuonCommonData/data/gem11/Run2/gem11.xml',
@bsunanda - Note, that from now on modifications to gemf.xml or gem11.xml will be rejected. Please, move them to a versioned structure to allow further modifications. For example: gem11/2017/v1/gem11.xml

2017-04-26 15:56 UTC, kpedro88 commented
I think this can also cause a conflict with #18373, so whoever is not merged first needs to rebase and rerun the 2023 geometry script

2017-04-27 09:53 UTC, cmsbuild commented
Pull request #18437 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please check and sign again.

2017-04-27 09:54 UTC, bsunanda commented
@cmsbuild Please test

2017-04-27 09:54 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-27 11:09 UTC, cmsbuild commented
+1
Tested at: 6a1b412dd859c88e76e7f9ebea145fc499db7ff0
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19434/summary.html

2017-04-27 11:09 UTC, cmsbuild commented
Comparison job queued.

2017-04-27 13:21 UTC, ianna commented
+1

2017-04-27 13:32 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19434/summary.html

Comparison Summary:
 - You potentially added 59 lines to the logs
 - Reco comparison results: 3363 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1783681
 - DQMHistoTests: Total failures: 47283
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1736225
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-27 13:59 UTC, bsunanda commented
@kpedro88 Could you sign this please. The next one is Hcal which is a beast

2017-04-27 14:58 UTC, kpedro88 commented
@bsunanda you need to rebase this on the latest IB and rerun the 2023 geometry script, as I noted before.

2017-04-28 07:06 UTC, cmsbuild commented
Pull request #18437 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please check and sign again.

2017-04-28 07:07 UTC, bsunanda commented
@cmsbuild Please test

2017-04-28 07:07 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-04-28 08:22 UTC, cmsbuild commented
+1
Tested at: de4a78d02ee542a6f9294f3e9b686ab0a9e718cd
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19451/summary.html

2017-04-28 08:22 UTC, cmsbuild commented
Comparison job queued.

2017-04-28 09:06 UTC, ianna commented
+1

2017-04-28 11:02 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19451/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1778755
 - DQMHistoTests: Total failures: 16634
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1761948
 - DQMHistoTests: Total skipped: 173
 - DQMHistoTests: Total Missing objects: 0
 - Checked 94 log files, 14 edm output root files, 23 DQM output files

2017-04-28 12:53 UTC, kpedro88 commented
+1

2017-04-28 12:53 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @muzaffar, @davidlange6, @smuzaffar

2017-05-01 15:44 UTC, kpedro88 commented
@davidlange6 @bsunanda NB, now this can have a conflict with #18524 - probably easier to merge this one first, then I can update that one

2017-05-02 13:37 UTC, kpedro88 commented
@bsunanda #18524 is now merged, so this needs to be rebased to the `CMSSW_9_1_X_2017-05-02-1100` IB with the geometry script rerun for the new configurations D15,D16,D17

2017-05-02 14:46 UTC, kpedro88 commented
-1
until rebased/updated

2017-05-02 15:39 UTC, bsunanda commented
@cmsbuild Please test

2017-05-02 15:39 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-05-02 15:39 UTC, cmsbuild commented
Pull request #18437 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @davidlange6 can you please check and sign again.

2017-05-02 15:39 UTC, bsunanda commented
@kpedro88 @ianna I have update this PR yet again. Please sign this

2017-05-02 16:25 UTC, ianna commented
+1

2017-05-02 17:05 UTC, cmsbuild commented
+1
Tested at: 24f84b8fa21f9ba69b6251f283b63f096f5f3e41
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19523/summary.html

2017-05-02 17:05 UTC, cmsbuild commented
Comparison job queued.

2017-05-02 20:02 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18437/19523/summary.html

Comparison Summary:
 - You potentially added 26 lines to the logs
 - Reco comparison results: 1670 differences found in the comparisons
 - DQMHistoTests: Total files compared: 24
 - DQMHistoTests: Total histograms compared: 1831595
 - DQMHistoTests: Total failures: 52689
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1778726
 - DQMHistoTests: Total skipped: 180
 - DQMHistoTests: Total Missing objects: 0
 - Checked 98 log files, 14 edm output root files, 24 DQM output files

2017-05-02 20:59 UTC, kpedro88 commented
+1

2017-05-02 21:00 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-05-03 08:24 UTC, davidlange6 commented
+1

2017-05-03 08:24 UTC, merged