L3 Muon Filter Fix (Backport to 91X)
cms-sw/cmssw pull request #18599
Opened 2017-05-06 22:33 UTC by BenjaminRS

This is a backport of PR #18598

2017-05-06 22:33 UTC, cmsbuild commented
A new Pull Request was created by  @BenjaminRS (Benjamin Radburn-Smith) for CMSSW_9_1_X.

It involves the following packages:

HLTrigger/Muon


@Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard, @davidlange6 can you please review it and eventually sign? Thanks.
@battibass, @abbiendi, @jhgoh, @Martin-Grunewald, @calderona, @HuguesBrun, @trocino this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-05-07 01:05 UTC, fwyzard requested changes

2017-05-07 01:05 UTC, fwyzard commented on HLTrigger/Muon/src/HLTMuonTrimuonL3Filter.cc
> +   bool useL3MTS=false;
same comments as above

2017-05-07 09:53 UTC, BenjaminRS commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +   auto tk = (*mucands)[0].track();
This is a tracker track; so maybe I can just dereference the track here:
https://github.com/BenjaminRS/cmssw/blob/9a5a3d38ba2cfe1bda5fb5598b46f39f6023d8d5/HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc#L175

2017-05-07 09:54 UTC, BenjaminRS commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +	   auto a = dynamic_cast<const L3MuonTrajectorySeed*>(tk->seedRef().get());
The dynamic_cast doesn't work if we are not using L3MuonTrajectorySeed ... if we dont use a L3MuonTrajectorySeed then we are using the normal TrajectorySeeds.

2017-05-07 10:01 UTC, fwyzard commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +   auto tk = (*mucands)[0].track();
I guess it is a TrackRef, not a track ?
Copying the TrackRef should be cheap; taking a `const &` should still be cheaper, though.

2017-05-07 10:02 UTC, fwyzard commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +	   auto a = dynamic_cast<const L3MuonTrajectorySeed*>(tk->seedRef().get());
ok

2017-05-07 10:04 UTC, fwyzard commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +	  const reco::MuonTrackLinks* link = &l;
why not simply
```c++
for(auto const & link : *links){
  ...
  const reco::Track& globalTrack = * link.globalTrack();
```

etc ?

2017-05-07 10:39 UTC, BenjaminRS commented on HLTrigger/Muon/src/HLTMuonDimuonL3Filter.cc
> +   auto tk = (*mucands)[0].track();
Yes its a TrackRef, ok I am testing with the const ref here and other suggestions below.

2017-05-08 07:28 UTC, Martin-Grunewald commented
please test

2017-05-08 07:28 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-05-08 08:38 UTC, cmsbuild commented
+1
Tested at: 094096c6583c54579ace98a04d62251e74da612c
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18599/19632/summary.html

2017-05-08 08:39 UTC, cmsbuild commented
Comparison job queued.

2017-05-08 10:50 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18599/19632/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 3347 differences found in the comparisons
 - DQMHistoTests: Total files compared: 24
 - DQMHistoTests: Total histograms compared: 1831084
 - DQMHistoTests: Total failures: 32561
 - DQMHistoTests: Total nulls: 1
 - DQMHistoTests: Total successes: 1798342
 - DQMHistoTests: Total skipped: 180
 - DQMHistoTests: Total Missing objects: 0
 - Checked 98 log files, 14 edm output root files, 24 DQM output files

2017-05-08 11:29 UTC, Martin-Grunewald commented
+1

2017-05-08 11:29 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_9_1_X IBs (tests are also fine) and once validation in the development release cycle CMSSW_9_2_X is complete. This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-05-09 08:10 UTC, BenjaminRS commented
Hello all, PR #18602 was merged for the master branch yesterday. Is there anything more that needs to be done for this backport to 91X?
Thanks,
Benjamin

2017-05-09 11:33 UTC, davidlange6 commented
+1

2017-05-09 11:33 UTC, merged