CMSSW 91X PVselections
cms-sw/cmssw pull request #18755
Opened 2017-05-15 23:04 UTC by francescobrivio

This is a "reprise" of the PR #18201 (now reverted and closed).
Basically we add two parameters in PVfitter in order to be able to apply further selection on PrimaryVertices. All python cfg files have been modified to account for these new parameters (also in DQM/BeamMonitor and in Calibration/TkAlCaRecoProducers).
The default values of the parameters are set so that nothing changes with respect to the previous situation.
We added a further switch to prevent the program from crashing when the needed track collection is not found: in that case the PVselection is not applied.
I also did some "cleaning" (removed "tabs" and useless commented lines) in order to have more or less the same indendation in all the files.

2017-05-15 23:05 UTC, cmsbuild commented
A new Pull Request was created by  @francescobrivio  for master.

It involves the following packages:

Calibration/TkAlCaRecoProducers
DQM/BeamMonitor
RecoVertex/BeamSpotProducer


@perrotta, @ghellwig, @arunhep, @cerminar, @dmitrijus, @cmsbuild, @franzoni, @slava77, @mmusich, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig, @makortel, @felicepantaleo, @GiacomoSguazzoni, @tocheng, @VinInn, @rovere, @ebrondol, @threus, @dgulhan this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-05-16 03:18 UTC, arunhep commented
please test

2017-05-16 03:19 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-05-16 06:07 UTC, cmsbuild commented
+1
Tested at: ae38b02bb1e784f8f9aa9635c2f32cf95d6d5daf
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18755/19858/summary.html

2017-05-16 06:08 UTC, cmsbuild commented
Comparison job queued.

2017-05-16 08:09 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18755/19858/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 1659 differences found in the comparisons
 - DQMHistoTests: Total files compared: 24
 - DQMHistoTests: Total histograms compared: 1829428
 - DQMHistoTests: Total failures: 40314
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1788934
 - DQMHistoTests: Total skipped: 180
 - DQMHistoTests: Total Missing objects: 0
 - Checked 98 log files, 14 edm output root files, 24 DQM output files

2017-05-19 10:08 UTC, rmanzoni commented
hi,

this PR has 91X in its title and the branch to merge has 91X in its name as well, however it is definitely meant to be in place for the data taking, that is it should enter 92X.

@francescobrivio can you please change the title to 92X?

@franzoni @arunhep might be that this slipped under your radars because of the confusing name, but this is *the* PR for 2017 BS. I see Arun triggered the tests, they went well, please have a look and give +1 (or -1 of course, if that's the case) to move forwards

2017-05-19 10:26 UTC, francescobrivio commented
@rmanzoni Title changed to 92X

2017-05-22 08:55 UTC, ghellwig requested changes
@francescobrivio can you point me to the lines of code or configuration that fix the issue mentioned in https://github.com/cms-sw/cmssw/pull/18201#issuecomment-295599218.
Unfortunately the link from David is now dead as the logs are cleaned up in the meantime.

2017-05-22 08:55 UTC, ghellwig commented on RecoVertex/BeamSpotProducer/src/PVFitter.cc
> +          catch (...)
@francescobrivio this is forbidden by the CMS code rules
Please catch only the exception you want to handle here.

2017-05-22 08:55 UTC, ghellwig commented on RecoVertex/BeamSpotProducer/src/PVFitter.cc
> +      upar.Add("ey"    , 0.010	    , 0.0001  	 , 0.   	, 10. 	    ); // 5
The PR description says that nothing changes wrt. the previous situation, but here you are changing hard-coded parameter values.
Please clarify the impact of those.

2017-05-23 12:42 UTC, perrotta commented
@francescobrivio 
- Please remove commented out lines from PVFitter.h, as you already did in previous #18201
- Please check otherwise if the track collection exists, as in the first comment of https://github.com/cms-sw/cmssw/pull/18755#pullrequestreview-39418364
- Please either explain or revert the changes in the hard coded parameters, as in the second comment of https://github.com/cms-sw/cmssw/pull/18755#pullrequestreview-39418364

2017-05-23 12:42 UTC, franzoni commented
hello @francescobrivio 
perhaps you may answer @ghellwig 's queries ?
We're preparing the PR's for our weekly ORP report and it would be good to proceed.

2017-05-23 12:55 UTC, francescobrivio commented
hi @franzoni sorry for the delay. I'm working on it right now.

2017-05-23 13:34 UTC, francescobrivio commented
hi @perrotta and @ghellwig 
I removed the commented lines in PVFitter.h and reverted the hard coded parameters in PVFitter.cc,
I just have to fix the try/catch part and then I will push the fixes.
Do you have any suggestion on how to catch a "ProductNotFound" exception in cmssw?

2017-05-23 13:54 UTC, makortel commented
@francescobrivio Check beforehand if `edm::Handle` is valid, or `Ref` is not null and is available. Here is an example how we nowadays check in the vertex validation code that the track collection referenced by the vertex collection is available in the `edm::Event` (and ignore the vertex collection if the track collection is missing)
https://github.com/cms-sw/cmssw/blob/master/Validation/RecoVertex/src/PrimaryVertexAnalyzer4PUSlimmed.cc#L1373-L1391

2017-05-23 16:47 UTC, cmsbuild commented
Pull request #18755 was updated. @perrotta, @ghellwig, @arunhep, @cerminar, @dmitrijus, @cmsbuild, @franzoni, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-05-23 16:50 UTC, francescobrivio commented
Hi @makortel thanks a lot for the tip, it was very useful!

2017-05-23 16:53 UTC, ghellwig commented
please test

2017-05-23 16:53 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-05-23 16:58 UTC, ghellwig commented
@francescobrivio thanks for the fixes, but I believe you still owe me an answer to this:

> @francescobrivio can you point me to the lines of code or configuration that fix the issue mentioned in https://github.com/cms-sw/cmssw/pull/18201#issuecomment-295599218.
Unfortunately the link from David is now dead as the logs are cleaned up in the meantime.

2017-05-23 17:16 UTC, francescobrivio commented
sorry I forgot to answer you!
the fix is indeed the try/catch which is now a more correct check on the edm::handle.
I hope this answers your question, if not, please let me know!
________________________________________
Da: Gregor Mittag [notifications@github.com]
Inviato: martedì 23 maggio 2017 18.58
A: cms-sw/cmssw
Cc: Francesco Brivio; Mention
Oggetto: Re: [cms-sw/cmssw] CMSSW 92X PVselections (#18755)

@francescobrivio<https://github.com/francescobrivio> thanks for the fixes, but I believe you still owe me an answer to this:

@francescobrivio<https://github.com/francescobrivio> can you point me to the lines of code or configuration that fix the issue mentioned in #18201 (comment)<https://github.com/cms-sw/cmssw/pull/18201#issuecomment-295599218>.
Unfortunately the link from David is now dead as the logs are cleaned up in the meantime.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/18755#issuecomment-303465968>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHddMaJURUL42nojo781d2-UKytIKo87ks5r8xBCgaJpZM4NbzTD>.

2017-05-23 17:26 UTC, ghellwig commented
+1

2017-05-23 17:26 UTC, ghellwig commented
thanks for the explanation

2017-05-23 18:03 UTC, cmsbuild commented
+1
Tested at: 7a559cea2f1b8e630aa420005b586e8ceb44aa3f
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18755/20047/summary.html

2017-05-23 18:03 UTC, cmsbuild commented
Comparison job queued.

2017-05-23 18:58 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18755/20047/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 1678 differences found in the comparisons
 - DQMHistoTests: Total files compared: 24
 - DQMHistoTests: Total histograms compared: 1833092
 - DQMHistoTests: Total failures: 9371
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1823541
 - DQMHistoTests: Total skipped: 180
 - DQMHistoTests: Total Missing objects: 0
 - Checked 98 log files, 14 edm output root files, 24 DQM output files

2017-05-23 20:53 UTC, perrotta commented
+1
As in #18201 (already merged and the reverted), this PR basically adds two extra parameters to be used for the fit of the BeamSpot: they can be used for tests, but they are kept by now at default values that fully reproduce the previous behavior of the algo.
With respect to the previous implementation, here a protection is added with a check on the presence of the track collection linked to the PV. Explicitely checked that the previous failing wf 1004 is now ending up correctly.

2017-05-23 21:02 UTC, perrotta commented
@francescobrivio : please change the title of this PR to something more descriptive. The previous "Adding the possibility to select the PVs before the BeamSpot fit" would be fine, for example.

2017-05-23 22:33 UTC, francescobrivio commented
@perrotta title changed

2017-05-24 14:34 UTC, dmitrijus commented
+1

2017-05-24 14:34 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-05-24 15:17 UTC, merged