adding new selection on the number of crystals in photon 3x3 matrix cl…
cms-sw/cmssw pull request #19228
Opened 2017-06-14 21:43 UTC by cippy

…uster and using deltaPhi function from /DataFormats/Math

- The main change is the implementation of a selection on the number of crystals in the 3x3 matrix that defines a photon according to the dedicated ECAL pi0/eta stream clustering algorithm.
- A minor fix is about using the deltaPhi() function in DataFormats/Math/interface/deltaPhi.h

These affect:
- HLTrigger/special/src/HLTRegionalEcalResonanceFilter.cc
- HLTrigger/special/interface/HLTRegionalEcalResonanceFilter.h

2017-06-14 21:43 UTC, cmsbuild commented
@cippy, CMSSW_9_2_X branch is closed for direct updates. cms-bot is going to move this PR to master branch.
In future, please use cmssw master branch to submit your changes.

2017-06-14 21:44 UTC, cmsbuild commented
A new Pull Request was created by  @cippy  for master.

It involves the following packages:

HLTrigger/special


@Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-06-14 21:49 UTC, cippy commented
Adding Emanuele di Marco and Chiara Rovelli as watchers

@emanueledimarco please follow
@crovelli  please follow

2017-06-14 21:58 UTC, fwyzard requested changes

2017-06-14 21:58 UTC, fwyzard commented on HLTrigger/special/interface/HLTRegionalEcalResonanceFilter.h
> +      //static float DeltaPhi(float phi1, float phi2);
please delete these lines instead of commenting them out

2017-06-14 21:58 UTC, fwyzard commented on HLTrigger/special/src/HLTRegionalEcalResonanceFilter.cc
> +      int Nxtal_pho2 = static_cast<int>(it_bc2->size());
use `unsigned int` or  `uint32_t` and remove the cast

2017-06-14 21:58 UTC, fwyzard commented on HLTrigger/special/src/HLTRegionalEcalResonanceFilter.cc
> +    seleNxtalBarrel_region1_ = barrelSelection.getParameter<int> ("seleNxtalBarrel_region1");
please use `unsigned int` or `uint32_t` for these parameters, as I don't think it makes sense to have negative values

2017-06-14 21:58 UTC, fwyzard commented on HLTrigger/special/src/HLTRegionalEcalResonanceFilter.cc
> +// float HLTRegionalEcalResonanceFilter::DeltaPhi(float phi1, float phi2){
same here, please remove the commented code

2017-06-14 21:58 UTC, fwyzard commented on HLTrigger/special/src/HLTRegionalEcalResonanceFilter.cc
> +	       + deltaPhi(phi1, phi2)*deltaPhi(phi1, phi2) );
I would suggest to use `std::hypot(eta1-eta2, deltaPhi(phi1, phi2))`, unless there already is some "delta R" function we can reuse.

2017-06-14 22:31 UTC, cmsbuild commented
Pull request #19228 was updated. @Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard, @davidlange6 can you please check and sign again.

2017-06-14 22:34 UTC, cippy commented
Comments implemented.

There is a "deltaR" function in /DataFormats/Math/interface/deltaR.h but based on the comments inside the header I preferred to use std:hypot()
Original HLTRegionalEcalResonanceFilter::GetDeltaR() function not needed anymore (was used only once)

2017-06-14 22:34 UTC, fwyzard commented
@cmsbuild please test

2017-06-14 22:34 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-15 00:24 UTC, cmsbuild commented
+1
Tested at: 3b15a69f474ca0e954777f6a2912c6efcf559ff2
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19228/20580/summary.html

2017-06-15 00:25 UTC, cmsbuild commented
Comparison job queued.

2017-06-15 02:13 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19228/20580/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 22
 - DQMHistoTests: Total histograms compared: 1817658
 - DQMHistoTests: Total failures: 49144
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1768348
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 90 log files, 14 edm output root files, 22 DQM output files

2017-06-15 06:29 UTC, Martin-Grunewald commented
+1

2017-06-15 06:29 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-06-15 08:00 UTC, davidlange6 commented
+1

2017-06-15 08:00 UTC, merged