Phase 1 Pixel Validation code for CMSSW_9_2_X to replace Phase 0 Pixel Validation code for Phase 1 Pixel era.
cms-sw/cmssw pull request #19403
Opened 2017-06-22 10:22 UTC by davidcarbonis

Revision of closed PRs: #18435 and #19175 . Small refinements added (such as suppressing phase 0 pixel validation output in phase 1 pixel era) and the recent DQM client changes (as the code inherits from the phase 1 pixel DQM framework). Binning for the new Hits histograms has been optimised to be of the same order of magnitude as those plots it replaces.

Added validation modules for the phase 1 pixel code based off the phase 1 dqm framework. Replicates the functionality of the phase 0 code, namely:

Digis
Hits
RecHits
Track Clusters
Tracking MC Truth (referred to as TrackingParticle in the phase 1 validation directory structure)
Validation/Configuration/python/globalValidation_cff.py; Validation/Configuration/python/postValidation_cff.py;
and Validation/Configuration/python/trackerSimValid_cff.py; have been modified so that if the era is phase1Pixel, the new validation code is used.

When in the phase 1 pixel era, the phase 0 pixel validation output is disabled. The phase0 validation has been kept in for cases where it may be needed in the future (such as a new rereco).

@fioriNTU @lunik1 @ckmackay - you might be interested in this.

@davidlange6 - Number of removed histogram bins from Phase 0 Validation for Pixel Tracker:
TrackerDigis: ~19,080
TrackerHits: ~1,440,000
TrackerRecHits: ~16,170
Total removed: ~1,475,250

Number of added histogram bins for Phase 1 Validation for Pixel Tracker:
SiPixelPhase1DigisV: ~841,600
SiPixelPhase1HitsV: ~5,006,800
SiPixelPhase1RecHitsV: ~981,640
SiPixelPhase1TrackClustersV: ~273,520
SiPixelPhase1TrackingParticleV: ~5,130
Total added: ~7,108,690

Total difference: +5,633,440 added 
N.B. Some plots in TrackerHits (~4,000,000 bins) and all plots in TrackingMCTruth (~1,630 bins) contain both pixel and strip information, and thus those bins are still filled (and not counted as removed above). In the case of the TrackerHits plots, only strip information is filled, but both pixel and strip information is still filled for TrackingMCTruth.

2017-06-22 10:23 UTC, cmsbuild commented
A new Pull Request was created by  @davidcarbonis (Alexander Morton) for master.

It involves the following packages:

Validation/Configuration
Validation/SiPixelPhase1ConfigV
Validation/SiPixelPhase1DigisV
Validation/SiPixelPhase1HitsV
Validation/SiPixelPhase1RecHitsV
Validation/SiPixelPhase1TrackClustersV
Validation/SiPixelPhase1TrackingParticleV
Validation/TrackerDigis
Validation/TrackerHits
Validation/TrackerRecHits


The following packages do not have a category, yet:

Validation/SiPixelPhase1ConfigV
Validation/SiPixelPhase1DigisV
Validation/SiPixelPhase1HitsV
Validation/SiPixelPhase1RecHitsV
Validation/SiPixelPhase1TrackClustersV
Validation/SiPixelPhase1TrackingParticleV
Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories.py to assign category

@perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@VinInn, @threus, @wmtford this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-06-22 12:51 UTC, slava77 commented
@cmsbuild please test

2017-06-22 12:51 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-22 14:29 UTC, cmsbuild commented
+1
Tested at: 00a15b63dd481a8b3bb6e01ab9ca8e5c8bd6472d
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20842/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/4bfcf97d60143ae1a56e803de7148e9d3ab6787e
https://github.com/cms-sw/cmssw/commit/1c5bd71bbc32a44aa0f0a9f9a797aab45b556f3f
https://github.com/cms-sw/cmssw/commit/8730b28a4110dcf3324f0c8f02fe5e4991840f94
https://github.com/cms-sw/cmssw/commit/259c301a5949bee03aaab3e1cfa6694a50d2ab1e
https://github.com/cms-sw/cmssw/commit/4e50f8623ce65b3e8f2290271755366c5cbc0788
https://github.com/cms-sw/cmssw/commit/d0a212b197fd609cda9afb5c965c6daa0ba6b5b8
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20842/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20842/git-merge-result

2017-06-22 14:29 UTC, cmsbuild commented
Comparison job queued.

2017-06-22 17:22 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20842/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 22
 - DQMHistoTests: Total histograms compared: 1801254
 - DQMHistoTests: Total failures: 29469
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1771619
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 90 log files, 14 edm output root files, 22 DQM output files

2017-06-23 01:37 UTC, slava77 commented
+1

for https://github.com/cms-sw/cmssw/pull/19403	00a15b6
- tangential to reco (enters via Validation/Configuration); this looks virtually the same as https://github.com/cms-sw/cmssw/pull/19175	e0aa61c, except for fewer bins in Validation/SiPixelPhase1HitsV/python/SiPixelPhase1HitsV_cfi.py and a white-space diffs in quite a few places
- jenkins tests pass

2017-06-23 13:43 UTC, dmitrijus requested changes

2017-06-23 13:43 UTC, dmitrijus commented on Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc
> +    simTC = simTrackCollection.product();
This survives and leaks outside analyze(). Please remove. The variable looks to be unused.

2017-06-23 13:43 UTC, dmitrijus commented on Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc
> +    simTC = simTrackCollection.product();
Same applies to `associatorByHits`, it should not be a class member!

2017-06-26 09:43 UTC, davidcarbonis commented on Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc
> +    simTC = simTrackCollection.product();
Sorry for the delay in getting around to fixing these.

You are correct re. simTrackCollection not being used any longer. It appears I forgot to clean up unused bits of code from previous implementation attempts.

You are correct that  `associatorByHits` is not required as a class member. It has been removed. Lines 228-232 are kept though as the variable is used for the reco to sim hit association.

These changes will be committed in the next few minutes.

2017-06-26 09:44 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-06-26 12:11 UTC, civanch commented
please test

2017-06-26 12:11 UTC, perrotta commented
please test

2017-06-26 12:11 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-26 12:17 UTC, cmsbuild commented
-1

Tested at: d014f8143ba4842f7772a2f92f30f9ec3d227475


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/fc51b5be13c935a544fbc6d7dc42b47194380ab5
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20914/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20914/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20914/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found an error when building: 
 
 <pre>>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1DigisV/src/SiPixelPhase1DigisV.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1DigisV/src/SiPixelPhase1DigisHarvesterV.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/RecoHI/plugins/HiBasicGenTest.cc 
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc:18:58: fatal error: Geometry/CommonDetUnit/interface/GeomDetUnit.h: No such file or directory
compilation terminated.
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc:18:58: fatal error: Geometry/CommonDetUnit/interface/GeomDetUnit.h: No such file or directory
compilation terminated.
gmake: *** [tmp/slc6_amd64_gcc530/src/Validation/SiPixelPhase1HitsV/src/ValidationSiPixelPhase1HitsV/SiPixelPhase1HitsV.o] Error 1
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/RecoHI/plugins/HitPixelLayersTPSelector.cc 
</pre>

* **Clang**:

I found a compilation error while trying to compile with clang: 
I used this command: 
 scram b vclean && scram build -k -j 16 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'


 <pre>>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/TrackerHits/src/TrackerHitAnalyzer.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1TrackingParticleV/src/SiPixelPhase1TrackingParticleV.cc 
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1RecHitsV/src/SiPixelPhase1RecHitsV.cc:37:40: warning: unused variable 'clust' [-Wunused-variable]
      SiPixelRecHit::ClusterRef const& clust = rechit.cluster();
                                       ^
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc:18:10: fatal error: 'Geometry/CommonDetUnit/interface/GeomDetUnit.h' file not found
#include "Geometry/CommonDetUnit/interface/GeomDetUnit.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-06-26-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc:18:10: fatal error: 'Geometry/CommonDetUnit/interface/GeomDetUnit.h' file not found
#include "Geometry/CommonDetUnit/interface/GeomDetUnit.h"
</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/fc51b5be13c935a544fbc6d7dc42b47194380ab5
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20914/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20914/git-merge-result

2017-06-26 12:17 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2017-06-26 12:23 UTC, boudoul commented
GeomDetUnit.h  has been removed recently, see #19368 how to update your PR

2017-06-26 14:30 UTC, cmsbuild commented
Pull request #19403 was updated. @ghellwig, @ianna, @kpedro88, @fabozzi, @Martin-Grunewald, @rekovic, @vanbesien, @perrotta, @civanch, @silviodonato, @cmsbuild, @fwyzard, @GurpreetSinghChahal, @davidlange6, @smuzaffar, @Dr15Jones, @kkousour, @mdhildreth, @cerminar, @slava77, @ggovi, @mulhearn, @vazzolini, @kmaeshima, @arunhep, @dmitrijus, @franzoni can you please check and sign again.

2017-06-26 14:31 UTC, davidcarbonis commented
Thanks @boudoul for pointing me in the right direction - fixed the issue.

2017-06-26 14:35 UTC, Martin-Grunewald commented
-1
rebase needed

2017-06-26 15:28 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-06-26 15:29 UTC, davidcarbonis commented
@Martin-Grunewald Attempted a rebase. Hopefully it worked (first time for everything).

2017-06-27 02:29 UTC, slava77 commented
@cmsbuild please test

2017-06-27 02:29 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-27 02:30 UTC, cmsbuild commented
-1
Tested at: UNKNOWN
 I was not able to find a release to test this PR. See the Jenkins logs for more details.

2017-06-27 08:27 UTC, perrotta commented
please test
(let check if the first 93X IB, CMSSW_9_3_X_2017-06-26-2300, is  now available for tests)

2017-06-27 08:28 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-27 11:01 UTC, cmsbuild commented
+1
Tested at: bc8d50a74bf764da4f2d98654315b474e9d489a5
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20930/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/3b01ccc4e3b8104d08bcfbecec39c470c02890cc
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20930/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20930/git-merge-result

2017-06-27 11:01 UTC, cmsbuild commented
Comparison job queued.

2017-06-27 14:10 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/20930/summary.html

Comparison Summary:
 - You potentially added 3 lines to the logs
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 22
 - DQMHistoTests: Total histograms compared: 1752601
 - DQMHistoTests: Total failures: 29471
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1722964
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 90 log files, 14 edm output root files, 22 DQM output files

2017-06-27 14:22 UTC, civanch commented
+1

2017-06-27 14:50 UTC, slava77 commented
+1

for https://github.com/cms-sw/cmssw/pull/19403	bc8d50a
- last updates were unrelated to reco category packages: in Validation/SiPixelPhase1HitsV https://github.com/cms-sw/cmssw/compare/4ce6dee66d78d7b35f111c9ce4177d63d188a829...bc8d50a74bf764da4f2d98654315b474e9d489a5
- jenkins tests pass (Reco comparison results: 0 differences found in the comparisons)

2017-07-06 06:46 UTC, dmitrijus commented
+1

2017-07-07 06:30 UTC, davidlange6 commented
hi @davidcarbonis - please make a PR to add your new package to the list at https://github.com/cms-sw/cms-bot/blob/master/categories.py

2017-07-07 08:14 UTC, davidcarbonis commented
@davidlange6 - sorry for not making the PR earlier. PR made.

2017-07-07 23:32 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-07-07 23:36 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-07-07 23:37 UTC, slava77 commented
@cmsbuild please test

2017-07-07 23:37 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-07-08 04:48 UTC, cmsbuild commented
+1
Tested at: 29ab6db37ac2dc8500fc03355e77897c5701d673
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21277/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/29ab6db37ac2dc8500fc03355e77897c5701d673
https://github.com/cms-sw/cmssw/commit/5a1ec36672608db7190ee9f485babbdcd2d42c4e
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21277/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21277/git-merge-result

2017-07-08 04:48 UTC, cmsbuild commented
Comparison job queued.

2017-07-08 09:06 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21277/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 1882672
 - DQMHistoTests: Total failures: 44298
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1838208
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 93 log files, 14 edm output root files, 23 DQM output files

2017-07-10 11:57 UTC, dmitrijus commented
+1

2017-07-10 15:03 UTC, slava77 commented on Validation/Configuration/python/postValidation_cff.py
> +phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
both phase1Pixel and run3_GEM are a part of Run3 era.
I'm not sure that there is enough magic to to make them both incrementally add the needed pieces, each starting from postValidation.copy() well above.
I think that the replacement target should be created right before the modifier call.

The same comment applies to other files in this PR with modifiers used in a similar way.

2017-07-10 15:12 UTC, davidcarbonis commented on Validation/Configuration/python/postValidation_cff.py
> +phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
Agreed - I had overlooked that. I shall update the effected files accordingly.

2017-07-11 13:10 UTC, davidcarbonis commented on Validation/Configuration/python/postValidation_cff.py
> +phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
Before I commit the changes, was this the sort of change you had in mind?

i.e. we check if it's phase 1 pixel first, but then replace that validation sequence with the Run 3 one if it is Run 3?

```
_phase1_postValidation = postValidation.copy()
_phase1_postValidation += siPixelPhase1OfflineDQM_harvestingV

_run3_postValidation = postValidation.copy()
_run3_postValidation += MuonGEMHitsPostProcessors
_run3_postValidation += MuonGEMDigisPostProcessors
_run3_postValidation += MuonGEMRecHitsPostProcessors
_run3_postValidation += siPixelPhase1OfflineDQM_harvestingV

_phase2_postValidation = _run3_postValidation.copy()
_phase2_postValidation += hgcalPostProcessor
_phase2_postValidation += MuonME0DigisPostProcessors
_phase2_postValidation += MuonME0SegPostProcessors

from Configuration.Eras.Modifier_phase1Pixel_cff import phase1Pixel
phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
from Configuration.Eras.Modifier_run2_GEM_2017_MCTest_cff import run2_GEM_2017_MCTest
run2_GEM_2017_MCTest.toReplaceWith( postValidation, _run3_postValidation )
from Configuration.Eras.Modifier_run3_GEM_cff import run3_GEM
run3_GEM.toReplaceWith( postValidation, _run3_postValidation )
from Configuration.Eras.Modifier_phase2_hgcal_cff import phase2_hgcal
phase2_hgcal.toReplaceWith( postValidation, _phase2_postValidation )
```

2017-07-13 02:42 UTC, slava77 commented on Validation/Configuration/python/postValidation_cff.py
> +phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
sorry, I missed your question.
I think that you can just move your lines right before the modifier lines (and leave everything else untouched)
```
_phase1_postValidation = postValidation.copy()
_phase1_postValidation += siPixelPhase1OfflineDQM_harvestingV
from Configuration.Eras.Modifier_phase1Pixel_cff import phase1Pixel
phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
```

the point is to keep the copies made after the previous modifiers have acted and right before the new one is to be used.

2017-07-13 10:18 UTC, davidcarbonis commented on Validation/Configuration/python/postValidation_cff.py
> +phase1Pixel.toReplaceWith( postValidation, _phase1_postValidation )
No worries - I poorly phrased an implicit question. You managed to answer it regardless though :) I'll submit the new commit shortly ...

2017-07-13 10:48 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-07-13 11:31 UTC, davidcarbonis commented
@cmsbuild please test

2017-07-13 11:44 UTC, perrotta commented
please test

2017-07-13 11:44 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-07-13 13:48 UTC, cmsbuild commented
+1
Tested at: a6c75949f0623b6b1c021d948438207e12c9e762
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21435/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9d873f4b0cd841d024834fd5e6955398035b4af4
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21435/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21435/git-merge-result

2017-07-13 13:49 UTC, cmsbuild commented
Comparison job queued.

2017-07-13 15:48 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21435/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 2020085
 - DQMHistoTests: Total failures: 14933
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2004986
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 93 log files, 14 edm output root files, 23 DQM output files

2017-07-14 12:52 UTC, dmitrijus requested changes

2017-07-14 12:52 UTC, dmitrijus commented on Validation/SiPixelPhase1ConfigV/python/SiPixelPhase1OfflineDQM_sourceV_cff.py
> +					    + SiPixelPhase1TrackingParticleAnalyzerV
Remove tabs and use spaces in python configuration files.
Here and in a few other places in this PR.

2017-07-14 13:03 UTC, davidcarbonis commented on Validation/SiPixelPhase1ConfigV/python/SiPixelPhase1OfflineDQM_sourceV_cff.py
> +					    + SiPixelPhase1TrackingParticleAnalyzerV
Understood. Will commit changes in the next few minutes.

2017-07-14 13:06 UTC, cmsbuild commented
Pull request #19403 was updated. @perrotta, @civanch, @vazzolini, @kmaeshima, @mdhildreth, @dmitrijus, @cmsbuild, @slava77, @vanbesien, @davidlange6 can you please check and sign again.

2017-07-14 15:36 UTC, perrotta commented
please test

2017-07-14 15:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-07-14 19:42 UTC, cmsbuild commented
+1
Tested at: df6ecd29c5f80c43ddf944025123334cb54a6108
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21487/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/a077a5315d5061ffa2d5d963935db289ebeeb694
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21487/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21487/git-merge-result

2017-07-14 19:42 UTC, cmsbuild commented
Comparison job queued.

2017-07-14 21:38 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19403/21487/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 23
 - DQMHistoTests: Total histograms compared: 2021099
 - DQMHistoTests: Total failures: 113
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2020820
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 93 log files, 14 edm output root files, 23 DQM output files

2017-07-17 08:43 UTC, dmitrijus commented
+1

2017-07-17 14:36 UTC, slava77 commented
+1

for https://github.com/cms-sw/cmssw/pull/19403	df6ecd2
- updates since the last reco signoff were made in  Validation/Configuration/python/globalValidation_cff.py and postValidation_cff.py to fix the load order of sequences modified in multiple modifiers for the same era. (relevant in run3 workflows)
- jenkins tests pass

2017-07-17 14:58 UTC, civanch commented
+1

2017-07-17 14:58 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-07-18 06:36 UTC, davidlange6 commented
+1

2017-07-18 06:36 UTC, merged

2017-07-18 20:33 UTC, Dr15Jones commented
This appears to be causing many segmentations faults in the RelVal workflows. E.g.
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_X_2017-07-18-1100/pyRelValMatrixLogs/run/250200.17_ZEE_13UP17+ZEE_13UP17INPUT+DIGIPRMXUP17_PU25+RECOPRMXUP17_PU25+HARVESTUP17_PU25/step3_ZEE_13UP17+ZEE_13UP17INPUT+DIGIPRMXUP17_PU25+RECOPRMXUP17_PU25+HARVESTUP17_PU25.log

2017-07-18 21:24 UTC, davidcarbonis commented
@Dr15Jones: Found where things break. Looking into why - will let you know asap and will open a PR with the fix required.

2017-07-18 23:12 UTC, davidcarbonis commented
PR: https://github.com/cms-sw/cmssw/pull/19811 solves the seg faults observed. My apologies @Dr15Jones for missing such an obvious check.

2017-09-27 02:07 UTC, slava77 commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
is this loop supposed to be inside the loop over tracks?
It seems like it should be outside.
[I arrived here after noticing that this module takes twice as much as all of reco in PU35]

2017-09-27 06:50 UTC, fioriNTU commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
Hi think this loop is here because originally the code was able to separate on-track and off-track clusters, however we decided to drop the off track clusters plots at a certain point and this loop should no more be useful. @davidcarbonis please check.

2017-09-27 09:48 UTC, davidcarbonis commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
@fioriNTU you are correct regarding the code formerly separating on- and off-track clusters and the consequently the loop no longer being useful. I'll open a PR to resolving this later today.

2017-09-27 19:25 UTC, davidcarbonis commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
@slava77 would a backport to CMSSW_9_3_X be more appropriate than a merge into the master base?

2017-09-27 19:34 UTC, boudoul commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
Hi @davidcarbonis , a PR to master is mandatory , so please make a PR there. Then you should backport - Thanks

2017-09-27 19:37 UTC, davidcarbonis commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
Cheers for clarifying @boudoul :)

2017-09-27 20:04 UTC, slava77 commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
I don't expect a 93X backport to be really necessary at this point.
93X is used for 2017 GEN-SIM and for phase-2 endcap TDR. Neither have this module running.

2017-09-27 21:33 UTC, boudoul commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
Hi @slava77 , thnaks, I was thinking of a backport just to save some time in std workflows ran in IB tests, PR tests etc..

2017-10-03 18:25 UTC, davidcarbonis commented on Validation/SiPixelPhase1TrackClustersV/src/SiPixelPhase1TrackClustersV.cc
> +  for (it = clusterColl->begin(); it != clusterColl->end(); ++it) {
Hi @boudoul and @slava77, now that the fix has been fully approved I thought I would check to re. views on backporting. I presume the consensus is not to backport?