Backport of generator parameter scan functionality to 71x
cms-sw/cmssw pull request #19443
Opened 2017-06-27 10:28 UTC by bendavid

Also brings Pythia8Interface ~in sync with master in general for easier backporting in the future.

@mkirsano

2017-06-27 10:29 UTC, cmsbuild commented
A new Pull Request was created by  @bendavid (Josh Bendavid) for CMSSW_7_1_X.

It involves the following packages:

GeneratorInterface/Configuration
GeneratorInterface/Core
GeneratorInterface/LHEInterface
GeneratorInterface/Pythia8Interface
SimDataFormats/GeneratorProducts


@cmsbuild, @govoni, @perrozzi, @thuer, @davidlange6 can you please review it and eventually sign? Thanks.
@alberto-sanchez, @agrohsje, @mkirsano this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-06-27 10:29 UTC, bendavid commented
@intrepid42  in order to bring things into sync, I effectively reverted your pull requests related to recent powheg veto hooks and then re-backported them from master.  Please check that the end result makes sense.

2017-06-27 10:56 UTC, perrozzi commented
please test

2017-06-27 10:56 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-27 11:07 UTC, mseidel42 requested changes
Ok, I have just 2 small comments

2017-06-27 11:07 UTC, intrepid42 commented on GeneratorInterface/Pythia8Interface/plugins/PowhegResHook.cc
> +      else if (abs(event[iDau].id())  <  0) ida = iDau;
This introduces a bug (abs() is always > 0)

2017-06-27 11:07 UTC, intrepid42 commented on GeneratorInterface/Pythia8Interface/test/pythia8ex12_cfg.py
> -import FWCore.ParameterSet.Config as cms
Please add back the example config.

2017-06-27 11:16 UTC, bendavid commented on GeneratorInterface/Pythia8Interface/plugins/PowhegResHook.cc
> +      else if (abs(event[iDau].id())  <  0) ida = iDau;
Ok thanks, indeed I missed a commit when restoring your changes, will update the pull request accordingly.

2017-06-27 11:17 UTC, bendavid commented on GeneratorInterface/Pythia8Interface/test/pythia8ex12_cfg.py
> -import FWCore.ParameterSet.Config as cms
Will do.

2017-06-27 12:00 UTC, cmsbuild commented
+1
Tested at: 15822b1b64242418f93618f6dfb63ccf2f3918f7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20937/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/e1124744acd737289b1905dc47c8fb337be6cb57
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20937/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20937/git-merge-result

2017-06-27 12:00 UTC, cmsbuild commented
Comparison job queued.

2017-06-27 12:47 UTC, bendavid commented
This still needs updates before it can be merged, given the comments from @intrepid42

2017-06-27 13:27 UTC, cmsbuild commented
Pull request #19443 was updated. @cmsbuild, @govoni, @perrozzi, @thuer, @davidlange6 can you please check and sign again.

2017-06-27 13:36 UTC, cmsbuild commented
Pull request #19443 was updated. @cmsbuild, @govoni, @perrozzi, @thuer, @davidlange6 can you please check and sign again.

2017-06-27 13:38 UTC, bendavid commented
Alright, I think this should be ok now.

2017-06-27 14:19 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20937/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 13
 - DQMHistoTests: Total histograms compared: 842166
 - DQMHistoTests: Total failures: 3930
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 837768
 - DQMHistoTests: Total skipped: 468
 - DQMHistoTests: Total Missing objects: 0
 - Checked 51 log files, 14 edm output root files, 13 DQM output files

2017-06-27 15:16 UTC, perrozzi commented
please test

2017-06-27 15:16 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-27 18:04 UTC, cmsbuild commented
+1
Tested at: 6843d68fbe8187ce9a83e1fb7d656daa0b0a1f2b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20953/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/e1124744acd737289b1905dc47c8fb337be6cb57
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20953/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20953/git-merge-result

2017-06-27 18:04 UTC, cmsbuild commented
Comparison job queued.

2017-06-27 18:49 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19443/20953/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 13
 - DQMHistoTests: Total histograms compared: 842166
 - DQMHistoTests: Total failures: 3934
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 837764
 - DQMHistoTests: Total skipped: 468
 - DQMHistoTests: Total Missing objects: 0
 - Checked 51 log files, 14 edm output root files, 13 DQM output files

2017-06-28 12:24 UTC, perrozzi commented
@efeyazgan

2017-06-28 12:25 UTC, perrozzi commented
@efeyazgan

2017-07-03 08:40 UTC, perrozzi commented
from what I can see and I learnt by discussing with Josh, things look ok and the feature will be active only when explicitly set ON, approving from the GEN side

2017-07-03 08:40 UTC, perrozzi commented
+1

2017-07-03 08:41 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_7_1_X IBs (tests are also fine) and once validation in the development release cycle CMSSW_9_3_X is complete. This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-07-03 09:47 UTC, bendavid commented
One caveat which I previously forgot about.
This pull request does add the new GenLumiInfoHeader data product as a lumi product even for workflows which don't use the new functionality.

This might cause problems for future 2015 MC requests with DIGI-RECO in 76x unless the corresponding data formats are added in 76x as well.  (Everything is already present in 80x and above, so no problem for 2016 MC)

2017-07-03 20:39 UTC, perrozzi commented
I have not seen a single request for 2015 MC in the last 18 months :-)

2017-07-06 16:17 UTC, davidlange6 commented
looks like its been at least 9 months since a 2015 request. Lets agree that 2015 GEN-SIM requests are now frozen to use the existing 71x releases.

2017-07-06 16:17 UTC, davidlange6 commented
+1

2017-07-06 16:17 UTC, merged

2017-07-06 17:12 UTC, perrozzi commented
agreed, thanks a lot