New feature allowing special value @currentProcess for InputTag proce…
cms-sw/cmssw pull request #19491
Opened 2017-06-30 00:05 UTC by wddgit

…ss name

2017-06-30 00:06 UTC, cmsbuild commented
A new Pull Request was created by  @wddgit (W. David Dagenhart) for master.

It involves the following packages:

FWCore/Framework
FWCore/Integration
FWCore/ParameterSet


@cmsbuild, @smuzaffar, @Dr15Jones, @davidlange6 can you please review it and eventually sign? Thanks.
@Martin-Grunewald this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-06-30 00:06 UTC, wddgit commented
please test

2017-06-30 00:06 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-30 00:14 UTC, wddgit commented
One negative comment about this new feature. If it is used and then one wants to split a single process into two processes, then a module configured this way might no longer be able to find its input. If the module was configured with an empty process name, then it would continue to succeed in this situation. I think this is why we decided not to implement this a long time ago. But I can imagine there will be some situations where this feature is useful.

2017-06-30 00:18 UTC, wddgit commented
@fwyzard This would replace PR #19285. It implements the same feature in a completely different way.

2017-06-30 02:37 UTC, cmsbuild commented
+1
Tested at: 39497dfd7d786857fd614e98c24881c2d997daee
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21012/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/31f9a620a0d872fcdc5dfead0a4d5bbcc14d90bb
https://github.com/cms-sw/cmssw/commit/1974578bdc7b4ef3a501f360274c7bec46ac7066
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21012/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21012/git-merge-result

2017-06-30 02:37 UTC, cmsbuild commented
Comparison job queued.

2017-06-30 04:54 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21012/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-19491/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17
   * /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-19491/20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 22
 - DQMHistoTests: Total histograms compared: 1756063
 - DQMHistoTests: Total failures: 15081
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1740816
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 90 log files, 14 edm output root files, 22 DQM output files

2017-06-30 14:05 UTC, Dr15Jones requested changes

2017-06-30 14:05 UTC, Dr15Jones commented on FWCore/Framework/src/EDConsumerBase.cc
> +static const std::string kCurrentProcess("@currentProcess");
How about moving this to be a class static of `InputTag` just like `kSkipCurrentProcess`?

2017-06-30 14:53 UTC, wddgit commented on FWCore/Framework/src/EDConsumerBase.cc
> +static const std::string kCurrentProcess("@currentProcess");
That would be better. I will change this.

2017-06-30 15:28 UTC, cmsbuild commented
Pull request #19491 was updated. @cmsbuild, @smuzaffar, @Dr15Jones, @davidlange6 can you please check and sign again.

2017-06-30 15:29 UTC, wddgit commented
please test

2017-06-30 15:29 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-06-30 15:37 UTC, Dr15Jones commented
+1

2017-06-30 15:37 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request requires discussion in the ORP meeting before it's merged. @davidlange6, @smuzaffar

2017-06-30 20:26 UTC, cmsbuild commented
-1

Tested at: 8fc5590a285d617500aab9492af9f0611b06fa48


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/97467bb9b4552da8afe894507ed4ca9404681e12
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test testAlignmentOfflineValidation had ERRORS



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/97467bb9b4552da8afe894507ed4ca9404681e12
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/git-merge-result

2017-06-30 20:26 UTC, cmsbuild commented
Comparison job queued.

2017-06-30 20:32 UTC, wddgit commented
The unit test that failed is not related to this PR. It is already failing in the IBs.

2017-06-30 22:13 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19491/21035/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 22
 - DQMHistoTests: Total histograms compared: 1756063
 - DQMHistoTests: Total failures: 29443
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 1726454
 - DQMHistoTests: Total skipped: 166
 - DQMHistoTests: Total Missing objects: 0
 - Checked 90 log files, 14 edm output root files, 22 DQM output files

2017-07-02 19:17 UTC, davidlange6 commented
merge

2017-07-02 19:18 UTC, merged

2017-07-03 22:54 UTC, fwyzard commented
@wddgit thank you for this.

Can I ask for a 9.2.x backport, in order to start using it at HLT ?

2017-07-05 15:58 UTC, wddgit commented
@fwyzard I will backport this to 9.2.X soon. There are couple of other things I need to finish up first.

2017-07-05 23:59 UTC, fwyzard commented
Thank you,
.A