clang check modernize-use-override
cms-sw/cmssw pull request #19529
Opened 2017-07-03 20:09 UTC by davidlange6

also for comment - this is what clang-tidy check modernize-use-override does

2017-07-03 20:09 UTC, cmsbuild commented
A new Pull Request was created by  @davidlange6 (David Lange) for master.

It involves the following packages:

Alignment/APEEstimation
Alignment/CocoaApplication
Alignment/CocoaDDLObjects
Alignment/CocoaDaq
Alignment/CocoaFit
Alignment/CocoaModel
Alignment/CocoaUtilities
Alignment/CommonAlignment
Alignment/CommonAlignmentAlgorithm
Alignment/CommonAlignmentMonitor
Alignment/CommonAlignmentParametrization
Alignment/CommonAlignmentProducer
Alignment/Geners
Alignment/HIPAlignmentAlgorithm
Alignment/LaserAlignment
Alignment/LaserAlignmentSimulation
Alignment/LaserDQM
Alignment/MillePedeAlignmentAlgorithm
Alignment/MuonAlignment
Alignment/MuonAlignmentAlgorithms
Alignment/OfflineValidation
Alignment/ReferenceTrajectories
Alignment/SurveyAnalysis
Alignment/TrackerAlignment
AnalysisAlgos/SiStripClusterInfoProducer
AnalysisAlgos/TrackInfoProducer
AnalysisDataFormats/EWK
AnalysisDataFormats/TopObjects
CalibCalorimetry/CaloMiscalibTools
CalibCalorimetry/CaloTPG
CalibCalorimetry/CastorCalib
CalibCalorimetry/EcalCorrectionModules
CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos
CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules
CalibCalorimetry/EcalLaserAnalyzer


@ghellwig, @arunhep, @cerminar, @monttj, @cmsbuild, @rekovic, @franzoni, @davidlange6, @mulhearn, @lpernie can you please review it and eventually sign? Thanks.
@ghellwig, @pakhotin, @kreczko, @abbiendi, @jhgoh, @argiro, @tocheng, @tlampen, @mschrode, @mmusich, @trocino this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-07-03 20:42 UTC, davidlange6 commented
please test

2017-07-03 20:43 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-07-04 04:14 UTC, cmsbuild commented
-1

Tested at: 7880f7b0c1432d8e6a679f9895853d0d06d676ad


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/ccc6917f9cac1f82c933e59268df17f3263c2d65
https://github.com/cms-sw/cmssw/commit/b1580cdb9b247f8d4a93ce44ec73c8c8213a595e
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19529/21105/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19529/21105/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19529/21105/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found an error when building: 
 
 <pre>>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/GMTConfigProducers/src/RecordHelper.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/GMTConfigProducers/src/L1MuGMTParametersProducer.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/GMTConfigProducers/src/SealModule.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/DTTrackFinder/src/DTPhiLutTester.cc 
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/GMTConfigProducers/src/L1MuGMTParametersOnlineProducer.cc: In member function 'void L1MuGMTParametersOnlineProducer::checkCMSSWVersion(const coral::AttributeList&)':
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/GMTConfigProducers/src/L1MuGMTParametersOnlineProducer.cc:130:60: error: statement has no effect [-Werror=unused-value]
       versionString + ", but this is "; PROJECT_VERSION "!";
                                                            ^
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/DTTrackFinder/src/DTQualPatternLutOnlineProd.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/DTTrackFinder/src/DTEtaPatternLutOnlineProd.cc 
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/L1TriggerConfig/DTTrackFinder/src/DTTrackFinderConfig.cc 
</pre>

* **Clang**:

I found a compilation error while trying to compile with clang: 
I used this command: 
 scram b vclean && scram build -k -j 16 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'


 <pre>Selected class -> LumiInfo for ROOT: LumiInfo
Selected class -> BeamCurrentInfo for ROOT: BeamCurrentInfo
Selected class -> reco::PixelClusterCounts for ROOT: reco::PixelClusterCounts
>> Compiling  /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/HeavyFlavorAnalysis/RecoDecay/src/BPHMultiSelect.cc 
In file included from /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/HeavyFlavorAnalysis/RecoDecay/src/BPHMultiSelect.cc:11:
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:85:53: error: only virtual member functions can be marked 'override'
  bool accept( const BPHDecayMomentum& cand ) const override { return false; }
                                                    ^~~~~~~~~
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-03-1100/src/HeavyFlavorAnalysis/RecoDecay/interface/BPHMultiSelect.h:129:6: note: in instantiation of template class 'BPHMultiSelect<BPHRecoSelect>' requested here
bool BPHMultiSelect<BPHRecoSelect    >::accept(
     ^
</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/ccc6917f9cac1f82c933e59268df17f3263c2d65
https://github.com/cms-sw/cmssw/commit/b1580cdb9b247f8d4a93ce44ec73c8c8213a595e
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19529/21105/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19529/21105/git-merge-result

2017-07-04 04:14 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2017-07-04 12:50 UTC, cmsbuild commented
Pull request #19529 was updated. @ghellwig, @lveldere, @perrozzi, @ianna, @kpedro88, @fabozzi, @Martin-Grunewald, @mommsen, @vanbesien, @govoni, @perrotta, @civanch, @monttj, @silviodonato, @fwyzard, @GurpreetSinghChahal, @davidlange6, @smuzaffar, @Dr15Jones, @kkousour, @ssekmen, @mdhildreth, @cerminar, @slava77, @ggovi, @mulhearn, @efeyazgan, @vazzolini, @rekovic, @kmaeshima, @arunhep, @emeschi, @thuer, @dmitrijus, @alja, @franzoni, @lpernie can you please check and sign again.

2017-07-04 16:06 UTC, slava77 commented
-1
just to have it off the reco list
the diff is too large to inspect reco files.

From the first few files that are displayed on the web interface, the change seems OK, although I'd probably keep the "virtual" specifier if it's already there.
Even though it's redundant, it was our code rule 3.26.

2017-07-04 16:36 UTC, ianna requested changes
I did not manage to get to the Geometry category - there are way to many files.

2017-07-04 16:36 UTC, ianna commented on Alignment/APEEstimation/plugins/ApeEstimator.cc
>  class ApeEstimator : public edm::EDAnalyzer {
@davidlange6 - this should be thread-safe analyzer. The rest of API changes would follow.

2017-07-04 16:36 UTC, ianna commented on Alignment/APEEstimation/plugins/ApeEstimatorSummary.cc
>  class ApeEstimatorSummary : public edm::EDAnalyzer {
@davidlange6 - the same here - it should be a thread-safe analyzer.

2017-07-04 16:36 UTC, ianna commented on Alignment/CocoaApplication/interface/CocoaAnalyzer.h
> +  ~ CocoaAnalyzer() override { }
@davidlange6 - just a general question: is COCOA still used/alive?

2017-07-04 16:36 UTC, ianna commented on Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorAsAnalyzer.cc
>  class AlignmentMonitorAsAnalyzer : public edm::EDAnalyzer {
it should be a thread-safe analyzer

2017-07-04 16:40 UTC, davidlange6 commented
this PR has only one purpose - to show what modernize-use-override does to our code (and it won't be merged in this form). Any effect to fix other old constructs existing in CMSSW is a separate discussion and PR......

but right, I think to see everything you need to just go look at my branch or checkout locally. Maybe some of the other tools will have smaller diffs..

> On Jul 4, 2017, at 6:36 PM, Ianna Osborne <notifications@github.com> wrote:
> 
> @ianna requested changes on this pull request.
> 
> I did not manage to get to the Geometry category - there are way to many files.
> 
> In Alignment/APEEstimation/plugins/ApeEstimator.cc:
> 
> > @@ -129,7 +129,7 @@
>  class ApeEstimator : public edm::EDAnalyzer {
> 
> @davidlange6 - this should be thread-safe analyzer. The rest of API changes would follow.
> 
> In Alignment/APEEstimation/plugins/ApeEstimatorSummary.cc:
> 
> > @@ -62,13 +62,13 @@
>  class ApeEstimatorSummary : public edm::EDAnalyzer {
> 
> @davidlange6 - the same here - it should be a thread-safe analyzer.
> 
> In Alignment/CocoaApplication/interface/CocoaAnalyzer.h:
> 
> > @@ -44,10 +44,10 @@ class CocoaAnalyzer : public edm::one::EDAnalyzer<edm::one::SharedResources>
>    
>    explicit  CocoaAnalyzer(edm::ParameterSet const& p);
>    explicit  CocoaAnalyzer(int i) { }
> -  virtual ~ CocoaAnalyzer() { }
> +  ~ CocoaAnalyzer() override { }
> 
> @davidlange6 - just a general question: is COCOA still used/alive?
> 
> In Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorAsAnalyzer.cc:
> 
> > @@ -66,15 +66,15 @@
>  class AlignmentMonitorAsAnalyzer : public edm::EDAnalyzer {
> 
> it should be a thread-safe analyzer
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-07-04 16:48 UTC, ianna commented
@davidlange6 - IMHO it's better to apply changes to smaller chunks of code. I'm afraid if I check the branch out, it will take a while to compile it.

2017-07-04 16:55 UTC, davidlange6 commented
I don't think I have that technology (things will be missed). eventually we will do things in steps.

> On Jul 4, 2017, at 6:48 PM, Ianna Osborne <notifications@github.com> wrote:
> 
> @davidlange6 - IMHO it's better to apply changes to smaller chunks of code. I'm afraid if I check the branch out, it will take a while to compile it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-07-07 09:05 UTC, ianna commented
-1

Please, use https://github.com/cms-sw/cmssw/pull/19610 to remove the need for geometry signature

2017-07-10 09:46 UTC, closed without merging