updating HI Jet DQM to include CS jets and removing VS jets
cms-sw/cmssw pull request #19943
Opened 2017-07-27 21:48 UTC by kurtejung

With addition of CS jets to the standard HI Workflows, we've modified the DQM modules to include some checks for the CS jet Reco, including the CS jet subtracted constituents.

Tested against today's IB: CMSSW_9_3_X_2017-07-27-1100

Also relevant for
@mandrenguyen @mverwe @cfmcginn

2017-07-27 21:49 UTC, cmsbuild commented
A new Pull Request was created by  @kurtejung (Kurt Jung) for master.

It involves the following packages:

DQMOffline/JetMET


@vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @vanbesien, @davidlange6 can you please review it and eventually sign? Thanks.
@TaiSakuma, @ahinzmann, @mmarionncern, @rappoccio, @jdolen, @nhanvtran, @gkasieczka, @schoef, @mariadalfonso, @seemasharmafnal, @rociovilar this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-07-27 22:31 UTC, kurtejung commented
For reference, the addition of CS jets was done in #19537

2017-08-02 08:58 UTC, mandrenguyen commented
Can someone trigger the tests please?

2017-08-14 11:54 UTC, kurtejung commented
Hi All - there's been no movement on this PR for more than 2 weeks.  Can we please run the tests?

2017-08-14 12:00 UTC, dmitrijus commented on DQMOffline/JetMET/python/jetAnalyzer_cff.py
> +					* jetDQMAnalyzerAkCs3PF
fix the indentation, don't mix tabs and spaces, use just spaces.

2017-08-14 12:00 UTC, dmitrijus commented on DQMOffline/JetMET/python/jetAnalyzer_cfi.py
> +					 PFcands = cms.InputTag("particleFlowTmp"),
same as above.

2017-08-14 12:02 UTC, dmitrijus requested changes

2017-08-14 12:02 UTC, dmitrijus commented on DQMOffline/JetMET/python/jetAnalyzer_cfi.py
> +					 etaMap    = cms.InputTag('hiFJRhoProducer','mapEtaEdges'),
Again, no tabs symbols are allows in python files.

2017-08-14 12:03 UTC, dmitrijus commented
please test

2017-08-14 12:03 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-14 13:28 UTC, cmsbuild commented
+1
Tested at: c3aa00a53129c7cfb3038706583d887b3820f787
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22277/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/8ef7e73e06eaf3499e183006f0ef93df28fa0c09
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22277/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22277/git-merge-result

2017-08-14 13:28 UTC, cmsbuild commented
Comparison job queued.

2017-08-14 16:36 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22277/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2712990
 - DQMHistoTests: Total failures: 256
 - DQMHistoTests: Total nulls: 18
 - DQMHistoTests: Total successes: 2712527
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 14 edm output root files, 26 DQM output files

2017-08-18 03:40 UTC, cmsbuild commented
Pull request #19943 was updated. @ghellwig, @ianna, @kpedro88, @fabozzi, @Martin-Grunewald, @rekovic, @vanbesien, @govoni, @perrotta, @civanch, @monttj, @silviodonato, @cmsbuild, @fwyzard, @GurpreetSinghChahal, @davidlange6, @smuzaffar, @Dr15Jones, @kkousour, @mdhildreth, @cerminar, @slava77, @ggovi, @mulhearn, @efeyazgan, @vazzolini, @kmaeshima, @arunhep, @perrozzi, @thuer, @dmitrijus, @franzoni, @lpernie can you please check and sign again.

2017-08-18 03:44 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-19943/194

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-19943/194/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/PR-19943/194/git-diff.patch | patch -p1`

In future, you can run `scram build code-checks` to apply code checks

2017-08-18 03:46 UTC, kurtejung commented
sorry i seem to have gone through the git rite of passage on accident - reverting...

2017-08-18 04:07 UTC, cmsbuild commented
Pull request #19943 was updated. @kmaeshima, @cmsbuild, @vanbesien, @vazzolini, @dmitrijus can you please check and sign again.

2017-08-18 04:09 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-19943/195

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-19943/195/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/PR-19943/195/git-diff.patch | patch -p1`

In future, you can run `scram build code-checks` to apply code checks

2017-08-18 04:13 UTC, cmsbuild commented
Pull request #19943 was updated. @kmaeshima, @cmsbuild, @vanbesien, @vazzolini, @dmitrijus can you please check and sign again.

2017-08-18 04:13 UTC, kurtejung commented
should be taken care of now - please let me know if there's more to be fixed. thanks.

2017-08-18 04:16 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-19943/196

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-19943/196/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/PR-19943/196/git-diff.patch | patch -p1`

In future, you can run `scram build code-checks` to apply code checks

2017-08-22 09:01 UTC, kurtejung commented
hi @dmitrijus - are these changes acceptable?

2017-08-23 09:05 UTC, dmitrijus commented
+1

2017-08-23 09:05 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-23 09:05 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-08-23 11:10 UTC, cmsbuild commented
+1
Tested at: e6990ee5f7e41a2f8ffc23363ae640332b48c357
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22441/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/dbd8653f98656d364a0000b5d4134ebd48491af1
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22441/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22441/git-merge-result

2017-08-23 11:10 UTC, cmsbuild commented
Comparison job queued.

2017-08-23 12:46 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22441/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2653352
 - DQMHistoTests: Total failures: 216
 - DQMHistoTests: Total nulls: 51
 - DQMHistoTests: Total successes: 2652896
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 14 edm output root files, 26 DQM output files

2017-08-23 22:10 UTC, davidlange6 commented on DQMOffline/JetMET/interface/JetAnalyzer_HeavyIons.h
> +  static const Int_t fourierOrder_ = 5;
hi @kurtejung - please use int rather than Int_t. Second, constexpr instead of static const would be more appropriate.

2017-08-24 17:03 UTC, davidlange6 commented
-1
pending answers to small comments

2017-08-24 20:55 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-08-24 20:55 UTC, cmsbuild commented
Pull request #19943 was updated. @ghellwig, @ianna, @kpedro88, @fabozzi, @rekovic, @vanbesien, @perrotta, @civanch, @monttj, @cmsbuild, @GurpreetSinghChahal, @smuzaffar, @Dr15Jones, @kkousour, @mdhildreth, @cerminar, @slava77, @ggovi, @mulhearn, @vazzolini, @kmaeshima, @arunhep, @dmitrijus, @franzoni, @lpernie can you please check and sign again.

2017-08-24 20:58 UTC, kpedro88 commented
-1
please follow http://cms-sw.github.io/tutorial-resolve-conflicts.html#recovering-from-a-bad-rebase-or-merge to undo what you just did and then use `cms-rebase-topic` or `cms-checkout-topic` as appropriate to rebase or recreate a working area, as described elsewhere on that page

2017-08-24 20:59 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-19943/306

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-19943/306/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/PR-19943/306/git-diff.patch | patch -p1`

In future, you can run `scram build code-checks` to apply code checks

2017-08-24 21:13 UTC, kurtejung commented
sorry about that - thats shockingly easy to do on the IB

2017-08-24 21:14 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-08-24 21:14 UTC, kpedro88 commented
from now on, just use rebase-topic instead of merge-topic to move to a new IB

2017-08-24 21:33 UTC, kurtejung commented
hi @davidlange6 - the static tag is required to ensure compatibility with its use in the array declaration below.  I changed to "static constexpr int".

2017-08-24 21:34 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-08-24 21:34 UTC, cmsbuild commented
Pull request #19943 was updated. @kmaeshima, @cmsbuild, @vanbesien, @vazzolini, @dmitrijus can you please check and sign again.

2017-08-24 21:35 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-19943/307

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-19943/307/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/PR-19943/307/git-diff.patch | patch -p1`

In future, you can run `scram build code-checks` to apply code checks

2017-08-31 13:16 UTC, dmitrijus commented
+1

2017-08-31 13:16 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-31 13:16 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-08-31 15:52 UTC, cmsbuild commented
+1
Tested at: 54ed0b9f05eab7dfd49855c76b89d73fee7a5ba4
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22614/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/94fab3e019e00215c7cc5373d84b920601f2aef5
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22614/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22614/git-merge-result

2017-08-31 15:52 UTC, cmsbuild commented
Comparison job queued.

2017-08-31 18:19 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19943/22614/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2655459
 - DQMHistoTests: Total failures: 211
 - DQMHistoTests: Total nulls: 51
 - DQMHistoTests: Total successes: 2655008
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 14 edm output root files, 26 DQM output files

2017-09-04 11:37 UTC, davidlange6 commented
+1

2017-09-04 11:37 UTC, merged

2017-09-05 21:34 UTC, smuzaffar commented
@kurtejung , couple of relval tests are failing after the integration of this PR in 93X IBs. The error message is
```
cmsRun: .../src/DQMOffline/JetMET/src/JetAnalyzer_HeavyIons.cc:607: virtual void JetAnalyzer_HeavyIons::analyze(const edm::Event&, const edm::EventSetup&): Assertion `csCandidateColl->size() < pfCandidateColl->size()' failed.
```

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_X_2017-09-05-1500/pyRelValMatrixLogs/run/140.52_RunHI2010+RunHI2010+RECOHID10+RECOHIR10D11+HARVESTDHI/step2_RunHI2010+RunHI2010+RECOHID10+RECOHIR10D11+HARVESTDHI.log

You can re-produce it by running ```runTheMatrix.py -l 140.52  --useInput all  -t 4``` . Can you please check and provide a fix.

2017-09-11 10:09 UTC, smuzaffar commented
@kurtejung , any update?

2017-09-11 13:23 UTC, kurtejung commented
hi @smuzaffar - I forgot an "<=" instead of a < in the assert line.  Should I make a new PR to push this since this is already merged?

2017-09-11 13:28 UTC, smuzaffar commented
yes please make a new PR. Thanks

2017-09-11 13:30 UTC, kurtejung commented
Done - PR #20454 created