New module which filters on logical expressions of Paths
cms-sw/cmssw pull request #20028
Opened 2017-08-02 19:22 UTC by wddgit

2017-08-02 19:22 UTC, cmsbuild commented
A new Pull Request was created by  @wddgit (W. David Dagenhart) for master.

It involves the following packages:

FWCore/Modules


@cmsbuild, @smuzaffar, @Dr15Jones can you please review it and eventually sign? Thanks.
@Martin-Grunewald this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-08-02 19:23 UTC, wddgit commented
please test

2017-08-02 19:23 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-02 20:01 UTC, Dr15Jones requested changes

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +    std::unique_ptr<pathStatusExpression::Evaluator> evaluator_;
Please see of `edm::propagate_const` can be used here.

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +      std::unique_ptr<Evaluator> operand_;
`std::propagate_const` here as well.

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +    class AndOperator : public Evaluator {
You could templatize the binary operator so you can share code between `And` and `Or`.

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +      virtual void setLeft(std::unique_ptr<Evaluator> && v) { operand_ = std::move(v); }
`override`

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +      virtual void setLeft(std::unique_ptr<Evaluator> && v) { left_ = std::move(v); }
`override` on both of these

2017-08-02 20:01 UTC, Dr15Jones commented on FWCore/Modules/src/PathStatusFilter.cc
> +      std::unique_ptr<Evaluator> left_;
`std::propagate_const`

2017-08-02 21:06 UTC, cmsbuild commented
+1
Tested at: 529de15fe7ac2372805be1520b423cffa78e9e7b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22026/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/f2e1b838950306bb054337f3416de8ee3b9d9905
https://github.com/cms-sw/cmssw/commit/9b8817fe6cb683a2a006008d165efa16ad257a3c
https://github.com/cms-sw/cmssw/commit/0655717cbd4f76fe5d3d1264c0b038ade11bab62
https://github.com/cms-sw/cmssw/commit/55c74ec96770bab1f37795c6cb88e51d0b8012c0
https://github.com/cms-sw/cmssw/commit/702105cf35e95b1fa2de7e63ac4bb5ad86479745
https://github.com/cms-sw/cmssw/commit/6e42d43fda0d479ba2f034c768087bf23b384962
https://github.com/cms-sw/cmssw/commit/393fae0319564c7f393334a9db92f59676786449
https://github.com/cms-sw/cmssw/commit/75a9ea0990552d69c378e449f3bab88ff75f96c1
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22026/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22026/git-merge-result

2017-08-02 21:06 UTC, cmsbuild commented
Comparison job queued.

2017-08-02 23:46 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22026/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 25
 - DQMHistoTests: Total histograms compared: 2625965
 - DQMHistoTests: Total failures: 46700
 - DQMHistoTests: Total nulls: 211
 - DQMHistoTests: Total successes: 2578873
 - DQMHistoTests: Total skipped: 181
 - DQMHistoTests: Total Missing objects: 0
 - Checked 102 log files, 14 edm output root files, 25 DQM output files

2017-08-03 04:44 UTC, Martin-Grunewald commented
What is the difference wrt the ```TriggerResultsFilter``` ?

2017-08-03 14:04 UTC, Dr15Jones commented
@Martin-Grunewald `TriggerResultsFilter` must wait until the `TriggerResults` is created which happens after all Paths have finished. This new module uses the individual `PathStatus` which are available once the Path has finished. This allows one to use the new module to use the results of one Path to influence the results of another Path. That is not something that `TriggerResultsFilter` can do.

2017-08-03 14:11 UTC, Martin-Grunewald commented
Ah, OK. 

What happens if one instance is on path A asking for path B and one instance is on path B asking for path A - how is the deadlock resolved? Or A->B->C->D->A?

2017-08-03 14:14 UTC, Dr15Jones commented
> What happens if one instance is on path A asking for path B and one instance is on path B asking for path A - how is the deadlock resolved? Or A->B->C->D->A?

The framework will throw an 'unrunnable schedule' exception before it starts to process data.

2017-08-03 14:18 UTC, Martin-Grunewald commented
I suppose the same throw if an instance asks for a non-existing path, right?

2017-08-03 14:20 UTC, Dr15Jones commented
I assume under that case you'd get a 'product missing' exception at run time.

The 'unrunnable schedule' is something the framework would throw anytime two modules say they depend on each other. 

The PathStatus object is just threated like any other data product in the Event.

2017-08-03 14:23 UTC, wddgit commented
Yes a Product Not Found exception is what you would get with the current version of this (although I could probably change that if we wanted some other error)

2017-08-03 14:24 UTC, Martin-Grunewald commented
OK, thanks for the clarifications!

2017-08-03 14:43 UTC, wddgit commented
A few more differences. This new filter does not support prescalers. It does not support reading path results from prior processes, only the current one. It does not get L1 trigger results. And there are some other options in TriggerResultsFilter that it does not support. The new filter does not support the XOR operator.  (These things could be added, but they are not in the current version of the new filter and as far as I know we do not plan to add them)

One other comment I will add. I could be completely wrong about this because I did not test it or spend a lot of time studying it. I likely just didn't understand the code. But in reading through it, I got the impression that TriggerResultsFilter did not get precedence order of the operators correct unless you used parentheses and that the NOT operator would not work. But most likely I just didn't understand the code because I didn't spend enough time studying it. Are there tests for those things somewhere?

2017-08-03 14:48 UTC, Martin-Grunewald commented
@fwyzard 
re @wddigit comment on issues with the ```TriggerResultsFilter```

2017-08-03 18:56 UTC, cmsbuild commented
Pull request #20028 was updated. @cmsbuild, @smuzaffar, @Dr15Jones can you please check and sign again.

2017-08-03 18:59 UTC, wddgit commented
The commit I just pushed should resolve all the comments from Chris. All good suggestions and I implemented them all.

2017-08-03 19:01 UTC, wddgit commented
please test

2017-08-03 19:01 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-03 19:08 UTC, Dr15Jones commented
+1

2017-08-03 19:08 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-08-03 20:34 UTC, cmsbuild commented
+1
Tested at: 2a328063710cab4ac48f2edf224f1c9c130bd473
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22078/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/cf6d2ab13b91fa5e0647df9baa064c31a09f9e7a
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22078/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22078/git-merge-result

2017-08-03 20:34 UTC, cmsbuild commented
Comparison job queued.

2017-08-03 22:33 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20028/22078/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 25
 - DQMHistoTests: Total histograms compared: 2643105
 - DQMHistoTests: Total failures: 29993
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2612931
 - DQMHistoTests: Total skipped: 181
 - DQMHistoTests: Total Missing objects: 0
 - Checked 102 log files, 14 edm output root files, 25 DQM output files

2017-08-04 06:32 UTC, davidlange6 commented
+1

2017-08-04 06:33 UTC, merged