FIX in GBL reference trajectories: add missing initialisations
cms-sw/cmssw pull request #20262
Opened 2017-08-24 16:30 UTC by mschrode

Adds missing matrix initialisations to the EIGEN matrices.
This was not needed in previous implementation of GBL based on ROOT TMatrix
(ROOT presets matrices to 0., EIGEN not).

Fix provided by @ckleinw

2017-08-24 16:30 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-08-24 16:30 UTC, cmsbuild commented
A new Pull Request was created by  @mschrode (Matthias Schroeder) for master.

It involves the following packages:

Alignment/ReferenceTrajectories


@ghellwig, @arunhep, @cerminar, @cmsbuild, @franzoni, @lpernie can you please review it and eventually sign? Thanks.
@ghellwig, @mmusich, @tocheng, @tlampen this is something you requested to watch as well.
@davidlange6, @slava77 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-08-24 16:32 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-20262/298

2017-08-29 12:51 UTC, franzoni commented
please test

2017-08-29 12:52 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-08-29 16:16 UTC, cmsbuild commented
+1
Tested at: 2c787dea21ec2046199633ba470dbfcff496bc3e
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/22556/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/f91659fc4e82a51406a453fdd846a0c2023f435e
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/22556/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/22556/git-merge-result

2017-08-29 16:16 UTC, cmsbuild commented
Comparison job queued.

2017-08-29 17:58 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/22556/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2653934
 - DQMHistoTests: Total failures: 217
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2653528
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 14 edm output root files, 26 DQM output files

2017-09-04 07:31 UTC, ghellwig requested changes
@mschrode Seem to be only minor changes and therefore, I have only the cosmetic comments above.
However, since you use hardcoded numbers (5, 7), you should include them.

PS: Back from parental leave ;)

2017-09-04 07:31 UTC, ghellwig commented on Alignment/ReferenceTrajectories/src/GblTrajectory.cc
> +    for (unsigned int i = 0; i < 5; ++i) anIndex[i] = 0;
@ckleinw, @mschrode I propose to replace this with the simpler statement
```
anIndex = {};
```
This sets every non-specified element to zero, i.e. all of them.

2017-09-04 07:31 UTC, ghellwig commented on Alignment/ReferenceTrajectories/src/GblTrajectory.cc
> +    for (unsigned int i = 0; i < 7; ++i) anIndex[i] = 0;
see above

2017-09-04 07:31 UTC, ghellwig commented on Alignment/ReferenceTrajectories/src/GblTrajectory.cc
> +	      matPDer.setZero();
@mschrode please stick to the indentation. This is likely due to tabs in the preceding whitespace.

2017-09-04 07:31 UTC, ghellwig commented on Alignment/ReferenceTrajectories/src/GblTrajectory.cc
> +	      proDer.setZero();
see above

2017-09-04 07:31 UTC, ghellwig commented on Alignment/ReferenceTrajectories/src/GblTrajectory.cc
> +	      proDer.setZero();
see above

2017-09-06 09:21 UTC, ghellwig commented
@mschrode Since the master is now 94X, you might consider backporting this (now 94X) PR to 93X.
As @arunhep pointed out in your other backports, you can close the PRs for 90X and 91X.

2017-09-11 06:55 UTC, ghellwig commented
@mschrode despite of what wrote in #20430, your PR for 94X is not fully superseded as I just saw.
You also change one line in [Alignment/ReferenceTrajectories/src/TwoBodyDecayTrajectory.cc](https://github.com/cms-sw/cmssw/pull/20262/files#diff-644bb0c2969220175cb518466a508f29) and this to happen also with GBL removed from CMSSW.

2017-09-19 14:09 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-09-19 14:10 UTC, mschrode commented
@ghellwig I just modified the commit of this PR by removing the changes to the superseded files

2017-09-19 14:11 UTC, ghellwig commented
please test

2017-09-19 14:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-20262/815

2017-09-19 14:11 UTC, ghellwig commented
type bugfix

2017-09-19 14:11 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-09-19 14:11 UTC, cmsbuild commented
Pull request #20262 was updated. @ghellwig, @arunhep, @cerminar, @cmsbuild, @franzoni, @lpernie can you please check and sign again.

2017-09-19 14:11 UTC, ghellwig commented
+1
provided jenkins agrees

2017-09-19 14:11 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-09-19 15:48 UTC, cmsbuild commented
-1

Tested at: 3eb947677bd7e44df50a19b5b037ac053eea12a0


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/e133687c2dd23771612485bf4baf046b9317e8e8
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23075/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23075/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23075/summary.html

I found follow errors while testing this PR

**Failed tests:  AddOn**

* **AddOn**:

I found errors in the following addon tests:

cmsDriver.py RelVal -s L1REPACK:Full --data --scenario=pp -n 10 --conditions auto:run2_hlt_PIon --relval 9000,50 --datatier "RAW" --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run2_2017 --eventcontent RAW --fileout file:RelVal_Raw_PIon_DATA.root --filein /store/data/Run2017A/HLTPhysics4/RAW/v1/000/295/606/00000/36DE5E0A-3645-E711-8FA1-02163E01A43B.root : FAILED - time: date Tue Sep 19 17:10:39 2017-date Tue Sep 19 17:07:26 2017 s - exit: 23552
cmsRun /cvmfs/cms-ib.cern.ch/nweek-02490/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_X_2017-09-19-0700/src/HLTrigger/Configuration/test/OnLine_HLT_PIon.py realData=True  globalTag=@ inputFiles=@  : FAILED - time: date Tue Sep 19 17:10:39 2017-date Tue Sep 19 17:07:26 2017 s - exit: 21504
cmsDriver.py RelVal -s HLT:PIon,RAW2DIGI,L1Reco,RECO --data --scenario=pp -n 10 --conditions auto:run2_data_PIon --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2017 --processName=HLTRECO --filein file:RelVal_Raw_PIon_DATA.root --fileout file:RelVal_Raw_PIon_DATA_HLT_RECO.root : FAILED - time: date Tue Sep 19 17:10:39 2017-date Tue Sep 19 17:07:26 2017 s - exit: 21504



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/e133687c2dd23771612485bf4baf046b9317e8e8
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23075/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23075/git-merge-result

2017-09-19 15:48 UTC, cmsbuild commented
Comparison job queued.

2017-09-19 15:57 UTC, ghellwig commented
failure seems unrelated
I have seen this already in another PR, but I retriggered the tests after fixing something minor that was totally unrelated to the addOn test, but the tests passed the second time
@davidlange6, @smuzaffar is there some known issue?

2017-09-19 16:58 UTC, ghellwig commented
please test
(hoping the xrootd failure vanishes...)

2017-09-19 16:58 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-09-19 20:46 UTC, cmsbuild commented
+1
Tested at: 3eb947677bd7e44df50a19b5b037ac053eea12a0
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23093/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/5e53c2b9539aa99597276fc2af455b7acffca3cf
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23093/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23093/git-merge-result

2017-09-19 20:46 UTC, cmsbuild commented
Comparison job queued.

2017-09-19 23:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20262/23093/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2649068
 - DQMHistoTests: Total failures: 231
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2648648
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 14 edm output root files, 26 DQM output files

2017-09-20 07:36 UTC, davidlange6 commented
+1

2017-09-20 07:37 UTC, merged