dqm for triplemuon_5_3_3_dz in master br.
cms-sw/cmssw pull request #20635
Opened 2017-09-23 10:46 UTC by gkaratha

Dear @mtosi @davidlange6 ,

I did the changes that were asked. And also the PR in master branch as well. Now there is one PR in master, one in 9_3_X and one in 9_2_X(backport of 9_3_X). For any other comment i am at your disposal. Thanks.

Best,
george

2017-09-23 10:46 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-09-23 10:48 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-20635/931

2017-09-23 10:48 UTC, cmsbuild commented
A new Pull Request was created by  @gkaratha  for master.

It involves the following packages:

DQMOffline/Trigger


@kmaeshima, @cmsbuild, @vanbesien, @vazzolini, @dmitrijus can you please review it and eventually sign? Thanks.
@battibass, @mtosi, @jhgoh, @calderona, @HuguesBrun, @trocino, @rociovilar this is something you requested to watch as well.
@davidlange6, @slava77 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-09-25 09:54 UTC, mtosi commented
@cmsbuild, please test

2017-09-25 09:55 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-09-25 12:38 UTC, cmsbuild commented
+1
Tested at: 67554a131c5f49c209c5b2c9b5f75e6c0a21beb9
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23202/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/630acaf4d413c283cf6a9ae3be6037f071b994cb
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23202/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23202/git-merge-result

2017-09-25 12:38 UTC, cmsbuild commented
Comparison job queued.

2017-09-25 13:18 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23202/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2691683
 - DQMHistoTests: Total failures: 226
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2691268
 - DQMHistoTests: Total skipped: 189
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 15 edm output root files, 26 DQM output files

2017-09-29 14:38 UTC, dmitrijus requested changes

2017-09-29 14:38 UTC, dmitrijus commented on DQMOffline/Trigger/plugins/TopMonitor.cc
> +                       }
please please indent your code
this is confusing and unreadable

2017-09-29 14:38 UTC, dmitrijus commented on DQMOffline/Trigger/python/SusyMonitoring_Client_cff.py
> +"effic_muPt_1       'efficiency vs muon pt; muon pt [GeV]; efficiency' muPt_1_numerator       muPt_1_variableBinning_denominator",
same as above

2017-10-03 11:49 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-10-03 11:49 UTC, gkaratha commented on DQMOffline/Trigger/python/SusyMonitoring_Client_cff.py
> +"effic_muPt_1       'efficiency vs muon pt; muon pt [GeV]; efficiency' muPt_1_numerator       muPt_1_variableBinning_denominator",
Hi @dmitrijus ,

Ok fixed thanks

2017-10-03 11:53 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/PR-20635/1107

2017-10-03 11:53 UTC, cmsbuild commented
Pull request #20635 was updated. @kmaeshima, @cmsbuild, @vanbesien, @vazzolini, @dmitrijus can you please check and sign again.

2017-10-04 08:41 UTC, dmitrijus commented
+1

2017-10-04 08:41 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-10-04 08:41 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar (and backports should be raised in the release meeting by the corresponding L2)

2017-10-04 10:49 UTC, cmsbuild commented
+1
Tested at: 73130a542667e8c24e71fd74138a1604e5272444
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23425/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/575a47c1dc033097d7d5fbda7e2fe14f71ee98b9
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23425/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23425/git-merge-result

2017-10-04 10:49 UTC, cmsbuild commented
Comparison job queued.

2017-10-04 11:29 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20635/23425/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2761357
 - DQMHistoTests: Total failures: 244
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2760926
 - DQMHistoTests: Total skipped: 187
 - DQMHistoTests: Total Missing objects: 0
 - Checked 107 log files, 10 edm output root files, 26 DQM output files

2017-10-05 08:43 UTC, mtosi commented
@davidlange6 @dmitrijus 
can we proceed w/ the merge ?
thanks !

2017-10-10 06:26 UTC, davidlange6 commented
merge

2017-10-10 06:27 UTC, merged