Tau HLT L1 match update
cms-sw/cmssw pull request #21697
Opened 2017-12-13 10:36 UTC by tstreble

This PR:
- introduces a new CaloTower producer for the regional PFlow based on L1 Tau objects associated with a fired L1 seed

2017-12-13 10:37 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-12-13 10:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21697/2569

2017-12-13 10:39 UTC, cmsbuild commented
A new Pull Request was created by  @tstreble  for master.

It involves the following packages:

RecoTauTag/HLTProducers


@Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard can you please review it and eventually sign? Thanks.
@davidlange6, @slava77 you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2017-12-13 11:23 UTC, fwyzard requested changes

2017-12-13 11:23 UTC, fwyzard commented on RecoTauTag/HLTProducers/src/CaloTowerFromL1TSeededCreatorForTauHLT.cc
> +CaloTowerFromL1TSeededCreatorForTauHLT::~CaloTowerFromL1TSeededCreatorForTauHLT() {
please replace this with
`CaloTowerFromL1TSeededCreatorForTauHLT::~CaloTowerFromL1TSeededCreatorForTauHLT() = default;`

2017-12-13 11:23 UTC, fwyzard commented on RecoTauTag/HLTProducers/interface/CaloTowerFromL1TSeededCreatorForTauHLT.h
> +  const int mVerbose;
please change the data members to follow the CMSSW naming conventions: either `m_verbose` or `verbose_`, and similarly for the others

2017-12-13 11:23 UTC, fwyzard commented on RecoTauTag/HLTProducers/src/CaloTowerFromL1TSeededCreatorForTauHLT.cc
> +  std::unique_ptr<CaloTowerCollection> cands( new CaloTowerCollection );
please use
```c++
auto cands = std::make_unique<CaloTowerCollection>();
```

2017-12-13 11:23 UTC, fwyzard commented on RecoTauTag/HLTProducers/src/CaloTowerFromL1TSeededCreatorForTauHLT.cc
> +  for(unsigned int iL1Tau = 0; iL1Tau < tauCandRefVec.size(); iL1Tau++){
please use
```c++
for(auto const& tauCandRef: tauCandRefVec){
```
and change `tauCandRefVec[iL1Tau]` to `tauCandRef` below.

2017-12-13 11:23 UTC, fwyzard commented
@cmsbuild, please test

2017-12-13 11:24 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-12-13 13:19 UTC, cmsbuild commented
+1
Tested at: 083d330735c5d4f451af39cf163b995d1c960382
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25073/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/25dd0613be10f0c654f7556670b4968aa6b26122
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25073/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25073/git-merge-result

2017-12-13 13:19 UTC, cmsbuild commented
Comparison job queued.

2017-12-13 13:34 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-12-13 13:37 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21697/2572

2017-12-13 13:37 UTC, cmsbuild commented
Pull request #21697 was updated. @Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard can you please check and sign again.

2017-12-13 14:15 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25073/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21697/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 18 differences found in the comparisons
 - DQMHistoTests: Total files compared: 27
 - DQMHistoTests: Total histograms compared: 2835291
 - DQMHistoTests: Total failures: 2872
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2832241
 - DQMHistoTests: Total skipped: 178
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.54999999986 KiB( 23 files compared)
 - Checked 113 log files, 9 edm output root files, 27 DQM output files

2017-12-14 07:14 UTC, Martin-Grunewald commented
please test

2017-12-14 07:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-12-14 09:20 UTC, cmsbuild commented
+1
Tested at: adbcc127880714690d9d1cc95760c42299a391d2
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25086/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/a4f36f26b092be8d42543d9bcf166711294af0ca
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25086/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25086/git-merge-result

2017-12-14 09:20 UTC, cmsbuild commented
Comparison job queued.

2017-12-14 11:36 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25086/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21697/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 20 differences found in the comparisons
 - DQMHistoTests: Total files compared: 27
 - DQMHistoTests: Total histograms compared: 2836711
 - DQMHistoTests: Total failures: 3984
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2832549
 - DQMHistoTests: Total skipped: 178
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.3800000001 KiB( 23 files compared)
 - Checked 113 log files, 9 edm output root files, 27 DQM output files

2017-12-19 11:04 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2017-12-19 20:03 UTC, davidlange6 commented on RecoTauTag/HLTProducers/src/CaloTowerFromL1TSeededCreatorForTauHLT.cc
> +    for (; idx < caloTowers->size(); idx++) {
hi @tstreble - please use a range based loop here

2017-12-19 20:03 UTC, davidlange6 commented on RecoTauTag/HLTProducers/src/CaloTowerFromL1TSeededCreatorForTauHLT.cc
> +	double delta  = ROOT::Math::VectorUtil::DeltaR((tauCandRef->p4()).Vect(), p);
please use DataFormats/Math/interface/deltaR (or better deltaR2)

2017-12-20 10:49 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2017-12-20 10:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21697/2692

2017-12-20 10:52 UTC, cmsbuild commented
Pull request #21697 was updated. @Martin-Grunewald, @silviodonato, @cmsbuild, @fwyzard can you please check and sign again.

2017-12-20 10:59 UTC, Martin-Grunewald commented
please test

2017-12-20 11:00 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2017-12-20 12:41 UTC, cmsbuild commented
+1
Tested at: 45ff9e875e84361c421eb89a8c2b2e11f0e2739a
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25204/summary.html

2017-12-20 12:41 UTC, cmsbuild commented
Comparison job queued.

2017-12-20 14:04 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21697/25204/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins-workarea/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21697/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 27
 - DQMHistoTests: Total histograms compared: 2832934
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2832755
 - DQMHistoTests: Total skipped: 178
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.37000000006 KiB( 23 files compared)
 - Checked 113 log files, 9 edm output root files, 27 DQM output files

2017-12-20 14:18 UTC, Martin-Grunewald commented
+1

2017-12-20 14:19 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2017-12-20 15:51 UTC, davidlange6 commented
merge

2017-12-20 15:52 UTC, merged