OnlineDB/CSCCondDB: Change return type of ESProducer::produce methods to unique_ptr or shared_ptr.
cms-sw/cmssw pull request #21916
Opened 2018-01-22 18:20 UTC by gartung

In preparation for a move to multi IOV events in parallel, the return type of ESProducer::produce mehtods must be changed to unique_ptr or shared_ptr. These ptrs should not refer to member data. Rather they should refer to new(copied) objects.

2018-01-22 18:21 UTC, gartung commented
@Dr15Jones

2018-01-22 18:21 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-22 23:17 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-22 23:18 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21916/2985

2018-01-22 23:21 UTC, cmsbuild commented
Pull request #21916 was updated. @ggovi, @cmsbuild can you please check and sign again.

2018-01-23 17:56 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-23 17:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21916/2995

2018-01-23 17:58 UTC, cmsbuild commented
Pull request #21916 was updated. @ggovi, @cmsbuild can you please check and sign again.

2018-01-24 13:56 UTC, ggovi commented
+1

2018-01-24 13:59 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-24 13:59 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-01-24 15:41 UTC, cmsbuild commented
+1
Tested at: 007e85437604cc81bff2601559b815255e0a6324
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25601/summary.html

2018-01-24 15:41 UTC, cmsbuild commented
Comparison job queued.

2018-01-24 17:05 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25601/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21916/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2467599
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2467429
 - DQMHistoTests: Total skipped: 169
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.08999999997 KiB( 22 files compared)
 - Checked 110 log files, 9 edm output root files, 26 DQM output files

2018-01-25 06:00 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-25 06:02 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21916/3029

2018-01-25 06:03 UTC, cmsbuild commented
Pull request #21916 was updated. @ggovi, @cmsbuild can you please check and sign again.

2018-01-25 16:40 UTC, Dr15Jones requested changes

2018-01-25 16:40 UTC, Dr15Jones commented on OnlineDB/CSCCondDB/src/CSCChamberTimeCorrectionsValues.cc
> +  return CSCChamberTimeCorrectionsValues::ReturnType( prefill(isForMC, isForMC ? ME11offsetMC : ME11offsetData, isForMC ? nonME11offsetMC : nonME11offsetData));
This could be simplified to just `return ReturnType( ...)`

2018-01-25 16:40 UTC, Dr15Jones commented on OnlineDB/CSCCondDB/src/CSCCrateMapValues.cc
> +  return CSCCrateMapValues::ReturnType( fillCrateMap() );
And here `return ReturnType(...);`

2018-01-25 16:40 UTC, Dr15Jones commented on OnlineDB/CSCCondDB/src/CSCDDUMapValues.cc
> +  return CSCDDUMapValues::ReturnType(fillDDUMap());
And here `return ReturnType(...);`

2018-01-25 19:43 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-25 19:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21916/3050

2018-01-25 19:46 UTC, cmsbuild commented
Pull request #21916 was updated. @ggovi, @cmsbuild can you please check and sign again.

2018-01-26 09:47 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-26 13:25 UTC, cmsbuild commented
-1

Tested at: 67c1572ddd8c3751447bd49f0f6196b80e900ae8


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25643/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25643/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25643/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

The relvals timed out after 2 hours.
When I ran the RelVals I found an error in the following worklfows:
4.22 step2
<pre>runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

</pre>136.7611 step2
<pre>runTheMatrix-results/136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM/step2_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM.log

</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25643/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25643/git-merge-result

2018-01-26 13:25 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2018-01-26 15:46 UTC, gartung commented
The errors are xrootd time outs opening a file.

2018-01-26 15:47 UTC, Dr15Jones commented
please test

2018-01-26 15:48 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-26 21:59 UTC, cmsbuild commented
-1

Tested at: 67c1572ddd8c3751447bd49f0f6196b80e900ae8


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25649/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25649/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25649/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

The relvals timed out after 2 hours.
When I ran the RelVals I found an error in the following worklfows:
4.22 step2
<pre>runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

</pre>136.7611 step2
<pre>runTheMatrix-results/136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM/step2_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM.log

</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25649/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25649/git-merge-result

2018-01-26 21:59 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2018-01-26 22:01 UTC, gartung commented
Problems opening files with xrootd again.

2018-01-29 08:46 UTC, ggovi commented
please test

2018-01-29 08:46 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-29 10:20 UTC, cmsbuild commented
+1
Tested at: 67c1572ddd8c3751447bd49f0f6196b80e900ae8
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25719/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25719/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25719/git-merge-result

2018-01-29 10:20 UTC, cmsbuild commented
Comparison job queued.

2018-01-29 11:47 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25719/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21916/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2464350
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2464180
 - DQMHistoTests: Total skipped: 169
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.27000000009 KiB( 22 files compared)
 - Checked 110 log files, 9 edm output root files, 26 DQM output files

2018-01-31 09:41 UTC, ggovi commented
+1

2018-01-31 09:41 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-01-31 15:10 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-31 15:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21916/3174

2018-01-31 15:13 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-31 15:13 UTC, cmsbuild commented
Pull request #21916 was updated. @cmsbuild can you please check and sign again.

2018-01-31 16:18 UTC, cmsbuild commented
+1
Tested at: ae2a7653e68cb060d0db5aabf90d8709ae34b38b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25808/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/ae2a7653e68cb060d0db5aabf90d8709ae34b38b
https://github.com/cms-sw/cmssw/commit/9b9cfd098136f2ba4f2af24a7de1f4b1a5e1eaed
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25808/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25808/git-merge-result

2018-01-31 16:18 UTC, cmsbuild commented
Comparison job queued.

2018-01-31 17:03 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21916/25808/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21916/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2463035
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2462865
 - DQMHistoTests: Total skipped: 169
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.990000000085 KiB( 22 files compared)
 - Checked 110 log files, 9 edm output root files, 26 DQM output files

2018-02-01 09:15 UTC, fabiocos commented
+1

2018-02-01 09:15 UTC, merged