RecoTracker/TransientTrackingRecHit: change return type of ESProducers.
cms-sw/cmssw pull request #21998
Opened 2018-01-26 23:09 UTC by gartung

Remove shared_ptr class member not needed.

2018-01-26 23:09 UTC, gartung commented
@Dr15Jones

2018-01-26 23:09 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-26 23:12 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21998/3087

2018-01-26 23:12 UTC, cmsbuild commented
A new Pull Request was created by  @gartung (Patrick Gartung) for master.

It involves the following packages:

RecoTracker/TransientTrackingRecHit


@perrotta, @cmsbuild, @slava77 can you please review it and eventually sign? Thanks.
@ghellwig, @makortel, @felicepantaleo, @GiacomoSguazzoni, @rovere, @VinInn, @mschrode, @gpetruc, @ebrondol, @dgulhan this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-01-27 01:37 UTC, Dr15Jones requested changes

2018-01-27 01:37 UTC, Dr15Jones commented on RecoTracker/TransientTrackingRecHit/plugins/TkTransientTrackingRecHitBuilderESProducer.cc
> +    return std::make_unique<TkTransientTrackingRecHitBuilder>(pDD.product(), pp, sp, mp, computeCoarseLocalPositionFromDisk);
You can remove the else and just return what is in that block

2018-01-27 23:20 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-01-27 23:24 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-21998/3089

2018-01-27 23:24 UTC, cmsbuild commented
Pull request #21998 was updated. @perrotta, @cmsbuild, @slava77 can you please check and sign again.

2018-01-29 04:46 UTC, slava77 commented
@cmsbuild please test

2018-01-29 04:47 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-01-29 06:28 UTC, cmsbuild commented
+1
Tested at: 2601b27d471b881287d6fd9743b64c2c4c9d6fb3
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21998/25707/summary.html

2018-01-29 06:28 UTC, cmsbuild commented
Comparison job queued.

2018-01-29 07:45 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21998/25707/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-21998/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 26
 - DQMHistoTests: Total histograms compared: 2464350
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2464180
 - DQMHistoTests: Total skipped: 169
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.48999999999 KiB( 22 files compared)
 - Checked 110 log files, 9 edm output root files, 26 DQM output files

2018-01-29 08:50 UTC, perrotta commented
+1
- technical
- jenkins tests pass

2018-01-29 08:50 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-01-29 10:43 UTC, fabiocos commented
+1

2018-01-29 10:43 UTC, merged