L1Trigger/TrackTrigger: Update return type of produce to unique_ptr.
cms-sw/cmssw pull request #22174
Opened 2018-02-10 19:11 UTC by gartung

Replace shared_ptr class member with function temporary unique_ptr.

2018-02-10 19:11 UTC, gartung commented
@Dr15Jones

2018-02-10 19:12 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-02-10 19:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22174/3320

2018-02-10 19:14 UTC, cmsbuild commented
A new Pull Request was created by  @gartung (Patrick Gartung) for master.

It involves the following packages:

L1Trigger/TrackTrigger


@nsmith-, @cmsbuild, @kpedro88, @thomreis, @rekovic can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @kreczko, @sviret this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-02-10 19:33 UTC, Dr15Jones requested changes

2018-02-10 19:33 UTC, Dr15Jones commented on L1Trigger/TrackTrigger/interface/TTClusterAlgorithm_neighbor.h
>        return _theAlgo;
It should be possible to replace the entire body with
```
return std::make_unique<TTClusterAlgorithm_neighbor< T >>();
```

2018-02-10 19:33 UTC, Dr15Jones commented on L1Trigger/TrackTrigger/interface/TTClusterAlgorithm_official.h
>        return _theAlgo;
```
return std::make_unique<TTClusterAlgorithm_official< T >>( mWidthCut );
```

2018-02-10 19:33 UTC, Dr15Jones commented on L1Trigger/TrackTrigger/interface/TTStubAlgorithm_cbc3.h
>        return _theAlgo;
```
return std::make_unique<TTStubAlgorithm_cbc3< T >>( theTrackerGeom, theTrackerTopo, mPerformZMatching2S );
```

2018-02-10 19:33 UTC, Dr15Jones commented on L1Trigger/TrackTrigger/interface/TTStubAlgorithm_official.h
>        return _theAlgo;
```
return std::make_unique<TTStubAlgorithm_official< T >>( theTrackerGeom, theTrackerTopo,
                                                        setBarrelCut, setRingCut, setTiltedCut, setBarrelNTilt,
                                                        mPerformZMatchingPS, mPerformZMatching2S);
```

2018-02-10 21:18 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-02-10 21:20 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22174/3321

2018-02-10 21:20 UTC, cmsbuild commented
Pull request #22174 was updated. @nsmith-, @cmsbuild, @kpedro88, @thomreis, @rekovic can you please check and sign again.

2018-02-10 21:32 UTC, Dr15Jones commented
please test

2018-02-10 21:33 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-02-11 00:27 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22174/26008/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-22174/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017+HARVESTNANOAODMC2017

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 6 differences found in the comparisons
 - DQMHistoTests: Total files compared: 27
 - DQMHistoTests: Total histograms compared: 2464162
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2463992
 - DQMHistoTests: Total skipped: 169
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.620000000061 KiB( 22 files compared)
 - Checked 111 log files, 9 edm output root files, 27 DQM output files

2018-02-14 23:18 UTC, kpedro88 commented
+1

2018-02-20 17:02 UTC, rekovic commented
+1

2018-02-20 17:03 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-02-20 21:14 UTC, fabiocos commented
+1

2018-02-20 21:14 UTC, merged