DQM: SiPixelPhase1- Added Big Pixel Charge Plots
cms-sw/cmssw pull request #22324
Opened 2018-02-23 16:47 UTC by emacdonald16

Added the charge of the big pixels for the barrel and the forward region, as well as per layer and per disk
For inclusive clusters and on-track clusters

2018-02-23 16:47 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-02-23 16:49 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22324/3535

2018-02-23 16:49 UTC, cmsbuild commented
A new Pull Request was created by  @emacdonald16  for master.

It involves the following packages:

DQM/SiPixelPhase1Clusters
DQM/SiPixelPhase1TrackClusters


@vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien can you please review it and eventually sign? Thanks.
@idebruyn, @threus, @fioriNTU, @hdelanno this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-02-23 16:51 UTC, emacdonald16 commented
hello @vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien : 
I'm a new offline DQM developer for the trackerDPG  [@fioriNTU , @boudoul for the tracker DPG are already aware, working with them ]

2018-02-23 16:53 UTC, emacdonald16 commented
@hbecerri FYI

2018-02-23 17:14 UTC, dmitrijus commented
+1

2018-02-23 17:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-02-23 17:14 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-02-23 20:19 UTC, boudoul commented
Looks like the error is related to the hlt dqm  , investigating with @emacdonald16

2018-02-24 21:58 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-02-24 22:14 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22324/3558

2018-02-24 22:14 UTC, cmsbuild commented
Pull request #22324 was updated. @vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien can you please check and sign again.

2018-02-27 17:08 UTC, emacdonald16 commented
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien can you please sign again?

2018-03-08 10:08 UTC, boudoul commented
Dear @fabiocos , We are unfortunately waiting for a DQM signature for a while, can you pass by or do something, it should really go in  10_1

2018-03-08 10:28 UTC, dmitrijus requested changes

2018-03-08 10:28 UTC, dmitrijus commented on DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc
> +          std::cout<<"Failure here 1?"<<std::endl;
Please don't use std::cout. Use proper MessageLogger.

2018-03-09 10:29 UTC, boudoul commented
Hi @emacdonald16 , could you please address the comment from @dmitrijus ?

2018-03-10 19:22 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-03-10 19:24 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22324/3899

2018-03-10 19:25 UTC, cmsbuild commented
Pull request #22324 was updated. @vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien can you please check and sign again.

2018-03-12 07:29 UTC, boudoul commented
Thanks @emacdonald16 !  
Could someone trigger the tests?

2018-03-12 08:37 UTC, jfernan2 commented
please test

2018-03-12 08:37 UTC, cmsbuild commented
The tests are being triggered in jenkins.
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/26781/console Started: 2018/03/12 09:38

2018-03-12 08:45 UTC, cmsbuild commented
-1

Tested at: 49b5b7368e6fda22bd63fbec3cbe14e8bf0187a8

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22324/26781/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found an error when building: 
 
 <pre>>> Compiling  /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/Utilities/StaticAnalyzers/src/ClassChecker.cpp 
>> Compiling  /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/Utilities/StaticAnalyzers/src/StaticLocalChecker.cpp 
>> Compiling  /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/Utilities/StaticAnalyzers/src/ClassDumper.cpp 
>> Compiling  /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/Utilities/StaticAnalyzers/src/ThrUnsafeFCallChecker.cpp 
>> Compiling  /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/Utilities/StaticAnalyzers/src/ClangCmsCheckerPluginRegister.cpp 
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc:1:1: error: expected unqualified-id before numeric constant
 0;95;0c// -*- C++ -*-
 ^
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc:1:3: error: expected unqualified-id before numeric constant
 0;95;0c// -*- C++ -*-
   ^~
</pre>

* **Clang**:

I found a compilation error while trying to compile with clang: 
I used this command: 
 scram b vclean && scram build -k -j 48 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'


 <pre>>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQMOffline/Trigger/src/JetMETHLTOfflineClient.cc 
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQMOffline/Trigger/src/EgHLTOffPho.cc 
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQMOffline/Trigger/src/EgHLTOfflineClient.cc 
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQMOffline/Trigger/src/TopDiLeptonHLTOfflineDQM.cc 
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQMOffline/Trigger/src/EgHLTOffEvt.cc 
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc:1:1: error: expected unqualified-id
0;95;0c// -*- C++ -*-
^
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-11-2300/src/DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc:1:3: error: expected unqualified-id
0;95;0c// -*- C++ -*-
  ^
</pre>

2018-03-12 08:45 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2018-03-12 08:53 UTC, boudoul commented
sigh ... please @emacdonald16 fix this - and please always compile and test your code before pushing to cmssw ...

2018-03-12 15:31 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-03-12 15:34 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22324/3917

2018-03-12 15:34 UTC, cmsbuild commented
Pull request #22324 was updated. @vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien can you please check and sign again.

2018-03-12 16:04 UTC, jfernan2 commented
please test

2018-03-12 16:04 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-03-12 18:05 UTC, cmsbuild commented
+1
Tested at: 138b43deb6a47534823be72b3fc40c5fa731f428
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22324/26797/summary.html

2018-03-12 18:05 UTC, cmsbuild commented
Comparison job queued.

2018-03-12 19:31 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22324/26797/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 29
 - DQMHistoTests: Total histograms compared: 2477919
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2477742
 - DQMHistoTests: Total skipped: 176
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 88.45 KiB( 23 files compared)
 - Checked 118 log files, 9 edm output root files, 29 DQM output files

2018-03-13 13:24 UTC, dmitrijus commented
+1

2018-03-13 13:24 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-03-29 15:05 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-03-29 16:30 UTC, cmsbuild commented
+1
Tested at: 138b43deb6a47534823be72b3fc40c5fa731f428
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22324/27194/summary.html

2018-03-29 16:30 UTC, cmsbuild commented
Comparison job queued.

2018-03-29 17:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22324/27194/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 29
 - DQMHistoTests: Total histograms compared: 2501822
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2501645
 - DQMHistoTests: Total skipped: 176
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 88.5600000001 KiB( 23 files compared)
 - Checked 119 log files, 9 edm output root files, 29 DQM output files

2018-03-30 14:52 UTC, fabiocos commented
+1

2018-03-30 14:52 UTC, merged

2018-03-30 15:26 UTC, boudoul commented
Dear @fabiocos , may I ask the motivation for not having included this in 10_1 while it has been signed for 2 weeks (and explicitely asked in this github conversation)? Shall we now go to the proces of backport ?.......... :(    And if yes when the next 10_1 release is going to be built? We indeed have to be sure this big pixel monitorig is in place in the software for  data taking ....

2018-03-30 15:48 UTC, fabiocos commented
Dear @boudoul this arrived in the "closed" period of 10_1_X, where I had to do a selection in the middle of several other priorities piling up. Several other things will have to be backported, we needed to close anyway. If you provide a backport, please mark it in next ORP spreadsheet as needed for operations, 10_1_1 will be built for sure in time for the beginning of the ramp-up, but if there is some urgent need for operations we may have patches.

2018-04-04 15:46 UTC, boudoul commented
ok @fabiocos , I created the backport  #22844  , I hope the DQM team in charge of reporting at the ORP will take care ... !

2018-04-05 07:52 UTC, fabiocos commented
@boudoul I saw it, thanks, we can integrate it when it is signed, we need to have a number of things into a 10_1_1 anyway soon

2018-04-05 08:02 UTC, boudoul commented
Thank you @fabiocos !