Phase2-hgx106 Step toward HGCal interface of Geometry
cms-sw/cmssw pull request #22891
Opened 2018-04-07 06:32 UTC by bsunanda

Defines all parameters needed to for deciding numbering cells

2018-04-07 06:33 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-04-07 06:34 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22891/4275

2018-04-07 06:34 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HGCalCommonData


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please review it and eventually sign? Thanks.
@ghellwig this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-04-07 06:37 UTC, bsunanda commented
@cmsbuild Please test

2018-04-07 06:37 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-04-07 08:42 UTC, cmsbuild commented
+1
Tested at: 7093ff469b108de97b7eb1200a1e75324232f2fa
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22891/27364/summary.html

2018-04-07 08:42 UTC, cmsbuild commented
Comparison job queued.

2018-04-07 10:12 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22891/27364/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 29
 - DQMHistoTests: Total histograms compared: 2504254
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2504077
 - DQMHistoTests: Total skipped: 176
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.17999999996 KiB( 22 files compared)
 - Checked 119 log files, 9 edm output root files, 29 DQM output files

2018-04-07 11:25 UTC, civanch commented
+1

2018-04-10 05:03 UTC, bsunanda commented
@kpedro88 Can you please approve this?

2018-04-10 13:28 UTC, cmsbuild commented
+1
Tested at: c1face7d0dc1503fa488c67b151c30c6d63429a3
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22891/27409/summary.html

2018-04-10 13:28 UTC, cmsbuild commented
Comparison job queued.

2018-04-10 15:00 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22891/27409/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 29
 - DQMHistoTests: Total histograms compared: 2504254
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2504077
 - DQMHistoTests: Total skipped: 176
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1.06999999999 KiB( 22 files compared)
 - Checked 119 log files, 9 edm output root files, 29 DQM output files

2018-04-10 17:05 UTC, kpedro88 commented
+1

2018-04-11 13:32 UTC, bsunanda commented
@ianna Please review and approve this

2018-04-13 12:27 UTC, ianna requested changes

2018-04-13 12:27 UTC, ianna commented on Geometry/HGCalCommonData/interface/HGCalParametersFromDD.h
> +  double getDDDValue(const char* s, const DDsvalues_type& sv);
@bsunanda - I do not see you using this here. Please remove it.

2018-04-13 12:55 UTC, ianna commented
+1

2018-04-13 12:55 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-04-14 09:30 UTC, fabiocos commented
+1

2018-04-14 09:30 UTC, merged