Phase2-hgx124 Split the SD for HGCal for silicon and scintillators
cms-sw/cmssw pull request #23772
Opened 2018-07-10 14:04 UTC by bsunanda

Allow fiducial volume cuts in silicon and scintillator detectors of HGCal

2018-07-10 14:06 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-10 14:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23772/5451

2018-07-10 14:13 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HGCalCommonData
Geometry/HGCalSimData
SimG4CMS/Calo
SimG4Core/Application


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please review it and eventually sign? Thanks.
@makortel this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-07-10 14:13 UTC, bsunanda commented
@cmsbuild Please test

2018-07-10 14:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-10 15:14 UTC, kpedro88 commented on SimG4CMS/Calo/src/HGCalSD.cc
> +    numberingScheme_ = new HGCalNumberingScheme(*hgcons_,mydet_,nameX_);
smart pointers here as well

2018-07-10 20:42 UTC, cmsbuild commented
-1

Tested at: ec638ada72ee567f6060d6a26c91a8449bde5aef

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23772/29063/summary.html

I found follow errors while testing this PR

**Failed tests:  RelVals**

* **RelVals**:

The relvals timed out after 2 hours.

2018-07-10 20:42 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2018-07-10 21:58 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-10 22:02 UTC, bsunanda commented
@cmsbuild Please test

2018-07-10 22:03 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23772/5455

2018-07-10 22:03 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-10 22:03 UTC, cmsbuild commented
Pull request #23772 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-07-11 01:59 UTC, cmsbuild commented
+1
Tested at: 512425c6be37bc84b1522b123509fea97b4c622e
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23772/29068/summary.html

2018-07-11 01:59 UTC, cmsbuild commented
Comparison job queued.

2018-07-11 03:49 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23772/29068/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2899490
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2899298
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 128 log files, 14 edm output root files, 31 DQM output files

2018-07-11 14:46 UTC, ianna requested changes

2018-07-11 14:46 UTC, ianna commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +double HGCalDDDConstants::distFromEdgeHex(double x, double y, double z) const {
@bsunanda - please, add a comment what is calculated here. Is the point(x,y) inside of the polygon?

2018-07-11 15:21 UTC, bsunanda commented
Hi Ianna

This is for a point inside the volume. I shall add a comment for the next version which is under preparation right now. Could this PR be merged as it is now. That will help in the progress of the next PR.  Best regards

Sunanda
________________________________
From: Ianna Osborne [notifications@github.com]
Sent: 11 July 2018 16:46
To: cms-sw/cmssw
Cc: Sunanda Banerjee; Mention
Subject: Re: [cms-sw/cmssw] Phase2-hgx124 Split the SD for HGCal for silicon and scintillators (#23772)


@ianna requested changes on this pull request.

________________________________

In Geometry/HGCalCommonData/src/HGCalDDDConstants.cc<https://github.com/cms-sw/cmssw/pull/23772#discussion_r201717819>:

> @@ -242,10 +243,88 @@ double HGCalDDDConstants::cellSizeHex(int type) const {
   return cell;
 }

+double HGCalDDDConstants::distFromEdgeHex(double x, double y, double z) const {


@bsunanda<https://github.com/bsunanda> - please, add a comment what is calculated here. Is the point(x,y) inside of the polygon?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/23772#pullrequestreview-136273630>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AEzMuowUP_8z70RJqJkm7iWLpbrjqjIDks5uFg_GgaJpZM4VJeLT>.

2018-07-11 21:48 UTC, bsunanda commented
@ianna @civanch Can you approve this PR so that I can make the subsequent PR's

2018-07-11 22:19 UTC, civanch commented
+1

2018-07-11 22:21 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-07-12 08:10 UTC, ianna commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +double HGCalDDDConstants::distFromEdgeHex(double x, double y, double z) const {
@bsunanda it takes longer for me to check the code without comment on what it suppose to do.

2018-07-12 20:57 UTC, fabiocos commented
+1

it affects only Phase2, g4SimHits is changed only for SD of HGCal.

2018-07-12 20:57 UTC, merged