HGCal material budget analysis
cms-sw/cmssw pull request #23770
Opened 2018-07-10 12:26 UTC by apsallid

This PR is the work done in the context of the HGCal DPG with @rovere and @felicepantaleo to study the material budget of the latest HGCal geometry by @bsunanda and @kpedro88 . All the code touched or written is done with main goal not to impact/conflict at all with the user from Tracker or others that will need to perform a material budget study. Detailed description of changes following the current 
style of the whole package: 
**1.** Added two files to declare/define HGCal materials. 

Validation/Geometry/data/hgcalMaterials.l0
Validation/Geometry/data/hgcalMaterials.x0

**2.** Added two files for the HGCal histos that will be produced. 

Validation/Geometry/interface/MaterialBudgetHGCalHistos.h
Validation/Geometry/src/MaterialBudgetHGCalHistos.cc

**3.** Added HGCal option

Validation/Geometry/interface/MaterialBudgetAction.h
Validation/Geometry/src/MaterialBudgetAction.cc

**4.** Added HGCal map of materials alongside the tracker one. 

Validation/Geometry/interface/MaterialBudgetCategorizer.h
Validation/Geometry/src/MaterialBudgetCategorizer.cc

**5.** Added the reading of HGCal data. 

Validation/Geometry/interface/MaterialBudgetData.h
Validation/Geometry/src/MaterialBudgetData.cc

**6.** Plotting tools for all HGCal material analysis plots that are not in the 
usual plot_utils.py or MaterialBudget.py .  Whatever is needed and it is 
already in the repository is imported in order to avoid code duplication. 

Validation/Geometry/python/plot_hgcal_utils.py
Validation/Geometry/test/MaterialBudgetHGCal.py

**7.** Added the main script of running the code: 

Validation/Geometry/test/runP_HGCal_cfg.py

2018-07-10 12:31 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5448

Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5448/git-diff.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5448/git-diff.patch | patch -p1`

You can run `scram build code-checks` to apply code checks directly

2018-07-10 13:06 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-10 13:19 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5450

2018-07-10 13:20 UTC, cmsbuild commented
A new Pull Request was created by  @apsallid  for master.

It involves the following packages:

Validation/Geometry


@civanch, @Dr15Jones, @vazzolini, @kmaeshima, @ianna, @mdhildreth, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien can you please review it and eventually sign? Thanks.
@rovere this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-07-10 14:09 UTC, kpedro88 commented
please test

2018-07-10 14:10 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-10 18:12 UTC, cmsbuild commented
+1
Tested at: 0130a9c657ebd154b99679eda72098ac57e9f9c7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29062/summary.html

2018-07-10 18:12 UTC, cmsbuild commented
Comparison job queued.

2018-07-10 19:44 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29062/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2899490
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2899298
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 128 log files, 14 edm output root files, 31 DQM output files

2018-07-11 14:25 UTC, ianna requested changes

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetAction.cc
> +
@apsallid - where is "theData" deleted?

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetAction.cc
> +      theHistos = new MaterialBudgetHGCalHistos( theData, theHistoMgr, saveToHistosFile );
the same here? Wouldn't it be better to use a smart pointer?

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +  theAirDmb               = new float[MAXNUMBERSTEPS];
@apsallid - please, consider using std::array or std::tuple. Alternatively, please, make sure the memory is released in the MaterialBudgetData destructor:
```
delete theAirDmb;
```
the same goes to all other pointers.

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +
please, remove commented out code

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +
please, remove commented out code

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +  // std::cout << " Material " << materialName << "\n";
please, remove commented out code

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +  // std::cout << "Volume ID " << volumeID << " and material ID " << materialID << "\n";
please, remove commented out code

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +      theAirFractionMB              = myMaterialBudgetCategorizer->HGCalx0fraction(materialName).at(0);
please, note that access to vector.at(i) is slower then vector[i]

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetData.cc
> +  // 			    << std::endl;
please, remove commented out code

2018-07-11 14:25 UTC, ianna commented on Validation/Geometry/src/MaterialBudgetHGCalHistos.cc
> +	hmgr->getHistoProf2(11072)->Fill(z,polarRadius, iLea * fillValue * cos( 2 * atan(exp(-fabs(eta))) ) );
please, calculate the expression cos( 2 * atan(exp(-fabs(eta))) ) once in advance instead of calculating it 22 times

2018-07-12 14:39 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-12 14:41 UTC, apsallid commented
@ianna

Thank you for the comments. I applied the changes. Specifically, 

1. Remove commented out code.
2. Used vector[i] instead of vector.at(i). 
3. Calculate the expression cos( 2 * atan(exp(-fabs(eta))) ) once. 
4. Used smart pointers.

2018-07-12 14:42 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5472

2018-07-12 14:42 UTC, cmsbuild commented
Pull request #23770 was updated. @civanch, @Dr15Jones, @vazzolini, @kmaeshima, @schneiml, @ianna, @mdhildreth, @dmitrijus, @cmsbuild, @jfernan2 can you please check and sign again.

2018-07-12 15:02 UTC, kpedro88 commented
please test

2018-07-12 15:02 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-12 17:02 UTC, cmsbuild commented
+1
Tested at: ab224f42a798322fbad654693af26b8b919d7cc6
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29094/summary.html

2018-07-12 17:02 UTC, cmsbuild commented
Comparison job queued.

2018-07-12 18:11 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29094/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2892290
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2892098
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 128 log files, 14 edm output root files, 31 DQM output files

2018-07-13 09:02 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-13 09:04 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-23770/5478

2018-07-13 09:04 UTC, cmsbuild commented
Pull request #23770 was updated. @civanch, @Dr15Jones, @vazzolini, @kmaeshima, @schneiml, @ianna, @mdhildreth, @dmitrijus, @cmsbuild, @jfernan2 can you please check and sign again.

2018-07-13 09:11 UTC, jfernan2 commented
please test

2018-07-13 09:11 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-13 12:11 UTC, cmsbuild commented
+1
Tested at: 414182d2491c3d09d215257fa8dcabd4aee72d0c
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29100/summary.html

2018-07-13 12:11 UTC, cmsbuild commented
Comparison job queued.

2018-07-13 14:01 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23770/29100/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2887250
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2887059
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 128 log files, 14 edm output root files, 31 DQM output files

2018-07-17 17:22 UTC, ianna commented
+1

2018-07-26 10:17 UTC, andrius-k commented
+1

2018-07-26 10:17 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-07-27 15:32 UTC, kpedro88 commented
+1

2018-07-27 15:32 UTC, merged

2018-09-20 11:42 UTC, vargasa reviewed
Suggested addition to commit

2018-09-20 11:42 UTC, vargasa commented on Validation/Geometry/src/MaterialBudgetAction.cc
> -  delete theData;
Hello @ianna 

The (required) deletion of this `delete` statements does not allow to create theHistos ROOT File some of the configuration files, the `save` method is (wrongly?) located in the destructor of `MaterialBudgetTrackerHistos` (not in this commit though) as you can see here:

https://github.com/cms-sw/cmssw/blob/fb7c415b2b63673b87d631ff2a16966d1c428180/Validation/Geometry/interface/MaterialBudgetTrackerHistos.h#L14

Which runs:

https://github.com/cms-sw/cmssw/blob/fb7c415b2b63673b87d631ff2a16966d1c428180/Validation/Geometry/src/MaterialBudgetTrackerHistos.cc#L739

As it is right now no ROOT file is being created by `runP_Tracker_cfg.py` (and probably not by `runP_HGCal_cfg.py` either @apsallid ). 

Please check this proposed solution:

 [`saveToFile` method](https://github.com/vargasa/cmssw/commit/2600a9b78b38dd0f880c6b3fac5e6eedade037d1) in `MaterialBudgetFormat` 

But will still need to see which other parts of the code should be modified. If you have any suggestion or comments please let me know

Thanks!

2018-09-20 14:08 UTC, apsallid commented
Hi @vargasa, @ianna, 

I can confirm also that I cannot see the root file. However, with the proposed saveToFile method I see the file and can create normally the usual histos. 
Thanks a lot for spotting this, 
Andreas

2018-09-22 14:56 UTC, apsallid commented
Hi @vargasa 

Ok, I just double check, it's ok. Thanks a lot!

2018-09-23 10:55 UTC, vargasa commented
Thanks @apsallid, I just finished doing some code clean up included in PR.