Phase2-hgx132 Bug fix for HGCal post TDR geometry
cms-sw/cmssw pull request #24134
Opened 2018-07-30 16:58 UTC by bsunanda

Correct cell assignments for virtual cells 
Also include some debug facility during SIM and DIGI steps

2018-07-30 16:59 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-30 17:02 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24134/5823

2018-07-30 17:02 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HGCalCommonData
SimCalorimetry/HGCalSimProducers
SimG4CMS/Calo


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please review it and eventually sign? Thanks.
@vandreev11, @sethzenz, @makortel, @kpedro88, @lgray, @cseez, @pfs this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-07-30 17:02 UTC, bsunanda commented
@cmsbuild Please test

2018-07-30 17:03 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-30 17:09 UTC, kpedro88 commented
@bsunanda there were a few different bugs reported by @hatakeyamak:
1. SimHits beyond high eta (small radius) boundary
2. Strip of digis w/ high R in layer 18
3. Digis outside OuterRadius

Can you clarify which bugs should be fixed by this PR?

2018-07-30 17:12 UTC, bsunanda commented
Hopefully all 3. There is a small issue of virtual cells. It may indicate a small excursion beyond the limit because the cell may be partially contained and the center of the cell (whose position is returned) may be outside the limit. This can be almost a few mm.

2018-07-30 19:39 UTC, cmsbuild commented
+1
Tested at: e04d5be4041a2c61088755f3f765ef5f3df7498b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24134/29569/summary.html

2018-07-30 19:39 UTC, cmsbuild commented
Comparison job queued.

2018-07-30 20:50 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24134/29569/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2891493
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2891302
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 128 log files, 14 edm output root files, 31 DQM output files

2018-07-31 07:19 UTC, ianna requested changes

2018-07-31 11:57 UTC, bsunanda commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +	if (debug)
The only reason is to trace a rare error. Now that the error is detected and corrected for I can revert this if you want. I wanted the debug to be active only when needed.

2018-07-31 11:59 UTC, bsunanda commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +	  if (debug)
Ianna - a compile time debug will print all occurrences. This allows only when there is some special investigation.

2018-07-31 12:01 UTC, ianna commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +	if (debug)
please, do. Thanks.

2018-07-31 12:30 UTC, ianna commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +	  if (debug)
Do you need to do special investigation in production? Because the check will be made every time even if you do not need any printout.

2018-07-31 13:26 UTC, bsunanda commented
@cmsbuild Please test

2018-07-31 13:26 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-07-31 13:27 UTC, bsunanda commented on Geometry/HGCalCommonData/src/HGCalDDDConstants.cc
> +	  if (debug)
I am leaving selective debug statement so that I can easily revive partial debug. Hope this is oK with you

2018-07-31 13:29 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24134/5833

2018-07-31 13:29 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-07-31 13:29 UTC, cmsbuild commented
Pull request #24134 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-07-31 16:55 UTC, cmsbuild commented
+1
Tested at: 751a8e5790119cad38362a6d2b13c3bc7674300b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24134/29583/summary.html

2018-07-31 16:55 UTC, cmsbuild commented
Comparison job queued.

2018-07-31 18:34 UTC, bsunanda commented
@civanch @ianna @kpedro88 Could you approve this? I have some thing in queue which I cannot submit till this one gets integrated

2018-07-31 18:36 UTC, kpedro88 commented
@bsunanda I would prefer to get confirmation from @hatakeyamak that this indeed fixes the bugs that were observed

2018-07-31 18:41 UTC, hatakeyamak commented
I am checking this today. Try to report here asap.

2018-08-01 07:51 UTC, ianna commented
@bsunanda - are differences in Reco comparison results justified: 3 differences found in the comparisons?

2018-08-01 12:55 UTC, kpedro88 commented
@ianna these are spurious differences from non-reproducibility in a PU workflow

2018-08-01 12:58 UTC, ianna commented
+1

2018-08-01 15:27 UTC, civanch commented
+1

2018-08-02 13:41 UTC, hatakeyamak commented
My check summary is here:
https://indico.cern.ch/event/747942/contributions/3095531/
I think
    SimHits beyond high eta (small radius) boundary
    Strip of digis w/ high R in layer 18
    Digis outside OuterRadius
are all addressed.

2018-08-02 14:07 UTC, kpedro88 commented
+upgrade

2018-08-02 14:08 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-08-03 08:01 UTC, fabiocos commented
+1

2018-08-03 08:02 UTC, merged