L1DQM: JIRA 326
cms-sw/cmssw pull request #24191
Opened 2018-08-03 11:20 UTC by CarstenHensel

L1DQM: connect caloLayer2 output to uGT input comparison results to reportSummaryMap

2018-08-03 11:20 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-03 11:23 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24191/5877

2018-08-03 11:24 UTC, cmsbuild commented
A new Pull Request was created by  @CarstenHensel (Carsten Hensel) for master.

It involves the following packages:

DQM/L1TMonitorClient


@kmaeshima, @cmsbuild, @andrius-k, @jfernan2, @schneiml can you please review it and eventually sign? Thanks.
@thomreis this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-08-03 11:25 UTC, thomreis commented
please test

2018-08-03 11:25 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-03 11:26 UTC, thomreis commented
@CarstenHensel works on the implementation of quality tests for the caloL2 trigger DQM.

2018-08-03 11:29 UTC, thomreis requested changes

2018-08-03 11:29 UTC, thomreis commented on DQM/L1TMonitorClient/python/L1TStage2EventInfoClient_cfi.py
> +                            cms.PSet(
Please move this to the uGT section (around line 337) since it is the uGT that should become red if there is a problem on the link.

2018-08-03 11:29 UTC, thomreis commented
please abort test

2018-08-03 11:29 UTC, cmsbuild commented
Jenkins tests are aborted.

2018-08-03 13:17 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-03 13:19 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24191/5881

2018-08-03 13:19 UTC, cmsbuild commented
Pull request #24191 was updated. @kmaeshima, @cmsbuild, @andrius-k, @jfernan2, @schneiml can you please check and sign again.

2018-08-03 14:08 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-03 14:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24191/5882

2018-08-03 14:11 UTC, cmsbuild commented
Pull request #24191 was updated. @kmaeshima, @cmsbuild, @andrius-k, @jfernan2, @schneiml can you please check and sign again.

2018-08-03 14:18 UTC, thomreis commented
please test

2018-08-03 14:18 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-03 17:26 UTC, cmsbuild commented
+1
Tested at: b75ede6395170beac8a722c9c02098c00320df95
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24191/29641/summary.html

2018-08-03 17:26 UTC, cmsbuild commented
Comparison job queued.

2018-08-03 18:52 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24191/29641/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2891565
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2891374
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 2.244 KiB( 30 files compared)
 - DQMHistoSizes: changed ( 11624.0,... ): 0.096 KiB        L1T/L1TStage2uGT
 - DQMHistoSizes: changed ( 11624.0,... ): 0.091 KiB        L1T/EventInfo
 - Checked 129 log files, 14 edm output root files, 31 DQM output files

2018-08-06 08:41 UTC, andrius-k commented
+1

2018-08-06 08:43 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-08-06 08:53 UTC, fabiocos commented
+1

2018-08-06 08:54 UTC, merged