Phase2-hgx138 Update HGCal v9 geometry to define fiducial boundaries correctly
cms-sw/cmssw pull request #24264
Opened 2018-08-10 19:27 UTC by bsunanda

Proper utilization of mixed layer and non-mixed layer for HE-Silicon part

2018-08-10 19:28 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-10 19:29 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24264/5978

2018-08-10 19:32 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HGCalCommonData


@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please review it and eventually sign? Thanks.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-08-10 20:42 UTC, davidlange6 commented
please test

2018-08-10 20:43 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-11 00:32 UTC, cmsbuild commented
+1
Tested at: 03402045917218c92b70c33d284f4134f042c8d7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24264/29773/summary.html

2018-08-11 00:32 UTC, cmsbuild commented
Comparison job queued.

2018-08-11 02:41 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24264/29773/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2891469
 - DQMHistoTests: Total failures: 7
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2891272
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 129 log files, 14 edm output root files, 31 DQM output files

2018-08-13 06:06 UTC, ianna requested changes

2018-08-13 06:06 UTC, ianna commented on Geometry/HGCalCommonData/src/HGCalParametersFromDD.cc
> +#define EDM_ML_DEBUG
@bsunanda - please, comment it out.

2018-08-13 13:12 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-13 13:14 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24264/5994

2018-08-13 13:15 UTC, cmsbuild commented
Pull request #24264 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-08-13 16:27 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24264/5999

2018-08-13 16:27 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-13 16:27 UTC, cmsbuild commented
Pull request #24264 was updated. @civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-08-13 19:02 UTC, cmsbuild commented
+1
Tested at: 496420db5a92efafd00b28ac94ed7eef25c9e8c6
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24264/29803/summary.html

2018-08-13 19:02 UTC, cmsbuild commented
Comparison job queued.

2018-08-13 20:13 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24264/29803/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 28
 - DQMHistoTests: Total histograms compared: 2811739
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2811556
 - DQMHistoTests: Total skipped: 181
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 27 files compared)
 - Checked 122 log files, 14 edm output root files, 28 DQM output files

2018-08-13 21:52 UTC, bsunanda commented
@ianna @kpedro88 @fabiocos It will be nice if this PR is integrated fast. The next sets of PR's including some earlier ones depend on this PR.

2018-08-14 08:53 UTC, ianna commented
+1

2018-08-20 21:21 UTC, kpedro88 commented
+upgrade

2018-08-20 21:21 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-08-21 09:36 UTC, fabiocos commented
+1

2018-08-21 09:36 UTC, merged