RUn2-hcx183 Try remove some comments from Static Analyzer reported in #24361
cms-sw/cmssw pull request #24386
Opened 2018-08-24 21:52 UTC by bsunanda

2018-08-24 21:52 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-24 21:54 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24386/6159

2018-08-24 21:55 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda  for master.

It involves the following packages:

Geometry/HcalCommonData
SimG4CMS/Calo
Validation/HcalHits


@andrius-k, @Dr15Jones, @kmaeshima, @cvuosalo, @schneiml, @ianna, @mdhildreth, @cmsbuild, @jfernan2, @civanch can you please review it and eventually sign? Thanks.
@makortel this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-08-24 22:42 UTC, davidlange6 commented
please test

2018-08-24 22:43 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-25 03:04 UTC, cmsbuild commented
+1
Tested at: a70e3533ff595314018633782db2045187247675
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24386/30052/summary.html

2018-08-25 04:40 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24386/30052/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2992850
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2992658
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 129 log files, 14 edm output root files, 31 DQM output files

2018-08-27 05:41 UTC, ianna requested changes

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  std::vector<CaloHit>                     caloHitCache;
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  int                                      nGroup, nTower;
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  double                                   mudist[20];   // Distance of muon from central part
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  double                                   edepHO, edepl[20];
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  double                                   edepEB, edepEE, edepHB, edepHE;
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 05:41 UTC, ianna commented on SimG4CMS/Calo/interface/HcalTestAnalysis.h
> +  unsigned int                             count;
@bsunanda - please, rename all private members to have trailing underscore for consistency.

2018-08-27 09:39 UTC, andrius-k commented
+1
Fine for DQM (no significant changes)

2018-08-27 14:54 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-27 14:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24386/6177

2018-08-27 14:57 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-27 14:57 UTC, cmsbuild commented
Pull request #24386 was updated. @andrius-k, @Dr15Jones, @kmaeshima, @cvuosalo, @schneiml, @ianna, @mdhildreth, @cmsbuild, @jfernan2, @civanch can you please check and sign again.

2018-08-27 18:09 UTC, cmsbuild commented
+1
Tested at: e18171c3cad65fd79e6e4be3b355ff9f7e7b4aa4
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24386/30071/summary.html

2018-08-27 18:09 UTC, cmsbuild commented
Comparison job queued.

2018-08-27 19:30 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24386/30071/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 31
 - DQMHistoTests: Total histograms compared: 2992850
 - DQMHistoTests: Total failures: 7
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2992653
 - DQMHistoTests: Total skipped: 190
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 30 files compared)
 - Checked 129 log files, 14 edm output root files, 31 DQM output files

2018-08-28 14:56 UTC, ianna commented
+1

2018-08-28 20:36 UTC, civanch commented
+1

2018-08-28 20:36 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-08-30 14:12 UTC, kpedro88 commented
+1

2018-08-30 14:12 UTC, merged