PPS Full simulation + PPS proton transport with totem parameterization
cms-sw/cmssw pull request #24420
Opened 2018-08-30 17:28 UTC by mundim

PR related to the presentation in the Simulation meeting of June, 8th. It includes the first PR with full simulation of PPS, including the new SD for the tracker and timing detectors. It relies on the new proton transport, redesigned in order to allow the propagation using also the TOTEM parameterization for the realistic optics and HECTOR as well. It also includes a utility module that holds methods used by simulation and reconstruction (full and fast as well), isolated into a separated module to avoid duplication of maintenance efforts.

@fabferro @jan-kaspar @dilsonjd @nminafra @forthommel @grzanka @setesami @nogima

2018-08-30 17:28 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-08-30 17:31 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24420/6233

2018-08-30 17:31 UTC, cmsbuild commented
A new Pull Request was created by  @mundim  for master.

It involves the following packages:

Configuration/Geometry
Configuration/StandardSequences
EventFilter/CTPPSRawToDigi
EventFilter/RawDataCollector
Geometry/CMSCommonData
Geometry/VeryForwardData
Geometry/VeryForwardGeometry
PPSTools/Utilities
SimG4CMS/PPS
SimG4Core/Application
SimGeneral/MixingModule
SimPPS/Configuration
SimPPS/PPSPixelDigiProducer
SimPPS/PPSSimTrackProducer
SimPPS/RPDigiProducer
SimTransport/HectorProducer
SimTransport/PPSProtonTransport
SimTransport/TotemRPProtonTransportParametrization


The following packages do not have a category, yet:

PPSTools/Utilities
SimG4CMS/PPS
SimPPS/Configuration
SimPPS/PPSPixelDigiProducer
SimPPS/PPSSimTrackProducer
SimPPS/RPDigiProducer
SimTransport/PPSProtonTransport
SimTransport/TotemRPProtonTransportParametrization
Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to assign category

@perrotta, @civanch, @Dr15Jones, @cvuosalo, @emeschi, @ianna, @mdhildreth, @cmsbuild, @franzoni, @kpedro88, @slava77, @mommsen, @fabiocos, @davidlange6 can you please review it and eventually sign? Thanks.
@makortel, @felicepantaleo, @forthommel, @jan-kaspar, @GiacomoSguazzoni, @rovere, @VinInn, @Martin-Grunewald, @dgulhan this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-08-30 18:55 UTC, slava77 commented
@cmsbuild please test

2018-08-30 18:56 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-30 18:59 UTC, cmsbuild commented
There was an issue with git-cms-merge-topic you can see the log here: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30156/git-merge-result

2018-08-30 20:19 UTC, cmsbuild commented
-1

Tested at: b78dc6f5a9cf2f0155f862433a39338fe9ea7053


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/b78dc6f5a9cf2f0155f862433a39338fe9ea7053
https://github.com/cms-sw/cmssw/commit/ad680b714d902146ac2f93b78147538821425427
https://github.com/cms-sw/cmssw/commit/a5b1e46ea6d2e7ea347b04e32bb4a6de5c74b349
https://github.com/cms-sw/cmssw/commit/fc59a02074c0e6f1f2abc277fa82199e0a5f5d2a
https://github.com/cms-sw/cmssw/commit/2d95ea10053446eaf856323d0e33b052e51116b3
https://github.com/cms-sw/cmssw/commit/a1dc06b47842f607bc4072eb8efba88bf163d493
https://github.com/cms-sw/cmssw/commit/3d33c111af29fac362bb2d5e0dafdc4f1accc363
https://github.com/cms-sw/cmssw/commit/c6eda536e9298a697b281514ae5a9a3e6ab79312
https://github.com/cms-sw/cmssw/commit/8fbe2ee9ef554507b925aae8377340a1943db8f4
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30159/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30159/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30159/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  HeaderConsistency**

* **Build**:

I found an error when building: 
 
 <pre>>> Package Configuration/Geometry built
>> Entering Package FastSimulation/CTPPSSimHitProducer
Entering library rule at src/FastSimulation/CTPPSSimHitProducer/plugins
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-08-30-1100/src/FastSimulation/CTPPSSimHitProducer/plugins/CTPPSSimHitProducer.cc 
In file included from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-08-30-1100/src/FastSimulation/CTPPSSimHitProducer/plugins/CTPPSSimHitProducer.cc:51:0:
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-08-30-1100/poison/SimTransport/HectorProducer/interface/CTPPSHectorParameters.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
  ^~~~~
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-08-30-1100/src/FastSimulation/CTPPSSimHitProducer/plugins/CTPPSSimHitProducer.cc: In member function 'virtual void CTPPSSimHitProducer::produce(edm::Event&, const edm::EventSetup&)':
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-08-30-1100/src/FastSimulation/CTPPSSimHitProducer/plugins/CTPPSSimHitProducer.cc:158:37: error: 'mm_to_m' was not declared in this scope
                 z_tr1 =  vertex.z()*mm_to_m;//move z from mm to meters
</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/b78dc6f5a9cf2f0155f862433a39338fe9ea7053
https://github.com/cms-sw/cmssw/commit/ad680b714d902146ac2f93b78147538821425427
https://github.com/cms-sw/cmssw/commit/a5b1e46ea6d2e7ea347b04e32bb4a6de5c74b349
https://github.com/cms-sw/cmssw/commit/fc59a02074c0e6f1f2abc277fa82199e0a5f5d2a
https://github.com/cms-sw/cmssw/commit/2d95ea10053446eaf856323d0e33b052e51116b3
https://github.com/cms-sw/cmssw/commit/a1dc06b47842f607bc4072eb8efba88bf163d493
https://github.com/cms-sw/cmssw/commit/3d33c111af29fac362bb2d5e0dafdc4f1accc363
https://github.com/cms-sw/cmssw/commit/c6eda536e9298a697b281514ae5a9a3e6ab79312
https://github.com/cms-sw/cmssw/commit/8fbe2ee9ef554507b925aae8377340a1943db8f4
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30159/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30159/git-merge-result

2018-08-30 20:19 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2018-08-30 20:26 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24420/6236

2018-08-30 20:27 UTC, cmsbuild commented
Pull request #24420 was updated. @perrotta, @ssekmen, @Dr15Jones, @lveldere, @cvuosalo, @civanch, @emeschi, @ianna, @mdhildreth, @cmsbuild, @franzoni, @kpedro88, @slava77, @mommsen, @fabiocos, @davidlange6 can you please check and sign again.

2018-08-30 20:36 UTC, slava77 commented
@cmsbuild please test

2018-08-30 20:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-08-30 22:13 UTC, cmsbuild commented
-1

Tested at: eef05053aea68ee30a17cf0c986ea45be6750740


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/b78dc6f5a9cf2f0155f862433a39338fe9ea7053
https://github.com/cms-sw/cmssw/commit/ad680b714d902146ac2f93b78147538821425427
https://github.com/cms-sw/cmssw/commit/a5b1e46ea6d2e7ea347b04e32bb4a6de5c74b349
https://github.com/cms-sw/cmssw/commit/fc59a02074c0e6f1f2abc277fa82199e0a5f5d2a
https://github.com/cms-sw/cmssw/commit/2d95ea10053446eaf856323d0e33b052e51116b3
https://github.com/cms-sw/cmssw/commit/a1dc06b47842f607bc4072eb8efba88bf163d493
https://github.com/cms-sw/cmssw/commit/3d33c111af29fac362bb2d5e0dafdc4f1accc363
https://github.com/cms-sw/cmssw/commit/c6eda536e9298a697b281514ae5a9a3e6ab79312
https://github.com/cms-sw/cmssw/commit/8fbe2ee9ef554507b925aae8377340a1943db8f4
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30165/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30165/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24420/30165/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests  RelVals  AddOn**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test testRecoMETMETProducers had ERRORS
---> test testPhase2PixelNtuple had ERRORS


* **RelVals**:

When I ran the RelVals I found an error in the following worklfows:
8.0 step2
<pre>runTheMatrix-results/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/step2_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS.log

</pre>1306.0 step2
<pre>runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15/step2_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log

</pre>5.1 step1
<pre>runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS/step1_TTbar+TTbarFS+HARVESTFS.log

</pre>135.4 step1
<pre>runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

</pre>7.3 step2
<pre>runTheMatrix-results/7.3_CosmicsSPLoose_UP17+CosmicsSPLoose_UP17+DIGICOS_UP17+RECOCOS_UP17+ALCACOS_UP17+HARVESTCOS_UP17/step2_CosmicsSPLoose_UP17+CosmicsSPLoose_UP17+DIGICOS_UP17+RECOCOS_UP17+ALCACOS_UP17+HARVESTCOS_UP17.log

</pre>1330.0 step2
<pre>runTheMatrix-results/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM/step2_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM.log

</pre>10042.0 step2
<pre>runTheMatrix-results/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017/step2_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017.log

</pre>9.0 step2
<pre>runTheMatrix-results/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/step2_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST.log

</pre>150.0 step2
<pre>runTheMatrix-results/150.0_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018+RECOHI2018+HARVESTHI2018/step2_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018+RECOHI2018+HARVESTHI2018.log

</pre>158.0 step2
<pre>runTheMatrix-results/158.0_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018PPRECO+RECOHI2018PPRECO+HARVESTHI2018PPRECO/step2_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018PPRECO+RECOHI2018PPRECO+HARVESTHI2018PPRECO.log

</pre>25.0 step2
<pre>runTheMatrix-results/25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/step2_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT.log

</pre>10024.0 step2
<pre>runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017.log

</pre>10224.0 step2
<pre>runTheMatrix-results/10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU.log

</pre>11624.0 step2
<pre>runTheMatrix-results/11624.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019.log

</pre>25202.0 step2
<pre>runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step2_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

</pre>10824.0 step2
<pre>runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018.log

</pre>250202.181 step2
<pre>runTheMatrix-results/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step2_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25.log

</pre>20034.0 step2
<pre>runTheMatrix-results/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17.log

</pre>20434.0 step2
<pre>runTheMatrix-results/20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19.log

</pre>21234.0 step2
<pre>runTheMatrix-results/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D21_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D21+RecoFullGlobal_2023D21+HARVESTFullGlobal_2023D21/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D21_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D21+RecoFullGlobal_2023D21+HARVESTFullGlobal_2023D21.log

</pre>

* **AddOn**:

I found errors in the following addon tests:

cmsDriver.py TTbar_8TeV_TuneCUETP8M1_cfi  --conditions auto:run1_mc --fast  -n 100 --eventcontent AODSIM,DQM --relval 100000,1000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,VALIDATION  --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --datatier GEN-SIM-DIGI-RECO,DQMIO --beamspot Realistic8TeVCollision : FAILED - time: date Fri Aug 31 00:01:17 2018-date Thu Aug 30 23:59:16 2018 s - exit: 18688
cmsDriver.py TTbar_Tauola_13TeV_TuneCUETP8M1_cfi -s GEN,SIM,DIGI,L1,DIGI2RAW --mc --scenario=pp -n 10 --conditions auto:run2_mc_GRun --relval 9000,50 --datatier "GEN-SIM-RAW" --eventcontent RAWSIM --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run2_2018 --fileout file:RelVal_Raw_GRun_MC.root : FAILED - time: date Fri Aug 31 00:08:53 2018-date Thu Aug 30 23:59:34 2018 s - exit: 18688
cmsRun /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/cms/cmssw-patch/CMSSW_10_3_X_2018-08-30-1100/src/HLTrigger/Configuration/test/OnLine_HLT_GRun.py realData=False globalTag=@ inputFiles=@  : FAILED - time: date Fri Aug 31 00:08:53 2018-date Thu Aug 30 23:59:34 2018 s - exit: 17920
cmsDriver.py RelVal -s HLT:GRun,RAW2DIGI,L1Reco,RECO --mc --scenario=pp -n 10 --conditions auto:run2_mc_GRun --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era Run2_2018 --processName=HLTRECO --filein file:RelVal_Raw_GRun_MC.root --fileout file:RelVal_Raw_GRun_MC_HLT_RECO.root : FAILED - time: date Fri Aug 31 00:08:53 2018-date Thu Aug 30  [...]

2018-08-30 22:13 UTC, cmsbuild commented
Comparison not run due to runTheMatrix errors (RelVals and Igprof tests were also skipped)

2018-08-31 18:09 UTC, slava77 commented on Configuration/StandardSequences/python/DigiToRaw_cff.py
> +DigiToRaw = cms.Sequence(L1TDigiToRaw*siPixelRawData*SiStripDigiToRaw*ecalPacker*esDigiToRaw*hcalRawData*cscpacker*dtpacker*rpcpacker*ctppsRawData*castorRawData*rawDataCollector)
add this with ```ctpps_2016```
see e.g. https://github.com/cms-sw/cmssw/blob/b59dc5246fb83a92d5f9cf445a6f2891d6181a32/Configuration/StandardSequences/python/RawToDigi_cff.py#L98-L102

2018-08-31 18:27 UTC, slava77 reviewed
this is rather cursory, covering reco-related files.
Some more comprehensive notes can be expected some time next week (after the code runs)

2018-08-31 18:27 UTC, slava77 commented on Configuration/StandardSequences/python/ctppsRecoForSimulation2016_cff.py
> +import FWCore.ParameterSet.Config as cms
this looks like a temporary test config. it doesn't belong in  Configuration/StandardSequences main python dir.
please remove.

2018-08-31 18:27 UTC, slava77 commented on Configuration/StandardSequences/python/ctppsRecoForSimulation2017_cff.py
> +import FWCore.ParameterSet.Config as cms
this looks like a temporary test config. it doesn't belong in Configuration/StandardSequences main python dir.
please remove.

2018-08-31 18:27 UTC, slava77 commented on Configuration/StandardSequences/python/ctppsRecoForSimulation2018_cff.py
> +import FWCore.ParameterSet.Config as cms
this looks like a temporary test config. it doesn't belong in Configuration/StandardSequences main python dir.
please remove.

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.h
> +class CTPPSPixelDigiToRaw final : public edm::EDProducer {
legacy module base is not allowed for new modules.
Please use one of the MT-aware modules
https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkModuleTypes

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.h
> +#ifndef CTPPSPixelDigiToRaw_H
.h file is not really needed for producers and the content can be merged to the corresponding .cc file

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSTotemDigiToRaw.h
> +class CTPPSTotemDigiToRaw final : public edm::EDProducer {
legacy module base is not allowed for new modules.
Please use one of the MT-aware modules
https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkModuleTypes

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSTotemDigiToRaw.h
> +#ifndef CTPPSTotemDigiToRaw_H
.h file is not really needed for producers and the content can be merged to the corresponding .cc file

Please use an include guard matching the full file name subsystem_package_fileName_h

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/SealModule.cc
> +DEFINE_FWK_MODULE(CTPPSTotemDigiToRaw);
SealModule.cc is not really needed.
The ```DEFINE_FWK_MODULE``` can be in the corresponding .cc file where the producers are defined

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.h
> +  edm::ParameterSet config_;
please do not make copies of the full PSet. Simply extract all needed parameters from it in the module constructor.

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSPixelDigiToRaw.h
> +typedef uint64_t Word64;
please define a sensible fillDescriptions method 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSTotemDigiToRaw.h
> +  edm::ParameterSet config_;
please do not make copies of the full PSet. Simply extract all needed parameters from it in the module constructor.

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/plugins/CTPPSTotemDigiToRaw.h
> +  typedef uint64_t Word64;
please define a fillDescriptions here as well

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/python/ctppsDigiToRaw_cfi.py
> +ctppsRawData = cms.Sequence(ctppsTotemRawData*ctppsPixelRawData)
sequences should not be defined in cfi files. Please move to cff.
Normally, a cfi file should define only one module instance with its default parameters.

For this file this means:
- ctppsPixelRawData_cfi and ctppsTotemRawData_cfi are needed . Note, that if the fillDescriptions methods are defined appropriately, these files will be generated by the framework
- this file can be renamed to ctppsRawData_cff or ctppsDigiToRaw_cff

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/python/ctppsDigiToRaw_cfi.py
> +ctppsRawData = cms.Sequence(ctppsTotemRawData*ctppsPixelRawData)
it seems like the default should be an empty sequence and a non-empty should be defind with ctpps_2016

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/python/pgctppsDigiToRaw_cfi.py
> +import FWCore.ParameterSet.Config as cms
move to cff file

2018-08-31 18:27 UTC, slava77 commented on EventFilter/CTPPSRawToDigi/python/pgctppsRawToDigi_cfi.py
> +import FWCore.ParameterSet.Config as cms
move to cff file

2018-09-01 05:54 UTC, civanch commented
@mundim , would it be possible to split this PR on some orthogonal peaces? Here you add full developments and it is difficult for reviewers even to access a particular file.

2018-09-01 20:37 UTC, mundim commented
> would it be possible to split this PR on some orthogonal peaces? Here you add full developments and it is difficult for reviewers even to access a particular file.

Yes, of course. How you suggest to do it? I would point out 4 PRs that can for sure be split:
1 - PPSTools (new package)
2 - SimTransport (drastically changed package, following up the changes stated in Jan, 2017 
3 - FastSimulation/CTPPS* (no new feature, just adaptation of the old fast sim to the new transport
4 - The PPS fullsim (new and bigger chunk of code)
In the simulation meeting, this was the suggestion, but we were told we cold do it as we wish, since all the code was updated in the same branch and given the short time, we decided to do it at once. We can do the way it is better and easier to get it though.

2018-09-03 07:37 UTC, civanch commented
@mundim , now when we far beyond 10_2 schedule there is no problem go step by step. You may try to start from 1 or 1+2 and see how it will pass review. I suspect, that this will be much faster.

2018-09-04 02:28 UTC, kpedro88 commented
@mundim you should make a branch with just the changes in that package, and then make a new PR. (Please make sure the new branch compiles before submitting the PR.)

2018-09-04 06:09 UTC, ianna requested changes

2018-09-04 06:09 UTC, ianna commented on Geometry/CMSCommonData/data/extend/cmsextent.xml
> +		<Tubs name="ZDCtoVF200" rMin="[Rmin]" rMax="[CMSR2]" dz="26*m" startPhi="0*deg" deltaPhi="360*deg"/>
@mundim - you must create a new version of this file in order not to change previous geometries. The rule for new files is as follows _name/year/version/name.xml_:
```
Geometry/CMSCommonData/data/cmsextent/2018/v1/cmsextent.xml
```

2018-09-04 06:10 UTC, ianna commented
-1

2018-09-04 13:46 UTC, mundim commented
[https://github.com/cms-sw/cmssw/pull/24420#issuecomment-418027754](url)
Since 1 and 2 are (almost) independent packages, I would suggest to make these first, then we can proceed with 3+4 together. Is this reasonable?

2018-09-04 13:48 UTC, mundim commented
@civanch @kpedro88 Ok, I'll do 1+2 together...

2018-09-04 14:14 UTC, civanch commented
@mundim , this is OK. I would advice to keep initial area from where this PR was pushed and create a fresh one based on the recent IB. You may copy files between areas, after 1+2 will be merged you may start 3 and 4 in other areas.

2018-09-05 22:56 UTC, mundim commented
@civanch @kpedro88 

I prepared a new branch with the item 1+2+3 (the third step is just adaptation to the new transport and was already in the release, in case it is not ok, I can redo it). However, after git checkdeps -a, the compilation fails at 

RecoEcal/EgammaClusterProducers/src/EcalDigiSelector.cc 

because of:

template <class T> struct is_complex<std::complex<T> > : public true_type{}: complex is not a member of std

The packages for which I'm issuing the PR doesn't depend on this package, so I don't know what to do.

2018-09-06 22:28 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-09-06 22:30 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24420/6333

2018-09-06 22:31 UTC, cmsbuild commented
Pull request #24420 was updated. @perrotta, @ssekmen, @Dr15Jones, @lveldere, @cvuosalo, @civanch, @emeschi, @ianna, @mdhildreth, @cmsbuild, @franzoni, @kpedro88, @slava77, @mommsen, @fabiocos, @davidlange6 can you please check and sign again.

2018-09-11 14:01 UTC, mundim commented
Just a clarification: this PR needs to be closed and reissued again due to the PR splitting (PR 24490) or will it proceed normally?

2018-09-11 14:07 UTC, kpedro88 commented
This PR should be closed in favor of the split PRs.

2018-09-11 14:10 UTC, mundim commented
Then, a new PR should be issued. We understood it wrong. Is there time yet to issue the PR for the remaining code? Sorry about it.

2018-09-11 14:53 UTC, kpedro88 commented
There is still a week until the last 10_3_X prerelease is closed (the schedule was revised recently), so you can start preparing the subsequent PR.

2018-09-12 12:30 UTC, mundim commented
Closing this PR, as agreed when asked to split this PR in smaller ones.

2018-09-12 12:30 UTC, closed without merging