Phase2-hgx158 Correct density of PCB for v9 geometry
cms-sw/cmssw pull request #24807
Opened 2018-10-04 18:23 UTC by bsunanda

A new material with density 1.85 g/cc and composition same a M_NEMA FR4 plate is defined and used for v9 HGCal geometry

2018-10-04 18:29 UTC, bsunanda commented
@cmsbuild Please test

2018-10-04 18:30 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-10-04 19:58 UTC, cmsbuild commented
+1
Tested at: aea54971ead77035c1180d9aa33f34824c344557
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24807/30892/summary.html

2018-10-04 19:58 UTC, cmsbuild commented
Comparison job queued.

2018-10-04 21:13 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24807/30892/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3162909
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3162710
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 134 log files, 14 edm output root files, 32 DQM output files

2018-10-08 08:21 UTC, ianna requested changes

2018-10-08 11:57 UTC, bsunanda commented on Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml
> +  <CompositeMaterial name="HGC_G10-FR4" density="1.85*g/cm3" symbol=" " method="mixture by weight">
@ianna I thought about that. Should I then change all scenario's with HGCal?

2018-10-08 12:12 UTC, ianna commented on Geometry/HGCalCommonData/data/hgcal/v9/hgcal.xml
> +  <CompositeMaterial name="HGC_G10-FR4" density="1.85*g/cm3" symbol=" " method="mixture by weight">
yes, please.

2018-10-08 14:35 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-10-08 14:38 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24807/6775

2018-10-08 14:38 UTC, cmsbuild commented
Pull request #24807 was updated. @civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-10-08 14:39 UTC, bsunanda commented
@cmsbuild Please test

2018-10-08 14:39 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-10-08 16:54 UTC, cmsbuild commented
+1
Tested at: e581c7a64b10c9bf36700c35af4a9a7383220067
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24807/30926/summary.html

2018-10-08 16:54 UTC, cmsbuild commented
Comparison job queued.

2018-10-08 18:33 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24807/30926/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3162979
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3162781
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 134 log files, 14 edm output root files, 32 DQM output files

2018-10-08 19:16 UTC, kpedro88 commented
+upgrade

2018-10-09 05:40 UTC, ianna commented
+1

2018-10-09 05:40 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-10-11 08:29 UTC, fabiocos commented
+1

2018-10-11 08:29 UTC, merged