[HGCal/FW] Add support for HGCal Geom in FW
cms-sw/cmssw pull request #25135
Opened 2018-11-06 14:35 UTC by Mourtz

2018-11-06 14:36 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-06 14:38 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25135/7131

2018-11-06 14:38 UTC, cmsbuild commented
A new Pull Request was created by  @Mourtz (Alex Mourtziapis) for master.

It involves the following packages:

.gitignore
Fireworks/Core
Fireworks/Geometry
Fireworks/SimData
Geometry/HGCalGeometry


@smuzaffar, @civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @alja, @kpedro88 can you please review it and eventually sign? Thanks.
@alja this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-11-06 14:54 UTC, Dr15Jones commented
Please remove the `.gitignore` file from this pull request.

2018-11-06 16:38 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-06 16:49 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25135/7140

2018-11-06 16:50 UTC, cmsbuild commented
Pull request #25135 was updated. @civanch, @Dr15Jones, @cvuosalo, @ianna, @kpedro88, @cmsbuild, @alja, @mdhildreth can you please check and sign again.

2018-11-06 16:56 UTC, alja commented
+1

2018-11-06 16:57 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-11-06 16:58 UTC, alja commented
@mourtz can you add a screenshot of graphical view in the PR?

2018-11-06 19:06 UTC, cmsbuild commented
+1
Tested at: aa33f9646fbfd2e3d7454a96b0147bea61629724
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31503/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/fe5711cc05bce79bca3d328060b8faa519c60762
https://github.com/cms-sw/cmssw/commit/c395e0cf260f1dcb5e5dd53aaaba6a7ff92a6111
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31503/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31503/git-merge-result

2018-11-06 19:06 UTC, cmsbuild commented
Comparison job queued.

2018-11-06 20:32 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31503/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 2993155
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2992957
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 134 log files, 14 edm output root files, 32 DQM output files

2018-11-07 16:16 UTC, Mourtz commented
@alja 
Here's the Geometry
![geom](https://user-images.githubusercontent.com/6444818/48144216-bf83af80-e2b0-11e8-96f9-019db4e342fa.png)

2018-11-08 11:28 UTC, ianna requested changes

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FW3DViewGeometry.cc
> +      for( std::vector<unsigned int>::const_iterator id = ids.begin();
@Mourtz - please, use a range-based for loop:
```
for( const auto& id : m_geom->getMatchedIds( FWGeometry::HGCalEE ))
```

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FW3DViewGeometry.cc
> +    for( std::vector<unsigned int>::const_iterator id = ids.begin();
@Mourtz - please, use a range-based for loop

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FW3DViewGeometry.cc
> +      for( std::vector<unsigned int>::const_iterator id = ids.begin();
@Mourtz - please, use a range-based for loop

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FWGeometry.cc
> +   for( IdToInfoItr it = m_idToInfo.begin(), itEnd = m_idToInfo.end();
@Mourtz - please, use a range-based for loop

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FWGeometry.cc
> +        for(std::vector<unsigned int>::iterator id_it = ids.begin(); id_it != ids.end(); ++id_it) {
@Mourtz - please, use a range-based for loop or should it be ```find_if```?

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FWGeometry.cc
> +   float sideToSideWaferSize = 16.7441;
```
16.7441f
```
Please use the literal here and also later in the code

2018-11-08 11:28 UTC, ianna commented on Fireworks/Core/src/FWGeometry.cc
> +   float dx = sideToSideWaferSize/2;
```
0.5f*sideToSideWaferSize
```

2018-11-08 11:28 UTC, ianna commented on Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
> +   for( std::vector<CaloParticle>::const_iterator iData = collection->begin(), end = collection->end(); iData != end; ++iData )
```
for( const auto& iData : collection )
```

2018-11-08 11:28 UTC, ianna commented on Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
> +         for( auto it = clusterDetIds.begin(), itEnd = clusterDetIds.end();
```
for( auto it : clusterDetIds )
```

2018-11-08 11:28 UTC, ianna commented on Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc
> +REGISTER_FWPROXYBUILDER( FWCaloParticleProxyBuilder, CaloParticleCollection, "CaloFTW", FWViewType::kAll3DBits | FWViewType::kAllRPZBits );
please, remove the special character at the end

2018-11-08 11:28 UTC, ianna commented on Geometry/HGCalGeometry/src/HGCalGeometry.cc
>      std::pair<float,float> xy;
@Mourtz - this is exact code duplication from line 281. Please, implement it as a separate private member function.

2018-11-08 11:28 UTC, ianna commented on Geometry/HGCalGeometry/src/HGCalGeometry.cc
> +    std::pair<float,float> xy;
@Mourtz - is it the same code as above?

2018-11-08 14:22 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-08 14:43 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-08 14:58 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25135/7157

2018-11-08 15:33 UTC, kpedro88 commented
please test

2018-11-08 15:34 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-11-08 18:33 UTC, cmsbuild commented
+1
Tested at: 55855feb8f7b0e9379eb8d1c8644507b112d4ac1
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31537/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
https://github.com/cms-sw/cmssw/commit/5fe97dc7ba54ac00b509a4ad568bbc257f20656f
https://github.com/cms-sw/cmssw/commit/291f20c37f6ec6a613100f42fbd4b2d1ac0eaef3
https://github.com/cms-sw/cmssw/commit/fe5711cc05bce79bca3d328060b8faa519c60762
https://github.com/cms-sw/cmssw/commit/c395e0cf260f1dcb5e5dd53aaaba6a7ff92a6111
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31537/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31537/git-merge-result

2018-11-08 18:33 UTC, cmsbuild commented
Comparison job queued.

2018-11-08 19:39 UTC, kpedro88 commented
+upgrade
The image in https://github.com/cms-sw/cmssw/pull/25135#issuecomment-436680639 looks very nice

2018-11-08 19:59 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25135/31537/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25135/7.3_CosmicsSPLoose_UP18+CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3013827
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3013629
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 134 log files, 14 edm output root files, 32 DQM output files

2018-11-12 14:10 UTC, ianna requested changes

2018-11-12 14:10 UTC, ianna commented on Geometry/HGCalGeometry/test/HGCalTestNeighbor.cc
> +	for (int iphi : iphis) {
@Mourtz - an indentation is missing

2018-11-12 14:10 UTC, ianna commented on Geometry/HGCalGeometry/src/HGCalGeometry.cc
>      std::pair<float,float> xy;
@Mourtz - I do not see where it was resolved.

2018-11-12 14:55 UTC, Mourtz commented on Geometry/HGCalGeometry/test/HGCalTestNeighbor.cc
> +	for (int iphi : iphis) {
Merged this code form #25027.

2018-11-12 15:01 UTC, Mourtz commented
@ianna 
The files that you are suggesting me to modify were merged from #25027.

2018-11-12 15:21 UTC, Mourtz commented
@ianna 
It shouldn't show any changes in those files....
Do you want me to get them out the PR?

2018-11-19 11:23 UTC, Mourtz commented
is there any problem with merging the PR?

2018-11-19 13:43 UTC, ianna commented
+1

2018-11-19 15:03 UTC, fabiocos commented
@alja could you please check and sign it in case?

2018-11-19 17:11 UTC, alja commented
+1

2018-11-19 17:11 UTC, alja commented
+1

2018-11-19 17:11 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-11-19 18:11 UTC, Mourtz commented
changes of this PR are included in #25284. Keeping only the last PR.

2018-11-19 18:11 UTC, closed without merging