Move MTD geometry test from expanded to filtered view
cms-sw/cmssw pull request #25217
Opened 2018-11-13 09:39 UTC by fabiocos

This PR addresses a comment of @ianna about using only filtered views for geometry navigation.
As in the case of these tests the whole geometry tree structure is scanned, a pass through filter is used.

2018-11-13 09:39 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-13 09:40 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25217/7229

2018-11-13 09:41 UTC, cmsbuild commented
A new Pull Request was created by  @fabiocos (Fabio Cossutti) for master.

It involves the following packages:

Geometry/MTDCommonData


@civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please review it and eventually sign? Thanks.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2018-11-13 09:42 UTC, fabiocos commented
please test

not testing anything, the test modules have been probed with the standalone configuration provided in the Geometry/MTDCommonData package

2018-11-13 09:43 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-11-13 09:44 UTC, fabiocos commented
@ianna please let me know whether this is what you had in mind, in this case I do not see a specific attribute to select without changing the logic of the code

2018-11-13 09:56 UTC, ianna requested changes

2018-11-13 09:56 UTC, ianna commented on Geometry/MTDCommonData/test/TestMTDNumbering.cc
>  #include "DetectorDescription/Core/interface/DDExpandedNode.h"
@fabiocos - is it needed?

2018-11-13 09:56 UTC, ianna commented on Geometry/MTDCommonData/test/TestMTDNumbering.cc
> +  typedef DDFilteredView::nav_type nav_type;
```
using nav_type = DDFilteredView::nav_type;
```

2018-11-13 09:56 UTC, ianna commented on Geometry/MTDCommonData/test/TestMTDNumbering.cc
>    typedef std::map<nav_type,int> id_type;
```
using id_type = std::map<nav_type,int>;
```

2018-11-13 09:56 UTC, ianna commented on Geometry/MTDCommonData/test/TestMTDPosition.cc
>  #include "DetectorDescription/Core/interface/DDExpandedNode.h"
is it needed?

2018-11-13 11:43 UTC, cmsbuild commented
+1
Tested at: 025c9c25de39ffc52545b82871793172ebdf88d7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25217/31621/summary.html

2018-11-13 11:43 UTC, cmsbuild commented
Comparison job queued.

2018-11-13 13:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25217/31621/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25217/27434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D35_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D35+RecoFullGlobal_2023D35+HARVESTFullGlobal_2023D35

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3013311
 - DQMHistoTests: Total failures: 11
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3013103
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 134 log files, 14 edm output root files, 32 DQM output files

2018-11-13 15:58 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2018-11-13 15:59 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25217/7234

2018-11-13 15:59 UTC, cmsbuild commented
Pull request #25217 was updated. @civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2018-11-13 16:12 UTC, ianna commented
+1

2018-11-13 16:13 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2018-11-13 18:37 UTC, cmsbuild commented
+1
Tested at: 5c8bc2a6de99a156d69b046c3fa5d384fcc24f55
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25217/31630/summary.html

2018-11-13 18:37 UTC, cmsbuild commented
Comparison job queued.

2018-11-14 06:46 UTC, fabiocos commented
@kpedro88 this is the code cleaning and move to filtered view of two standalone test classes not used in any production workflow

2018-11-14 15:04 UTC, kpedro88 commented
+upgrade

2018-11-14 15:04 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2018-11-15 08:52 UTC, fabiocos commented
+1

2018-11-15 08:53 UTC, merged