Utilities and fixes for HipPy alignment
cms-sw/cmssw pull request #25874
Opened 2019-02-06 14:24 UTC by hroskes

2019-02-06 14:25 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-06 14:31 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25874/8338

- This PR adds an extra 36KB to repository

2019-02-06 14:32 UTC, cmsbuild commented
A new Pull Request was created by  @hroskes (Heshy Roskes) for master.

It involves the following packages:

Alignment/CommonAlignment
Alignment/HIPAlignmentAlgorithm


@cmsbuild, @pohsun, @franzoni, @tocheng can you please review it and eventually sign? Thanks.
@pakhotin, @adewit, @tocheng, @tlampen, @mschrode, @mmusich this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-02-08 09:45 UTC, fabiocos commented
please test

2019-02-08 09:45 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-02-08 12:03 UTC, cmsbuild commented
+1
Tested at: 4adf40bbdc5e37d40f0f10daa75d67f59ea4e415
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33046/summary.html

2019-02-08 12:03 UTC, cmsbuild commented
Comparison job queued.

2019-02-08 13:37 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33046/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 8 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3097440
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3097242
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-02-13 19:03 UTC, pohsun requested changes

2019-02-13 19:40 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-13 19:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25874/8424

- This PR adds an extra 40KB to repository

2019-02-13 19:45 UTC, cmsbuild commented
Pull request #25874 was updated. @cmsbuild, @pohsun, @franzoni, @tocheng can you please check and sign again.

2019-02-13 20:33 UTC, pohsun commented
please test

2019-02-13 20:35 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-02-13 22:14 UTC, cmsbuild commented
+1
Tested at: 46b62017689d3893ffa075411d49a49ce778466b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33119/summary.html

2019-02-13 22:14 UTC, cmsbuild commented
Comparison job queued.

2019-02-13 22:27 UTC, pohsun commented
+1

2019-02-13 22:28 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-02-13 23:32 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33119/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 3 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3097440
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3097242
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-02-15 09:02 UTC, fabiocos commented on Alignment/HIPAlignmentAlgorithm/scripts/hippyaddtobaddatafiles.py
> +        print "found and added a bad file:\n"+filename
@hroskes could you please make this python3 compliant adding parentheses to the print statements and 
from __future__ import print_function
at the beginning?

2019-02-15 22:59 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-15 23:04 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25874/8456

- This PR adds an extra 40KB to repository

2019-02-15 23:04 UTC, cmsbuild commented
Pull request #25874 was updated. @cmsbuild, @pohsun, @franzoni, @tocheng can you please check and sign again.

2019-02-17 14:35 UTC, pohsun commented
please test

2019-02-17 14:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-02-17 16:59 UTC, cmsbuild commented
+1
Tested at: c1bac5e5492ce05effd27a5c9896ec55197f4e27
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33166/summary.html

2019-02-17 16:59 UTC, cmsbuild commented
Comparison job queued.

2019-02-17 18:22 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25874/33166/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3098286
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3098088
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-02-19 13:17 UTC, pohsun commented
+1

2019-02-19 13:17 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-02-19 14:48 UTC, fabiocos commented
+1

2019-02-19 14:48 UTC, merged