fixed bugs in relval_step.py and added VBF Hbb Hinv 2018 workflows
cms-sw/cmssw pull request #25948
Opened 2019-02-15 04:02 UTC by chayanit

Dear experts, 

I have added VBFHToZZTo4Nu_M125 and VBFHToBB_M125 2018 workflows as they are missing and needed for HCAL changes study (according to https://its.cern.ch/jira/browse/PDMVRELVALS-4). I have also found some bugs in relval_steps.py where geometry is missing in Digi, Reco, Harvest steps and PU Minbias was not added in RecoPU17 step  for 2017 relvals. 

Please consider and merge these changes for PdmV. Thank you. 

Cheers,
Chayanit as L3 validation manager in PdmV

2019-02-15 04:03 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-15 04:08 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25948/8442

- This PR adds an extra 52KB to repository

2019-02-15 04:09 UTC, cmsbuild commented
A new Pull Request was created by  @chayanit (Chayanit Asawatangtrakuldee) for master.

It involves the following packages:

Configuration/PyReleaseValidation


@cmsbuild, @zhenhu, @prebello, @pgunnell, @kpedro88 can you please review it and eventually sign? Thanks.
@makortel, @Martin-Grunewald this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-02-15 20:34 UTC, prebello commented
Hi @chayanit , did you contact someone else to know about the 'Geom' : 'DB:Extended' in 2017?
in 2017 you have to check the file
Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
and you can see that for 2017 option there is 
upgradeProperties[2017] = {
    '2017' : {
        'Geom' : 'DB:Extended',
        'GT' : 'auto:phase1_2017_realistic',
        'HLTmenu': '@relval2017',
	'Era' : 'Run2_2017',
       'ScenToRun' : ['GenSimFull','DigiFull','RecoFull','HARVESTFull','ALCAFull'], 

threrefore this new inclusion of 'Geom' : 'DB:Extended', is not needed in principle, unless you have added wfs in a different way. 
Please take a look in your new wfs before testing this PR.

2019-02-16 02:09 UTC, zhenhu commented
Hi Patricia, the workflows Chayanit updated in this PR are used to produce the special LHE relvals. They are the standard workflows rather than the upgrade ones. I’ll double check to make sure this PR works properly.

2019-02-16 11:37 UTC, prebello commented
Hi @zhenhu I know and I also know that new 2017 relvals are added as "standard" instead of "upgrade" because it seems to be easier, and the implementation looks not wrong.
What I am pointing here is:
1) is it actually a bug in 2017 conditions? 
2) how this change in Geometry affect other 2017 wfs? was it checked?
We know from past experience that changing code here affects things elsewhere.. so just to be careful when saying that "a bug was fixed". ;-)  
FYI @chayanit

2019-02-16 15:06 UTC, prebello commented
Other thing @zhenhu  is baseDataSetRelease[13] string for the input right, acc our latest PR with updates?

2019-02-16 15:15 UTC, prebello commented
@zhenhu  @chayanit  your injections based on this PR is wrong, 
CMSSW_10_4_0_patch1__fullsimPU_2018_JMEforHCALchanges_VBF-1550206669
CMSSW_10_4_0_patch1__fullsimPU_2017_JMEforHCALchanges_VBF-1550206307
acc
https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/fd52f8388d9216eb70af7c83a4d0a084/configFile
it is using
--pileup_input das:/RelValMinBias_13/CMSSW_10_4_0-103X_mc2017_realistic_v2-v1/GEN-SIM 
please close it and reject your batches.
Please, before injecting, make a test to check cmsdrivers. After all ends ok, then you can make PR for implementing changes. 
Thank you.

2019-02-16 16:22 UTC, zhenhu commented
Hi @prebello , yes, baseDataSetRelease[13] in this PR should be updated to 'CMSSW_10_5_0_pre1-103X_mc2017_realistic_v2-v1' to be consistent with the upgrade2017 workflows. 
But the previous injections by Chayanit seem fine to me, since they were submitted in 104X, and the strings used there were also for 104X.

2019-02-21 08:21 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-21 08:22 UTC, chayanit commented
Hi @prebello, I updated string at baseDataSetRelease[13] to the one I used for 10_4_0_patch1 campaign (CMSSW_10_4_0-103X_mc2017_realistic_v2-v1). I'm not sure why we need to do this as the string at baseDataSetRelease[13] is not used anymore for our main campaign (10_5_X). Anyway let me know if everything is ok now.

2019-02-21 08:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25948/8502

- This PR adds an extra 52KB to repository

2019-02-21 08:25 UTC, cmsbuild commented
Pull request #25948 was updated. @cmsbuild, @zhenhu, @prebello, @pgunnell, @kpedro88 can you please check and sign again.

2019-02-21 15:08 UTC, kpedro88 commented
please test

2019-02-21 15:09 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-02-21 16:08 UTC, prebello commented
> Hi @prebello, I updated string at baseDataSetRelease[13] to the one I used for 10_4_0_patch1 campaign (CMSSW_10_4_0-103X_mc2017_realistic_v2-v1). I'm not sure why we need to do this as the string at baseDataSetRelease[13] is not used anymore for our main campaign (10_5_X). Anyway let me know if everything is ok now.

Hi @chayanit, you have to update with the new 10-5-0-pre1 strings instead (the latest regenerated), not 10-4-0-patch1(used before). The reason: you added new wfs that will recycle GEN-SIM  for PU. Making this PR means that your updates will come in next releases and these relvals have to read theis proper inputs (not from 10-4-X but from 10-5-X). Is it clear?

2019-02-21 16:23 UTC, prebello requested changes
please use 'CMSSW_10_5_0_pre1-103X_mc2017_realistic_v2-v1' to be consistent with the upgrade2017 workflows.

2019-02-22 07:00 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-02-22 07:05 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-25948/8514

- This PR adds an extra 52KB to repository

2019-02-22 07:06 UTC, cmsbuild commented
Pull request #25948 was updated. @cmsbuild, @zhenhu, @prebello, @pgunnell, @kpedro88 can you please check and sign again.

2019-02-22 08:21 UTC, zhenhu commented
please test workflow 1362.17,1362.18,25212.17,25212.18

2019-02-22 08:23 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-02-22 11:01 UTC, cmsbuild commented
+1
Tested at: 04297559f04de6d6f048bcb288383d794792afd9
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25948/33220/summary.html

2019-02-22 11:02 UTC, cmsbuild commented
Comparison job queued.

2019-02-22 12:26 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25948/33220/summary.html

@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25948/1362.17_VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP17+VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP17+DIGIUP17+RECOUP17+HARVESTUP17
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25948/1362.18_VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP18+VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP18+DIGIUP18+RECOUP18+HARVESTUP18
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25948/25212.17_VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP17+VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP17+DIGIUP17_PU25+RECOUP17_PU25+HARVESTUP17_PU25
   * /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-25948/25212.18_VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP18+VBFHToZZTo4Nu_M125_Pow_py8_Evt_13UP18+DIGIUP18_PU25+RECOUP18_PU25+HARVESTUP18_PU25

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 1 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3098286
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3098088
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-02-22 12:32 UTC, zhenhu commented
+1

2019-02-22 13:29 UTC, prebello commented on Configuration/PyReleaseValidation/python/relval_steps.py
> +    'CMSSW_10_4_0-103X_mc2017_realistic_v2-v1',		# 21 - GEN-SIM inputs for LHE-GEN-SIM 2017 workflows
perfect. thank you

2019-02-22 13:30 UTC, prebello commented on Configuration/PyReleaseValidation/python/relval_steps.py
> +    'CMSSW_10_4_0-103X_upgrade2018_realistic_v8-v1',		# 22 - GEN-SIM inputs for LHE-GEN-SIM 2018 workflows
perfect too

2019-02-26 10:49 UTC, fabiocos commented
@kpedro88 this update is not upgrade specific, could you please anyway have a look? It seems ok to me

2019-02-26 10:49 UTC, fabiocos commented
+1

2019-02-26 15:18 UTC, kpedro88 commented
+upgrade

2019-02-26 15:21 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will be automatically merged.

2019-02-26 15:21 UTC, merged