Fix: FWHGCRecHitProxyBuilder
cms-sw/cmssw pull request #26058
Opened 2019-03-04 16:31 UTC by Mourtz

HGCRecHitProxy now renders the rechits with the correct geometry.
Also added Layer, Heatmap and Endcap selector.

@rovere

2019-03-04 16:32 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-03-04 16:38 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26058/8612

- This PR adds an extra 16KB to repository

2019-03-04 16:38 UTC, cmsbuild commented
A new Pull Request was created by  @Mourtz (Alex Mourtziapis) for master.

It involves the following packages:

Fireworks/Calo


@cmsbuild, @alja, @Dr15Jones can you please review it and eventually sign? Thanks.
@alja this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-03-04 16:44 UTC, Dr15Jones requested changes

2019-03-04 16:44 UTC, Dr15Jones commented on Fireworks/Calo/plugins/FWHGCRecHitProxyBuilder.cc
> +   static const uint8_t gradient_steps = 9;
Best to be `static constexpr`

2019-03-04 16:44 UTC, Dr15Jones commented on Fireworks/Calo/plugins/FWHGCRecHitProxyBuilder.cc
> +   const float gradient[3][gradient_steps] = {
Please make `static constexpr float`

2019-03-05 09:32 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-03-05 09:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26058/8620

- This PR adds an extra 16KB to repository

2019-03-05 09:40 UTC, cmsbuild commented
Pull request #26058 was updated. @cmsbuild, @alja, @Dr15Jones can you please check and sign again.

2019-03-05 10:46 UTC, fabiocos commented
please test

2019-03-05 10:47 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-03-05 11:13 UTC, cmsbuild commented
+1
Tested at: 5d9488dce12722205756caf3bbc135f4b4b219cf
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26058/33406/summary.html

2019-03-05 11:13 UTC, cmsbuild commented
Comparison not run due to Fireworks only changes in PR (RelVals and Igprof tests were also skipped)

2019-03-05 18:23 UTC, alja commented
+1

2019-03-05 18:24 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-03-05 21:02 UTC, fabiocos commented
+1

2019-03-05 21:02 UTC, merged