Fix clang warnings in Calibration
cms-sw/cmssw pull request #26112
Opened 2019-03-08 15:03 UTC by mrodozov

#### PR description:

#### PR validation:

2019-03-08 15:04 UTC, mrodozov commented
please test

2019-03-08 15:06 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-03-08 15:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26112/8680

- This PR adds an extra 20KB to repository

2019-03-08 15:14 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-03-08 15:14 UTC, cmsbuild commented
A new Pull Request was created by  @mrodozov (Mircho Rodozov) for master.

It involves the following packages:

Calibration/EcalAlCaRecoProducers
Calibration/HcalCalibAlgos


@cmsbuild, @pohsun, @franzoni, @tocheng can you please review it and eventually sign? Thanks.
@mmusich, @tocheng, @argiro this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-03-08 18:45 UTC, cmsbuild commented
+1
Tested at: ed140d8d2e220fe61982ca585b824730d52461a0
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26112/33481/summary.html

2019-03-08 18:45 UTC, cmsbuild commented
Comparison job queued.

2019-03-08 20:06 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26112/33481/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 8 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3114829
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3114631
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-03-10 18:06 UTC, pohsun requested changes

2019-03-10 18:06 UTC, pohsun commented on Calibration/HcalCalibAlgos/test/HcalCorrPFCalculation.cc
> +      HcalDetId tempId;
It's better to remove also L388~L395, which are related to `tempId1` and `tempId2`.

2019-03-11 11:19 UTC, mrodozov commented
please test

2019-03-11 11:19 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-03-11 11:24 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26112/8708

- This PR adds an extra 24KB to repository

2019-03-11 11:25 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-03-11 11:25 UTC, cmsbuild commented
Pull request #26112 was updated. @cmsbuild, @pohsun, @franzoni, @tocheng can you please check and sign again.

2019-03-11 14:31 UTC, cmsbuild commented
+1
Tested at: dabe25bca3026f269d76ca2fa4f3804f5d6d44db
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26112/33513/summary.html

2019-03-11 14:31 UTC, cmsbuild commented
Comparison job queued.

2019-03-11 14:53 UTC, pohsun commented
+1

2019-03-11 14:54 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-03-11 15:53 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26112/33513/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 32
 - DQMHistoTests: Total histograms compared: 3114829
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3114631
 - DQMHistoTests: Total skipped: 197
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 31 files compared)
 - Checked 133 log files, 14 edm output root files, 32 DQM output files

2019-03-11 17:28 UTC, fabiocos commented
+1

2019-03-11 17:28 UTC, merged