Scripts to create "candidates" and GTs for Scenario 2021
cms-sw/cmssw pull request #27749
Opened 2019-08-12 09:44 UTC by slomeo

#### PR description:

Scripts to create "candidates" and GTs for Scenario 2021

#### PR validation:

test ok by using Scenario 2021 (see PR #27744 ): no overlaps inside Muon System and all MB4Shields for Run3
candidate name: 106X_mcRun3_2021_realistic_Candidate_2019_08_12_09_16_22
candidate label: Extended2021
from GT: 106X_mcRun3_2021_realistic_Queue
scenario: RunIII Simulation

2019-08-12 09:44 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-08-12 09:51 UTC, cmsbuild commented
A new Pull Request was created by  @slomeo (Sergio Lo Meo) for master.

It involves the following packages:

CondTools/Geometry
DetectorDescription/DDCMS
Geometry/CMSCommonData


@civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88, @ggovi can you please review it and eventually sign? Thanks.
@mmusich, @vargasa this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-08-12 23:00 UTC, cvuosalo commented
@cmsbuild please test

2019-08-12 23:00 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-08-13 02:10 UTC, cmsbuild commented
+1
Tested at: 1385ea75fcb5748df9ef5999559ad4629f7690f1
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4bd72f/1983/summary.html

2019-08-13 02:10 UTC, cmsbuild commented
Comparison job queued.

2019-08-13 04:15 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4bd72f/1983/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2939508
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2939166
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 142 log files, 14 edm output root files, 34 DQM output files

2019-08-13 06:44 UTC, ianna requested changes

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometryCTPPStest_local.py
> +             tag = cms.string('XMLFILE_Geometry_110YV1_Extended2017_mc'),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("CASTORRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("ZDCRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("CTRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("EERECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("CSCRECODIGI_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("CSCRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("EBRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("RPCRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("DTRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("EPRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("XMLFILE_Geometry_Extended_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("TKExtra_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("TKRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string('TKParameters_Geometry_110YV1'),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrytest_local.py
> +             tag = cms.string("HCALRECO_Geometry_110YV1"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrywriter.py
> +                                           XMLFileName = cms.untracked.string("./geSingleBigFile.xml"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometrywriter.py
> +                                          toPut = cms.VPSet(cms.PSet(record = cms.string('GeometryFileRcd'),tag = cms.string('XMLFILE_Geometry_110YV2_Extended_mc')),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/geometryxmlwriter.py
> +                              fileName = cms.untracked.string("./geSingleBigFile.xml")
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/xmlgeometrywriter.py
> +                                           XMLFileName = cms.untracked.string("./geSingleBigFile.xml"),
TagXX is replaced by a script, please do not change it

2019-08-13 06:44 UTC, ianna commented on CondTools/Geometry/test/xmlgeometrywriter.py
> +                                          toPut = cms.VPSet(cms.PSet(record = cms.string('GeometryFileRcd'),tag = cms.string('XMLFILE_Geometry_110YV2_Extended_mc')))
TagXX is replaced by a script, please do not change it

2019-08-13 06:49 UTC, ianna commented
@slomeo - it looks like a duplicate of https://github.com/cms-sw/cmssw/pull/27693

@fabiocos, @ggovi - FYI

2019-08-13 06:55 UTC, slomeo commented
@ianna Yes, it seems the same PR. Probably it's better to close #27749

2019-08-13 07:28 UTC, closed without merging