Fix GCC 9 shadowing compiler warnings in Core
cms-sw/cmssw pull request #27949
Opened 2019-09-06 21:49 UTC by wddgit

#### PR description:

Fix GCC 9 shadowing compiler warnings in Core. This should not change behavior. Most of this is variable renaming. One unused variable deleted. A couple places the same variable could be reused instead of declaring a new one.

As far as I could tell no real bugs uncovered by this.

#### PR validation:

Existing tests should be adequate, there is no new functionality.

#### if this PR is a backport please specify the original PR:

Not a backport.

2019-09-06 21:49 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-09-06 21:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-27949/11803

- This PR adds an extra 216KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  FWCore/Framework/src/EventProcessor.cc  modified in PR(s): #27948

2019-09-06 21:58 UTC, cmsbuild commented
A new Pull Request was created by  @wddgit (W. David Dagenhart) for master.

It involves the following packages:

DataFormats/Common
DataFormats/FWLite
DataFormats/Provenance
FWCore/Catalog
FWCore/Concurrency
FWCore/Framework
FWCore/Integration
FWCore/ParameterSet
FWCore/PluginManager
FWCore/ServiceRegistry
FWCore/Services
IOMC/RandomEngine
IOPool/Input


@cmsbuild, @smuzaffar, @Dr15Jones can you please review it and eventually sign? Thanks.
@makortel, @Martin-Grunewald, @rovere, @fwyzard this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-09-06 21:59 UTC, wddgit commented
please test

2019-09-06 21:59 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-09-06 22:02 UTC, wddgit commented
Note in the code checks it reported a possible conflict with another PR I submitted. I checked and the same lines are not modified. At one spot the changes are only separated by 2 or 3 lines... I think they won't conflict, but I'm not really sure what the criteria git uses.

2019-09-07 05:52 UTC, cmsbuild commented
+1
Tested at: 8f556ad20c97e4bff71b8746001998ac96fe2991
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cc64d8/2417/summary.html

2019-09-07 05:52 UTC, cmsbuild commented
Comparison job queued.

2019-09-07 08:43 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cc64d8/2417/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2955796
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2955454
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 145 log files, 15 edm output root files, 34 DQM output files

2019-09-10 20:29 UTC, Dr15Jones reviewed
Partial

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Common/src/RefCoreStreamer.cc
> +      cl = TClass::GetClass("edm::RefCoreWithIndex");
Let's move the previous declarations of `cl` and `st` to be in their own block.

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Common/test/containermask_t.cppunit.cc
> +    std::vector<bool> alternate1(3, false);
Let's move the original `alternate` to be within its own block

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Common/test/ptr_t.cppunit.cc
> -    auto ptr = std::make_unique<SDCollection>();
Can the original `ptr` be put into its own block?

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Common/test/reftobaseprod_t.cppunit.cc
> -    auto ptr = std::make_unique<SDCollection>();
Can the original `ptr` be put into a block?

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Common/test/testOwnVector.cc
> +    edm::OwnVector<test::a> v1;
Can put the original `v` intos its own block?

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/FWLite/src/DataGetterHelper.cc
> +        edm::TypeWithDict type1(iInfo);
Name it `typeWithDict` to better express what it is.

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Provenance/src/ProductRegistry.cc
> +            auto iter1 = containedTypeToBaseTypesMap.find(containedTypeID);
More expressive name would be useful. Say `itFoundContainedTypeID`?

2019-09-10 20:29 UTC, Dr15Jones commented on DataFormats/Provenance/test/indexIntoFile3_t.cppunit.cc
> +    edm::IndexIntoFile::IndexIntoFileItr iterFirst1 = indexIntoFile.begin(IndexIntoFile::numericalOrder);
Move original `iterFirst` to its own block.

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Catalog/test/FileLocator_t.cpp
> +    std::string file_name1("/src/FWCore/Catalog/test/override_catalog.xml");
How about `override_file_name`?

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Catalog/test/FileLocator_t.cpp
> +    std::string full_file_name1 = boost::filesystem::exists((CMSSW_BASE + file_name1).c_str())
`override_full_name`?

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Concurrency/src/SerialTaskQueue.cc
> +        t = nullptr;
OK

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Concurrency/test/limitedtaskqueue_t.cppunit.cpp
> +                std::shared_ptr<tbb::task> guard1{pWaitTask, [](tbb::task* iTask) { iTask->decrement_ref_count(); }};
How about `guardAgain`? since it is actually guarding the same reference count.

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Concurrency/test/waitingtasklist_t.cppunit.cpp
> +    std::exception_ptr excPtr1;
Can the original be put into a block?

2019-09-10 20:29 UTC, Dr15Jones commented on FWCore/Framework/src/EventProcessor.cc
> +                      ServiceRegistry::Operate operate1(serviceToken_);
How about `beginLumiOperate`?

2019-09-10 20:31 UTC, Dr15Jones commented on FWCore/Services/test/test_catch2_SiteLocalConfigService.cc
> +    dir = getenv("CMSSW_BASE");
```suggestion
    auto  base_dir = getenv("CMSSW_BASE");
```

2019-09-10 20:32 UTC, Dr15Jones commented on IOPool/Input/src/RootEmbeddedFileSequence.cc
> -      bool found = rootFile()->readCurrentEvent(cache);
fine

2019-09-10 20:34 UTC, Dr15Jones commented on IOPool/Input/src/RootEmbeddedFileSequence.cc
> +      found = rootFile()->setEntryAtItem(id.run(), id.luminosityBlock(), 0);
OK

2019-09-10 20:37 UTC, Dr15Jones commented on IOPool/Input/src/RootEmbeddedFileSequence.cc
> +        found = rootFile()->setEntryAtNextEventInLumi(id.run(), id.luminosityBlock());
```suggestion
        bool foundEventInLumi = rootFile()->setEntryAtNextEventInLumi(id.run(), id.luminosityBlock());
```

2019-09-10 20:53 UTC, Dr15Jones requested changes

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/EventProcessor.cc
> +            ServiceRegistry::Operate operate1(serviceToken_);
```suggestion
            ServiceRegistry::Operate looperEventOperate(serviceToken_);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/EventProcessor.cc
> +                auto& lp1 = *(status->lumiPrincipal());
I think the original can be moved to after this statement since the original does not seem to be used until later.

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/OutputModuleCommunicatorT.cc
> +        auto sentry(make_sentry(activityRegistry, [&globalContext, &mcc](ActivityRegistry* activityRegistry1) {
How about just `ar`?

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/OutputModuleCommunicatorT.cc
> +        auto sentry(make_sentry(activityRegistry, [&globalContext, &mcc](ActivityRegistry* activityRegistry1) {
```suggestion
        auto sentry(make_sentry(activityRegistry, [&globalContext, &mcc](ActivityRegistry* ar) {
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/OutputModuleCommunicatorT.cc
> +          activityRegistry1->postModuleWriteLumiSignal_(globalContext, mcc);
```suggestion
          ar->postModuleWriteLumiSignal_(globalContext, mcc);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Principal.cc
> +        auto nameIter1 = std::find(lookupProcessNames.begin(), lookupProcessNames.end(), iter->processName());
How about `historyNameItr`?

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/ProductResolvers.cc
> +      auto failedStatusSetter = [this](ProductStatus* presentStatus1) {
How about just `status`?

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/ProductResolvers.cc
> +        ServiceRegistry::Operate guard1(token);
```suggestion
        ServiceRegistry::Operate workToDoGuard(token);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Schedule.cc
> +          for (auto const& item1 : preg.productList()) {
is `prod` taken?

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Schedule.cc
> +                for (auto const& item2 : bd.branchAliases()) {
`alias`?

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/SubProcess.cc
> +            ServiceRegistry::Operate operate1(serviceToken_);
```suggestion
            ServiceRegistry::Operate writeOneOperate(serviceToken_);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/SubProcess.cc
> +            ServiceRegistry::Operate operate1(serviceToken_);
```suggestion
            ServiceRegistry::Operate writeLumiOperate(serviceToken_);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Worker.h
> +              ServiceRegistry::Operate guard1(serviceToken);
```suggestion
              ServiceRegistry::Operate runModuleGuard(serviceToken);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Worker.h
> +              ServiceRegistry::Operate guard1(serviceToken);
```suggestion
              ServiceRegistry::Operate runAcquireGuard(serviceToken);
```

2019-09-10 20:53 UTC, Dr15Jones commented on FWCore/Framework/src/Worker.h
> +        auto taskToDo = make_functor_task(tbb::task::allocate_root(), toDo);
OK

2019-09-18 21:28 UTC, wddgit commented
Closing this one and will resubmit a fresh PR with revised fixes for these warnings.

2019-09-18 21:28 UTC, closed without merging