Make HLTDisplacedmumumuVtxProducer a stream producer
cms-sw/cmssw pull request #28175
Opened 2019-10-15 12:29 UTC by Martin-Grunewald

#### PR description:

Make HLTDisplacedmumumuVtxProducer a stream producer

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

2019-10-15 12:30 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-15 12:38 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12249

- This PR adds an extra 12KB to repository

2019-10-15 12:38 UTC, cmsbuild commented
A new Pull Request was created by  @Martin-Grunewald (Martin Grunewald) for master.

It involves the following packages:

HLTrigger/btau


@Martin-Grunewald, @cmsbuild, @fwyzard can you please review it and eventually sign? Thanks.
@emilbols, @smoortga, @acaudron, @HeinerTholen, @JyothsnaKomaragiri, @mverzett, @ferencek, @andrzejnovak, @pvmulder this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-10-15 12:43 UTC, Martin-Grunewald commented
please test

2019-10-15 12:43 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-15 14:25 UTC, cmsbuild commented
+1
Tested at: e25d7c5798c73ca7b034316936a64b8fa5fb83ba
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/2947/summary.html

2019-10-15 14:25 UTC, cmsbuild commented
Comparison job queued.

2019-10-15 16:22 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/2947/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961064
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960722
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-10-16 07:56 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-16 08:04 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12272

- This PR adds an extra 24KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)
- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12272/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12272/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2019-10-16 08:07 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-16 08:16 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12273

- This PR adds an extra 24KB to repository

2019-10-16 08:17 UTC, cmsbuild commented
Pull request #28175 was updated. @Martin-Grunewald, @cmsbuild, @fwyzard can you please check and sign again.

2019-10-16 08:23 UTC, Martin-Grunewald commented
please test

2019-10-16 08:24 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-16 10:24 UTC, cmsbuild commented
+1
Tested at: ede5ee17ce05f954ebb7a1ecc55cb958c684f64b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/2972/summary.html

2019-10-16 10:24 UTC, cmsbuild commented
Comparison job queued.

2019-10-16 12:38 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/2972/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961064
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960721
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-10-16 14:25 UTC, Dr15Jones requested changes

2019-10-16 14:28 UTC, Dr15Jones commented
Did I miss something? On a quick look at the code it appears this could be a global module instead.

2019-10-16 16:22 UTC, Martin-Grunewald commented on HLTrigger/btau/plugins/HLTDisplacedmumumuVtxProducer.h
> +  virtual void beginJob();
I guess I can just remove them, given they are empty in the cc files...

2019-10-16 16:22 UTC, Martin-Grunewald commented on HLTrigger/btau/plugins/HLTDisplacedmumumuVtxProducer.h
> +  virtual void endJob();
I guess I can just remove them, given they are empty in the cc files...

2019-10-17 06:28 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-17 06:35 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12296

- This PR adds an extra 24KB to repository

2019-10-17 06:35 UTC, cmsbuild commented
Pull request #28175 was updated. @Martin-Grunewald, @cmsbuild, @fwyzard can you please check and sign again.

2019-10-17 07:34 UTC, Martin-Grunewald commented
please test

2019-10-17 07:35 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-17 11:19 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/3003/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961064
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960722
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-10-18 14:42 UTC, Martin-Grunewald commented
+1

2019-10-18 14:42 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-10-18 20:13 UTC, fabiocos commented
@Martin-Grunewald any comment to https://github.com/cms-sw/cmssw/pull/28175#issuecomment-542729127 ?

2019-10-21 08:04 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-21 08:04 UTC, Martin-Grunewald commented
please test

2019-10-21 08:12 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28175/12349

- This PR adds an extra 24KB to repository

2019-10-21 08:13 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-21 08:13 UTC, cmsbuild commented
Pull request #28175 was updated. @Martin-Grunewald, @cmsbuild, @fwyzard can you please check and sign again.

2019-10-21 10:51 UTC, cmsbuild commented
+1
Tested at: 9fa17448e1952ef4267fd3de7942fd04a2322fd1
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/3045/summary.html

2019-10-21 10:51 UTC, cmsbuild commented
Comparison job queued.

2019-10-21 13:35 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-392143/3045/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961064
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960721
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-10-21 13:56 UTC, Martin-Grunewald commented
+1

2019-10-21 13:57 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-10-21 17:21 UTC, fabiocos commented
+1

@Martin-Grunewald thanks for addressing the comment of @Dr15Jones

2019-10-21 17:22 UTC, merged