Enable C++ modules for FWCore and FWCore
cms-sw/cmssw pull request #28219
Opened 2019-10-20 15:04 UTC by oshadura

#### PR description:
Enable C++ modules for FWCore and FWCore (small fixes in dependencies and header includes)
cc: @vgvassilev  @davidlange6 @smuzaffar

2019-10-20 15:04 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-20 15:14 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28219/12345

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DataFormats/CTPPSReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/EgammaTrackReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/L1TrackTrigger/BuildFile.xml  modified in PR(s): #28209

2019-10-20 15:14 UTC, cmsbuild commented
A new Pull Request was created by  @oshadura (Oksana Shadura) for master.

It involves the following packages:

DataFormats/CTPPSReco
DataFormats/Candidate
DataFormats/EgammaTrackReco
DataFormats/HLTReco
DataFormats/HeavyIonEvent
DataFormats/L1TrackTrigger
DataFormats/TauReco


@perrotta, @cmsbuild, @benkrikler, @fwyzard, @kpedro88, @Martin-Grunewald, @rekovic, @slava77, @santocch can you please review it and eventually sign? Thanks.
@yslai, @forthommel, @jan-kaspar, @sviret, @rovere, @gpetruc, @mandrenguyen, @yetkinyilmaz this is something you requested to watch as well.
@davidlange6, @slava77, @fabiocos you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2019-10-20 16:01 UTC, Dr15Jones requested changes

2019-10-20 16:01 UTC, Dr15Jones commented on DataFormats/HLTReco/interface/TriggerEvent.h
> +#include <assert.h>
```suggestion
#include <cassert>
```

2019-10-20 16:01 UTC, Dr15Jones commented on DataFormats/HLTReco/interface/HLTPerformanceInfo.h
> +#include <assert.h>
```suggestion
#include <cassert>
```

2019-10-20 16:01 UTC, Dr15Jones commented
The pull request title doesn't seem to match what was changed.

2019-10-21 09:15 UTC, oshadura commented on DataFormats/HLTReco/interface/TriggerEvent.h
> +#include <assert.h>
Thank you! it is fixed!

2019-10-21 09:15 UTC, oshadura commented on DataFormats/HLTReco/interface/HLTPerformanceInfo.h
> +#include <assert.h>
Thank you! it is fixed!

2019-10-21 09:17 UTC, oshadura commented
> The pull request title doesn't seem to match what was changed.
You are right, I changed it (this PR is part of https://github.com/cms-sw/cmsdist/pull/5284)

2019-10-21 09:21 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28219/12352

- This PR adds an extra 24KB to repository

- Found files with invalid states:
  - MagneticField/GeomBuilder/test/python/testMagneticFieldDB_parameterized_cfg.py:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/testMagneticFieldDB_cfg.results:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/testMagneticFieldDB_valueOverride_cfg.results:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/python/testMagneticFieldDB_cfg.py:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/testMagneticFieldDB_parameterized_cfg.results:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/python/testMagneticFieldDB_valueOverride_cfg.py:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9
  - MagneticField/GeomBuilder/test/testMagneticFieldDB.sh:
    - Added: 12e01e3a1e3d9328bd3575156ac9118c8be200e2
    - Deleted: 273811c5a8bfc1122cd2a7d03bad8d86e474c9d9


- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DataFormats/CTPPSReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/EgammaTrackReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/L1TrackTrigger/BuildFile.xml  modified in PR(s): #28209

2019-10-21 09:25 UTC, perrotta commented
-1
(wrong rebase...)

2019-10-21 09:36 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-21 09:43 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28219/12353

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DataFormats/CTPPSReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/EgammaTrackReco/BuildFile.xml  modified in PR(s): #28209
  - File  DataFormats/L1TrackTrigger/BuildFile.xml  modified in PR(s): #28209

2019-10-21 09:44 UTC, perrotta commented
please test

2019-10-21 09:44 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-21 12:00 UTC, davidlange6 commented
@oshadura and i agreed to use #28209 and #28222 instead of this PR.

2019-10-21 12:00 UTC, closed without merging

2019-10-21 13:54 UTC, cmsbuild commented
+1
Tested at: 13cc6f7612ac6cc751e2018bd2dc59bb83f1a37b
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-295398/3046/summary.html

2019-10-21 13:55 UTC, cmsbuild commented
Comparison job queued.

2019-10-21 16:01 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-295398/3046/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961064
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960722
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files