Run3-sim47 Remove reference to trackermaterial in materials.xml
cms-sw/cmssw pull request #28313
Opened 2019-10-30 16:14 UTC by bsunanda

#### PR description:

Several cfi files use only materials.xml and not trackermaterial.xml. A couple of materials refer to trackermaterial.xml for elements which are identically defined in materials.xml. Removing the references will allow the cfi's which only used materials.xml to work without any warnings.

#### PR validation:

Tested with runTheMatrix.py for standard workflows

#### if this PR is a backport please specify the original PR:

Nothing special

2019-10-30 16:15 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-10-30 16:50 UTC, ianna commented
-1

@bsunanda - we cannot change legacy scenarios. In addition, the materials used in Tracker should be moved out of **materials.xml** so that they can still use and modify **T_Copper** and **T_Aluminum** for zero material studies. Please see the issue https://github.com/cms-sw/cmssw/issues/28285

2019-10-30 16:50 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-10-30 16:59 UTC, ianna commented
> @ianna I am happy as long as materials.xml does not refer to trackermaterial

One should move these materials from **materials.xml** to **trackermaterial.xml** and update all Tracker xml files that use them. Then update the payloads.

Alternatively, you can use the new **materials.xml** version since it's not used in the payloads and can be modified:
```
Geometry/CMSCommonData/data/materials/2021/v1/materials.xml
```

2019-10-30 19:02 UTC, cmsbuild commented
+1
Tested at: 4fdd5db0f363307f07df26dfd60c7cbb014ca10c
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/3269/summary.html

2019-10-30 19:02 UTC, cmsbuild commented
Comparison job queued.

2019-10-30 19:42 UTC, bsunanda commented
@ianna I shall modify the xml files to do that but can someone update the payloads. But I don't see why payloads to be created. Moving the definition from one file to another will not change the physical quantities

2019-10-30 21:21 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/3269/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2961036
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2960694
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-11-01 18:16 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-11-01 18:22 UTC, bsunanda commented
@ianna I updated all trackermaterial.xml and materials.xml files.

2019-11-01 18:22 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/12595

- This PR adds an extra 60KB to repository

2019-11-01 18:22 UTC, bsunanda commented
@cmsbuild Please test

2019-11-01 18:22 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-11-01 18:22 UTC, cmsbuild commented
Pull request #28313 was updated. @civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2019-11-01 19:47 UTC, cmsbuild commented
+1
Tested at: 1ce28fd0cc4ce88242265ff245b8208167a1ebaf
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/3309/summary.html

2019-11-01 19:47 UTC, cmsbuild commented
Comparison job queued.

2019-11-01 21:23 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/3309/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2939026
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2938684
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-11-04 22:54 UTC, kpedro88 commented
+upgrade

2019-11-05 06:51 UTC, ianna commented
-1

Material variation scenarios have to use T_* materials.

2019-11-05 16:12 UTC, ianna requested changes
@bsunanda, please, check the comments and cleanup the xml files and their scenarios. Most of the material variation definitions were produced automatically. Modifying them by hand is not as easy as it may seem. 

As this PR goes against CMS policy **not to change existing xml files** it should be discussed at Sim meeting when @cvuosalo is back. Also, who will take responsibility to create and validate the new payloads should be discussed and agreed. The change in **materials.xml** file touches all of them. The GTs will have to be updated in order to insure that the next significant change in Geometry is unrelated to the materials restructuring.

2019-11-05 16:12 UTC, ianna requested changes
@bsunanda, please, check the comments and cleanup the xml files and their scenarios. Most of the material variation definitions were produced automatically. Modifying them by hand is not as easy as it may seem. 

As this PR goes against CMS policy **not to change existing xml files** it should be discussed at Sim meeting when @cvuosalo is back. Also, who will take responsibility to create and validate the new payloads should be discussed and agreed. The change in **materials.xml** file touches all of them. The GTs will have to be updated in order to insure that the next significant change in Geometry is unrelated to the materials restructuring.

2020-01-08 14:57 UTC, silviodonato commented
@bsunanda Do you have news about this PR?

2020-01-08 16:03 UTC, bsunanda commented
@silviodonato I shall take comments from Yana, implement them and revive this PR.

2020-01-08 19:05 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-01-08 19:09 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/13313

- This PR adds an extra 28KB to repository

2020-01-08 19:10 UTC, cmsbuild commented
Pull request #28313 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2020-01-08 19:18 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-01-08 19:23 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/13314

- This PR adds an extra 212KB to repository

2020-01-08 19:24 UTC, cmsbuild commented
Pull request #28313 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2020-01-08 19:40 UTC, bsunanda commented
@cmsbuild Please test

2020-01-08 19:41 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-01-08 19:47 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-01-08 19:52 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/13315

- This PR adds an extra 212KB to repository

2020-01-08 19:53 UTC, cmsbuild commented
Pull request #28313 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2020-01-08 20:18 UTC, bsunanda commented
@cmsbuild Please test

2020-01-08 20:18 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-01-08 21:27 UTC, cmsbuild commented
+1
Tested at: cc9dda98c3301b06f763872148e4f8e3af44740e
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/4174/summary.html
CMSSW: CMSSW_11_1_X_2020-01-08-1100
SCRAM_ARCH: slc7_amd64_gcc820

2020-01-08 21:27 UTC, cmsbuild commented
Comparison job queued.

2020-01-08 22:56 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/4174/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2815513
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2815166
 - DQMHistoTests: Total skipped: 346
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2020-01-09 16:31 UTC, cvuosalo commented
hold

2020-01-09 16:32 UTC, cmsbuild commented
Pull request has been put on hold by  @cvuosalo
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2020-01-09 16:34 UTC, cvuosalo commented
@bsunanda: This PR needs to be discussed at the next Sim meeting, so it should stay on hold until then. Please make a presentation at the next Sim meeting explaining how the payloads and GTs will be updated and by whom, as Yana requested.

2020-01-28 14:58 UTC, silviodonato commented
@bsunanda @cvuosalo could you write a comment about the outcome about this PR of the Sim meeting? thanks

2020-01-28 16:50 UTC, cvuosalo commented
I will try to do a test to assess the impact of this PR on the payloads.

2020-01-31 22:18 UTC, cvuosalo commented on Geometry/TrackerCommonData/data/2016/FlatMinus05Percent/trackermaterial.xml
> +    <CompositeMaterial name="micro_twisted_power_cable" density="0.95*3.639*g/cm3" symbol=" " method="mixture by weight">
@bsunanda, @ianna There are two "micro_twisted_power_cable" composite materials defined here. Aren't duplicate names an error? What effect does this duplication have? Does anyone in CMS know?

2020-02-06 20:48 UTC, cvuosalo commented
@bsunanda, @ianna, @civanch I keep running into show-stoppers in attempting to validate this PR. We may need to have a meeting to develop a clear, workable protocol for validation.

2020-02-18 14:36 UTC, silviodonato commented
Do you have any news on this PR?

2020-02-18 15:16 UTC, bsunanda commented
@cmsbuild Please test

2020-02-18 15:16 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-02-18 15:21 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/13821

- This PR adds an extra 128KB to repository

2020-02-18 15:22 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-02-18 15:22 UTC, cmsbuild commented
Pull request #28313 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @kpedro88 can you please check and sign again.

2020-02-18 15:25 UTC, bsunanda commented
@silviodonato @cvuosalo @ianna @civanch I tried to resolve duplicate names which came from original files

2020-02-18 16:36 UTC, cmsbuild commented
+1
Tested at: 18f063cdccba88df1d1f9368dddff25a7c849f50
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/4737/summary.html
CMSSW: CMSSW_11_1_X_2020-02-18-1100
SCRAM_ARCH: slc7_amd64_gcc820

2020-02-18 16:36 UTC, cmsbuild commented
Comparison job queued.

2020-02-18 18:11 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/4737/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2694086
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2693765
 - DQMHistoTests: Total skipped: 319
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2020-02-25 09:49 UTC, silviodonato commented
Do you have any comments about this PR? @Dr15Jones @civanch  @cvuosalo @ianna @makortel @mdhildreth

2020-02-25 11:57 UTC, bsunanda commented
As far as I see, this is okay.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------
From: Silvio Donato <notifications@github.com>
Date: 2/25/20 3:49 AM (GMT-06:00)
To: cms-sw/cmssw <cmssw@noreply.github.com>
Cc: Sunanda Banerjee <Sunanda.Banerjee@cern.ch>, Mention <mention@noreply.github.com>
Subject: Re: [cms-sw/cmssw] Run3-sim47 Remove reference to trackermaterial in materials.xml (#28313)


Do you have any comments about this PR? @Dr15Jones<https://github.com/Dr15Jones> @civanch<https://github.com/civanch> @cvuosalo<https://github.com/cvuosalo> @ianna<https://github.com/ianna> @makortel<https://github.com/makortel> @mdhildreth<https://github.com/mdhildreth>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/28313?email_source=notifications&email_token=ABGMZOXMFL6ZV76NI7QZHALRETSR3A5CNFSM4JG4GDCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM3JFFA#issuecomment-590779028>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABGMZOXLUEC3L5SFKIUYSMLRETSR3ANCNFSM4JG4GDCA>.

2020-02-25 15:09 UTC, cvuosalo commented
Validation of these XML changes continues to be very difficult. There does not seem to be a workable process yet to check the XML, payloads, and database. Discussions are ongoing.

2020-02-26 22:49 UTC, cvuosalo commented
@bsunanda One conclusion of discussions with Yana is that XML files for Run 2 and earlier should not be changed. The validation process for changing any XML is already quite onerous, but to do so for all the old scenarios verges on being unfeasible. Also, it is not clear that processing old scenarios with DD4hep will ever be even necessary.

Please remove files for old scenarios from this PR. Only the XML used for 2021 and later and Run 3 and later should be included in this PR. Thanks.

2020-02-26 23:07 UTC, cvuosalo commented
The timeline for this PR will have to be significantly extended. We have discovered significant discrepancies between geometry XML and the DB payloads in the current master. Before any geometry XML files can be changed, new payloads and global tags will need to be generated from the current master and validated to establish a reliable baseline. This process may be quite lengthy. Only after we have established the baseline can new payloads and global tags from this PR be tested to see whether they cause any differences.

2020-03-25 20:31 UTC, cvuosalo commented
unhold

2020-03-25 20:32 UTC, cvuosalo commented
This PR can probably go ahead. Comparison with the Conditions DB shows that there is no real change in simulation geometry.

2020-03-25 20:52 UTC, cvuosalo commented
I am not sure how meaningful it is to change the files for Run 2 and earlier scenarios. New payloads for these scenarios are very unlikely to be created with CMSSW 11_1 or later versions. My impression is the the Ultra-Legacy is the final word for Run 2.

2020-03-26 12:49 UTC, silviodonato commented
please test
refresh

2020-03-26 12:50 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-03-26 12:50 UTC, silviodonato commented
code-checks

2020-03-26 12:50 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-03-26 12:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28313/14386

- This PR adds an extra 8KB to repository

2020-03-26 14:30 UTC, cmsbuild commented
+1
Tested at: 18f063cdccba88df1d1f9368dddff25a7c849f50
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/5396/summary.html
CMSSW: CMSSW_11_1_X_2020-03-26-1100
SCRAM_ARCH: slc7_amd64_gcc820

2020-03-26 14:30 UTC, cmsbuild commented
Comparison job queued.

2020-03-26 16:00 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64d438/5396/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 7 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2692110
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2691788
 - DQMHistoTests: Total skipped: 319
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2020-03-29 21:42 UTC, bsunanda commented
@cvuosalo @kpedro88 Can you sign this now?

2020-03-30 02:30 UTC, cvuosalo commented
I have tested more carefully. The Run 1 payloads from this PR don't seem to match what is in Conditions DB. Do we really want to change Runs 1-2 right now? I am unsure how we want to approach DD4hep migration for Runs 1-2 at this time.

2020-03-30 07:25 UTC, fabiocos commented
@cvuosalo could you please elaborate on the differences observed in your test?

2020-03-30 15:50 UTC, kpedro88 commented
+upgrade

2020-03-31 18:50 UTC, cvuosalo commented
hold

2020-03-31 18:50 UTC, cmsbuild commented
Pull request has been put on hold by  @cvuosalo
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2020-03-31 18:53 UTC, cvuosalo commented
The conclusion that is emerging is that we don't want to change Runs 1-2 XML files. Ultimately, they may be deleted. I was hoping to discuss this issue at the planned April 3rd Sim meeting, but that meeting has been postponed until April 10th.
In the interim, I suggest closing this PR. A new PR with files only for 2021 and later could then be submitted so we could go ahead with those changes. After the April 10th meeting, we may have a final decision on what to do with Runs 1-2 geometry XML files.

2020-04-03 00:06 UTC, cvuosalo commented
@fabiocos There are several differences between Run 1 XML and the geometry in the DB. I suppose these differences can be explained by inadvertent changes being made to the Run 1 XML over the years while the DB geometry has not been touched.

There are differences in the concatenated geometry XML file from CMSSW 11_1 and the one in the DB. For example:
```
25987c25945
< <Box dx="138.500000000000000000*mm" dy="15.349999999999999645*mm" dz="4.650000000000000355*mm" name="esalgo:SFAbs1PbLOutAltmp"/>
---
> <Box dx="1384.099999999999909051*mm" dy="15.349999999999999645*mm" dz="4.650000000000000355*mm" name="esalgo:SFAbs1PbLOutAltmp"/>
26094c26052
< <Box dx="169.800000000000011369*mm" dy="20.350000000000001421*mm" dz="1.850000000000000089*mm" name="esalgo:SFAbs2PbLOutAltmp"/>
---
> <Box dx="1697.099999999999909051*mm" dy="20.350000000000001421*mm" dz="1.850000000000000089*mm" name="esalgo:SFAbs2PbLOutAltmp"/>
26254c26212
< <Box dx="20.149999999999955946*mm" dy="158.550000000000011369*mm" dz="1.850000000000000089*mm" name="esalgo:SFAbs2PbLOutAltmp2"/>
---
> <Box dx="20.149999999999955946*mm" dy="1584.599999999999909051*mm" dz="1.850000000000000089*mm" name="esalgo:SFAbs2PbLOutAltmp2"/>
26309c26267
< <Box dx="24.150000000000069633*mm" dy="173.400000000000005684*mm" dz="4.650000000000000355*mm" name="esalgo:SFAbs1PbLOutAltmp2"/>
---
> <Box dx="24.150000000000069633*mm" dy="1733.099999999999909051*mm" dz="4.650000000000000355*mm" name="esalgo:SFAbs1PbLOutAltmp2"/>
```
If you look carefully, you can see some of these lengths changed by a factor of 10.

The Simulation geometry also has differences.

I think all these Run 1 differences are moot because I don't think we have any plan to create new Run 1 DB payloads.

2020-04-03 14:52 UTC, fabiocos commented
@cvuosalo I see, so this has nothing to do with the material reorganization. In any case a factor of 10 in preshower volumes does not sound healthy, but it depends on the real use of these volumes. And I do not see them in Run2/Run3 xml geometry.

In any case, if we update xmls we have unrelated changes already, and if we want to keep the capability to produce Run1 geometries when DDD has gone I think we need to make the update, right? Although I am not sure this update is specifically needed by DD4hep (@bsunanda could you please confirm?)

2020-04-03 22:43 UTC, civanch commented
Hi all,

because we do not want change DB geometry for Run-1,2 can we sign this PR, which for today will change XML geometry for Run-3 and Phase-2 any. Any result for Run-1,2 will not be changed.

We agreed to restore functionality of XML for Run1,2, when Run3 will be completed and DD4Hep migration will be done. The condition: XML for Run1,2 should be identical to DB Run1,2. Only after that we can drop old DD.

@ianna , @cvuosalo , would you agree?

2020-04-04 00:01 UTC, cvuosalo commented
@civanch What I understand you saying is that, since we are not planning to make new DB payloads for Runs 1-2 in the near future, we are then free to change the Runs 1-2 XML files. The problem of the Runs 1-2 XML files will be pushed back until after the DD4hep migration is completed.

But the plan you mentioned concerns me. The stated condition "XML for Runs 1-2 should be identical to the DB payloads for Runs 1-2" is true for the legacy releases of CMSSW (5_3 and 10_6) but will pose significant problems for new versions of CMSSW. We will need to discuss it at the next Sim meeting.

2020-04-06 21:08 UTC, cvuosalo commented
unhold

2020-04-06 21:14 UTC, cvuosalo commented
+1

2020-04-06 21:14 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo (and backports should be raised in the release meeting by the corresponding L2)

2020-04-07 07:31 UTC, silviodonato commented
hold

> We will need to discuss it at the next Sim meeting.

2020-04-07 07:31 UTC, cmsbuild commented
Pull request has been put on hold by  @silviodonato
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2020-04-07 07:38 UTC, silviodonato commented
If I understand correctly, 
- the current XML geometry does not match the DB geometry
- this PR does not change the XML geometry
- hence, even after this PR, we will continue to have a XML geometry that does not match the DB geometry

If this is correct, I think we can safety merge this PR.
The mismatch between XML geometry and DB geometry is a different issue and will be fixed with another PR.

2020-04-07 07:48 UTC, ianna commented
@silviodonato - you are correct.

I'd suggest to merge this PR and upload the new DB payloads for all Runs (and update the Run3 GTs). The GT change will result in a baseline comparison differences. However, we know that it would be superficial at this point. Then we'd need to update the baseline. This would make sure we'd catch any further geometry changes resulting in a baseline comparison differences.

2020-04-07 08:00 UTC, civanch commented
I agree with Ianna. Probably, optimal would be to complete fixing of Run-3 geometry and after make GTs for Run-3? We may agree, at what pre-release we stop updating Run-3 geometry. In a mean time this PR may be merged.

2020-04-07 13:08 UTC, silviodonato commented
unhold
ok, I will integrate this PR in the next IB

2020-04-07 13:08 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo (and backports should be raised in the release meeting by the corresponding L2)

2020-04-07 13:08 UTC, silviodonato commented
+1

2020-04-07 13:08 UTC, merged