Run3-TB46 Fix the test beam runs in view of present changes
cms-sw/cmssw pull request #28395
Opened 2019-11-13 17:41 UTC by bsunanda

#### PR description:

Fix 2006 test beam configuration in view of recent changes in accessing the geometry parameters

#### PR validation:

Tested with many cfg files in the area SimG4CMS/HcalTestBeam/test/python. The changes are supposed not to affect standard workflows

#### if this PR is a backport please specify the original PR:

Nothing special

2019-11-13 17:42 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-11-13 17:47 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28395/12742

- This PR adds an extra 36KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)
- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28395/12742/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28395/12742/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2019-11-13 17:59 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-11-13 18:07 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28395/12743

- This PR adds an extra 36KB to repository

2019-11-13 18:36 UTC, bsunanda commented
@cmsbuild Please test

2019-11-13 18:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-11-13 18:50 UTC, civanch commented
@bsunanda , thanks, it is running fine to me.

2019-11-13 19:50 UTC, cmsbuild commented
+1
Tested at: abc96640001fe7c2c1922cf0799d4afb80750758
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-45c42b/3468/summary.html

2019-11-13 19:51 UTC, cmsbuild commented
Comparison job queued.

2019-11-13 21:39 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-45c42b/3468/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2936360
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2936017
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-11-14 08:56 UTC, ianna requested changes

2019-11-14 08:56 UTC, ianna commented on SimG4CMS/Calo/src/HCalSD.cc
> +      hfLV.push_back(lv);
```
emplace_back
```

2019-11-14 08:56 UTC, ianna commented on SimG4CMS/Calo/src/HCalSD.cc
> +      hfLevels.push_back(temp[i]);
```
emplace_back
```

2019-11-14 12:21 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2019-11-14 12:22 UTC, bsunanda commented
@cmsbuild Please test

2019-11-14 12:27 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28395/12755

- This PR adds an extra 40KB to repository

2019-11-14 12:28 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2019-11-14 12:28 UTC, cmsbuild commented
Pull request #28395 was updated. @civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild can you please check and sign again.

2019-11-14 16:55 UTC, cmsbuild commented
+1
Tested at: 9623a80a6575814b184959b5c564baae3d7b0a94
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-45c42b/3482/summary.html

2019-11-14 16:55 UTC, cmsbuild commented
Comparison job queued.

2019-11-14 20:00 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-45c42b/3482/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 34
 - DQMHistoTests: Total histograms compared: 2936360
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2936017
 - DQMHistoTests: Total skipped: 341
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
 - Checked 147 log files, 16 edm output root files, 34 DQM output files

2019-11-15 11:17 UTC, ianna commented
+1

2019-11-15 11:41 UTC, civanch commented
+1

2019-11-15 11:42 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6, @slava77, @smuzaffar, @fabiocos (and backports should be raised in the release meeting by the corresponding L2)

2019-11-17 19:34 UTC, fabiocos commented
+1

@bsunanda I understand that the test beam code behaviour has been tested in standalone studies

2019-11-17 19:34 UTC, merged