Reduce boost regex dependencies
cms-sw/cmssw pull request #30333
Opened 2020-06-22 19:22 UTC by camolezi

#### PR description:
Replaced boost regex for c++11 stl regex, they should have similar behavior and performance.

#### PR validation:
Passed on basic runTheMatrix test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@vgvassilev @davidlange6

2020-06-22 19:22 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-06-22 19:31 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30333/16335

- This PR adds an extra 104KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQMOffline/Trigger/plugins/HLTMuonRefMethod.cc  modified in PR(s): #29935
  - File  DQMServices/StreamerIO/plugins/DQMFileIterator.cc  modified in PR(s): #29933
  - File  DQMServices/StreamerIO/plugins/RamdiskMonitor.cc  modified in PR(s): #29927, #29933, #30326
  - File  EventFilter/L1TRawToDigi/src/MP7FileReader.cc  modified in PR(s): #29936
  - File  EventFilter/L1TRawToDigi/src/MP7PacketReader.cc  modified in PR(s): #29936, #29937
  - File  Fireworks/Core/src/FWFileEntry.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWHLTTriggerTableView.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWHLTValidator.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWL1TriggerTableView.cc  modified in PR(s): #29935, #29936, #29937
  - File  HLTrigger/Timer/plugins/FastTimerServiceClient.cc  modified in PR(s): #29933
  - File  PhysicsTools/FWLite/src/TH1Store.cc  modified in PR(s): #29936
  - File  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc  modified in PR(s): #29937
  - File  RecoTracker/FinalTrackSelectors/plugins/TrackerTrackHitFilter.cc  modified in PR(s): #29935, #29937


Code check has found code style and quality issues which could be resolved by applying following patch(s)
- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30333/16335/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30333/16335/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2020-06-22 19:44 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-06-22 19:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30333/16336

- This PR adds an extra 104KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQMOffline/Trigger/plugins/HLTMuonRefMethod.cc  modified in PR(s): #29935
  - File  DQMServices/StreamerIO/plugins/DQMFileIterator.cc  modified in PR(s): #29933
  - File  DQMServices/StreamerIO/plugins/RamdiskMonitor.cc  modified in PR(s): #29927, #29933, #30326
  - File  EventFilter/L1TRawToDigi/src/MP7FileReader.cc  modified in PR(s): #29936
  - File  EventFilter/L1TRawToDigi/src/MP7PacketReader.cc  modified in PR(s): #29936, #29937
  - File  Fireworks/Core/src/FWFileEntry.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWHLTTriggerTableView.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWHLTValidator.cc  modified in PR(s): #29935, #29936, #29937
  - File  Fireworks/Core/src/FWL1TriggerTableView.cc  modified in PR(s): #29935, #29936, #29937
  - File  HLTrigger/Timer/plugins/FastTimerServiceClient.cc  modified in PR(s): #29933
  - File  PhysicsTools/FWLite/src/TH1Store.cc  modified in PR(s): #29936
  - File  RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc  modified in PR(s): #29937
  - File  RecoTracker/FinalTrackSelectors/plugins/TrackerTrackHitFilter.cc  modified in PR(s): #29935, #29937

2020-06-22 19:51 UTC, cmsbuild commented
A new Pull Request was created by  @camolezi (Lucas Camolezi) for master.

It involves the following packages:

CommonTools/Utils
CondCore/CondDB
DQMOffline/Trigger
DQMServices/StreamerIO
DataFormats/PatCandidates
EventFilter/L1TRawToDigi
FWCore/Framework
Fireworks/Core
HLTrigger/Timer
PhysicsTools/FWLite
RecoLocalTracker/SiPixelRecHits
RecoTracker/FinalTrackSelectors


@perrotta, @smuzaffar, @benkrikler, @Dr15Jones, @alja, @makortel, @fwyzard, @schneiml, @andrius-k, @cmsbuild, @rekovic, @jfernan2, @kmaeshima, @fioriNTU, @Martin-Grunewald, @slava77, @ggovi, @santocch can you please review it and eventually sign? Thanks.
@gouskos, @felicepantaleo, @Martin-Grunewald, @wddgit, @thomreis, @threus, @mmusich, @cericeci, @calderona, @makortel, @JanFSchulte, @jhgoh, @peruzzim, @missirol, @HuguesBrun, @trocino, @rociovilar, @barvic, @GiacomoSguazzoni, @rovere, @VinInn, @hatakeyamak, @mschrode, @ebrondol, @mtosi, @dgulhan, @Fedespring, @alja, @dkotlins, @cbernet, @gpetruc, @folguera this is something you requested to watch as well.
@silviodonato, @dpiparo you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2020-06-22 20:23 UTC, alja commented
+1

2020-06-22 20:23 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-06-22 20:44 UTC, makortel commented on FWCore/Framework/doc/EventSelector.cc-with-cerr-traces
> +#include <regex>
This file is obsolete. I suggest we let this change go in and then I remove the file (among others). Unless this PR needs to be modified for other reasons, in which case I'd ask to leave this file untouched (but only in that case).

2020-06-22 20:44 UTC, makortel commented
+core

2020-06-22 21:15 UTC, cmsbuild commented
-1

Tested at: c9f59b4c81265cf14f6eeb94c9a83bcbffa88dc9

CMSSW: CMSSW_11_2_X_2020-06-22-1100
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-53c91e/7259/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  HeaderConsistency**

* **Build**:

I found compilation error when building: 

<pre>>> Package CondTools/SiPixel built
>> Entering Package CondCore/AlignmentPlugins
Entering library rule at src/CondCore/AlignmentPlugins/plugins
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-1100/src/CondCore/AlignmentPlugins/plugins/TrackerSurfaceDeformations_PayloadInspector.cc
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-1100/src/CondCore/AlignmentPlugins/plugins/TrackerSurfaceDeformations_PayloadInspector.cc:12:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-1100/src/CondCore/Utilities/interface/PayloadInspector.h:253:12: error: 'set' in namespace 'std' does not name a template type
       std::set<std::string> m_inputParams;
            ^~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-1100/src/CondCore/Utilities/interface/PayloadInspector.h:253:7: note: 'std::set' is defined in header '<set>'; did you forget to '#include <set>'?
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-1100/src/CondCore/Utilities/interface/PayloadInspector.h:14:1:
+#include <set>
</pre>

2020-06-22 21:15 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-06-23 08:08 UTC, fwyzard requested changes

2020-06-23 08:08 UTC, fwyzard commented on HLTrigger/Timer/plugins/FastTimerServiceClient.cc
> +#include <regex>
Could you move this header to the "C++ headers" section, and remove the now empty "boost headers" section ?

2020-06-23 08:08 UTC, fwyzard commented on HLTrigger/Timer/plugins/ThroughputServiceClient.cc
> +#include <regex>
Could you move this header to the "C++ headers" section, and remove the now empty "boost headers" section ?

2020-06-23 08:08 UTC, fwyzard commented on PhysicsTools/FWLite/src/TH1Store.cc
```suggestion
```

2020-06-23 08:08 UTC, fwyzard commented on CommonTools/Utils/src/TFileDirectory.cc
> +#include <regex>
Could you move this header with the other standard headers above ?

2020-06-23 08:08 UTC, fwyzard commented on CondCore/CondDB/interface/Utils.h
>  //
```suggestion
```

2020-06-23 08:08 UTC, fwyzard commented on EventFilter/L1TRawToDigi/interface/MP7FileReader.h
> +#include <regex>
Could you move this header with the other standard headers above ?

2020-06-23 08:08 UTC, fwyzard commented on EventFilter/L1TRawToDigi/src/MP7FileReader.cc
> +#include <regex>
Could you move this header with the other standard headers below ?

2020-06-25 13:40 UTC, camolezi commented
I don't think we should go on with this replacement anymore, unless performance is not a concern.

I've made some benchmarks on std::regex vs boost::regex.
They show that std::regex is at least 10x slower than boost::regex.

https://gist.github.com/camolezi/87283aaf7cdeb584ba294588a5d77abd
https://gist.github.com/camolezi/ae83ce140a5ade6e9c4aee158f9f95e2

2020-06-25 13:45 UTC, makortel commented
@camolezi Interesting (and quick internet searches support that). I'd be curious if adding `-O2` would make any difference?

2020-06-25 14:11 UTC, camolezi commented
> @camolezi Interesting (and quick internet searches support that). I'd be curious if adding `-O2` would make any difference?

wow, It made a big difference. The performance difference is much more reasonable with -O2 flag.
In the regex_match benchmark, with -O2 flag.

                                    cpu-time      iterations
boost_regex                2805 ns       250338
std_regex                    2214 ns       312415

2020-06-25 17:13 UTC, camolezi commented
> > @camolezi Interesting (and quick internet searches support that). I'd be curious if adding `-O2` would make any difference?
> 
> wow, It made a big difference. The performance difference is much more reasonable with -O2 flag.
> In the regex_match benchmark, with -O2 flag.
> 
> boost_regex: 2805ns - iterations: 250338
> std_regex: 2214ns - iterations: 312415
> 
> edit: it seems that std_regex is faster with -O2 flag. I benchmarked again a couple of times and this result seems right.

Okay, my regex_match benchmarks do show that std_regex is comparable to boost regex.
But even with optimizations, in my other benchmark (regex_seach), still suggest a huge difference in performance.

Based on this:
https://www.boost.org/doc/libs/1_73_0/libs/regex/doc/html/boost_regex/background/performance.html

It seems like in some specific cases std::regex does have a comparable performance to boost::regex. But in general, it seems like std::regex is significantly slower.

2020-06-25 19:13 UTC, fwyzard commented
Interesting - thanks a lot for the investigation.

I am, of course, in favour of staying with the better-performing option :-)

2020-06-25 19:14 UTC, closed without merging