Port COCOA to rely on DD4hep
cms-sw/cmssw pull request #30507
Opened 2020-07-02 15:51 UTC by ghugo83

Moved COCOA DD dependencies to DD4hep.
As discussed in https://github.com/cms-sw/cmssw/pull/25356. 

**General description of COCOA:**
https://cds.cern.ch/record/1047121/files/p193.pdf
COCOA is now basically standalone alignment software. 
It is designed to simulate and reconstruct optical alignment systems for CMS. It was also used (in the past I presume) to analyze the CMS optical alignment data, and pass the alignment correction to the CMS reconstruction.

**PR description**:
Following was done for port to DD4hep (this can also be seen as a HOWTO):
- DetectorDescription/Core -> DetectorDescription/DDCMS dependencies.
- Switch to DD4hep-based versions of DDCompactView and DDFilteredView.
- Switch to DD4hep-based geometry building of a cms::DDDetector optical alignment system, with DDDetectorESProducer.
- Remove use of old DDExpandedNode and navigation.
- DDLogicalPart -> dd4hep::PlacedVolume and her friends.
- DDTranslation -> dd4hep::Direction (ROOT::Math::XYZVector)
- DDRotationMatrix -> dd4hep::Rotation3D (ROOT::Math::Rotation3D)
- Remove use of DDsvalues_type and DDValue -> Instead, use of cms::DDSpecParRegistry,  cms::DDSpecParRefs, and cms::DDSpecPar::value<T>.

**PR validation:**
Had to 'reconstruct' input files to be able to run COCOA.
Notably created an input XML file + an OpticalAlignmentsRcd stored in local .db.
Created small guide: Alignment/CocoaApplication/README.md, so that one can now easily run COCOA and reproduce results.
No regression due to port to DD4hep: 
- Fully checked ideal geometry building, perfectly matching geometry from XML.
- Checked parameters and measurements from XMLs. 

**Issues in COCOA:**
While checking for regressions, I spotted & fixed the following issues in COCOA (independent from port to DD4hep). Visible in the code before PR:
- https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X/Alignment/CocoaApplication/src/CocoaAnalyzer.cc#L214
colX, colY and colZ are obviously not columns, but rows. 
This results in rotation matrix rotclhep to be ill-formed (transpose, hence inverse, of what it should be). Hence, the local rotations in ideal geometry were inverse of what they should be, and could not be properly checked against those of the geometry from DB.
- https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X/Alignment/CocoaFit/src/CocoaDBMgr.cc#L191
This is used to write results to DB. Error in the conversion (!!!), should go from m (in COCOA) to cm (in DB). Hence data stored in DB was wrong.
- https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X/Alignment/CocoaApplication/src/CocoaAnalyzer.cc#L343 
std::string type is initialized with value from previous iteration. Hence, within the loop, there is a telescopage of its values. This leads to dimFactor being not properly calculated, hence all 'extra alignment parameters' values were wrong.

**Disclaimer:**
The COCOA packages were very bad style, I re-wrote and commented only part of it, in the context of the port to DD4hep. Notably, src/CocoaAnalyzer.cc was removed then restored, hence I am partially attributed parts of old code there which is not mine.
I fully debugged COCOA behavior in the fields of ideal geometry building + measurements corrections + results write to DB. Though, there are other important aspects which I did not debug (notably the least-square parameters fitting).

2020-07-02 15:51 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-02 15:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30507/16703

- This PR adds an extra 216KB to repository

- Found files with invalid states:
  - Alignment/CocoaApplication/test/test_CocoaAnalyzer_cfg.py:
    - Added: e1c64b5e1edc3e0f86441d7a42a79cf93ab67605
    - Modified: 41218f0c372663835b20e984ca9ac075cdd0d34c, 72caeaf11d81d57ab8c2ebe7aaa1e5f08c62e1e2, af2a7b94dae098cc56ef1a8d1ba1879fb0eac578
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/table2DWithMirror_dd4hep.xml:
    - Added: 9fbc6107238ddc075f7f345f58083af7f9c9afb4
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/OpticalAlignments_testInput.db:
    - Added: 7655e3d3ad0d313da4798add64d4e2edf595c166
    - Deleted: 39558aca02985c625fd50985674a1a3bedf8fbaa


- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Alignment/CocoaFit/src/CocoaDBMgr.cc  modified in PR(s): #29936
  - File  Alignment/CocoaUtilities/interface/ALIUtils.h  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/ALIUtils.cc  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/GlobalOptionMgr.cc  modified in PR(s): #29933, #29936

2020-07-02 15:57 UTC, cmsbuild commented
A new Pull Request was created by  @ghugo83  for master.

It involves the following packages:

Alignment/CocoaApplication
Alignment/CocoaFit
Alignment/CocoaUtilities


@cmsbuild, @pohsun, @christopheralanwest, @tocheng, @tlampen can you please review it and eventually sign? Thanks.
@mschrode, @mmusich, @tocheng, @adewit this is something you requested to watch as well.
@silviodonato, @dpiparo you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2020-07-02 16:04 UTC, ghugo83 commented
Adding @ianna @civanch @cvuosalo

2020-07-02 16:47 UTC, civanch commented
please test

2020-07-02 16:47 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-07-02 18:02 UTC, cmsbuild commented
+1
Tested at: 72c4f773064b9b8e2946a1daa3220a7b4757bee6
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-99a8a0/7618/summary.html
CMSSW: CMSSW_11_2_X_2020-07-02-1100
SCRAM_ARCH: slc7_amd64_gcc820

2020-07-02 18:02 UTC, cmsbuild commented
Comparison job queued.

2020-07-02 19:49 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-99a8a0/7618/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 37
 - DQMHistoTests: Total histograms compared: 2784120
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2784069
 - DQMHistoTests: Total skipped: 50
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 36 files compared)
 - Checked 154 log files, 17 edm output root files, 37 DQM output files

2020-07-02 22:00 UTC, ianna requested changes
@ghugo83 - Good job! Some comments are just suggestions. Using `MessageLogger` is important and please, squash the commits if you can - it would be easier to scroll to a relevant discussion. Thanks.

2020-07-03 09:47 UTC, ghugo83 commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> +      getAllParameterValuesFromSpecParSections<T>(allSpecParSections, nodePath, parameterName);
Thanks @ianna  for the review!
Yes the thing is that apart from the README and getAllParameterValuesFromSpecParSections<T>, all the other comments address (very old) code which is not mine, it was already like that in 10_3_X:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X/Alignment/CocoaApplication/interface/CocoaAnalyzer.h 
https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X/Alignment/CocoaApplication/src/CocoaAnalyzer.cc
When CocoaAnalyzer is introduced back after https://github.com/cms-sw/cmssw/pull/25356 , it also contains the sections which were not modified in the context of the to port to DD4hep.
But ok, will address it :)

2020-07-03 13:20 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-03 13:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30507/16739

- This PR adds an extra 224KB to repository

- Found files with invalid states:
  - Alignment/CocoaApplication/test/test_CocoaAnalyzer_cfg.py:
    - Added: e1c64b5e1edc3e0f86441d7a42a79cf93ab67605
    - Modified: 41218f0c372663835b20e984ca9ac075cdd0d34c, 72caeaf11d81d57ab8c2ebe7aaa1e5f08c62e1e2, af2a7b94dae098cc56ef1a8d1ba1879fb0eac578
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/table2DWithMirror_dd4hep.xml:
    - Added: 9fbc6107238ddc075f7f345f58083af7f9c9afb4
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/OpticalAlignments_testInput.db:
    - Added: 7655e3d3ad0d313da4798add64d4e2edf595c166
    - Deleted: 39558aca02985c625fd50985674a1a3bedf8fbaa


- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Alignment/CocoaFit/src/CocoaDBMgr.cc  modified in PR(s): #29936
  - File  Alignment/CocoaUtilities/interface/ALIUtils.h  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/ALIUtils.cc  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/GlobalOptionMgr.cc  modified in PR(s): #29933, #29936

2020-07-03 13:26 UTC, cmsbuild commented
Pull request #30507 was updated. @cmsbuild, @pohsun, @christopheralanwest, @tocheng, @tlampen can you please check and sign again.

2020-07-03 13:26 UTC, ghugo83 commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> + */
Hmm within the same SpecPar block, all parameters values are stored in a std::vector.
But a cms::DDSpecParRefs itself is a std::vector<const DDSpecPar*>, ie a vector of SpecPar blocks.

2020-07-03 13:28 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-03 13:30 UTC, ghugo83 commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> +      getAllParameterValuesFromSpecParSections<T>(allSpecParSections, nodePath, parameterName);
@ianna Ok I addressed the review :)
Regarding the commits: is it possible to just do a squash-and-merge when merging the PR?

2020-07-03 13:33 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30507/16741

- This PR adds an extra 228KB to repository

- Found files with invalid states:
  - Alignment/CocoaApplication/test/test_CocoaAnalyzer_cfg.py:
    - Added: e1c64b5e1edc3e0f86441d7a42a79cf93ab67605
    - Modified: 41218f0c372663835b20e984ca9ac075cdd0d34c, 72caeaf11d81d57ab8c2ebe7aaa1e5f08c62e1e2, af2a7b94dae098cc56ef1a8d1ba1879fb0eac578
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/table2DWithMirror_dd4hep.xml:
    - Added: 9fbc6107238ddc075f7f345f58083af7f9c9afb4
    - Deleted: a910afabcc282715c374dc08706e4539614e11f7
  - Alignment/CocoaApplication/test/OpticalAlignments_testInput.db:
    - Added: 7655e3d3ad0d313da4798add64d4e2edf595c166
    - Deleted: 39558aca02985c625fd50985674a1a3bedf8fbaa


- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Alignment/CocoaFit/src/CocoaDBMgr.cc  modified in PR(s): #29936
  - File  Alignment/CocoaUtilities/interface/ALIUtils.h  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/ALIUtils.cc  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/GlobalOptionMgr.cc  modified in PR(s): #29933, #29936

2020-07-03 13:34 UTC, cmsbuild commented
Pull request #30507 was updated. @cmsbuild, @pohsun, @christopheralanwest, @tocheng, @tlampen can you please check and sign again.

2020-07-03 13:51 UTC, ianna commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> +      getAllParameterValuesFromSpecParSections<T>(allSpecParSections, nodePath, parameterName);
@ghugo83 - Thanks! Here is the link to CMS FAQ http://cms-sw.github.io/faq.html#how-do-i-collapse-multiple-commits-into-one 
Note, it's considered an advanced user question :-)

2020-07-03 14:58 UTC, ghugo83 commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> +      getAllParameterValuesFromSpecParSections<T>(allSpecParSections, nodePath, parameterName);
@ianna There are repos with a github feature called 'Squah and merge' allowed. But dont know if that is the case for CMSSW. 
Ok but usually when I do git --amend, I cannot push to the remote github branch anymore, without doing a forced push. Will it still be fine, given an open PR?

2020-07-03 15:58 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-03 15:59 UTC, ghugo83 commented on Alignment/CocoaApplication/src/CocoaAnalyzer.cc
> +      getAllParameterValuesFromSpecParSections<T>(allSpecParSections, nodePath, parameterName);
Ok all my work is now in the second commit :)

2020-07-03 16:04 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30507/16748

- This PR adds an extra 44KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Alignment/CocoaFit/src/CocoaDBMgr.cc  modified in PR(s): #29936
  - File  Alignment/CocoaUtilities/interface/ALIUtils.h  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/ALIUtils.cc  modified in PR(s): #29933
  - File  Alignment/CocoaUtilities/src/GlobalOptionMgr.cc  modified in PR(s): #29933, #29936

2020-07-03 16:05 UTC, cmsbuild commented
Pull request #30507 was updated. @cmsbuild, @pohsun, @christopheralanwest, @tocheng, @tlampen can you please check and sign again.

2020-07-03 17:42 UTC, cvuosalo commented
@cmsbuild please test

2020-07-03 17:42 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-07-03 18:59 UTC, cmsbuild commented
+1
Tested at: 7af821c9afe9537ac8afa5e05e432404c98416f5
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-99a8a0/7672/summary.html
CMSSW: CMSSW_11_2_X_2020-07-03-1200
SCRAM_ARCH: slc7_amd64_gcc820

2020-07-03 18:59 UTC, cmsbuild commented
Comparison job queued.

2020-07-03 20:47 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-99a8a0/7672/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 37
 - DQMHistoTests: Total histograms compared: 2784120
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2784069
 - DQMHistoTests: Total skipped: 50
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 36 files compared)
 - Checked 154 log files, 17 edm output root files, 37 DQM output files

2020-07-07 14:15 UTC, christopheralanwest commented
assign geometry

Since this PR involves DD4hep, I would like to have a sign-off from geometry prior to signing off for alca.

2020-07-07 14:15 UTC, cmsbuild commented
New categories assigned: geometry

@Dr15Jones,@cvuosalo,@mdhildreth,@makortel,@ianna,@civanch you have been requested to review this Pull request/Issue and eventually sign? Thanks

2020-07-07 16:19 UTC, cvuosalo commented
+1

2020-07-08 17:01 UTC, christopheralanwest commented
+1

2020-07-08 17:02 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo (and backports should be raised in the release meeting by the corresponding L2)

2020-07-08 20:19 UTC, silviodonato commented
+1

2020-07-08 20:19 UTC, merged