Rel val add qcd pt 1800 2400
cms-sw/cmssw pull request #30548
Opened 2020-07-06 10:38 UTC by mtosi

#### PR description:
as described in the JIRA [PDMVRELVALS-86](https://its.cern.ch/jira/browse/PDMVRELVALS-86)
the TRK POG would need to have the QCD_Pt_1800_2400 in the list of relval samples for the validation campaigns,
in particular for checking the tracking in the phase space of the dense environment typical of the high pT jets

this PR adds the genFragments (both for 13 and 14 TeV) and the element in the relval matrix

2020-07-06 10:38 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-06 10:43 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30548/16778

- This PR adds an extra 32KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py  modified in PR(s): #30527

2020-07-06 10:43 UTC, cmsbuild commented
A new Pull Request was created by  @mtosi (mia tosi) for master.

It involves the following packages:

Configuration/Generator
Configuration/PyReleaseValidation


@SiewYan, @pgunnell, @mkirsano, @chayanit, @wajidalikhan, @kpedro88, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez, @qliphy can you please review it and eventually sign? Thanks.
@Martin-Grunewald, @makortel, @fabiocos, @slomeo this is something you requested to watch as well.
@silviodonato, @dpiparo you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2020-07-06 10:56 UTC, chayanit requested changes

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_13TeV_TuneCUETP8M1_cfi.py
> +from Configuration.Generator.Pythia8CUEP8M1Settings_cfi import *
please update to TuneCP5
`from Configuration.Generator.MCTunes2017.PythiaCP5Settings_cfi import *`

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_13TeV_TuneCUETP8M1_cfi.py
> +        pythia8CUEP8M1SettingsBlock,
please update to TuneCP5
`pythia8CP5SettingsBlock`

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_13TeV_TuneCUETP8M1_cfi.py
> +                                    'pythia8CUEP8M1Settings',
please update to TuneCP5
`pythia8CP5Settings`

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi.py
> +from Configuration.Generator.Pythia8CUEP8M1Settings_cfi import *
please update to TuneCP5

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi.py
> +        pythia8CUEP8M1SettingsBlock,
please update to TuneCP5

2020-07-06 10:56 UTC, chayanit commented on Configuration/Generator/python/QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi.py
> +                                    'pythia8CUEP8M1Settings',
please update to TuneCP5

2020-07-06 10:56 UTC, chayanit commented on Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
> +    ('QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi', UpgradeFragment(Kby(9,50), 'QCD_Pt_1800_2400_14')),
should be QCD_Pt_1800_2400_14TeV_TuneCU5_cfi after you update to TuneCP5

2020-07-06 11:03 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-06 11:06 UTC, chayanit requested changes

2020-07-06 11:06 UTC, chayanit commented on Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
> +    ('QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi', UpgradeFragment(Kby(9,50), 'QCD_Pt_1800_2400_14')),
@mtosi the file names also need to be updated to TuneCP5 sorry and thanks!

2020-07-06 11:08 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30548/16779

- This PR adds an extra 36KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py  modified in PR(s): #30527

2020-07-06 11:08 UTC, cmsbuild commented
Pull request #30548 was updated. @SiewYan, @pgunnell, @mkirsano, @chayanit, @wajidalikhan, @kpedro88, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez, @qliphy can you please check and sign again.

2020-07-06 11:13 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-06 11:13 UTC, mtosi commented
opsi, you are right, sorry
it should be fixed, now

2020-07-06 11:16 UTC, chayanit commented
please test

2020-07-06 11:18 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30548/16780

- This PR adds an extra 36KB to repository

- Found files with invalid states:
  - Configuration/Generator/python/QCD_Pt_1800_2400_14TeV_TuneCUETP8M1_cfi.py:
    - Added: 201db8edcb1bc54840e42537b1034bf3442abbe3
    - Deleted: 05146bc1592dbf1ade7a883c3fc7d4428fe3ddd2
  - Configuration/Generator/python/QCD_Pt_1800_2400_13TeV_TuneCUETP8M1_cfi.py:
    - Added: 201db8edcb1bc54840e42537b1034bf3442abbe3
    - Deleted: 05146bc1592dbf1ade7a883c3fc7d4428fe3ddd2


- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py  modified in PR(s): #30527

2020-07-06 11:19 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-07-06 11:19 UTC, cmsbuild commented
Pull request #30548 was updated. @SiewYan, @pgunnell, @mkirsano, @chayanit, @wajidalikhan, @kpedro88, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez, @qliphy can you please check and sign again.

2020-07-06 12:34 UTC, cmsbuild commented
+1
Tested at: 05146bc1592dbf1ade7a883c3fc7d4428fe3ddd2
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3da262/7704/summary.html
CMSSW: CMSSW_11_2_X_2020-07-05-2300
SCRAM_ARCH: slc7_amd64_gcc820

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - #30455 @Dr15Jones: Fix TSGFromPropagation
 - #30543 @makortel: Move edm::defaultModuleLabel() body out-of-line

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3da262/7704/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3da262/7704/git-merge-result

2020-07-06 12:34 UTC, cmsbuild commented
Comparison job queued.

2020-07-06 12:45 UTC, chayanit commented
+1

2020-07-06 14:54 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3da262/7704/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 37
 - DQMHistoTests: Total histograms compared: 2787364
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2787313
 - DQMHistoTests: Total skipped: 50
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 36 files compared)
 - Checked 154 log files, 17 edm output root files, 37 DQM output files

2020-07-06 14:57 UTC, qliphy commented
+1

2020-07-06 22:42 UTC, kpedro88 commented
+upgrade

2020-07-06 22:42 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo (and backports should be raised in the release meeting by the corresponding L2)

2020-07-07 07:26 UTC, silviodonato commented
+1

2020-07-07 07:27 UTC, merged