missing buildfile dependencies in DataFormats and CondFormats
cms-sw/cmssw pull request #31005
Opened 2020-07-31 12:37 UTC by davidlange6

as usual - just grepping for #include...

2020-07-31 12:38 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-31 12:43 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31005/17468

- This PR adds an extra 44KB to repository

2020-07-31 12:44 UTC, davidlange6 commented
please test

2020-07-31 12:44 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-07-31 12:44 UTC, cmsbuild commented
A new Pull Request was created by  @davidlange6 (David Lange) for master.

It involves the following packages:

CondFormats/AlignmentRecord
CondFormats/CSCObjects
CondFormats/CastorObjects
CondFormats/DTObjects
CondFormats/DataRecord
CondFormats/ESObjects
CondFormats/EcalCorrections
CondFormats/EcalObjects
CondFormats/External
CondFormats/GEMObjects
CondFormats/GeometryObjects
CondFormats/JetMETObjects
CondFormats/MFObjects
CondFormats/PPSObjects
CondFormats/SiPixelTransient
DataFormats/Alignment
DataFormats/BTauReco
DataFormats/BeamSpot
DataFormats/CSCDigi
DataFormats/CTPPSDetId
DataFormats/CTPPSDigi
DataFormats/CTPPSReco
DataFormats/CastorReco
DataFormats/DTDigi
DataFormats/EcalDigi
DataFormats/EcalRecHit
DataFormats/EgammaCandidates
DataFormats/EgammaReco
DataFormats/EgammaTrackReco
DataFormats/FP420Cluster
DataFormats/FTLDigi
DataFormats/FTLRecHit
DataFormats/GEMDigi
DataFormats/GEMRecHit
DataFormats/GeometrySurface
DataFormats/GsfTrackReco
DataFormats/HGCDigi
DataFormats/HGCRecHit
DataFormats/HGCalReco
DataFormats/HLTReco
DataFormats/HcalCalibObjects
DataFormats/HcalDetId
DataFormats/HcalDigi
DataFormats/Histograms
DataFormats/JetReco
DataFormats/L1TCalorimeterPhase2
DataFormats/L1TCorrelator
DataFormats/L1TGlobal
DataFormats/L1THGCal
DataFormats/L1TMuon
DataFormats/L1TParticleFlow
DataFormats/L1TrackTrigger
DataFormats/L1Trigger
DataFormats/LTCDigi
DataFormats/Luminosity
DataFormats/METReco
DataFormats/Math
DataFormats/MuonReco
DataFormats/MuonSeed
DataFormats/OnlineMetaData
DataFormats/ParticleFlowCandidate
DataFormats/ParticleFlowReco
DataFormats/ProtonReco
DataFormats/Provenance
DataFormats/RPCDigi
DataFormats/RecoCandidate
DataFormats/SiPixelCluster
DataFormats/SiPixelDetId
DataFormats/SiPixelRawData
DataFormats/SiStripCluster
DataFormats/SiStripCommon
DataFormats/Streamer
DataFormats/TauReco
DataFormats/TestObjects
DataFormats/TrackCandidate
DataFormats/TrackerRecHit2D
DataFormats/TrackingRecHit
DataFormats/TrajectoryState
DataFormats/VertexReco


@andrius-k, @ggovi, @christopheralanwest, @kpedro88, @Martin-Grunewald, @rekovic, @fioriNTU, @tlampen, @pohsun, @santocch, @perrotta, @civanch, @makortel, @cmsbuild, @fwyzard, @smuzaffar, @Dr15Jones, @tocheng, @jfernan2, @mdhildreth, @slava77, @jpata, @benkrikler, @kmaeshima, @emeschi, @mommsen can you please review it and eventually sign? Thanks.
@erikbutz, @rappoccio, @gouskos, @echabert, @felicepantaleo, @jainshilpi, @hatakeyamak, @robervalwalsh, @emilbols, @sviret, @argiro, @jshlee, @Fedespring, @thomreis, @ahinzmann, @lgray, @abbiendi, @varuns23, @seemasharmafnal, @mmarionncern, @smoortga, @sethzenz, @JyothsnaKomaragiri, @makortel, @threus, @jhgoh, @amagitte, @apsallid, @jbsauvan, @cericeci, @dildick, @battibass, @pieterdavid, @forthommel, @vandreev11, @Sam-Harper, @HuguesBrun, @cbernet, @rovere, @VinInn, @cseez, @ferencek, @nhanvtran, @gkasieczka, @tocheng, @deguio, @schoef, @alesaggio, @mmusich, @ptcox, @abdoulline, @fabiocos, @clelange, @kreczko, @jdamgov, @jdolen, @rchatter, @trocino, @riga, @jan-kaspar, @wddgit, @calderona, @mverzett, @sobhatta, @lecriste, @afiqaize, @gpetruc, @mariadalfonso, @amarini, @andrzejnovak, @folguera, @pfs this is something you requested to watch as well.
@silviodonato, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2020-07-31 13:06 UTC, cmsbuild commented
-1

Tested at: f9b0ef83d691f4e103fa9a466df12fdd3a5aae6e

CMSSW: CMSSW_11_2_X_2020-07-31-1100
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-70fc35/8467/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  HeaderConsistency  ClangBuild**

* **Build**:

I found compilation warning when building:  See details on the summary page.

* **Clang**:

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2020-07-31 13:06 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-07-31 13:07 UTC, makortel commented on DataFormats/Provenance/BuildFile.xml
> +<use name="FWCore/ParameterSet"/>
The `#include`'s of `FWCore/ParameterSet` look unnecessary (code compiles without), so I'll make a PR to remove them to avoid this dependence.

2020-07-31 13:09 UTC, makortel commented on DataFormats/Provenance/BuildFile.xml
> +<use name="FWCore/ParameterSet"/>
Also, this would appear to add a circular dependence.

2020-07-31 13:12 UTC, davidlange6 commented
Great - if you want to suggest a patch, I can apply it in this PR.

On Jul 31, 2020, at 3:08 PM, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:



@makortel commented on this pull request.

________________________________

In DataFormats/Provenance/BuildFile.xml<https://github.com/cms-sw/cmssw/pull/31005#discussion_r463599782>:

> @@ -1,5 +1,6 @@
 <use name="FWCore/Utilities"/>
 <use name="FWCore/Reflection"/>
+<use name="FWCore/ParameterSet"/>


The #include's of FWCore/ParameterSet look unnecessary (code compiles without), so I'll make a PR to remove them to avoid this dependence.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/31005#pullrequestreview-459158825>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABGPFQZL6Q4ZC6LZ3IAWPGDR6K63TANCNFSM4PQF44EA>.

2020-07-31 13:44 UTC, makortel commented
> Great - if you want to suggest a patch, I can apply it in this PR.

Could you cherry-pick this one https://github.com/makortel/cmssw/commit/78688417e4b1e9f5456d6f0042ce3179de894a27 ?

2020-07-31 14:02 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-07-31 14:04 UTC, davidlange6 commented
abort

2020-07-31 14:07 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31005/17474

- This PR adds an extra 52KB to repository

2020-07-31 14:08 UTC, cmsbuild commented
Pull request #31005 was updated. @andrius-k, @ggovi, @christopheralanwest, @kpedro88, @Martin-Grunewald, @rekovic, @fioriNTU, @tlampen, @pohsun, @santocch, @perrotta, @civanch, @makortel, @cmsbuild, @fwyzard, @smuzaffar, @Dr15Jones, @tocheng, @jfernan2, @mdhildreth, @slava77, @jpata, @benkrikler, @kmaeshima, @emeschi, @mommsen can you please check and sign again.

2020-07-31 17:46 UTC, davidlange6 commented
please test

2020-07-31 17:46 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-07-31 18:00 UTC, cmsbuild commented
-1

Tested at: d4f52cbc3d09e3f892b01d9ece0ebc57779d08e7

CMSSW: CMSSW_11_2_X_2020-07-31-1100
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-70fc35/8481/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  HeaderConsistency  ClangBuild**

* **Build**:

I found compilation warning when building:  See details on the summary page.

* **Clang**:

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2020-07-31 18:00 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-08-01 05:53 UTC, davidlange6 commented
.please test

2020-08-01 06:29 UTC, davidlange6 commented
please test




On 1 Aug 2020, at 07:54, David Lange <notifications@github.com> wrote:

﻿

.please test

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/31005#issuecomment-667477709>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABGPFQ3VB2ZCIY5L7KIIW43R6OUXFANCNFSM4PQF44EA>.

2020-08-01 06:30 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-08-01 08:44 UTC, cmsbuild commented
-1

Tested at: d4f52cbc3d09e3f892b01d9ece0ebc57779d08e7

CMSSW: CMSSW_11_2_X_2020-07-31-2300
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-70fc35/8488/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  HeaderConsistency  ClangBuild**

* **Build**:

I found compilation warning when building:  See details on the summary page.

* **Clang**:

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2020-08-01 08:44 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-08-01 12:26 UTC, Dr15Jones commented
So it looks like this is causing scram to find circular dependencies?

2020-08-01 13:12 UTC, davidlange6 commented
I suspect as well. I’ll look more when back to a computer....


David


On 1 Aug 2020, at 14:27, Chris Jones <notifications@github.com> wrote:

﻿

So it looks like this is causing scram to find circular dependencies?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/31005#issuecomment-667524111>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABGPFQZ65IZ4WCPFLEJBQCLR6QCXTANCNFSM4PQF44EA>.

2020-08-01 15:59 UTC, Dr15Jones requested changes

2020-08-01 15:59 UTC, Dr15Jones commented on DataFormats/ParticleFlowReco/BuildFile.xml
> +<use name="DataFormats/EgammaCandidates"/>
```suggestion
```
This is already earlier in the list

2020-08-01 15:59 UTC, Dr15Jones commented on DataFormats/ParticleFlowReco/BuildFile.xml
> +<use name="DataFormats/EgammaReco"/>
```suggestion
```
This is already earlier in the list

2020-08-01 16:19 UTC, Dr15Jones commented
The problem is a direct circular dependency between DataFormats/GeometrySurface and DataFormats/GeometryCommonDetAlgo. It looks like GeometrySurface was intended to be the 'lower level' package. Unfortunately it grew the following dependency

```
[cdj@cmslpc151 src]$ grep GeometryCommonDetAlgo $CMSSW_RELEASE_BASE/src/DataFormats/GeometrySurface/*/*
[cut]DataFormats/GeometrySurface/interface/LocalErrorBaseExtended.h:#include "DataFormats/GeometryCommonDetAlgo/interface/DeepCopyPointer.h"
[cut]/DataFormats/GeometrySurface/interface/LocalErrorExtended.h:#include "DataFormats/GeometryCommonDetAlgo/interface/ErrorMatrixTag.h"
```

The inclusion of `DeepCopyPointer.h` is unnecessary while `ErrorMatrixTag` is used. However, the definition of LocalErrorExtended is only used in two places

```
[cdj@cmslpc151 src]$ git grep DataFormats/GeometrySurface/interface/LocalErrorExtended.h
DataFormats/GeometryCommonDetAlgo/interface/ErrorFrameTransformer.h:#include "DataFormats/GeometrySurface/interface/LocalErrorExtended.h"
Geometry/CommonTopologies/interface/MuonGeomDet.h:#include "DataFormats/GeometrySurface/interface/LocalErrorExtended.h"
```
and
```
[cdj@cmslpc151 src]$ git grep DataFormats/GeometrySurface/interface/LocalErrorBaseExtended.h
DataFormats/GeometrySurface/interface/LocalErrorExtended.h:#include "DataFormats/GeometrySurface/interface/LocalErrorBaseExtended.h"
```

Therefore `LocalErrorBaseExtended.h` and `LocalErrorExtended.h` can easily be moved to `DataFormats/GeometryCommonDetAlgo`.

2020-08-01 17:57 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-08-01 18:04 UTC, cmsbuild commented
Pull request #31005 was updated. @andrius-k, @ggovi, @christopheralanwest, @kpedro88, @Martin-Grunewald, @rekovic, @fioriNTU, @tlampen, @pohsun, @santocch, @perrotta, @civanch, @makortel, @cmsbuild, @fwyzard, @smuzaffar, @Dr15Jones, @tocheng, @jfernan2, @mdhildreth, @slava77, @jpata, @benkrikler, @kmaeshima, @emeschi, @mommsen can you please check and sign again.

2020-08-01 18:05 UTC, Dr15Jones commented
@davidlange6 I'm working on a pull request now to fix the geometry dependencies.

2020-08-01 18:23 UTC, Dr15Jones commented
See ##31018

2020-08-02 07:13 UTC, davidlange6 commented
thanks @dr15jones - I see that there is at least one more circular dep to fix too:(

2020-08-02 07:30 UTC, davidlange6 commented
ok - I close this - there are numerous circular dependencies revealed by this PR

2020-08-02 07:30 UTC, closed without merging

2020-08-03 14:49 UTC, makortel commented
> > Great - if you want to suggest a patch, I can apply it in this PR.
> 
> Could you cherry-pick this one [makortel@7868841](https://github.com/makortel/cmssw/commit/78688417e4b1e9f5456d6f0042ce3179de894a27) ?

I'll make a separate PR of this then.