GeometricDetExtra, PGeometricDetExtra schema removal
cms-sw/cmssw pull request #31729
Opened 2020-10-09 14:16 UTC by vargasa

#### PR description:

Addresses https://github.com/cms-sw/cmssw/issues/31567 

FYI: @ianna, @ghugo83, @cvuosalo

2020-10-09 14:17 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-09 14:23 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18927

- This PR adds an extra 72KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)
- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18927/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18927/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2020-10-09 14:33 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-09 14:40 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18929

- This PR adds an extra 72KB to repository

2020-10-09 14:40 UTC, cmsbuild commented
A new Pull Request was created by  @vargasa (Andres Vargas) for master.

It involves the following packages:

CondCore/GeometryPlugins
CondCore/Utilities
CondFormats/GeometryObjects
CondTools/Geometry
Geometry/CaloEventSetup
Geometry/Records
Geometry/TrackerGeometryBuilder
Geometry/TrackerNumberingBuilder
SLHCUpgradeSimulations/Geometry


@civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please review it and eventually sign? Thanks.
@fabiocos, @makortel, @JanFSchulte, @tocheng, @VinInn, @mmusich, @mtosi, @ebrondol, @seemasharmafnal, @venturia this is something you requested to watch as well.
@silviodonato, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2020-10-09 14:44 UTC, ianna commented
please check

2020-10-09 15:11 UTC, ianna commented
please test

2020-10-09 15:11 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-10-09 16:03 UTC, mmusich commented on Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
> +    int subdetid = module->geographicalID().subdetId();
isn't this broken by #31573?
Now it's `geographicalId()`

2020-10-09 16:03 UTC, mmusich commented on SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc
> +    int subdetid = modules[i]->geographicalID().subdetId();
isn't this broken by #31573?
Now it's `geographicalId()`

2020-10-09 16:11 UTC, mmusich commented
-1
@vargasa, if the Global Tags are not cleaned by the record first, I suspect this will fail... 

BTW: why have you proceeded without explicit aknowledgement from the DPG?

2020-10-09 16:44 UTC, cmsbuild commented
-1

Tested at: 54d75b9dee374c6b3f44d1d8425b4d645cb6d784

CMSSW: CMSSW_11_2_X_2020-10-09-1100
SCRAM_ARCH: slc7_amd64_gcc820

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - #31713 @mmusich: Introduce TrackingEffFromHitPatternClientConfigZeroBias and use it for the trackingZeroBias DQM Harvesting sequence

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9833/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9833/git-merge-result

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9833/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found compilation error when building: 

<pre>trackerTopology
--- Registered EDM Plugin: GeometryTrackerNumberingBuilderPlugins
Entering library rule at src/Geometry/TrackerNumberingBuilder/test
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc:41:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
  ^~~~~
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc:41:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
</pre>

* **Clang**:

I found compilation error while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```


<pre>>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerGeometryBuilder/test/phase1PixelTopology_t.cpp
Entering library rule at src/Geometry/TrackerGeometryBuilder/test
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerGeometryBuilder/test/GeoHierarchyTest.cc
Entering library rule at src/Geometry/TrackerGeometryBuilder/test
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc:168:28: error: no member named 'geographicalID' in 'GeometricDet'; did you mean 'geographicalId'?
    int subdetid = module->geographicalID().subdetId();
                           ^~~~~~~~~~~~~~
                           geographicalId
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1100/src/Geometry/TrackerNumberingBuilder/interface/GeometricDet.h:96:16: note: 'geographicalId' declared here
  const DetId& geographicalId() const { return geographicalID_; }
</pre>


The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - #31713 @mmusich: Introduce TrackingEffFromHitPatternClientConfigZeroBias and use it for the trackingZeroBias DQM Harvesting sequence

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9833/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9833/git-merge-result

2020-10-09 16:44 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-10-09 16:57 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-09 17:00 UTC, mmusich commented
@vargasa please remove from the history my commit 02601ad already merged.

2020-10-09 17:01 UTC, mmusich commented
@christopheralanwest,@yuanchao, @tocheng, @ggovi
This PR should be put on hold, until all the Global Tags in autoCond have been cleaned by the removed record

2020-10-09 17:06 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-09 17:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18941

- This PR adds an extra 72KB to repository

2020-10-09 17:11 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-09 17:23 UTC, vargasa commented
> BTW: why have you proceeded without explicit aknowledgement from the DPG?

Hi @mmusich, no answer was collected from the announcement https://hypernews.cern.ch/HyperNews/CMS/get/tracker-performance/2388.html except your concern in a private conversation (Sep 29, 2020 email) regarding its usage which I tried to address to the best of my knowledge. Am I missing something? or Do we need to go through an approval process for this PR? If so, I would still suggest to run the tests so both things can be done in parallel. If you don't agree I can also close the PR but that may put additional waiting time within our already tight timeline

2020-10-09 17:41 UTC, mmusich commented
>  Am I missing something? or Do we need to go through an approval process for this PR? If so, I would still suggest to run the tests so both things can be done in parallel. 

@vargasa, this PR "as-is" is 100% going to fail. We need to clean all the records in DB. If you'd have alerted us in time we could have asked AlCA to clean the autoCond Global Tag *before* submitting the PR....

2020-10-09 17:59 UTC, vargasa commented
@mmusich the submission of the PR doesn't represent a problem by itself. We didn't have that information prior to this. It's now a draft, please let me know if there is any other requirement to proceed with this

2020-10-09 20:46 UTC, mmusich commented
@cmsbuild, please test

2020-10-09 20:46 UTC, cmsbuild commented
The tests are being triggered in jenkins.

2020-10-09 22:14 UTC, cmsbuild commented
-1

Tested at: f3692fd5ec709cee41d2346d32334094a0ef8f57

CMSSW: CMSSW_11_2_X_2020-10-09-1500
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-617005/9844/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found compilation error when building: 

<pre>trackerTopology
--- Registered EDM Plugin: GeometryTrackerNumberingBuilderPlugins
Entering library rule at src/Geometry/TrackerNumberingBuilder/test
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1500/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1500/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc:41:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1500/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
  ^~~~~
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1500/src/Geometry/TrackerNumberingBuilder/test/ModuleNumbering.cc:41:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-09-1500/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
</pre>

* **Clang**:

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2020-10-09 22:14 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-10-09 23:24 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-09 23:31 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/18947

- This PR adds an extra 72KB to repository

2020-10-09 23:31 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-10 03:00 UTC, christopheralanwest commented
> > BTW: why have you proceeded without explicit aknowledgement from the DPG?
> 
> Hi @mmusich, no answer was collected from the announcement https://hypernews.cern.ch/HyperNews/CMS/get/tracker-performance/2388.html except your concern in a private conversation (Sep 29, 2020 email) regarding its usage which I tried to address to the best of my knowledge. Am I missing something? or Do we need to go through an approval process for this PR? If so, I would still suggest to run the tests so both things can be done in parallel. If you don't agree I can also close the PR but that may put additional waiting time within our already tight timeline

AlCa will need to remove the relevant records from all 38 different GTs in autoCond. It is easiest to make such a change when there are no open PRs that would conflict with this change, which is not currently the case. I don't understand the reason for urgency mentioned above--could you explain? On what time scale are you hoping to have this removal accomplished?

2020-10-10 05:35 UTC, ianna commented
> > > BTW: why have you proceeded without explicit aknowledgement from the DPG?
> > 
> > 
> > Hi @mmusich, no answer was collected from the announcement https://hypernews.cern.ch/HyperNews/CMS/get/tracker-performance/2388.html except your concern in a private conversation (Sep 29, 2020 email) regarding its usage which I tried to address to the best of my knowledge. Am I missing something? or Do we need to go through an approval process for this PR? If so, I would still suggest to run the tests so both things can be done in parallel. If you don't agree I can also close the PR but that may put additional waiting time within our already tight timeline
> 
> AlCa will need to remove the relevant records from all 38 different GTs in autoCond. It is easiest to make such a change when there are no open PRs that would conflict with this change, which is not currently the case. I don't understand the reason for urgency mentioned above--could you explain? On what time scale are you hoping to have this removal accomplished?

This is directly related to DD4HEP migration. The time scale is defined by 11_2. We have limited resources and would like to move fast. I have contacted @ggovi for an advice how to proceed. It seems that opening a PR is the fastest option to collect feedback 😀

Please advise which part of this PR must stay to avoid pressure on the GT update. Thanks!

2020-10-12 07:54 UTC, civanch commented
@vargasa , @ianna , is it possible to make an intermediate step, when GeometricDetExtra is not used but not removed from GT?

2020-10-12 08:57 UTC, ianna commented
> @vargasa , @ianna , is it possible to make an intermediate step, when GeometricDetExtra is not used but not removed from GT?

Yes. However, in this case we need to keep the minimum required. @ggovi and @christopheralanwest please, mark the files in this PR that must stay in CMSSW. Thanks!

2020-10-13 04:37 UTC, christopheralanwest commented
> > @vargasa , @ianna , is it possible to make an intermediate step, when GeometricDetExtra is not used but not removed from GT?
> 
> Yes. However, in this case we need to keep the minimum required. @ggovi and @christopheralanwest please, mark the files in this PR that must stay in CMSSW. Thanks!

I've prepared the necessary queues and will submit the PR to update `autoCond` once an IB with PR #31645 is available.

A potential complication is that sometimes HLT requires running on GTs from old releases. Without a definition of `PGeometricDetExtra` in CMSSW, GTs that contain that record will no longer be readable, even if the record is not actually used. @cms-sw/hlt-l2 Do you have any concerns with removing `PGeometricDetExtra` entirely or does its definition need to be retained? As a test, I have successfully run `addOnTests.py` and `runTheMatrix.py` after removing the record from these GTs: https://github.com/cms-sw/cmssw/blob/2037e05d590a623f1024c5228ca9fbcff0de7ab9/Configuration/AlCa/python/autoCond.py#L39-L46

2020-10-13 17:14 UTC, cvuosalo commented
What is the risk in deleting these records? We are trying to complete the Run 3 DD4hep migration in a very short time frame, and we should not take unnecessary risks. If the records are deleted and then the missing records cause problems, reverting and fixing the problems will take time and effort that we cannot afford.

2020-10-14 04:56 UTC, christopheralanwest commented
Removing the records from the GTs in master poses essentially no risk because they are unused--if they were not, the matrix workflows would crash. PR #31780 removes these records from all GTs in autoCond. A problem will arise if an old GT is used in a release built after this PR is merged, but to resolve this issue AlCa could simply prepare a new version of the old GT that excludes the obsolete record.

2020-10-14 06:41 UTC, mmusich commented
test parameters:
* pull_request = #31780

2020-10-14 06:41 UTC, mmusich commented
@cmsbuild, please test

2020-10-14 06:41 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Tested with other pull request(s) cms-sw/cmssw#31780

2020-10-14 08:05 UTC, cmsbuild commented
-1

Tested at: cc0d5f758b08a3baf3782ca71164bd65b4029b4b

CMSSW: CMSSW_11_2_X_2020-10-13-2300
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9934/summary.html

I found follow errors while testing this PR

**Failed tests:  Build  ClangBuild**

* **Build**:

I found compilation error when building: 

<pre>@@@@ Running edmWriteConfigs for TrackerTopologyAnalyzer
--- Registered EDM Plugin: TrackerTopologyAnalyzer
Entering library rule at src/Geometry/TrackerNumberingBuilder/test
>> Compiling edm plugin /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-13-2300/src/Geometry/TrackerNumberingBuilder/test/GeometricDetAnalyzer.cc
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-13-2300/src/Geometry/TrackerNumberingBuilder/test/GeometricDetAnalyzer.cc:37:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-13-2300/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
  ^~~~~
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-13-2300/src/Geometry/TrackerNumberingBuilder/test/GeometricDetAnalyzer.cc:37:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-13-2300/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
</pre>

* **Clang**:

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2020-10-14 08:05 UTC, cmsbuild commented
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)

2020-10-14 08:45 UTC, mmusich requested changes
@vargasa can you please provide a *compiling* branch?
How to reproduce the issue:
```
cmsrel CMSSW_11_2_X_2020-10-13-2300
cd CMSSW_11_2_X_2020-10-13-2300/src/
cmsenv
git cms-merge-topic 31729
scramv1 b -j 20
...
```
leads to:
```
In file included from /tmp/musich/CMSSW_11_2_X_2020-10-13-2300/src/SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc:45:
/tmp/musich/CMSSW_11_2_X_2020-10-13-2300/poison/Geometry/TrackerNumberingBuilder/interface/CmsTrackerDebugNavigator.h:1:2: error: #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
 #error THIS FILE HAS BEEN REMOVED FROM THE PACKAGE.
  ^~~~~
```

in addition, can you please fix the couple of clang warnings below?

2020-10-14 08:45 UTC, mmusich commented on Geometry/TrackerGeometryBuilder/test/ModuleInfo.cc
> -    double density = gdei->density() / density_units;
`density_units` is now unused.
Please remove from line 80 of this file: https://github.com/cms-sw/cmssw/pull/31729/files#diff-35e53a427c13b6405f6885a94301343db11c1dae1173319765299c82ac39c5aeR80

2020-10-14 08:45 UTC, mmusich commented on SLHCUpgradeSimulations/Geometry/test/ModuleInfo_Phase2.cc
> -    double density = gdei->density() / density_units;
`density_units` is now unused, please remove it from L90 of this file:
https://github.com/cms-sw/cmssw/pull/31729/files#diff-6b0322842aa80408bfebe8127dd0ad0467828812b3498aafae6251228e33a137R90

This triggers the following errors in compilation: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9934/clang-new-warnings.log

2020-10-14 13:56 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-14 13:58 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-14 14:05 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19055

- This PR adds an extra 32KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)
- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19055/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19055/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2020-10-14 15:26 UTC, mmusich commented
@vargasa this still fails code-checks, can you apply the patch?

2020-10-14 15:40 UTC, vargasa commented
@mmusich please wait. It is still building locally to make sure it doesn't happen the same. For some reason I was not seeing these compilation errors before. I'll let you know when it is ready :+1:

2020-10-14 17:01 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-14 17:05 UTC, vargasa commented
@mmusich ready. I double checked, it compiles locally with no warnings. Please ping me again if you see any problem

2020-10-14 17:06 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19066

- This PR adds an extra 116KB to repository

2020-10-14 17:06 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-14 17:08 UTC, mmusich commented
@cmsbuild, please test

2020-10-14 17:08 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Tested with other pull request(s) cms-sw/cmssw#31780

2020-10-14 19:52 UTC, cmsbuild commented
-1

Tested at: 0cc0d777a0b181a828c9750130fe88a91690b5cc

CMSSW: CMSSW_11_2_X_2020-10-14-1100
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9960/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test UnitTestConcurrentIOVsCondCore had ERRORS
---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS
---> test testSSTGainPCL_fromRECO had ERRORS
---> test checkMultiRunHarvestingOutput had ERRORS

2020-10-14 19:53 UTC, cmsbuild commented
Comparison job queued.

2020-10-14 21:06 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9960/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 35
 - DQMHistoTests: Total histograms compared: 2543752
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2543729
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 34 files compared)
 - Checked 149 log files, 22 edm output root files, 35 DQM output files

2020-10-14 21:15 UTC, christopheralanwest commented
For the `UnitTestConcurrentIOVsCondCore` unit test, you will need to modify https://github.com/cms-sw/cmssw/blob/526b69270db14b611d10847a81d78821fb36d49e/CondCore/ESSources/test/TestConcurrentIOVsCondCore_cfg.py#L69 to point to the GT `112X_dataRun2_v5`. I think that we want to use the actual GT name rather than the key names in `autoCond` because in principle the content of `112X_dataRun2_v5` referenced in the unit test could change.

I will let @mmusich comment on the other unit test failures.

2020-10-14 21:27 UTC, vargasa commented
@christopheralanwest thanks. Just did it. Now that one runs locally. There are a couple throwing:
```
----- Begin Fatal Exception 14-Oct-2020 20:36:07 CEST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
   [2] While attempting to load plugin PGeometricDetExtraRcd@NewProxy
Exception Message:
unable to load /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-14-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so because /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-14-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so: cannot open shared object file: No such file or directory
```
However, all references to `PGeometricDetExtraRcd` were removed. It is the same error that `UnitTestConcurrentIOVsCondCore` was throwing before

2020-10-14 21:46 UTC, christopheralanwest commented
I think that error is due to loading an old global tag at:

https://github.com/cms-sw/cmssw/blob/18f41ede8ac62f7097030abe8f052451c78e08ad/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh#L7

The global tag should be changed to `111X_dataRun3_Express_v4`.

2020-10-15 10:38 UTC, mmusich commented
@vargasa @christopheralanwest 
regarding the failures:

> ---> test UnitTestConcurrentIOVsCondCore had ERRORS

this, as pointed out in https://github.com/cms-sw/cmssw/pull/31729#issuecomment-708664358 can be solved by using the new run2 data GT: `112X_dataRun2_v5`, but I do not quite understand what is the advantage of having an actual GT name rather than the key names in `autoCond`. As just demonstrated in this PR, hardcoded GTs do not age well. 
Actually it seems to me, that the entire concept of using a GT for this test is an overkill, as what the original author actually wants to access is just a multi-IOV per-LS record (in this case the `BeamSpotRcd`).
I have followed up with a question for the author in the orignial PR here: https://github.com/cms-sw/cmssw/pull/28010/files#r505439543

> ---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS

the error here is: 
```
----- Begin Fatal Exception 14-Oct-2020 20:36:49 CEST-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Producers want to deliver type="GeometricDet" label=""
 from record IdealGeometryRecord. The two providers are 
1) type="TrackerGeometricDetESModule" label=""
2) type="TrackerGeometricDetESModule" label="trackerNumberingGeometryDB"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
```

you can introduce (as suggested by the framework error) an `ESPrefer` for the label you wish to retain: adding this line:
```python
process.es_prefer_geomdet = cms.ESPrefer("TrackerGeometricDetESModule","")
``` 
here: https://github.com/cms-sw/cmssw/blob/0cc0d777a0b181a828c9750130fe88a91690b5cc/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDB_cfg.py#L15-L18

> ---> test testSSTGainPCL_fromRECO had ERRORS
> ---> test checkMultiRunHarvestingOutput had ERRORS

as for this you can update the GT name to be `111X_dataRun3_Express_v4` as pointed out in https://github.com/cms-sw/cmssw/pull/31729#issuecomment-708677819, though in the same spirit of above I'd rather ask you to change it into an `autoCond` key:
```diff
iff --git a/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh b/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
index 690462fca00..9fa8fb8b17b 100755
--- a/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
+++ b/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
@@ -4,4 +4,4 @@ function die { echo $1: status $2 ;  exit $2; }
 (cmsRun ${LOCAL_TEST_DIR}/testSSTGain_PCL_FromRECO_cfg.py era=A) || die 'Failure running cmsRun testSSTGain_PCL_FromRECO_cfg.py era=A' $?
 (cmsRun ${LOCAL_TEST_DIR}/testSSTGain_PCL_FromRECO_cfg.py era=B) || die 'Failure running cmsRun testSSTGain_PCL_FromRECO_cfg.py era=B' $?
 (cmsRun ${LOCAL_TEST_DIR}/testSSTGain_HARVEST_FromRECO.py 0) || die 'Failure running cmsRun testSSTGain_HARVEST_FromRECO.py 0' $?
-(cmsRun ${LOCAL_TEST_DIR}/testSSTGain_MultiRun_ALCAHARVEST.py globalTag=102X_dataRun2_Express_v3) || die 'Failure running cmsRun testSSTGain_MultiRun_ALCAHARVEST.py 0' $?
+(cmsRun ${LOCAL_TEST_DIR}/testSSTGain_MultiRun_ALCAHARVEST.py globalTag=auto:run3_data_express) || die 'Failure running cmsRun testSSTGain_MultiRun_ALCAHARVEST.py 0' $?
```

2020-10-15 15:20 UTC, wddgit commented
I submitted a fix for UnitTestConcurrentIOVsCondCore, #31806

2020-10-15 16:22 UTC, vargasa commented
> though in the same spirit of above I'd rather ask you to change it into an `autoCond` key

Hi @mmusich. Thanks. Can you point me to an example on how to do that?

2020-10-15 16:25 UTC, mmusich commented
@vargasa 

> Can you point me to an example on how to do that?

I provided you the exact git patch to apply at the end of https://github.com/cms-sw/cmssw/pull/31729#issuecomment-709137245

2020-10-15 16:59 UTC, vargasa commented
> I provided you the exact git patch to apply at the end of [#31729 (comment)](https://github.com/cms-sw/cmssw/pull/31729#issuecomment-709137245)

It didn't work tho:

```
===== Test "testSSTGainPCL_fromRECO" ====
argument 0: testSSTGainPCL_fromRECO
argument 1: /bin/bash
argument 2: CalibTracker/SiStripChannelGain/test
argument 3: testSSTGain_PCL_FromRECO.sh
shell is: /bin/bash
Current directory is: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100
topdir is: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100
testdir is: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/src/CalibTracker/SiStripChannelGain/test
tmpdir is: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/tmp/slc7_amd64_gcc820
testbin is: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/test/slc7_amd64_gcc820
Running script: /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/src/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
----- Begin Fatal Exception 15-Oct-2020 11:47:06 CDT-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
   [2] While attempting to load plugin PGeometricDetExtraRcd@NewProxy
Exception Message:
unable to load /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so because /uscms_data/d3/nsf/ac8qnc90c/CMSSW_11_2_X_2020-10-09-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so: cannot open shared object file: No such file or directory
----- End Fatal Exception -------------------------------------------------
Failure running cmsRun testSSTGain_HARVEST_FromRECO.py 0: status 65
status = 16640

---> test testSSTGainPCL_fromRECO had ERRORS
```
Same message is thrown now for `GeometryTrackerGeometryBuilderTestDriver`

2020-10-15 17:02 UTC, mmusich commented
@vargasa

> It didn't work tho:

 don't foget to merge locally this commit 32b91acd007f51c4688596f26058f76ae24615bc from https://github.com/cms-sw/cmssw/pull/31780!!

2020-10-15 17:04 UTC, mmusich commented
@vargasa, why don't just push the mods here? The bot will take care of merging #31780 in the PR tests

2020-10-15 17:10 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-15 17:13 UTC, vargasa commented on CondCore/ESSources/test/TestConcurrentIOVsCondCore_cfg.py
> +    globaltag = cms.string('112X_dataRun2_v5'),
I'll drop this one. So it doesn't conflict with @wddgit PR

2020-10-15 17:20 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19105

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  CondCore/ESSources/test/TestConcurrentIOVsCondCore_cfg.py  modified in PR(s): #31806

2020-10-15 17:20 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-15 17:25 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-15 17:33 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19106

- This PR adds an extra 132KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  CUDADataFormats/Common/interface/HeterogeneousSoA.h  modified in PR(s): #27983
  - File  CUDADataFormats/Common/interface/HostProduct.h  modified in PR(s): #27983
  - File  CUDADataFormats/StdDictionaries/BuildFile.xml  modified in PR(s): #27983
  - File  CUDADataFormats/StdDictionaries/src/classes.h  modified in PR(s): #27983
  - File  CUDADataFormats/StdDictionaries/src/classes_def.xml  modified in PR(s): #27983

2020-10-15 17:33 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-15 17:35 UTC, vargasa commented
>@mmusich why don't just push the mods here?

Done

2020-10-15 17:35 UTC, mmusich commented
@cmsbuild, please test

2020-10-15 17:36 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Tested with other pull request(s) cms-sw/cmssw#31780

2020-10-15 17:37 UTC, vargasa commented
@mmusich Can we test it with https://github.com/cms-sw/cmssw/pull/31806 too?

2020-10-15 17:41 UTC, mmusich commented
> Can we test it with #31806 too?

Technically yes, though I have seen funny merges when more than one PR is tested.  There should be only one failing test remaining in this round.  I suppose we can retest after #31806 is merged.

2020-10-15 23:38 UTC, cmsbuild commented
-1

Tested at: 6acb366aaa1152947697e62f98b73dfcc063d28d

CMSSW: CMSSW_11_2_X_2020-10-15-1100
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9997/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test UnitTestConcurrentIOVsCondCore had ERRORS
---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS

2020-10-15 23:39 UTC, cmsbuild commented
Comparison job queued.

2020-10-16 00:55 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/9997/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 35
 - DQMHistoTests: Total histograms compared: 2543752
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2543729
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 34 files compared)
 - Checked 149 log files, 22 edm output root files, 35 DQM output files

2020-10-16 02:43 UTC, christopheralanwest commented
> I found errors in the following unit tests:
> 
> ---> test UnitTestConcurrentIOVsCondCore had ERRORS
> ---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS

Previously the unit test error logs showed

```
===== Test "cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-14-1100/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDB_cfg.py " ====
----- Begin Fatal Exception 14-Oct-2020 20:36:49 CEST-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Producers want to deliver type="GeometricDet" label=""
 from record IdealGeometryRecord. The two providers are 
1) type="TrackerGeometricDetESModule" label=""
2) type="TrackerGeometricDetESModule" label="trackerNumberingGeometryDB"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
>>> processed 0 events
Failure using cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-14-1100/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDB_cfg.py: status 65
status = 16640

---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS
```

but now the test `Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDB_cfg.py` completes successfully and the error is in the next test in the same package:

```
===== Test "cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-15-1100/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py " ====
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-15-1100/python/Configuration/Geometry/GeometryExtended_cff.py:2: UserWarning: ATTENTION: This job uses Run 1 Geometry.
  warnings.warn('ATTENTION: This job uses Run 1 Geometry.')
----- Begin Fatal Exception 16-Oct-2020 00:20:31 CEST-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Producers want to deliver type="GeometricDet" label=""
 from record IdealGeometryRecord. The two providers are 
1) type="TrackerGeometricDetESModule" label=""
2) type="TrackerGeometricDetESModule" label="trackerNumberingGeometry"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 16-Oct-2020 00:20:31 CEST-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Producers want to deliver type="GeometricDet" label=""
 from record IdealGeometryRecord. The two providers are 
1) type="TrackerGeometricDetESModule" label=""
2) type="TrackerGeometricDetESModule" label="trackerNumberingGeometry"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
>>> processed 0 events
>>> processed 0 events
Failure using cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-15-1100/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py: status 65
status = 16640

---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS
```

After correcting `testTrackerModuleInfoDDD_cfg.py`, please verify in local tests that there are not any additional similar failures prior to pushing your updates.

2020-10-16 11:12 UTC, mmusich commented
@christopheralanwest 

> After correcting `testTrackerModuleInfoDDD_cfg.py`, please verify in local tests that there are not any additional similar failures prior to pushing your updates.

in order to help @vargasa with the PR, I had a look, by locally merging our commit 32b91ac from #31780 on top of this branch and re-running the unit tests by hand (as this checks out the entire observable universe, in order to speed-up tests, I launch them by hand via
```csh
foreach i ( `ls ./Geometry/TrackerGeometryBuilder/test | grep test` )
    cmsRun $i >& $i.log&
 end
```
): 

The resulting log files are available at `/afs/cern.ch/user/m/musich/public/forAndres/`.
The tests which fail are:
```
$ grep Fatal * | awk -F" " '{print $1}' | sort -n | uniq -c
      4 testTrackerModuleInfoDDD_cfg.py.log:-----
      2 testTrackerModuleInfoFromDDDNoPrintDDD_cfg.py.log:-----

```

This should be resolved by applying the following patch:
```diff 
diff --git a/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py b/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
index cf146b437ce..320c6fa075d 100644
--- a/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
+++ b/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoDDD_cfg.py
@@ -14,6 +14,8 @@ process.TrackerGeometricDetESModule = cms.ESProducer( "TrackerGeometricDetESModu
                                                       fromDDD = cms.bool( True )
                                                      )
 
+process.es_prefer_geomdet = cms.ESPrefer("TrackerGeometricDetESModule","")
+
 process.load("Alignment.CommonAlignmentProducer.FakeAlignmentSource_cfi")
 process.preferFakeAlign = cms.ESPrefer("FakeAlignmentSource") 
 
diff --git a/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoFromDDDNoPrintDDD_cfg.py b/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoFromDDDNoPrintDDD_cfg.py
index 5276ccd84aa..74d71bd5195 100644
--- a/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoFromDDDNoPrintDDD_cfg.py
+++ b/Geometry/TrackerGeometryBuilder/test/python/testTrackerModuleInfoFromDDDNoPrintDDD_cfg.py
@@ -10,6 +10,7 @@ process.source = cms.Source("EmptySource")
 process.TrackerGeometricDetESModule = cms.ESProducer( "TrackerGeometricDetESModule",
                                                       fromDDD = cms.bool( True )
                                                      )
+process.es_prefer_geomdet = cms.ESPrefer("TrackerGeometricDetESModule","")
 
 process.load("Alignment.CommonAlignmentProducer.FakeAlignmentSource_cfi")
 process.preferFakeAlign = cms.ESPrefer("FakeAlignmentSource") 

```

2020-10-16 13:32 UTC, vargasa commented
Hi @mmusich. Great! Thanks! I'll apply the patch, rerun the tests locally and update the PR

2020-10-16 13:41 UTC, cmsbuild commented
The code-checks are being triggered in jenkins.

2020-10-16 13:44 UTC, vargasa commented
When running locally `cmsRun testTrackerModuleInfoDB_cfg.py` I get 

```                                                                                                                      
----- Begin Fatal Exception 16-Oct-2020 08:38:53 CDT-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
   [2] While attempting to load plugin PGeometricDetExtraRcd@NewProxy
Exception Message:
unable to load /uscms_data/d3/nsf/grt82kjasoa/CMSSW_11_2_X_2020-10-09-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so because /uscms_data/d3/
nsf/grt82kjasoa/CMSSW_11_2_X_2020-10-09-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so: cannot open shared object file: No such file or dire
ctory
----- End Fatal Exception -------------------------------------------------
```
But I didn't merge #31780 so I guess that's expected

2020-10-16 13:48 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31729/19128

- This PR adds an extra 120KB to repository

2020-10-16 13:48 UTC, cmsbuild commented
Pull request #31729 was updated. @civanch, @Dr15Jones, @makortel, @cvuosalo, @christopheralanwest, @ianna, @mdhildreth, @cmsbuild, @yuanchao, @tocheng, @tlampen, @ggovi, @pohsun, @kpedro88 can you please check and sign again.

2020-10-16 13:50 UTC, mmusich commented
> But I didn't merge #31780 so I guess that's expected

yes...

2020-10-16 14:15 UTC, christopheralanwest commented
please test

2020-10-16 14:16 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Tested with other pull request(s) cms-sw/cmssw#31780

2020-10-16 17:02 UTC, cmsbuild commented
-1

Tested at: 8f6e93a4ed87a413cee6bf8e211605519b90ccd7

CMSSW: CMSSW_11_2_X_2020-10-15-2300
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/10024/summary.html

I found follow errors while testing this PR

**Failed tests:  UnitTests**

* **Unit Tests**:

I found errors in the following unit tests: 
 
 ---> test UnitTestConcurrentIOVsCondCore had ERRORS

2020-10-16 17:03 UTC, cmsbuild commented
Comparison job queued.

2020-10-16 17:16 UTC, vargasa commented
> I submitted a fix for UnitTestConcurrentIOVsCondCore, #31806

@christopheralanwest #31806 was just merged (thanks @wddgit) that would fix the last unit test

2020-10-16 18:19 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/10024/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 3 differences found in the comparisons
 - DQMHistoTests: Total files compared: 35
 - DQMHistoTests: Total histograms compared: 2543752
 - DQMHistoTests: Total failures: 7
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2543723
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 34 files compared)
 - Checked 149 log files, 22 edm output root files, 35 DQM output files

2020-10-17 17:32 UTC, christopheralanwest commented
please test

to re-run the tests with in an IB with PR #31806 included

2020-10-17 17:32 UTC, cmsbuild commented
The tests are being triggered in jenkins.
Tested with other pull request(s) cms-sw/cmssw#31780

2020-10-17 20:22 UTC, cmsbuild commented
+1
Tested at: 8f6e93a4ed87a413cee6bf8e211605519b90ccd7
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/10049/summary.html
CMSSW: CMSSW_11_2_X_2020-10-17-1100
SCRAM_ARCH: slc7_amd64_gcc820

2020-10-17 20:22 UTC, cmsbuild commented
Comparison job queued.

2020-10-17 21:40 UTC, cmsbuild commented
Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-abcf69/10049/summary.html

Comparison Summary:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 35
 - DQMHistoTests: Total histograms compared: 2543752
 - DQMHistoTests: Total failures: 10
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2543720
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 34 files compared)
 - Checked 149 log files, 22 edm output root files, 35 DQM output files

2020-10-17 22:12 UTC, christopheralanwest commented
Should the "Draft" status of this PR be removed?

2020-10-18 07:41 UTC, ianna commented
+1

2020-10-18 12:38 UTC, silviodonato commented
urgent
I have merged #31780 too early

2020-10-18 17:56 UTC, kpedro88 commented
+upgrade

2020-10-18 17:59 UTC, christopheralanwest commented
+alca

2020-10-19 08:34 UTC, silviodonato commented
Do you have any comments? @ggovi

2020-10-19 15:07 UTC, silviodonato commented
merge
@ggovi I have to merge this PR to fix a failure in a unit test which makes fail all PR tests.
Please let us know if you have any comments/objections on this PR

2020-10-19 15:08 UTC, merged

2020-10-20 08:27 UTC, silviodonato commented
We are getting several errors after having merged this PR 
see https://github.com/cms-sw/cmssw/issues/31869