[DD4hep] Add support for Assembly tags in XML and creating DB payload
cms-sw/cmssw pull request #34344
Opened 2021-07-06 05:15 UTC by cvuosalo

Up to now, our DD4hep code has supported Assemblies being used in algorithms but did not support explicit Assembly definitions in XML. This PR  provides support for Assembly definitions in XML.

Secondly, it also provides support for the tool from PR #34111 for creating the DD4hep ideal geometry description DB payload. This PR is required for #34111 to work.

The new Assembly XML syntax is simple. In the Solids section, Assemblies are defined merely with a name:
```
 <Assembly name="assembly1"/>
```
Then in the Logical Part section, an Assembly is treated like any other Logical Part. Its material should be "Air", but the material is never actually used. The PosPart placement of Assemblies is just like that of other Logical Parts.

#### PR validation:

This PR has been put through the following tests:
* DD4hep simulation reading from XML (wf 11634.911)
* DD4hep simulation reading the ideal geometry description(with Assemblies) from an Sqlite DB (modified wf 11634.911)
* DB payload creation tool (PR 34111) reading the ideal geometry description (stress test, only done for testing purposes)
* Unit tests

No backport will be done.

2021-07-06 05:17 UTC, cvuosalo commented
urgent

2021-07-06 05:18 UTC, cvuosalo commented
This PR is aimed for 12_0_0_pre4.

2021-07-06 05:23 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-34344/23716

- This PR adds an extra 36KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DetectorDescription/DDCMS/data/testLogicalParts.xml  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/data/testPosParts.xml  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/data/testSolids.xml  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/interface/DDDetector.h  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/interface/DDNamespace.h  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/interface/DDParsingContext.h  modified in PR(s): #33548, #34111
  - File  DetectorDescription/DDCMS/interface/DDSolidShapes.h  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/plugins/DDDetectorESProducer.cc  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc  modified in PR(s): #33548, #34111, #34212
  - File  DetectorDescription/DDCMS/src/DDDetector.cc  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/src/DDFilteredView.cc  modified in PR(s): #34212
  - File  DetectorDescription/DDCMS/src/DDNamespace.cc  modified in PR(s): #34111
  - File  DetectorDescription/DDCMS/test/DDSolidLegacyShapes.cppunit.cc  modified in PR(s): #34111

2021-07-06 05:24 UTC, cmsbuild commented
A new Pull Request was created by  @cvuosalo (Carl Vuosalo) for master.

It involves the following packages:

DetectorDescription/DDCMS


@civanch, @Dr15Jones, @makortel, @cvuosalo, @ianna, @mdhildreth, @cmsbuild can you please review it and eventually sign? Thanks.
@fabiocos, @slomeo, @vargasa this is something you requested to watch as well.
@silviodonato, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2021-07-06 05:25 UTC, cvuosalo commented
@cmsbuild please test

2021-07-06 08:48 UTC, cmsbuild commented
-1

**Failed Tests**: UnitTests 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-417079/16480/summary.html
**COMMIT**: 1e620ab431134ebc5c1666cc47e837b2ae37ba2d
**CMSSW**: CMSSW_12_0_X_2021-07-05-1100/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/34344/16480/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Unit Tests

I found errors in the following unit tests:

<pre>---> test test_PixelBaryCentreTool had ERRORS
</pre>

## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 38
 - DQMHistoTests: Total histograms compared: 2785924
 - DQMHistoTests: Total failures: 1
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2785901
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 37 files compared)
 - Checked 160 log files, 37 edm output root files, 38 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-05-1100+417079/43846/triggerResults): no differences found

2021-07-06 11:44 UTC, civanch commented
Failed unit test related to Run-2 not to Run-3, it should be unchanged I guess.

2021-07-06 12:04 UTC, qliphy commented
The unit failure is already in IB and reported by #34223
It is related to #33583 and being fixed.  Thus it is not related to this PR.
See also https://github.com/cms-sw/cmssw/pull/34259#issuecomment-871443024

2021-07-06 14:18 UTC, civanch commented
+1

2021-07-06 14:19 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (but tests are reportedly failing). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo, @qliphy (and backports should be raised in the release meeting by the corresponding L2)

2021-07-06 14:33 UTC, ianna requested changes
@cvuosalo - Firstly, `DDParsingContext` is a context of an XML parser, it must not be exposed in `DDDetector`. Secondly, dd4hep can handle placing assemblies. Assembly is a shapeless solid. Please, simplify the implementation. Thanks.

2021-07-06 14:33 UTC, ianna commented on DetectorDescription/DDCMS/interface/DDDetector.h
> +    DDParsingContext* m_context;
@cvuosalo - `DDDetector` should not have `DDParsingContext`. The `DDParsingContext` is created for a `DDDetector`:
```c++
cms::DDParsingContext context(det);
```

2021-07-06 14:33 UTC, ianna commented on DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
> +    placeAssembly(parentPtr, parentName, childPtr, childName, copy, transform, ns);
@cvuosalo - please, let dd4hep place it:
https://cmssdt.cern.ch/lxr/source/Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc#0976

2021-07-06 14:33 UTC, ianna commented on DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
> +  ns.addSolid(nam, Box(nam, 1, 1, 1));  // Add a dummy solid to allow assembly to be treated like other volumes
@cvuosalo - you only need to add a name to the namespace. Please, see the Ecal algorithm. Then, there is no need for extra code to handle the assemblies. dd4hep will do it for you.

2021-07-06 14:33 UTC, ianna commented on DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc
> +    // crash when IsAssembly() method is called on them.
@cvuosalo - no need to check if it is an assembly as long as you let dd4hep handle it.

2021-07-06 14:33 UTC, ianna commented
-1

2021-07-06 17:40 UTC, civanch commented
@cvuosalo , @ianna , is it possible to merge this PR just now, create an issue and improve the code in the next PR? We need it for tomorrow morning.

2021-07-06 17:49 UTC, cvuosalo commented
Issue #34367 created to document and track concerns raised by @ianna. These concerns will be addressed on a high priority basis in one or more upcoming PRs.

2021-07-07 07:09 UTC, civanch commented
+1

let us merge this for pre4, the code will be improved in the next PR after pre4.

2021-07-07 07:10 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (but tests are reportedly failing). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo, @qliphy (and backports should be raised in the release meeting by the corresponding L2)

2021-07-07 07:14 UTC, ianna commented
> +1
> 
> let us merge this for pre4, the code will be improved in the next PR after pre4.

@civanch - I do not see why we have to rush this in and lower our standards.

2021-07-07 07:23 UTC, civanch commented
If this PR will not be merged for pre4 then validation campaign cannot be proposed and will be shifted to the last opened pre-release.

2021-07-07 07:26 UTC, ianna commented
> If this PR will not be merged for pre4 then validation campaign cannot be proposed and will be shifted to the last opened pre-release.

IMHO, it is better to validate a final solution than a temporary work-around.

2021-07-07 07:32 UTC, civanch commented
@ianna ,  I agree but using work around we may earlier face other problem which today is hidden.

2021-07-07 07:45 UTC, ianna commented
> @ianna , I agree but using work around we may earlier face other problem which today is hidden.

We will also face new issues introduced with this work-around that it there to stay - @cvuosalo [argues](https://github.com/cms-sw/cmssw/pull/34111#discussion_r664738554) that this is the solution. I respectfully disagree with that statement. The goal of migrating to DD4hep to improve our code is being compromised.

2021-07-07 08:01 UTC, cvuosalo commented
@ianna @civanch "@cvuosalo argues that this is the solution. " No, I think improvement and revision is likely.
I favor an incremental approach. It is useful to get a software project up and running and then improve from there.

2021-07-07 09:48 UTC, ianna commented
> @ianna @civanch "@cvuosalo argues that this is the solution. " No, I think improvement and revision is likely.
> I favor an incremental approach. It is useful to get a software project up and running and then improve from there.

@cvuosalo - an incremental approach emphasises the virtue of taking small steps toward the goal. At each increment, the key phases of the software development life cycle, including functional specification, design, implementation, and testing, are reiterated. Even though "an incremental approach" sounds good, this PR ain't it.

2021-07-08 11:31 UTC, cvuosalo commented
@cmsbuild please test

2021-07-08 11:35 UTC, cvuosalo commented
The unit test that failed was not related to this PR. It was fixed in #34369. I started the tests again, just to clear the "test-rejected" marker. The first tests already gave a good result for the changes in this PR.

2021-07-08 14:52 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-417079/16598/summary.html
**COMMIT**: 1e620ab431134ebc5c1666cc47e837b2ae37ba2d
**CMSSW**: CMSSW_12_0_X_2021-07-07-2300/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/34344/16598/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 5163 differences found in the comparisons
 - DQMHistoTests: Total files compared: 38
 - DQMHistoTests: Total histograms compared: 2786260
 - DQMHistoTests: Total failures: 7
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2786231
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 37 files compared)
 - Checked 160 log files, 37 edm output root files, 38 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-07-2300+417079/43919/triggerResults): no differences found

2021-07-08 17:38 UTC, silviodonato commented
+1
about the comparison, please note that the previous PR tests (https://github.com/cms-sw/cmssw/pull/34344#issuecomment-874579904) were ok. Both of them are based on the same commit https://github.com/cms-sw/cmssw/commit/1e620ab431134ebc5c1666cc47e837b2ae37ba2d 
Moreover about

> Reco comparison results: 5163 differences found in the comparisons

these are fake failures which appeared already in other PRs and Slava has proposed a fix right now #34409.

2021-07-08 17:38 UTC, merged