Run3-alca189 Add a few Hcal related AlCaReco streams to HLTPhysics
cms-sw/cmssw pull request #34628
Opened 2021-07-26 16:33 UTC by bsunanda

#### PR description:

Add a few Hcal related AlCaReco streams to HLTPhysics

#### PR validation:

Tested with some old datasets

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

2021-07-26 16:42 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-34628/24214

- This PR adds an extra 20KB to repository

2021-07-26 16:42 UTC, cmsbuild commented
A new Pull Request was created by  @bsunanda (Sunanda Banerjee) for master.

It involves the following packages:

- Calibration/HcalAlCaRecoProducers (**alca**)
- Calibration/HcalCalibAlgos (**alca**)
- Configuration/AlCa (**alca**)


@malbouis, @yuanchao, @cmsbuild, @tlampen, @pohsun, @francescobrivio, @tvami can you please review it and eventually sign? Thanks.
@makortel, @Martin-Grunewald, @mmusich, @fabiocos, @tocheng this is something you requested to watch as well.
@silviodonato, @dpiparo, @qliphy, @perrotta you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2021-07-26 16:46 UTC, bsunanda commented
@cmsbuild Please test

2021-07-26 17:05 UTC, tvami requested changes
Just some cosmetic changes

2021-07-26 17:05 UTC, tvami commented on Calibration/HcalCalibAlgos/test/python/isoTrackRecoAnalysis_cfg.py
> +#auto:run3_mc
Please remove commented out line

2021-07-26 17:05 UTC, tvami commented on Calibration/HcalCalibAlgos/test/python/isoTrackRecoAnalysis_cfg.py
> +        #'root://xrootd.ba.infn.it///store/data/Run2017E/JetHT/ALCARECO/HcalCalIsoTrkFilter-09Aug2019_UL2017-v1/50000/FF19B3B8-39D3-D941-8162-1AA7FB482D48.root'
If you are already touching this file for cosmetic purposes, would you mind removing these lines too? Or explain why they might be needed?

2021-07-26 17:08 UTC, tvami commented
Hi @bsunanda , may I ask what the "Run3-alca189" refers to in the title of the PR? Also for the validation part, do you maybe have a presentation to refer to? I assume "Nothing special" means there is no need for a backport. Thanks!

2021-07-26 17:21 UTC, bsunanda commented
@cmsbuild Please test

2021-07-26 17:26 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-34628/24215

- This PR adds an extra 20KB to repository

2021-07-26 17:26 UTC, cmsbuild commented
Pull request #34628 was updated. @malbouis, @yuanchao, @tlampen, @pohsun, @francescobrivio, @tvami can you please check and sign again.

2021-07-26 22:11 UTC, cmsbuild commented
-1

**Failed Tests**: RelVals-INPUT 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/summary.html
**COMMIT**: 1715b64c3056d1e3ab9482d260f1e31524ecd67d
**CMSSW**: CMSSW_12_0_X_2021-07-26-1100/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/34628/17212/install.sh` to create a dev area with all the needed externals and cmssw changes.


## RelVals-INPUT

- [11634.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)```11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log```
- [11601.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11601.0_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)```11601.0_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log```
- [11602.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11602.0_SingleElectronPt35+2021+SingleElectronPt35_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)```11602.0_SingleElectronPt35+2021+SingleElectronPt35_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_SingleElectronPt35+2021+SingleElectronPt35_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log```
<details>
<summary>Expand to see more relval errors ...</summary>

- [11603.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11603.0_SingleElectronPt1000+2021+SingleElectronPt1000_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11604.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11604.0_SingleGammaPt10+2021+SingleGammaPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11605.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11605.0_SingleGammaPt35+2021+SingleGammaPt35_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11607.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11607.0_SingleMuPt10+2021+SingleMuPt10_Eta2p85_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11606.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11606.0_SingleMuPt1+2021+SingleMuPt1_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11608.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11608.0_SingleMuPt100+2021+SingleMuPt100_Eta2p85_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11609.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11609.0_SingleMuPt1000+2021+SingleMuPt1000_Eta2p85_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11630.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11630.0_QCD_Pt_3000_3500_14TeV+2021+QCD_Pt_3000_3500_14TeV_TuneCUETP8M1_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11634.1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.1_TTbar_14TeV+2021_trackingOnly+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.24](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.24_TTbar_14TeV+2021_0T+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11634.5](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.5_TTbar_14TeV+2021_pixelTrackingOnly+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.501](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.501_TTbar_14TeV+2021_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.505](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.505_TTbar_14TeV+2021_Patatrack_PixelOnlyTripletsCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11723.17](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11723.17_QCD_Pt_1800_2400_14+2021_seedingDeepCore+QCD_Pt_1800_2400_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.511](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.511_TTbar_14TeV+2021_Patatrack_ECALOnlyCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.521](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.521_TTbar_14TeV+2021_Patatrack_HCALOnlyCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.7](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.7_TTbar_14TeV+2021_trackingMkFit+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11634.91](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11634.91_TTbar_14TeV+2021_trackdnn+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11640.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11640.0_MinBias_14TeV+2021+MinBias_14TeV_pythia8_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11643.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11643.0_QCD_FlatPt_15_3000HS_14+2021+QCDForPF_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11646.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11646.0_ZEE_14+2021+ZEE_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11650.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11650.0_ZMM_14+2021+ZMM_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11650.501](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11650.501_ZMM_14+2021_Patatrack_PixelOnlyCPU+ZMM_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11650.505](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11650.505_ZMM_14+2021_Patatrack_PixelOnlyTripletsCPU+ZMM_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST)
- [11725.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11725.0_GluGluTo2Jets_14TeV+2021+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSimINPUT+Digi+Reco+HARVEST+ALCA)
- [11834.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11834.0_TTbar_14TeV+2021PU+TTbar_14TeV_TuneCP5_GenSimINPUT+DigiPU+RecoPU+HARVESTPU+Nano)
- [11834.13](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11834.13_TTbar_14TeV+2021PU_mlpf+TTbar_14TeV_TuneCP5_GenSimINPUT+DigiPU+RecoPU+HARVESTPU+Nano)
- [11834.24](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11834.24_TTbar_14TeV+2021PU_0T+TTbar_14TeV_TuneCP5_GenSimINPUT+DigiPU+RecoPU+HARVESTPU+Nano)
- [11846.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17212/runTheMatrixINPUT-results/11846.0_ZEE_14+2021PU+ZEE_14TeV_TuneCP5_GenS [...]

2021-07-26 22:30 UTC, bsunanda commented
@cmsbuild Please test

2021-07-27 04:43 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8b0c50/17222/summary.html
**COMMIT**: 1715b64c3056d1e3ab9482d260f1e31524ecd67d
**CMSSW**: CMSSW_12_0_X_2021-07-26-1100/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/34628/17222/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 8 differences found in the comparisons
 - DQMHistoTests: Total files compared: 39
 - DQMHistoTests: Total histograms compared: 2998564
 - DQMHistoTests: Total failures: 12
 - DQMHistoTests: Total nulls: 1
 - DQMHistoTests: Total successes: 2998529
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.004 KiB( 38 files compared)
 - DQMHistoSizes: changed ( 312.0 ): 0.004 KiB        MessageLogger/Warnings
 - Checked 165 log files, 37 edm output root files, 39 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-26-1100+8b0c50/44370/triggerResults): found differences in 1 / 38 workflows

2021-07-27 15:19 UTC, srimanob commented
Urgent

2021-07-27 15:24 UTC, tvami commented
> Hi @bsunanda , may I ask what the "Run3-alca189" refers to in the title of the PR? Also for the validation part, do you maybe have a presentation to refer to? I assume "Nothing special" means there is no need for a backport. Thanks!

Hi @bsunanda I can sign this after you do these changes, thanks!

2021-07-27 15:35 UTC, mmusich commented
> Urgent
out of curiosity, why is this urgent?
The real AlCaMatrix is driven by Tier-0 configuration, this just updates tests.

2021-07-27 16:28 UTC, bsunanda commented
@tvami Made the required changes

2021-07-27 16:33 UTC, tvami commented
+alca

2021-07-27 16:33 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @silviodonato, @dpiparo, @qliphy, @perrotta (and backports should be raised in the release meeting by the corresponding L2)

2021-07-27 16:35 UTC, bsunanda commented
It also changes behavior of the filters.
________________________________
From: Marco Musich ***@***.***
Sent: 27 July 2021 17:35
To: cms-sw/cmssw
Cc: Sunanda Banerjee; Mention
Subject: Re: [cms-sw/cmssw] Run3-alca189 Add a few Hcal related AlCaReco streams to HLTPhysics (#34628)


Urgent

out of curiosity, why is this urgent?
The real AlCaMatrix is driven by Tier-0 configuration, this just updates tests.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/cms-sw/cmssw/pull/34628#issuecomment-887616228>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABGMZOTZI5PDG3LMATOKM23TZ3G5PANCNFSM5BAOUXRA>.

2021-07-27 16:49 UTC, qliphy commented
+1

2021-07-27 16:49 UTC, merged