Remove boost lexical_cast dependency in EventFilter
cms-sw/cmssw pull request #35168
Opened 2021-09-06 15:00 UTC by Purva-Chaudhari

#### PR description:

Remove boost lexical cast dependency in EventFilter with corresponding stl alternatives.

#### PR validation:

Passed runtests

#### if this PR is a backport:

@davidlange6 @vgvassilev

2021-09-06 15:05 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35168/25096

- This PR adds an extra 48KB to repository

2021-09-06 15:06 UTC, cmsbuild commented
A new Pull Request was created by  @Purva-Chaudhari  for master.

It involves the following packages:

- EventFilter/L1TRawToDigi (**l1**)
- EventFilter/Utilities (**daq, reconstruction**)


@emeschi, @smorovic, @cmsbuild, @rekovic, @slava77, @jpata, @cecilecaillol can you please review it and eventually sign? Thanks.
@dinyar, @Martin-Grunewald, @thomreis this is something you requested to watch as well.
@perrotta, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2021-09-06 16:02 UTC, smorovic requested changes

2021-09-06 16:27 UTC, Purva-Chaudhari commented on EventFilter/Utilities/src/EvFDaqDirector.cc
> +    } catch (const std::exception& e) {
Oh alright thanks, I will fix it

2021-09-06 16:27 UTC, Purva-Chaudhari commented on EventFilter/Utilities/src/EvFDaqDirector.cc
> +    } catch (const std::out_of_range&) {
Yes, adding it

2021-09-06 17:12 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35168/25098

- This PR adds an extra 48KB to repository

2021-09-06 17:12 UTC, cmsbuild commented
Pull request #35168 was updated. @emeschi, @smorovic, @cmsbuild, @rekovic, @slava77, @jpata, @cecilecaillol can you please check and sign again.

2021-09-06 17:19 UTC, smorovic commented
+1
thanks

2021-09-06 17:19 UTC, smorovic commented
@cmsbuild please test

2021-09-06 20:23 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-36eb2d/18343/summary.html
**COMMIT**: 97ce6ad107dbbc61dd4049bd4fc6666ded2fe5c1
**CMSSW**: CMSSW_12_1_X_2021-09-05-2300/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/35168/18343/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 39
 - DQMHistoTests: Total histograms compared: 3001001
 - DQMHistoTests: Total failures: 0
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3000979
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 38 files compared)
 - Checked 165 log files, 37 edm output root files, 39 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-05-2300+36eb2d/45250/triggerResults): no differences found

2021-09-09 01:11 UTC, slava77 commented
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35168	97ce6ad 
- the updates in reco category package EventFilter/Utilities (shared with DAQ) do not touch reco-related files

2021-09-13 01:19 UTC, qliphy commented
merge
@cms-sw/l1-l2  This is a technical PR. Let's know if you have any concern.

2021-09-13 01:19 UTC, merged