AJJGenJet filter added.
cms-sw/cmssw pull request #35547
Opened 2021-10-05 23:04 UTC by hbakhshi

#### PR description:
A new filter added to the GeneratorInterface/GenFilters package. It is specially designed to select events with 1 photon + 2VBF jets. cuts on photon and jet are completely configurable.

#### PR validation:

the filter tested on run-2 and snowmass gridpacks and fragments. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

this filter is going to be used to generate vbf+photon samples for run2 and snowmass analyses

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

2021-10-05 23:04 UTC, cmsbuild commented
@hbakhshi, CMSSW_12_1_X branch is closed for direct updates. cms-bot is going to move this PR to master branch.
In future, please use cmssw master branch to submit your changes.

2021-10-05 23:10 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25777

- This PR adds an extra 20KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25777/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25777/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2021-10-05 23:40 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25779

- This PR adds an extra 20KB to repository

2021-10-05 23:40 UTC, cmsbuild commented
A new Pull Request was created by  @hbakhshi (Hamed Bakhshian) for master.

It involves the following packages:

- GeneratorInterface/GenFilters (**generators**)


@SiewYan, @mkirsano, @Saptaparna, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez can you please review it and eventually sign? Thanks.
@alberto-sanchez, @mkirsano this is something you requested to watch as well.
@perrotta, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2021-10-06 02:28 UTC, Dr15Jones requested changes

2021-10-06 02:28 UTC, Dr15Jones commented on GeneratorInterface/GenFilters/plugins/AJJGenJetFilter.h
> +class AJJGenJetFilter : public edm::EDFilter {
Please use a thread friendly base class.

2021-10-06 09:48 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25787

- This PR adds an extra 20KB to repository

- Found files with invalid states:
  - GeneratorInterface/GenFilters/plugins/AJJGenJetFilter.h:
    - Added: a99b0a930e7b604a77571ee9ceb025f9ea3deb53
    - Modified: 09b7d9ea6394ebf25b6a2616c45befaa2a948847
    - Deleted: ec83a8cf31755fa4817589eaa06fcaec42197ebe

2021-10-06 09:48 UTC, cmsbuild commented
Pull request #35547 was updated. @SiewYan, @mkirsano, @Saptaparna, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez can you please check and sign again.

2021-10-06 23:42 UTC, cmsbuild commented
Pull request #35547 was updated. @SiewYan, @mkirsano, @Saptaparna, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez can you please check and sign again.

2021-10-08 10:29 UTC, hbakhshi commented
Should I do something special for the test? I have already tested it with my gridpacks and it works.

2021-10-09 15:56 UTC, Dr15Jones commented
@cmsbuild please test

2021-10-09 15:56 UTC, Saptaparna commented
@hbakhshi let's wait to hear from @SiewYan and @Dr15Jones. @SiewYan since this a VBF filter, should we test a VBF-like workflow?

2021-10-09 19:10 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fd1cc7/19524/summary.html
**COMMIT**: ff34c1aec5027a39820759e971a456ed8f13b1ff
**CMSSW**: CMSSW_12_1_X_2021-10-09-1100/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/35547/19524/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 40
 - DQMHistoTests: Total histograms compared: 2798082
 - DQMHistoTests: Total failures: 6
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 2798054
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 39 files compared)
 - Checked 169 log files, 37 edm output root files, 40 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-09-1100+fd1cc7/46073/triggerResults): no differences found

2021-10-11 14:16 UTC, hbakhshi commented
@SiewYan @Saptaparna thanks a lot for triggering the test. what should I expect now? passing the tests, can it be considered as merged?

2021-10-11 14:31 UTC, Dr15Jones requested changes

2021-10-11 21:23 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25882

- This PR adds an extra 20KB to repository

- Found files with invalid states:
  - GeneratorInterface/GenFilters/plugins/AJJGenJetFilter.h:
    - Added: a99b0a930e7b604a77571ee9ceb025f9ea3deb53
    - Modified: 09b7d9ea6394ebf25b6a2616c45befaa2a948847
    - Deleted: ec83a8cf31755fa4817589eaa06fcaec42197ebe

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25882/code-format.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25882/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2021-10-11 21:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35547/25883

- This PR adds an extra 24KB to repository

- Found files with invalid states:
  - GeneratorInterface/GenFilters/plugins/AJJGenJetFilter.h:
    - Added: a99b0a930e7b604a77571ee9ceb025f9ea3deb53
    - Modified: 09b7d9ea6394ebf25b6a2616c45befaa2a948847
    - Deleted: ec83a8cf31755fa4817589eaa06fcaec42197ebe

2021-10-11 21:45 UTC, cmsbuild commented
Pull request #35547 was updated. @SiewYan, @mkirsano, @Saptaparna, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez can you please check and sign again.

2021-10-13 02:17 UTC, SiewYan commented
please test workflow 552,554

2021-10-13 05:30 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fd1cc7/19577/summary.html
**COMMIT**: 4a7e485b26f075f1943cfc041f4688c76772ed43
**CMSSW**: CMSSW_12_1_X_2021-10-12-2300/slc7_amd64_gcc900
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/35547/19577/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-fd1cc7/552.0_VHToHtt_NLO_Pow_13TeV_py8+VHToH_Pow_LHE_13TeV+Hadronizer_TuneCP5_13TeV_Htt_powhegEmissionVeto_pythia8+HARVESTGEN2
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-fd1cc7/554.0_VBFToH4l_NLO_Pow_JHU_13TeV_py8+VBFToH_Pow_JHU4l_LHE_13TeV+Hadronizer_TuneCP5_13TeV_powhegEmissionVeto_pythia8+HARVESTGEN2

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 6 differences found in the comparisons
 - DQMHistoTests: Total files compared: 40
 - DQMHistoTests: Total histograms compared: 2798082
 - DQMHistoTests: Total failures: 11
 - DQMHistoTests: Total nulls: 1
 - DQMHistoTests: Total successes: 2798048
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.004 KiB( 39 files compared)
 - DQMHistoSizes: changed ( 312.0 ): 0.004 KiB        MessageLogger/Warnings
 - Checked 169 log files, 37 edm output root files, 40 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-12-2300+fd1cc7/46124/triggerResults): no differences found

2021-10-14 03:33 UTC, SiewYan commented
Hello @hbakhshi , The three workflows used for the test are GGToHgg_NLO_Pow_13TeV_py8 (514), VHToHtt_NLO_Pow_13TeV_py8 (552) and VBFToH4l_NLO_Pow_JHU_13TeV_py8 (554), they are defined in [1]. For all intents and purposes, these tests (VBF-like) are suffice to understand if those added filters compiled and worked, and they compiled and successful.

Unfortunately the baseline comparison is not available (due to missing matrix map), otherwise we may look at the set of DQM plots.

I suggest to approve this PR, @Saptaparna @GurpreetSinghChahal , what do you think?

[1] https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_extendedgen.py#L34-L36

2021-10-17 15:27 UTC, Saptaparna commented
It looks good. Just one question:
```
minEta = cms.untracked.double( -4.5 ),
maxEta = cms.untracked.double( 4.5 ),
```
Why not extend it to 5.0?

2021-10-17 15:50 UTC, hbakhshi commented
Looking into some delphes files for HL-LHC, I guessed the CMS endcap goes up to 4.5 
If I am wrong and it extends to 5, I will change it. Please let me know.

2021-10-19 08:00 UTC, hbakhshi commented
It seems that all the tests have passed again. I would appreciate if you could accept this PR, so I can proceed with the sample request. @Saptaparna

2021-10-25 13:29 UTC, merged