Cuda time measurements
cms-sw/cmssw pull request #37141
Opened 2022-03-04 11:18 UTC by AliinCern

#### What is the purpose of the program?

A device (GPU) in a local machine can read/write host (CPU) memory in different methods by using Cuda API. In this program, we measured these methods in a local machine in order to find the best approachable to memory with respect to time. The program has four directions in time measurements:

1. From Host To Device.
2. On the Device.
3. On the Host.
4. From Device to Host.

#### What methods are used in the Program?

> With respect of First Direction Measurement:
Part 0) The Device reads from Host memory directly without using Cuda API.
Part 1) Measuring time to copy data from Host memory to Device memory using (cudaMemcpy).
Part 2) Measuring time to lock Host pages for Device to read/write data using (cudaHostRegister).
Part 3) Measuring time to copy from Host memory to Host page-lock using (cudaMemcpy).
Part 4) Measuring time to copy from Host memory to Host page-lock using (memcpy), then Measuring time to copy from Host 
page-lock to Device memory using (cudaMemcpy).
Part 5) Measuring time to lock Host pages using (cudaHostRegister) and Measuring time to copy from Host page-lock to Device memory using (cudaMemcpy). 

> With respect of Second Direction Measurement:
All Parts) Measuring time operations that are done on the Device using (cudaEventRecord).

> With respect of Third Direction Measurement:
All Parts) Measuring time operations that are done on the Device using Host time elapse.

> With respect of Fourth Direction Measurement:
Part 0) The Device writes on Host memory directly without using Cuda API.
Part 1) Measuring time to copy data from Device memory to Host memory using (cudaMemcpy).
Part 2) Measuring time to unlock Host pages using (cudaHostUnregister).
Part 3) Measuring time to copy from Host page-lock to Host memory using (cudaMemcpy).
Part 4) Measuring time to copy from Device memory to Host page-lock using (cudaMemcpy), then Measuring time to copy from Host page-lock to Host memory using (memcpy).
Part 5) Measuring time to copy from Device memory to Host page-lock using (cudaMemcpy), then unlock Host pages using (cudaHostUnregister).

#### What are the command line Options to run the Program?
  -p PARTS     select which parts (methods) to run, for example -p 12345 will run all methods. Please note that to run Part 0, use 
                      number 6 for example -p 6
  -a COUNT   repeat each set of tasks COUNT times, and compute the average.
  -f                 to save the result to a file.
 
  -q                print the standard deviation of the measurements.
  -t TASKS      repeat the task on the device/gpu TASKS times.

#### Program Validation:
we ran the program using **_scram b runtests_**, and the result is this:
---> test cudaTimeMeasurement succeeded
TestTime:1
^^^^ End Test cudaTimeMeasurement ^^^^

2022-03-04 11:24 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37141/28677

- This PR adds an extra 24KB to repository

- Found files with invalid states:
  - HeterogeneousCore/CUDACore/test/cuda_check.h:
    - Added: 66965c1809185665e2e68553c3ada858855c54bb
    - Deleted: d9810c4465f1f05005403b380097a4676ed882c9

2022-03-04 11:24 UTC, cmsbuild commented
A new Pull Request was created by  @AliinCern (Marafi) for master.

It involves the following packages:

- HeterogeneousCore/CUDACore (**heterogeneous**)


@cmsbuild, @makortel, @fwyzard can you please review it and eventually sign? Thanks.
@makortel, @rovere this is something you requested to watch as well.
@perrotta, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2022-03-04 11:25 UTC, fwyzard commented
enable gpu

2022-03-04 11:25 UTC, fwyzard commented
@cmsbuild, please test

2022-03-04 12:49 UTC, cmsbuild commented
-1

**Failed Tests**: UnitTests RelVals RelVals-GPU RelVals-INPUT AddOn 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22833/summary.html
**COMMIT**: d9810c4465f1f05005403b380097a4676ed882c9
**CMSSW**: CMSSW_12_3_X_2022-03-03-2300/slc7_amd64_gcc10
**Additional Tests**: GPU
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Unit Tests

I found errors in the following unit tests:

<pre>---> test cudaTimeMeasurement had ERRORS
</pre>

## RelVals

- [4.22](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22833/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC)
```
----- Begin Fatal Exception 04-Mar-2022 12:46:30 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_RAW2DIGI_L1Reco_RECO_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoEgamma/PhotonIdentification/data/beamHaloTaggerID/xgboostToTMVA_BHtagger.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC


At:
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(840): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(925): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(918): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Config.py(1143): _insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Config.py(1399): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
- [5.1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22833/runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS)
```
----- Begin Fatal Exception 04-Mar-2022 12:46:51 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named TTbar_8TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_VALIDATION_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoEgamma/PhotonIdentification/data/beamHaloTaggerID/xgboostToTMVA_BHtagger.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS


At:
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(840): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(925): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(918): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Config.py(1143): _insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Config.py(1399): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
- [135.4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22833/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS)
```
----- Begin Fatal Exception 04-Mar-2022 12:46:55 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ZEE_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_VALIDATION_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoEgamma/PhotonIdentification/data/beamHaloTaggerID/xgboostToTMVA_BHtagger.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22833/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/poison:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/external/slc7_amd64_gcc10/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS


At:
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(840): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(925): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Types.py(918): insertInto
  /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_X_2022-03-03-2300/python/FWCore/ParameterSet/Co [...]

2022-03-04 12:54 UTC, fwyzard requested changes
The new test can only work if the machine has a GPU...
@AliinCern could you add `cms::cudatest::requireDevices();` at the beginning of the `main()` functions ?

2022-03-04 12:54 UTC, fwyzard commented on HeterogeneousCore/CUDACore/test/cudaTimeMeasurement.cu
> +int main(int argc, char *argv[]) {
```suggestion
int main(int argc, char *argv[]) {
  cms::cudatest::requireDevices();
  
```

2022-03-04 13:21 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37141/28680

- This PR adds an extra 24KB to repository

- Found files with invalid states:
  - HeterogeneousCore/CUDACore/test/cuda_check.h:
    - Added: 66965c1809185665e2e68553c3ada858855c54bb
    - Deleted: d9810c4465f1f05005403b380097a4676ed882c9

2022-03-04 13:21 UTC, cmsbuild commented
Pull request #37141 was updated. @cmsbuild, @makortel, @fwyzard can you please check and sign again.

2022-03-04 14:00 UTC, fwyzard commented
enable gpu

2022-03-04 14:00 UTC, fwyzard commented
@cmsbuild, please test

2022-03-04 15:06 UTC, cmsbuild commented
-1

**Failed Tests**:   Build 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22843/summary.html
**COMMIT**: b5c70108f812b58eb79808e3d55eb21f45bf0547
**CMSSW**: CMSSW_12_3_X_2022-03-04-0800/slc7_amd64_gcc10
**Additional Tests**: GPU
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22843/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Build

I found compilation error when building: 

<pre>>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-03-04-0800/src/HeterogeneousCore/CUDACore/test/cudaTimeMeasurement.cu
>> Cuda Device Link tmp/slc7_amd64_gcc10/src/HeterogeneousCore/CUDACore/test/cudaTimeMeasurement/cudaTimeMeasurement_cudadlink.o 
>> Building binary cudaTimeMeasurement
/cvmfs/cms-ib.cern.ch/nweek-02722/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/HeterogeneousCore/CUDACore/test/cudaTimeMeasurement/cudaTimeMeasurement.cu.o: in function `main':
tmpxft_00001f0e_00000000-6_cudaTimeMeasurement.compute_75.cudafe1.cpp:(.text.startup+0x4f): undefined reference to `cms::cudatest::requireDevices()'
collect2: error: ld returned 1 exit status
>> Deleted: tmp/slc7_amd64_gcc10/src/HeterogeneousCore/CUDACore/test/cudaTimeMeasurement/cudaTimeMeasurement
gmake: *** [tmp/slc7_amd64_gcc10/src/HeterogeneousCore/CUDACore/test/cudaTimeMeasurement/cudaTimeMeasurement] Error 1
>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-03-04-0800/src/HeterogeneousCore/CUDACore/test/test_ProcessAcceleratorCUDA.cc
>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-03-04-0800/src/HeterogeneousCore/CUDACore/test/test_ScopedContext.cc
>> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-03-04-0800/src/HeterogeneousCore/CUDACore/test/test_main.cc
</pre>

2022-03-04 15:42 UTC, fwyzard commented on HeterogeneousCore/CUDACore/test/BuildFile.xml
> +    <use name="cuda"/>
My bad, I forgot that you need to add here:
```xml
    <use name="HeterogeneousCore/CUDAUtilities"/>
```

2022-03-05 21:28 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37141/28696

- This PR adds an extra 12KB to repository

- Found files with invalid states:
  - HeterogeneousCore/CUDACore/test/cuda_check.h:
    - Added: 66965c1809185665e2e68553c3ada858855c54bb
    - Deleted: d9810c4465f1f05005403b380097a4676ed882c9

2022-03-05 21:29 UTC, cmsbuild commented
Pull request #37141 was updated. @cmsbuild, @makortel, @fwyzard can you please check and sign again.

2022-03-05 21:29 UTC, fwyzard commented
enable gpu

2022-03-05 21:29 UTC, fwyzard commented
please test

2022-03-06 00:44 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-169591/22876/summary.html
**COMMIT**: 2b0b12428eb8e883317297dca3db2fea1212f3bf
**CMSSW**: CMSSW_12_3_X_2022-03-05-1100/slc7_amd64_gcc10
**Additional Tests**: GPU
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37141/22876/install.sh` to create a dev area with all the needed externals and cmssw changes.


## GPU Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 24 differences found in the comparisons
 - DQMHistoTests: Total files compared: 4
 - DQMHistoTests: Total histograms compared: 19811
 - DQMHistoTests: Total failures: 2414
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 17397
 - DQMHistoTests: Total skipped: 0
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 3 files compared)
 - Checked 12 log files, 9 edm output root files, 4 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_3_X_2022-03-05-1100+169591/48742/triggerResults): no differences found


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 8 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3987741
 - DQMHistoTests: Total failures: 13
 - DQMHistoTests: Total nulls: 1
 - DQMHistoTests: Total successes: 3987705
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.004 KiB( 48 files compared)
 - DQMHistoSizes: changed ( 312.0 ): 0.004 KiB        MessageLogger/Warnings
 - Checked 204 log files, 45 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+169591/48743/triggerResults): no differences found

2022-03-06 07:29 UTC, fwyzard commented
+heterogeneous

2022-03-06 07:30 UTC, fwyzard commented
@smuzaffar is there a way to request running the unit tests on the GPU machine ?

2022-03-06 07:30 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @qliphy (and backports should be raised in the release meeting by the corresponding L2)

2022-03-07 08:37 UTC, smuzaffar commented
> @smuzaffar is there a way to request running the unit tests on the GPU machine ?

No @fwyzard , currently there is no way to requests for unit tests to be run on GPU. As for PR tests, we are not deploying the `cmssw/tmp` directory under `/cvmfs/cms-ci.cern.ch` which means one needs to re-build on GPU machine to run tests. It is on my todo list to add support for unit tests for GPUs but will do when find some time

2022-03-07 16:42 UTC, perrotta commented
+1
- It adds measurement tools in the test area
- Verified working correctly by the author in a private test
- Unit test not actually tested in bot because those unit tests do not run on GPU machines

2022-03-07 16:43 UTC, merged