Added the switch for the inclusion of PS energy
cms-sw/cmssw pull request #37491
Opened 2022-04-07 14:29 UTC by ram1123

#### PR description:

EGamma regression can be trained with and without PS energy taking into consideration. So, we added a switch for this while performing the evaluation in the CMSSW.

#### PR validation:

We run the code with the current version of update and it worked as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

2022-04-07 14:41 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37491/29193

- This PR adds an extra 16KB to repository

2022-04-07 14:43 UTC, cmsbuild commented
A new Pull Request was created by  @ram1123 (Ramkrishna Sharma) for master.

It involves the following packages:

- RecoEcal/EgammaClusterAlgos (**reconstruction**)


@jpata, @cmsbuild, @clacaputo, @slava77 can you please review it and eventually sign? Thanks.
@Sam-Harper, @rchatter, @jainshilpi, @valsdav, @lgray, @sobhatta, @thomreis, @afiqaize, @simonepigazzini, @wrtabb, @argiro, @varuns23 this is something you requested to watch as well.
@perrotta, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2022-04-07 15:10 UTC, thomreis commented on RecoEcal/EgammaClusterAlgos/interface/SCEnergyCorrectorSemiParm.h
> +  regTrainedWithPS_ = iConfig.getParameter<bool>("regTrainedWithPS");
This parameter should be added to the `fillPSetDescription` as well.
Why is it set in this function and not in the constructor itself? It is not needed to set any token.

2022-04-07 15:22 UTC, swagata87 commented
> Hi @ram1123 this is relevant for Run-3 only right? If yes, then I believe it should be under the Run-3 modifier.

Aren't modifiers relevant only for offline reco? 
Ram's PR is specific to HLT supercluster regression.

2022-04-07 16:18 UTC, francescobrivio commented
From private conversation with @swagata87 and EGm experts we understood that this change should go together with update of the EGM conditions in the HLT GT.
Note that the official request to update the GT hasn't come yet (@saumyaphor4252 please do it asap!), so we might need a couple of days. I'll bring this up at the ORP tomorrow. FYI @perrotta @qliphy

2022-04-07 16:20 UTC, francescobrivio commented
urgent

 - with the caveat described in https://github.com/cms-sw/cmssw/pull/37491#issuecomment-1091946705

2022-04-07 17:13 UTC, francescobrivio requested changes
After more discussion with EGM experts and @cms-sw/alca-l2 we came up with a tentative plan:
 - include this PR in the release with `false` flag (since the conditions are not there yet)
 - we cut the 12_3_0 release
 - we (alca) do the FullTrackValidation (where we can change the flag by hand and thus really test the new conditions)
 - we (alca) will do a PR with the new HLT GT and changing the flag to `true`

The only drawback is that 12_3_0 won't have the latest HLT GT, but that can always be added later, and this is a good way to include already in 12_3_0 all the `c++` changes needed.

2022-04-07 17:13 UTC, francescobrivio commented on RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc
> +      regTrainedWithPS_(true),
@ram1123 please change this to `false`. As far as I understood this should restore things to the way they are now.
Once we have the new conditions validate we (@cms-sw/alca-l2) we'll take care of changing it to `true` when we update the GT.

2022-04-07 17:52 UTC, swagata87 commented
@ram1123 somewhere in PR description, please make it clear that this PR is relevant ONLY for HLT supercluster regression, and that it does not effect the offline egamma regression.

2022-04-07 23:18 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37491/29206

- This PR adds an extra 16KB to repository

2022-04-07 23:18 UTC, cmsbuild commented
Pull request #37491 was updated. @jpata, @cmsbuild, @clacaputo, @slava77 can you please check and sign again.

2022-04-08 00:49 UTC, qliphy commented
please test

2022-04-08 05:45 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-63d4f5/23752/summary.html
**COMMIT**: e70ade1da47e0f426b3baecc9e4bc0ad4b366634
**CMSSW**: CMSSW_12_4_X_2022-04-07-2300/slc7_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37491/23752/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3593039
 - DQMHistoTests: Total failures: 2
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3593015
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 47 files compared)
 - Checked 200 log files, 45 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-07-2300+63d4f5/49491/triggerResults): no differences found

2022-04-08 10:24 UTC, clacaputo commented
assign hlt

2022-04-08 10:24 UTC, cmsbuild commented
New categories assigned: hlt

@missirol,@Martin-Grunewald you have been requested to review this Pull request/Issue and eventually sign? Thanks

2022-04-08 10:26 UTC, clacaputo commented
+reconstruction

- PR relevant only for HLT supercluster regression
- boolean set to `false`, see https://github.com/cms-sw/cmssw/pull/37491#pullrequestreview-935418113

2022-04-08 10:38 UTC, missirol commented
+hlt

2022-04-08 10:39 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @qliphy (and backports should be raised in the release meeting by the corresponding L2)

2022-04-08 11:01 UTC, perrotta commented
+1
- A new option added, and the default value does not change previous behaviour

2022-04-08 11:01 UTC, merged