Added the switch for the inclusion of PS energy
cms-sw/cmssw pull request #37494
Opened 2022-04-07 15:35 UTC by ram1123

#### PR description:

EGamma regression can be trained with and without PS energy taking into consideration. So, we added a switch for this while performing the evaluation in the CMSSW.

#### PR validation:

We run the code with the current version of update and it worked as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/37491

We need this update from 12_3_X onwards.

2022-04-07 15:42 UTC, perrotta commented
backport of https://github.com/cms-sw/cmssw/pull/37491

2022-04-07 16:18 UTC, francescobrivio commented
@ram1123 please include "[12_3_X]" in the title of the PR

2022-04-07 16:19 UTC, francescobrivio commented
urgent

 - This is potentially needed for 12_3_0, but it also requires an update to the HLT GT which has not been officially requested yet (see https://github.com/cms-sw/cmssw/pull/37491#issuecomment-1091946705). I'll bring this up at the ORP tomorrow.

2022-04-07 17:15 UTC, francescobrivio requested changes

2022-04-07 17:15 UTC, francescobrivio commented on RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc
> +      regTrainedWithPS_(true),
@ram1123 please change this to `false`, see discussion at https://github.com/cms-sw/cmssw/pull/37491#pullrequestreview-935418113

2022-04-07 23:19 UTC, cmsbuild commented
Pull request #37494 was updated. @jpata, @cmsbuild, @clacaputo, @slava77 can you please check and sign again.

2022-04-08 00:50 UTC, qliphy commented
please test

2022-04-08 05:59 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0e0fc4/23753/summary.html
**COMMIT**: 67edf1031a441724eb10358d4ce43cb605ca80df
**CMSSW**: CMSSW_12_3_X_2022-04-07-2300/slc7_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37494/23753/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 8 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3697381
 - DQMHistoTests: Total failures: 14
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3697345
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 48 files compared)
 - Checked 204 log files, 45 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-04-07-2300+0e0fc4/49492/triggerResults): no differences found

2022-04-08 11:41 UTC, clacaputo commented
+reconstruction

- backport https://github.com/cms-sw/cmssw/pull/37491
- PR relevant only for HLT supercluster regression
- boolean set to false and doesn't change the previous behaviour see https://github.com/cms-sw/cmssw/pull/37491#pullrequestreview-935418113

2022-04-08 11:41 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next CMSSW_12_3_X IBs (tests are also fine) and once validation in the development release cycle CMSSW_12_4_X is complete. This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @qliphy (and backports should be raised in the release meeting by the corresponding L2)

2022-04-08 17:48 UTC, perrotta commented
+1
- The fix is simple, and it is an exact backport of #37491: let have it merged even if the IB tests of the master version haven't been concluded yet

2022-04-08 17:48 UTC, merged