Adding SONIC ParticleNet Producer to CMSSW
cms-sw/cmssw pull request #37964
Opened 2022-05-16 15:51 UTC by wpmccormack

#### PR description:

This PR introduces a producer for ParticleNet using SONIC for co-processor-enabled inferences-as-a-service.  The main versions of ParticleNet are all included (AK4, AK8 general, MassDecorrelation, and MassRegression), as are configs for both ONNX versions and PyTorch versions of the models.  For more information on the status of SONIC, please refer to this presentation to JetMET DPG: https://indico.cern.ch/event/1143469/contributions/4799423/attachments/2416540/4135308/March_28_JetMET_SONIC.pdf. Please note that the producer introduced here does not affect the main ParticleNet producer in any way (https://github.com/cms-sw/cmssw/blob/master/RecoBTag/ONNXRuntime/plugins/BoostedJetONNXJetTagsProducer.cc). This is an alternate way to run the standard ParticleNet model using inference as a service. As noted in the linked slides, this producer has been validated locally on Tier 2 resources and at scale with cloud computing, but with this PR, we hope to perform more "official" production tests.  Again, this producer does not any workflow unless explicitly called. A helper-function macro is slightly modified, as are a few config files. There will be an accompanying PR into https://github.com/cms-data/RecoBTag-Combined, which adds needed model files.

Tagging @kpedro88 @yongbinfeng @violatingcp @nhanvtran @jmduarte

#### PR validation:

This PR was tested on LPC using a Triton server running on the GPU-enabled AILab machines at FermiLab. Tests have also been performed using the ParticleNet SONIC producer at Purdue T2 and in Google Cloud. When the producer is not called, there is no performance impact, and when it is called, the Jet Tagging results are the same as for the generic ParticleNet producer.

2022-05-16 15:56 UTC, wpmccormack commented
Accompanying model-file PR is here: https://github.com/cms-data/RecoBTag-Combined/pull/48

2022-05-16 16:00 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30036

- This PR adds an extra 32KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/ProcessModifiers/python/allSonicTriton_cff.py  modified in PR(s): #37963

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30036/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30036/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2022-05-17 07:21 UTC, jpata commented
code checks should be addressed before we proceed further (it's worth to run `scram b code-format` every time before pushing).

2022-05-17 07:22 UTC, jpata commented
assign btv-pog-l2 

@emilbols @cms-sw/btv-pog-l2 could you please review this from the BTV side?

2022-05-18 16:19 UTC, wpmccormack commented
Hi @jpata , I ran `scram b code-format`, and pushed the change to one of the files.  Sorry, I think I _had_ run that command after pushing the first time, but forgot to push the change that came out of it.

2022-05-18 21:05 UTC, kpedro88 commented
test parameters:
pull_request = https://github.com/cms-data/RecoBTag-Combined/pull/48
workflow = 11824.9001,23434.9001
relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

2022-05-18 21:06 UTC, kpedro88 commented
please test

2022-05-19 09:39 UTC, cmsbuild commented
-1

**Failed Tests**: UnitTests 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24840/summary.html
**COMMIT**: 60e20a1cb69037d450a013c907c3e907154ddb80
**CMSSW**: CMSSW_12_5_X_2022-05-18-1100/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37964/24840/install.sh` to create a dev area with all the needed externals and cmssw changes.



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - @wddgit cms-sw/cmssw#37991
 - @iarspider cms-sw/cmssw#37990
 - @bsunanda cms-sw/cmssw#37993

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24840/git-recent-commits.json
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24840/git-merge-result


## Unit Tests

I found errors in the following unit tests:

<pre>---> test SiStripDAQ_O2O_test had ERRORS
</pre>

## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 50
 - DQMHistoTests: Total histograms compared: 3672423
 - DQMHistoTests: Total failures: 9
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3672392
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 49 files compared)
 - Checked 208 log files, 45 edm output root files, 50 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-05-18-1100+603a48/50391/triggerResults): no differences found

2022-05-23 15:45 UTC, clacaputo commented
test parameters:

- pull_request = https://github.com/cms-data/RecoBTag-Combined/pull/48
- workflow = 11824.9001,23434.9001
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

2022-05-23 15:45 UTC, clacaputo commented
@cmsbuild please test

2022-05-23 21:45 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24918/summary.html
**COMMIT**: 60e20a1cb69037d450a013c907c3e907154ddb80
**CMSSW**: CMSSW_12_5_X_2022-05-23-1100/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/24918/install.sh` to create a dev area with all the needed externals and cmssw changes.



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - @SanghyunKo cms-sw/cmssw#38012
 - @cms-sw cms-sw/cmsdist#7881

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24918/git-recent-commits.json
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/24918/git-merge-result


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/11824.9001_TTbar_13+2021PU_SonicTriton+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/23434.9001_TTbar_14TeV+2026D49PU_SonicTriton+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 52
 - DQMHistoTests: Total histograms compared: 3920484
 - DQMHistoTests: Total failures: 14
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3920448
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 51 files compared)
 - Checked 216 log files, 54 edm output root files, 52 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-05-23-1100+603a48/50454/triggerResults): no differences found

2022-05-31 20:02 UTC, wpmccormack commented
Hi All, this recent push was made to make this PR align more closely with the deepMET PR (https://github.com/cms-sw/cmssw/pull/37963).  The particleNet model files are now not duplicated for the generic and sonic versions, and there is a symbolic link from the sonic version to the generic version

2022-05-31 20:08 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30300

- This PR adds an extra 16KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/ProcessModifiers/python/allSonicTriton_cff.py  modified in PR(s): #37963

2022-05-31 20:08 UTC, cmsbuild commented
Pull request #37964 was updated. @perrotta, @clacaputo, @cmsbuild, @slava77, @jpata, @qliphy, @fabiocos, @davidlange6 can you please check and sign again.

2022-06-02 07:53 UTC, jpata commented
type btv

2022-06-03 09:52 UTC, clacaputo commented
assign btv-pog

let's ask for explicit BTV signoff here

2022-06-03 09:52 UTC, cmsbuild commented
New categories assigned: btv-pog

@soureek,@johnalison you have been requested to review this Pull request/Issue and eventually sign? Thanks

2022-06-08 19:38 UTC, johnalison commented
BTV is happy to sign off.

2022-06-09 16:20 UTC, clacaputo requested changes
It would be good to change `cout` in `LogDebug`. I've pointed out few cases.

2022-06-09 21:45 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/BoostedJetONNXJetTagsProducer.cc
>          std::cout << " -- var=" << varname << ", center=" << info.center << ", scale=" << info.norm_factor
Changed

2022-06-09 21:45 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/BoostedJetONNXJetTagsProducer.cc
> +          std::cout << group_values[i] << ",";
Changed all instances here

2022-06-09 21:45 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/ParticleNetSonicJetTagsProducer.cc
> +        std::cout << group_name << "\nshapes: ";
Yep, changed

2022-06-09 21:45 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/ParticleNetSonicJetTagsProducer.cc
> +            std::cout << " -- var=" << varname << ", center=" << info.center << ", scale=" << info.norm_factor
changed here

2022-06-09 21:46 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/ParticleNetSonicJetTagsProducer.cc
> +    std::cout << "=== " << iEvent.id().run() << ":" << iEvent.id().luminosityBlock() << ":" << iEvent.id().event()
Yes, changed

2022-06-09 21:46 UTC, wpmccormack commented on RecoBTag/ONNXRuntime/plugins/ParticleNetSonicJetTagsProducer.cc
> +  //preprocessInfoLoader(&iConfig);
Deleted, thanks!

2022-06-09 21:52 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30480

- This PR adds an extra 32KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/ProcessModifiers/python/allSonicTriton_cff.py  modified in PR(s): #37963

2022-06-09 21:52 UTC, cmsbuild commented
Pull request #37964 was updated. @perrotta, @soureek, @clacaputo, @cmsbuild, @johnalison, @slava77, @jpata, @qliphy, @fabiocos, @davidlange6 can you please check and sign again.

2022-06-10 10:30 UTC, clacaputo commented
@cmsbuild please test

2022-06-10 13:10 UTC, cmsbuild commented
-1

**Failed Tests**: RelVals 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25423/summary.html
**COMMIT**: 27267a5fab7175b5dc5dbe4e8bdc5bb413ca61ca
**CMSSW**: CMSSW_12_5_X_2022-06-09-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/install.sh` to create a dev area with all the needed externals and cmssw changes.



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - @mkirsano cms-sw/cmssw#37689
 - @Dr15Jones cms-sw/cmssw#38308
 - @silviodonato cms-sw/cmssw#38065
 - @pmandrik cms-sw/cmssw#38282
 - @smuzaffar cms-sw/cmssw#38296
 - @cms-sw cms-sw/cmsdist#7919

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25423/git-recent-commits.json
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25423/git-merge-result


## RelVals

- [11824.9001](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25423/runTheMatrix-results/11824.9001_TTbar_13+2021PU_SonicTriton+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU)
```
----- Begin Fatal Exception 10-Jun-2022 14:51:10 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_NANO_VALIDATION_DQM_PU.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoBTag/Combined/data/particlenet_modelsForSonic/particlenet_AK4/config.pbtxt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/poison:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/src:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/external/el8_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/matrix-results/11824.9001_TTbar_13+2021PU_SonicTriton+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU


At:
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(840): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(925): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(918): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(511): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Modules.py(161): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Config.py(1199): _insertManyInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Config.py(1465): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
- [23434.9001](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25423/runTheMatrix-results/23434.9001_TTbar_14TeV+2026D49PU_SonicTriton+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU)
```
----- Begin Fatal Exception 10-Jun-2022 15:03:14 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step3_RAW2DIGI_RECO_RECOSIM_PAT_VALIDATION_DQM_PU.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoBTag/Combined/data/particlenet_modelsForSonic/particlenet_AK4/config.pbtxt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/poison:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/src:/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/37964/25423/CMSSW_12_5_X_2022-06-09-2300/external/el8_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/matrix-results/23434.9001_TTbar_14TeV+2026D49PU_SonicTriton+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU


At:
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(840): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(925): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Types.py(918): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(376): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Mixins.py(511): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Modules.py(161): insertInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Config.py(1199): _insertManyInto
  /cvmfs/cms-ib.cern.ch/week0/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-06-09-2300/src/FWCore/ParameterSet/python/Config.py(1465): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

2022-06-10 17:28 UTC, wpmccormack commented
This was my bad, somehow I had forgotten to push a change in the config files to reference a new path for the model files

2022-06-10 17:34 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-37964/30502

- This PR adds an extra 36KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  Configuration/ProcessModifiers/python/allSonicTriton_cff.py  modified in PR(s): #37963

2022-06-10 17:34 UTC, cmsbuild commented
Pull request #37964 was updated. @perrotta, @soureek, @clacaputo, @cmsbuild, @johnalison, @slava77, @jpata, @qliphy, @fabiocos, @davidlange6 can you please check and sign again.

2022-06-13 09:56 UTC, clacaputo commented
@cmsbuild please test

2022-06-13 19:05 UTC, cmsbuild commented
-1

**Failed Tests**: RelVals-INPUT 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25480/summary.html
**COMMIT**: 7b1de53cea008eb12e7c1f98e2e774129dd69c6d
**CMSSW**: CMSSW_12_5_X_2022-06-12-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37964/25480/install.sh` to create a dev area with all the needed externals and cmssw changes.



The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic: 
 - @minerva1993 cms-sw/cmssw#38298
 - @sayanchatterjee38 cms-sw/cmssw#38288
 - @silviodonato cms-sw/cmssw#38326
 - @cms-tsg-storm cms-sw/cmssw#38346
 - @eyigitba cms-sw/cmssw#38319
 - @cms-sw cms-sw/cmsdist#7927

You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25480/git-recent-commits.json
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25480/git-merge-result


## RelVals-INPUT

The relvals timed out after 4 hours.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/11824.9001_TTbar_13+2021PU_SonicTriton+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/23434.9001_TTbar_14TeV+2026D49PU_SonicTriton+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU

**Summary**:
 - No significant changes to the logs found
 - ROOTFileChecks: Some differences in event products or their sizes found
 - Reco comparison results: 745 differences found in the comparisons
 - DQMHistoTests: Total files compared: 52
 - DQMHistoTests: Total histograms compared: 3929316
 - DQMHistoTests: Total failures: 292
 - DQMHistoTests: Total nulls: 5
 - DQMHistoTests: Total successes: 3928997
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 219.22399999999996 KiB( 51 files compared)
 - DQMHistoSizes: changed ( 11634.0,... ): 32.252 KiB       HLT/HLTEgammaValidation
 - DQMHistoSizes: changed ( 11634.0,... ): 1.167 KiB        HLT/Filters
 - DQMHistoSizes: changed ( 11824.9001 ): 17.539 KiB       HLT/HLTEgammaValidation
 - DQMHistoSizes: changed ( 312.0 ): 0.004 KiB        MessageLogger/Warnings
 - Checked 216 log files, 54 edm output root files, 52 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-06-12-2300+603a48/50967/triggerResults): no differences found

2022-06-14 11:02 UTC, clacaputo commented
@cmsbuild please test

2022-06-14 16:30 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-603a48/25508/summary.html
**COMMIT**: 7b1de53cea008eb12e7c1f98e2e774129dd69c6d
**CMSSW**: CMSSW_12_5_X_2022-06-14-1100/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37964/25508/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /pool/condor/dir_34533/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/11824.9001_TTbar_13+2021PU_SonicTriton+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoNanoPU+HARVESTNanoPU
   * /pool/condor/dir_34533/jenkins/workspace/compare-root-files-short-matrix/data/PR-603a48/23434.9001_TTbar_14TeV+2026D49PU_SonicTriton+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 52
 - DQMHistoTests: Total histograms compared: 3929865
 - DQMHistoTests: Total failures: 13
 - DQMHistoTests: Total nulls: 1
 - DQMHistoTests: Total successes: 3929829
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.004 KiB( 51 files compared)
 - DQMHistoSizes: changed ( 312.0 ): 0.004 KiB        MessageLogger/Warnings
 - Checked 216 log files, 54 edm output root files, 52 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-06-14-1100+603a48/50983/triggerResults): no differences found

2022-06-16 14:12 UTC, clacaputo commented
+reconstruction

- PR introduce an alternative way to run ParticleNet inference via SONIC (disabled by default)
- testable in the workflow = 11824.9001,23434.9001
- code reorganization does not affect existing reco
- requires https://github.com/cms-data/RecoBTag-Combined/pull/48

2022-06-16 14:14 UTC, clacaputo commented
> BTV is happy to sign off.

Hi @johnalison , to trigger the change from `btv-pog-pending` to `btv-pog-approved`, could you please comment `+1`? Thanks

2022-06-28 00:42 UTC, qliphy commented
ping @cms-sw/btv-pog-l2

2022-06-28 06:19 UTC, perrotta commented
please test
(to rfresh)

2022-06-28 17:31 UTC, johnalison commented
+1

2022-06-30 06:37 UTC, perrotta commented
+1
- The differences reported in the test outputs are all due to a log-warning removed by #38526, which for some reason was added to this PR in the tests

2022-06-30 06:38 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will be automatically merged.

2022-06-30 06:38 UTC, merged