Replace Geometry_cff with GeometryDB_cff in RecoEgamma
cms-sw/cmssw pull request #38285
Opened 2022-06-08 11:33 UTC by jeongeun

**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoEgamma configuration files (14 files) are fixed.
```
modified:   RecoEgamma/EgammaElectronProducers/test/egammaClustersToGsfElectrons_cfg.py
modified:   RecoEgamma/EgammaElectronProducers/test/egammaCoresToGsfElectrons_cfg.py
modified:   RecoEgamma/EgammaElectronProducers/test/egammaRawDataToGsfElectrons_cfg.py
modified:   RecoEgamma/EgammaElectronProducers/test/egammaRecHitsToElectronSeeds_cfg.py
modified:   RecoEgamma/EgammaElectronProducers/test/egammaRecHitsToGsfElectrons_cfg.py
modified:   RecoEgamma/EgammaIsolationAlgos/test/egammaIsoTest_cfg.py
modified:   RecoEgamma/EgammaIsolationAlgos/test/pfclusterIsoTest_cfg.py
modified:   RecoEgamma/EgammaIsolationAlgos/test/runInterestingEgammaIsoDetIdsSequence_cfg.py
modified:   RecoEgamma/ElectronIdentification/test/eidSelectorTest_cfg.py
modified:   RecoEgamma/ElectronIdentification/test/runElectronID_cfg.py
modified:   RecoEgamma/Examples/test/ElectronSeedMCAnalyzer_cfg.py
modified:   RecoEgamma/Examples/test/GsfElectronRedoFromCore_cfg.py
modified:   RecoEgamma/Examples/test/GsfElectronRedoFromRaw_cfg.py
modified:   RecoEgamma/Examples/test/SimplePi0DiscAnalyzer_cfg.py
```

2022-06-08 11:39 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-38285/30438

ERROR: Unable to merge PR.

See log https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-38285/30438/cms-checkout-topic.log

2022-06-08 11:53 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-38285/30440

- This PR adds an extra 24KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  RecoEgamma/Examples/test/ElectronSeedMCAnalyzer_cfg.py  modified in PR(s): #37429
  - File  RecoEgamma/Examples/test/GsfElectronRedoFromCore_cfg.py  modified in PR(s): #37429
  - File  RecoEgamma/Examples/test/GsfElectronRedoFromRaw_cfg.py  modified in PR(s): #37429
  - File  RecoEgamma/Examples/test/SimplePi0DiscAnalyzer_cfg.py  modified in PR(s): #37429

2022-06-08 11:54 UTC, cmsbuild commented
A new Pull Request was created by  @jeongeun (JeongEun Lee) for master.

It involves the following packages:

- RecoEgamma/EgammaElectronProducers (**reconstruction**)
- RecoEgamma/EgammaIsolationAlgos (**reconstruction**)
- RecoEgamma/ElectronIdentification (**reconstruction**)
- RecoEgamma/Examples (**reconstruction**)


@jpata, @cmsbuild, @clacaputo, @slava77 can you please review it and eventually sign? Thanks.
@Sam-Harper, @jainshilpi, @valsdav, @rovere, @lgray, @sobhatta, @lecriste, @afiqaize, @wrtabb, @varuns23, @ram1123 this is something you requested to watch as well.
@perrotta, @dpiparo, @qliphy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2022-06-10 10:58 UTC, clacaputo requested changes

2022-06-10 10:58 UTC, clacaputo commented on RecoEgamma/ElectronIdentification/test/eidSelectorTest_cfg.py
>  process.load('FWCore/MessageService/MessageLogger_cfi')
Could you please also change
```suggestion
process.load('FWCore.MessageService.MessageLogger_cfi')
```

2022-06-10 10:58 UTC, clacaputo commented on RecoEgamma/ElectronIdentification/test/eidSelectorTest_cfg.py
>  process.load('Configuration/StandardSequences/Services_cff')
```suggestion
process.load('Configuration.StandardSequences.Services_cff')
```

2022-06-10 10:58 UTC, clacaputo commented on RecoEgamma/ElectronIdentification/test/runElectronID_cfg.py
>  process.load('FWCore/MessageService/MessageLogger_cfi')
```suggestion
process.load('FWCore.MessageService.MessageLogger_cfi')
```

2022-06-10 10:58 UTC, clacaputo commented on RecoEgamma/ElectronIdentification/test/runElectronID_cfg.py
>  process.load('Configuration/StandardSequences/Services_cff')
```suggestion
process.load('Configuration.StandardSequences.Services_cff')
```

2022-06-14 15:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-38285/30563

- This PR adds an extra 16KB to repository

2022-06-15 08:18 UTC, clacaputo commented
@cmsbuild please test

2022-06-15 12:16 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-50eeb2/25534/summary.html
**COMMIT**: 99ed83e1c8d3ee0474b5d347ea519ea34e22a1b2
**CMSSW**: CMSSW_12_5_X_2022-06-14-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/38285/25534/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 2 differences found in the comparisons
 - DQMHistoTests: Total files compared: 50
 - DQMHistoTests: Total histograms compared: 3659074
 - DQMHistoTests: Total failures: 8
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3659044
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 49 files compared)
 - Checked 208 log files, 45 edm output root files, 50 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-06-14-2300+50eeb2/51005/triggerResults): no differences found

2022-06-15 13:46 UTC, perrotta commented
+1

2022-06-15 13:46 UTC, merged

2022-06-16 00:34 UTC, tvami commented
Let me comment that when the `GeometryDB` is used (as the name says) the geometry is taken from the DB, meaning that a GT will have to be specified. I see some of the modified files dont have that, for example
https://github.com/jeongeun/cmssw/blob/99ed83e1c8d3ee0474b5d347ea519ea34e22a1b2/RecoEgamma/EgammaIsolationAlgos/test/egammaIsoTest_cfg.py
so that's not expected to work after this migration. Some other files have very old GTs, which might work or not.

Given that fact that no wf has been broken that means these files are actually not used anywhere... but when/if they will be used, they'll need to have a GT in them