HGCAL simulation of ToA constant jitter noise term
cms-sw/cmssw pull request #39316
Opened 2022-09-06 11:02 UTC by stahlleiton

#### PR description:

This PR introduces the simulation of the constant term of the jitter noise on the time of arrival (ToA) measurement of the HGCAL. This is done by modelling a Gaussian noise term common to all HGCAL hits and added as a bias to the ToA.
This is part of the set of updates already announced in the HGCAL DPG meeting (see https://indico.cern.ch/event/1158758/contributions/4880969/attachments/2451390/4201020/Timining%2020220525%20v2-2.pdf).

#### PR validation:

PR was validated using the runTheMatrix.py -w upgrade -l 23234.103 test.
HGCAL-related changes were mainly observed on the ToA distribution as expected while changes in the ADC are due to different number of calls of the random number generator, which causes some smearing visible at lower ADC values.

Plots of ToA for jitter constant of 20 ps: 
![](https://psilva.web.cern.ch/psilva/HGCAL/prtoajitterfloor/6Sep2022_113200/toaperdetid_0.png)
Plots of ToA for jitter constant of 1000 ps: 
![](https://psilva.web.cern.ch/psilva/HGCAL/prtoajitterfloor/6Sep2022_120600/toaperdetid_0.png)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

2022-09-06 11:09 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39316/32011

- This PR adds an extra 20KB to repository

2022-09-06 11:10 UTC, cmsbuild commented
A new Pull Request was created by  @stahlleiton (Andre Stahl) for master.

It involves the following packages:

- SimCalorimetry/HGCalSimProducers (**upgrade, simulation**)


@cmsbuild, @AdrianoDee, @srimanob, @civanch, @mdhildreth can you please review it and eventually sign? Thanks.
@youyingli, @vandreev11, @sethzenz, @bsunanda, @rovere, @lgray, @cseez, @apsallid, @pfs, @hatakeyamak, @trtomei, @beaucero this is something you requested to watch as well.
@perrotta, @dpiparo, @rappoccio you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2022-09-06 11:48 UTC, pfs commented
assign hgcal-dpg

2022-09-06 11:51 UTC, pfs commented
please test

2022-09-06 11:51 UTC, cmsbuild commented
New categories assigned: hgcal-dpg

@felicepantaleo,@rovere,@pfs,@cseez you have been requested to review this Pull request/Issue and eventually sign? Thanks

2022-09-06 16:45 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4940f1/27362/summary.html
**COMMIT**: 30fd24cf9498c6ab427ba0d7be230fe1b4f8291d
**CMSSW**: CMSSW_12_6_X_2022-09-05-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39316/27362/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 17092 differences found in the comparisons
 - DQMHistoTests: Total files compared: 51
 - DQMHistoTests: Total histograms compared: 3618210
 - DQMHistoTests: Total failures: 187261
 - DQMHistoTests: Total nulls: 25
 - DQMHistoTests: Total successes: 3430902
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 50 files compared)
 - Checked 212 log files, 49 edm output root files, 51 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-09-05-2300+4940f1/52598/triggerResults): found differences in 1 / 50 workflows

2022-09-07 09:28 UTC, felicepantaleo commented
@stahlleiton thanks for this PR. 
I add some trivial technical changes to the review.

Did you have the chance to look at what happens downstream? If you want, as further validation that what you are doing is correct, but also to "warn" other POGs using timing.
I see some suspicious new entries in the ECAL PFClusters timing at 10^38...
![image](https://user-images.githubusercontent.com/6595715/188842636-37516761-e36e-4e7b-a683-6a263e224a43.png)

2022-09-07 09:28 UTC, felicepantaleo requested changes

2022-09-07 13:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39316/32036

- This PR adds an extra 24KB to repository

2022-09-07 13:46 UTC, cmsbuild commented
Pull request #39316 was updated. @cseez, @civanch, @felicepantaleo, @rovere, @cmsbuild, @AdrianoDee, @srimanob, @mdhildreth, @pfs can you please check and sign again.

2022-09-08 10:27 UTC, civanch commented
please test

2022-09-08 11:11 UTC, stahlleiton commented on SimCalorimetry/HGCalSimProducers/src/HGCFEElectronics.cc
> +    timeToA += eventTimeOffset_ns_.at(thickness - 1);
changed all the .at() with []

2022-09-08 11:12 UTC, stahlleiton commented on SimCalorimetry/HGCalSimProducers/src/HGCFEElectronics.cc
> +    float noise = std::sqrt(jitterNoise2_ns_.at(thickness - 1)) * sensor_noise;
changed the jitterNoise2_ns_ and jitterConstant2_ns_ to their normal (not squared) versions jitterNoise_ns_ and jitterConstant_ns_

2022-09-08 15:31 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4940f1/27428/summary.html
**COMMIT**: 11bab1e28d981b63c9ad8cdf247f98cc4d857400
**CMSSW**: CMSSW_12_6_X_2022-09-07-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39316/27428/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 17093 differences found in the comparisons
 - DQMHistoTests: Total files compared: 51
 - DQMHistoTests: Total histograms compared: 3618326
 - DQMHistoTests: Total failures: 187264
 - DQMHistoTests: Total nulls: 25
 - DQMHistoTests: Total successes: 3431015
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 50 files compared)
 - Checked 212 log files, 49 edm output root files, 51 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-09-07-2300+4940f1/52664/triggerResults): found differences in 1 / 50 workflows

2022-09-14 08:24 UTC, civanch commented
+1

2022-09-14 17:01 UTC, felicepantaleo commented
+1

2022-09-28 21:57 UTC, sameasy commented
Hi, The differences seen when testing this PR seem to be not restricted to ECAL information only, but also appear in other sub-systems as well. There seems to be no migration of clusters between HGCAL and ECAL/HCAL etc. In order to check if there were any issues in the unit tests, I ran a test workflow [runTheMatrix.py -w upgrade -l 23234.103] with and without the PR. Differences persist still and can be seen in rechit collections from ecal, hcal and mtd from the attached plots (red is before and blue is after the PR). It seems that the issue may be with the random number generators. They should be distinct but it seems like there is some dependency on the calls made by the sub-systems.

For the issue about the the appearance of new entries at very high ECAL time values I find that the high values are actually there even without the PR. So this may point to some other issue unrelated to the PR.
![mtdrechits](https://user-images.githubusercontent.com/8367794/192895608-32205fbb-b3fa-4a03-926c-f8108034b341.png)
![hcalrechits](https://user-images.githubusercontent.com/8367794/192895611-013fc085-5652-48d3-b723-617402f82b05.png)
![ecalrechits](https://user-images.githubusercontent.com/8367794/192895614-d397600d-846f-4613-b9a4-f2a1f93ac184.png)
![timedist](https://user-images.githubusercontent.com/8367794/192895615-0a85dc85-4f64-4276-8e3b-cc2f59f334c4.png)

2022-10-02 17:14 UTC, srimanob commented
@cmsbuild please test
Just re-trigger the test after 3 weeks. Then we can sign.

2022-10-02 21:56 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4940f1/27910/summary.html
**COMMIT**: 11bab1e28d981b63c9ad8cdf247f98cc4d857400
**CMSSW**: CMSSW_12_6_X_2022-10-02-0000/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39316/27910/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-4940f1/41834.0_TTbar_14TeV+2026D94+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 9085 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3432650
 - DQMHistoTests: Total failures: 124471
 - DQMHistoTests: Total nulls: 21
 - DQMHistoTests: Total successes: 3308136
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 48 files compared)
 - Checked 204 log files, 49 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-02-0000+4940f1/53094/triggerResults): found differences in 1 / 48 workflows

2022-10-04 10:27 UTC, pfs commented
@srimanob  Is it ok to approve now that the tests have run?

2022-10-04 10:31 UTC, srimanob commented
+Upgrade

2022-10-04 10:32 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2022-10-05 08:40 UTC, perrotta commented
+1

2022-10-05 08:41 UTC, merged