Modernize SiStripMonitorClient, bugfix to the destructor of two scripts
cms-sw/cmssw pull request #39518
Opened 2022-09-28 02:57 UTC by tvami

#### PR description:

Tracker Offline DQM shift scripts, such as
`python3 PhaseITreeProducer.py DQM_V0001_R000359278__ZeroBias__Run2022E-PromptReco-v1__DQMIO.root`
gave the following
```
Histograms to read 114
Histograms saved to internal data structure
Data saved as TTree object
Exception ignored in: <function ModuleLvlValuesReader.__del__ at 0x7f99aa46ed30>
Traceback (most recent call last):
  File "/data/vami/projects/DQM/CMSSW_12_4_9/src/DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py", line 317, in __del__
AttributeError: 'CPyCppyy_NoneType' object has no attribute 'IsOpen'
```

After adding a check on the existence, this is gone.

Since I touched the package and gave a lot of warnings about the Legacy modules, 
 * I moved everything to a `::one::` module
 * merged the header files to the cc files
 * moves the es consume into the initializer list

#### PR validation:

`PhaseITreeProducer.py` runs fine. For the rest, the code compiles w/o warning.s

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not sure, it's a cleanup, but the PhaseITreeProducer.py is used during the shifts for every run, so in that aspect, at least that part should be backported to 12_4_X (and then of course 12_5_X too)

2022-09-28 02:57 UTC, tvami commented
type bugfix,trk

2022-09-28 03:04 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39518/32277

- This PR adds an extra 32KB to repository

2022-09-28 03:05 UTC, cmsbuild commented
A new Pull Request was created by  @tvami (Tamas Vami) for master.

It involves the following packages:

- DQM/SiStripMonitorClient (**dqm**)


@emanueleusai, @ahmad3213, @cmsbuild, @jfernan2, @syuvivida, @pmandrik, @micsucmed, @rvenditti can you please review it and eventually sign? Thanks.
@arossi83, @hdelanno, @sroychow, @fioriNTU, @jandrea, @idebruyn, @mmusich, @threus, @venturia this is something you requested to watch as well.
@perrotta, @dpiparo, @rappoccio you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2022-09-28 03:28 UTC, tvami commented
@cmsbuild , please test

2022-09-28 04:19 UTC, mmusich commented on DQM/SiStripMonitorClient/plugins/SiStripAnalyser.cc
> +class SiStripAnalyser : public edm::one::EDAnalyzer<> {
Is this the right fix?
I think this should be moved to `DQMEDHarvester` instead.

2022-09-28 04:21 UTC, mmusich commented on DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc
> +class SiStripCertificationInfo : public edm::one::EDAnalyzer<> {
Is this the right fix?
I think this should be moved to `DQMEDHarvester` instead.

2022-09-28 04:21 UTC, mmusich commented on DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
> +
Is this the right fix?
I think this should be moved to `DQMEDHarvester` instead.

2022-09-28 04:21 UTC, mmusich commented on DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
> +class SiStripDcsInfo : public edm::one::EDAnalyzer<> {
Is this the right fix?
I think this should be moved to `DQMEDHarvester` instead.

2022-09-28 09:05 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5d35e/27807/summary.html
**COMMIT**: 419be43a3c348ef2a649c6f6a73ac2d9b2f0523e
**CMSSW**: CMSSW_12_6_X_2022-09-27-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/39518/27807/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 0 differences found in the comparisons
 - DQMHistoTests: Total files compared: 51
 - DQMHistoTests: Total histograms compared: 3624338
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3624313
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: -39.132000000000005 KiB( 50 files compared)
 - DQMHistoSizes: changed ( 1000.0,... ): -1.131 KiB       SiStrip/EventInfo
 - DQMHistoSizes: changed ( 140.53 ): -0.352 KiB       SiStrip/MechanicalView
 - DQMHistoSizes: changed ( 4.22 ): -4.852 KiB       SiStrip/MechanicalView
 - Checked 212 log files, 49 edm output root files, 51 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-09-27-2300+b5d35e/52995/triggerResults): no differences found

2022-09-28 12:24 UTC, tvami commented
OK, I can make them `DQMEDHarvester`, thanks Marco for the feedback!

2022-09-28 16:14 UTC, mmusich commented
assign trk-dpg

> DQMHistoSizes: Histogram memory added: -39.132000000000005 KiB( 50 files compared)
DQMHistoSizes: changed ( 1000.0,... ): -1.131 KiB SiStrip/EventInfo
DQMHistoSizes: changed ( 140.53 ): -0.352 KiB SiStrip/MechanicalView
DQMHistoSizes: changed ( 4.22 ): -4.852 KiB SiStrip/MechanicalView

By the way the comparison in the DQM bin-by-bin does not look good (see [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-09-27-2300+b5d35e/52995/dqm-histo-comparison-summary.html))

-1 fwiw.

2022-09-28 16:14 UTC, cmsbuild commented
New categories assigned: trk-dpg

@connorpa,@sroychow you have been requested to review this Pull request/Issue and eventually sign? Thanks

2022-10-03 00:10 UTC, tvami commented
I decoupled the two changes in this PR, as the migration to `DQMEDHarvester` is non-trivial. I get the following error when I simply move to it

```

>> Compiling edm plugin /data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc
/data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc:37:8: error: virtual function 'virtual void SiStripCertificationInfo::endLuminosityBlock(const edm::LuminosityBlock&, const edm::EventSetup&)' overriding final function
   37 |   void endLuminosityBlock(edm::LuminosityBlock const& lumiSeg, edm::EventSetup const& iSetup);
      |        ^~~~~~~~~~~~~~~~~~
In file included from /data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc:9:
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/DQMServices/Core/interface/DQMEDHarvester.h:132:8: note: overridden function is 'virtual void DQMEDHarvester::endLuminosityBlock(const edm::LuminosityBlock&, const edm::EventSetup&)'
  132 |   void endLuminosityBlock(edm::LuminosityBlock const &, edm::EventSetup const &) final{};
      |        ^~~~~~~~~~~~~~~~~~
In file included from /cvmfs/cms-ib.cern.ch/nweek-02752/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/memory:83,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/FunctorESHandleExceptionFactory.h:24,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/EventSetupRecord.h:42,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/EventSetupRecordImplementation.h:26,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/CalibTracker/Records/interface/SiStripDependentRecords.h:4,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/CalibTracker/Records/interface/SiStripDetCablingRcd.h:1,
                 from /data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc:2:
/cvmfs/cms-ib.cern.ch/nweek-02752/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = SiStripCertificationInfo; _Args = {const edm::ParameterSet&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<SiStripCertificationInfo, std::default_delete<SiStripCertificationInfo> >]':
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/maker/MakeModuleHelper.h:39:40:   required from 'static std::unique_ptr<_Tp> edm::MakeModuleHelper<Base>::makeModule(const edm::ParameterSet&) [with T = SiStripCertificationInfo; Base = edm::one::EDProducerBase]'
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/maker/WorkerMaker.h:82:107:   required from 'std::shared_ptr<edm::maker::ModuleHolder> edm::WorkerMaker<T>::makeModule(const edm::ParameterSet&) const [with T = SiStripCertificationInfo]'
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/FWCore/Framework/interface/maker/WorkerMaker.h:76:40:   required from here
/cvmfs/cms-ib.cern.ch/nweek-02752/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/bits/unique_ptr.h:962:30: error: invalid new-expression of abstract class type 'SiStripCertificationInfo'
  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc:28:7: note:   because the following virtual functions are pure within 'SiStripCertificationInfo':
   28 | class SiStripCertificationInfo : public DQMEDHarvester {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/vami/projects/DQM/CMSSW_12_6_X_2022-09-27-1100/src/DQM/SiStripMonitorClient/plugins/SiStripCertificationInfo.cc:9:
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-09-27-1100/src/DQMServices/Core/interface/DQMEDHarvester.h:166:16: note:     'virtual void DQMEDHarvester::dqmEndJob(dqm::legacy::DQMStore::IBooker&, dqm::legacy::DQMStore::IGetter&)'
  166 |   virtual void dqmEndJob(DQMStore::IBooker &, DQMStore::IGetter &) = 0;
      |                ^~~~~~~~~
```

2022-10-03 08:23 UTC, mmusich requested changes

2022-10-03 09:22 UTC, mmusich commented
this commit https://github.com/cms-sw/cmssw/commit/40ce9a88c7083ffcabc10edd842538d897bcdf93 should address my https://github.com/cms-sw/cmssw/pull/39518#pullrequestreview-1127916371 comments

2022-10-03 19:31 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39518/32379

- This PR adds an extra 32KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py  modified in PR(s): #39573
  - File  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py  modified in PR(s): #39573

2022-10-03 19:32 UTC, cmsbuild commented
Pull request #39518 was updated. @connorpa, @sroychow, @emanueleusai, @ahmad3213, @cmsbuild, @jfernan2, @syuvivida, @pmandrik, @micsucmed, @rvenditti can you please check and sign again.

2022-10-03 19:52 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39518/32381

- This PR adds an extra 24KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQM/SiStripMonitorClient/scripts/PhaseITreeProducer.py  modified in PR(s): #39573
  - File  DQM/SiStripMonitorClient/scripts/TH2PolyOfflineMaps.py  modified in PR(s): #39573

2022-10-03 19:52 UTC, cmsbuild commented
Pull request #39518 was updated. @connorpa, @sroychow, @emanueleusai, @ahmad3213, @cmsbuild, @jfernan2, @syuvivida, @pmandrik, @micsucmed, @rvenditti can you please check and sign again.

2022-10-03 20:12 UTC, tvami commented
Thanks Marco! I included your commit. 

I also removed the change in the scripts, however I see this
https://github.com/cms-sw/cmssw/pull/39518/files#diff-6c8707826386170053faf1ed45f98db106967576c345280443c9b830cef288c9

so maybe we can let https://github.com/cms-sw/cmssw/pull/39573 in and then I'll remove on the top of that?

2022-10-03 20:13 UTC, tvami commented
@cmsbuild , please test

2022-10-04 22:15 UTC, mmusich commented
seems tests got stuck here?

2022-10-04 22:17 UTC, tvami commented
> seems tests got stuck here?

@smuzaffar ?

2022-10-05 02:53 UTC, perrotta commented
@cmsbuild , please test

2022-10-05 18:12 UTC, mmusich commented
Is this PR really making the relvals take so long, or is there a problem with the bot?

2022-10-05 23:22 UTC, tvami commented
I see this in the Jenkins
```
15:37:08 [parameterized-trigger] Properties file update-das-queries did not exist.
15:37:08 Not triggering due to missing file - did you archive it as a build artifact ?
15:37:08 Triggering projects: [update-das-queries](https://cmssdt.cern.ch/jenkins/job/update-das-queries/)
15:37:08 New run name is 'PR cms-sw/cmssw#39518 el8_amd64_gcc10'
15:37:08 [WS-CLEANUP] Deleting project workspace...
15:37:08 [WS-CLEANUP] Deferred wipeout is used...
15:37:08 [WS-CLEANUP] done
15:37:08 Finished: SUCCESS
```
so it seems it's not actually running

2022-10-05 23:24 UTC, tvami commented
@cmsbuild , please abort

2022-10-05 23:27 UTC, tvami commented
@cmsbuild , please test

2022-10-06 12:55 UTC, aandvalenzuela commented
please test

- Tests need to be restarted due to an issue in cvmfs. Sorry for the inconvenience!

2022-10-06 17:01 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5d35e/28064/summary.html
**COMMIT**: ee27d0df5fae211611c6879af4a01947378cbd60
**CMSSW**: CMSSW_12_6_X_2022-10-05-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39518/28064/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-b5d35e/41834.0_TTbar_14TeV+2026D94+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3391103
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3391078
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 48 files compared)
 - Checked 204 log files, 49 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-05-2300+b5d35e/53229/triggerResults): no differences found

2022-10-06 17:31 UTC, tvami commented
@mmusich now that my other PR got merged, should I rebase it? (there is no conflict)

2022-10-06 18:32 UTC, mmusich commented
> DQMHistoTests: Total failures: 3

Now tests are ~ cleaner

> now that my other PR got merged, should I rebase it? (there is no conflict)

I think it would be cleaner, I honestly don't know how git will resolve the conflict internally.

2022-10-07 05:23 UTC, emanueleusai commented
+1

2022-10-08 01:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39518/32486

- This PR adds an extra 24KB to repository

2022-10-08 01:13 UTC, cmsbuild commented
Pull request #39518 was updated. @connorpa, @sroychow can you please check and sign again.

2022-10-08 01:16 UTC, tvami commented
> I think it would be cleaner, I honestly don't know how git will resolve the conflict internally.

I rebased, but I still see the `100755 → 100644` change... not sure if we care or not?

2022-10-08 04:11 UTC, mmusich commented
> I rebased, but I still see the 100755 → 100644 change... 

did you change the file permissions (i.e. now it is executable)?

2022-10-08 08:41 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5d35e/28116/summary.html
**COMMIT**: a1cdce8d3d6de503ba5c26d504cf6987606f490c
**CMSSW**: CMSSW_12_6_X_2022-10-07-2300/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39518/28116/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-b5d35e/41834.0_TTbar_14TeV+2026D94+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 9 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3391103
 - DQMHistoTests: Total failures: 9
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3391072
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 48 files compared)
 - Checked 204 log files, 49 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-07-2300+b5d35e/53275/triggerResults): no differences found

2022-10-08 14:51 UTC, tvami commented
> did you change the file permissions (i.e. now it is executable)?

Oh I guess yes, I needed that for the unit test I think

2022-10-09 13:47 UTC, mmusich commented
> Oh I guess yes, I needed that for the unit test I think

so it's expected. I guess this is ready for merge

2022-10-09 13:48 UTC, mmusich commented
@sroychow @connorpa would you mind to sign?

2022-10-09 14:13 UTC, sroychow commented
+1

2022-10-09 14:13 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2022-10-10 07:23 UTC, perrotta commented on DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
> +#include <iostream>
Duplicates:
```suggestion
```

2022-10-10 07:23 UTC, perrotta commented on DQM/SiStripMonitorClient/plugins/SiStripDaqInfo.cc
> +#include "FWCore/ParameterSet/interface/ParameterSet.h"
Duplicate:
```suggestion
```

2022-10-10 07:23 UTC, perrotta commented on DQM/SiStripMonitorClient/plugins/SiStripDcsInfo.cc
> +#include "FWCore/ParameterSet/interface/ParameterSet.h"
Duplicate:
```suggestion
```

2022-10-10 15:12 UTC, tvami commented
@perrotta I fixed the duplicate includes, thanks for noticing that!

2022-10-10 15:12 UTC, tvami commented
@cmsbuild , please test

2022-10-10 15:16 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-39518/32516

- This PR adds an extra 24KB to repository

2022-10-10 15:16 UTC, cmsbuild commented
Pull request #39518 was updated. @connorpa, @sroychow, @emanueleusai, @ahmad3213, @jfernan2, @syuvivida, @pmandrik, @micsucmed, @rvenditti can you please check and sign again.

2022-10-10 19:02 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5d35e/28161/summary.html
**COMMIT**: 391bbb1fd87b54eb1a55e5d36dfb31d050af0c29
**CMSSW**: CMSSW_12_6_X_2022-10-10-1100/el8_amd64_gcc10
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/39518/28161/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



@slava77 comparisons for the following workflows were not done due to missing matrix map:
   * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-b5d35e/41834.0_TTbar_14TeV+2026D94+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal

**Summary**:
 - No significant changes to the logs found
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 49
 - DQMHistoTests: Total histograms compared: 3392309
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3392284
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 48 files compared)
 - Checked 204 log files, 49 edm output root files, 49 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-10-1100+b5d35e/53310/triggerResults): no differences found

2022-10-11 00:45 UTC, tvami commented
@sroychow @emanueleusai  can you please re-sign?

2022-10-11 04:52 UTC, emanueleusai commented
+1

2022-10-11 05:01 UTC, perrotta commented
@sroychow last updates were just cleanings: I think you can sign once again fror @cms-sw/trk-dpg-l2

2022-10-11 05:45 UTC, sroychow commented
+1

2022-10-11 05:46 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2022-10-11 06:26 UTC, perrotta commented
+1

2022-10-11 06:27 UTC, merged