EMTF add DQM plots for unconstrained pT and dxy
cms-sw/cmssw pull request #42155
Opened 2023-06-29 17:51 UTC by elledesa

#### PR description:

This PR adds DQM plots using unconstrained pT and dxy. These plots will be useful for monitoring now that the neural network is working at P5.

This PR will be back-ported to 13_0_X and 13_1_X to be used online.

#### PR validation:

Validated by `runTheMatrix.py -l limited -i all --ibeos`  and everything looks good.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

2023-07-03 05:36 UTC, emanueleusai commented
type l1t

2023-07-03 05:36 UTC, emanueleusai commented
please test

2023-07-03 05:36 UTC, cmsbuild commented
A new Pull Request was created by  @lutuck (Lucas Faria de Sá Tucker) for master.

It involves the following packages:

- DQM/L1TMonitor (**dqm**)


@nothingface0, @emanueleusai, @pmandrik, @syuvivida, @tjavaid, @micsucmed, @rvenditti can you please review it and eventually sign? Thanks.
@missirol this is something you requested to watch as well.
@perrotta, @dpiparo, @rappoccio you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2023-07-03 06:57 UTC, cmsbuild commented
-1

**Failed Tests**: RelVals RelVals-INPUT 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/summary.html
**COMMIT**: ada07caa21d83fc89bba900fc65a39325310e95a
**CMSSW**: CMSSW_13_2_X_2023-07-02-2300/el8_amd64_gcc11
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/42155/33510/install.sh` to create a dev area with all the needed externals and cmssw changes.


## RelVals

- [10224.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrix-results/10224.0_TTbar_13+2017PU)
```
----- Begin Fatal Exception 03-Jul-2023 08:11:43 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://cms-xrd-global.cern.ch//eos/cms/store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root
      [b] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root
      [c] Input file root://xrootd-cms.infn.it//store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root could not be opened.
      [d] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file. 
' (errno=3011, code=400). No additional data servers were found.
      [e] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_12_0_0_pre4/RelValMinBias_13/GEN-SIM/113X_mc2017_realistic_v5-v1/00000/a21693e9-4d25-496a-96e2-c28232a7a712.root?tried=+1213xrootd-redic.pi.infn.it,&xrdcl.requuid=7b465282-3733-4303-9016-5a8935a568c4
      [f] Problematic data server: cms-xrd-global.cern.ch:1094
      [g] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```


## RelVals-INPUT

- [23.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/23.0_JpsiMM)```23.0_JpsiMM/step2_JpsiMM.log```
- [134.806](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/134.806_RunMuonEG2015C)```134.806_RunMuonEG2015C/step2_RunMuonEG2015C.log```
- [134.808](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/134.808_RunSingleMuPrpt2015C)```134.808_RunSingleMuPrpt2015C/step2_RunSingleMuPrpt2015C.log```
<details>
<summary>Expand to see more relval errors ...</summary>

- [136.749](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.749_RunDoubleMuon2016D)
- [4.29](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/4.29_RunMinBias2011B)
- [136.756](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.756_RunZeroBias2016D)
- [136.752](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.752_RunMuonEG2016D)
- [136.75](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.75_RunJetHT2016D)
- [134.907](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/134.907_RunDoubleEGPrpt2015D)
- [136.754](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.754_RunSingleMu2016D)
- [136.741](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.741_RunMuonEG2016C)
- [136.795](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.795_RunJetHT2017C)
- [136.803](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.803_RunNoBPTX2017C)
- [136.869](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.869_RunMuOnia2018B)
- [136.832](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.832_RunMET2017F)
- [136.839](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/136.839_RunNoBPTX2017F)
- [1347.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/1347.0_Upsilon1SToMuMu_13)
- [1325.517](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/1325.517_TTbar13reMINIAODin2017UL)
- [13992502.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/13992502.0_TTbar_13_HS)
- [134.99601](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/134.99601_RunJetHT2015HLHS)
- [134.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/134.0_MinimumBiasBS)
- [10004.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/10004.0_SingleGammaPt10+2017)
- [10803.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/10803.0_SingleElectronPt1000+2018)
- [10007.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/10007.0_SingleMuPt10+2017)
- [250206.18](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33510/runTheMatrixINPUT-results/250206.18_ZMM_13UP18)
</details>

2023-07-04 05:15 UTC, perrotta commented
please test

2023-07-04 07:50 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/33536/summary.html
**COMMIT**: ada07caa21d83fc89bba900fc65a39325310e95a
**CMSSW**: CMSSW_13_2_X_2023-07-03-2300/el8_amd64_gcc11
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/42155/33536/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially removed 3 lines from the logs
 - Reco comparison results: 4 differences found in the comparisons
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3193832
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3193807
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1129.1800000000005 KiB( 47 files compared)
 - DQMHistoSizes: changed ( 10024.0,... ): 56.459 KiB       L1T/L1TStage2EMTF
 - Checked 207 log files, 159 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-07-03-2300+3f4d2d/57803/triggerResults): no differences found

2023-07-05 07:12 UTC, emanueleusai commented
+1

2023-07-05 07:12 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2023-07-05 08:01 UTC, perrotta commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +    int singleMuUPT = 10;  //Lucas Faria de Sa Tucker June 28 2023
Why integers the two pts?
In addition, please make them constexpr (including quality), and move them outside the loop

2023-07-07 14:22 UTC, rappoccio commented
hold

Place on explicit hold until comments from Andrea are addressed.

2023-07-07 14:22 UTC, cmsbuild commented
Pull request has been put on hold by  @rappoccio
They need to issue an `unhold` command to remove the `hold` state or L1 can `unhold` it for all

2023-07-11 06:20 UTC, eyigitba commented
I can have a look at this if @lutuck is unable to apply the changes. It's not urgent and can stay on hold in the meantime

2023-08-04 10:36 UTC, menglu21 commented
Hi, it seems Lucas is unable to work on this, could you please close this PR and the backports, I'll make a new PR and backports with the comments addressed.

2023-08-04 11:13 UTC, perrotta commented
> Hi, it seems Lucas is unable to work on this, could you please close this PR and the backports, I'll make a new PR and backports with the comments addressed.

Thank you @menglu21 : please go ahead with the PR, we can centrally close this one once the replacement is there

2023-08-07 22:20 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36510

- This PR adds an extra 28KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36510/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36510/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2023-08-09 05:10 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36524

- This PR adds an extra 28KB to repository

2023-08-09 05:10 UTC, cmsbuild commented
Pull request #42155 was updated. @nothingface0, @emanueleusai, @cmsbuild, @pmandrik, @syuvivida, @tjavaid, @micsucmed, @rvenditti can you please check and sign again.

2023-08-10 22:38 UTC, emanueleusai commented
please test

2023-08-11 04:26 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/34216/summary.html
**COMMIT**: 3a34c461cd7e6a651321ffbfc86eb1150cd34252
**CMSSW**: CMSSW_13_3_X_2023-08-10-2300/el8_amd64_gcc11
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/42155/34216/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially removed 11 lines from the logs
 - Reco comparison results: 3 differences found in the comparisons
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3150947
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3150922
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1129.1800000000005 KiB( 47 files compared)
 - DQMHistoSizes: changed ( 10024.0,... ): 56.459 KiB       L1T/L1TStage2EMTF
 - Checked 207 log files, 159 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-10-2300+3f4d2d/58350/triggerResults): no differences found

2023-08-15 13:32 UTC, emanueleusai commented
+1

2023-08-15 13:49 UTC, emanueleusai requested changes
@lutuck, I believe @perrotta suggests to change singleMuPT and singleMuUPT from int to float because track pT is not an integer quantity in general.
Additionally could  you please remove the name, date tags? they are not needed and do not add any useful info to the code. Author and date of the changes are tracked by github already.

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackUnconstrainedPt;             // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackDxy;                         // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackPtHighQuality;               //Chad Freer May 8 2018
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackUnconstrainedPtHighQuality;  // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackUnconstrainedPtHighQualityHighUPT;  // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
>    MonitorElement* emtfTrackEtaHighQuality;  //Chad Freer May 8 2018
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfTrackEtaHighQualityHighUPT;  // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfMuonhwPtUnconstrained;  // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/interface/L1TStage2EMTF.h
> +  MonitorElement* emtfMuonhwDxy;              // Lucas Faria de Sa Tucker Jun 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  // end new plots
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  //Lucas Faria de Sa Tucker June 28 2023 (Unconstrained Pt Plot)
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
>    //Chad Freer May 8 2018 (END new plots)
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  //Lucas Faria de Sa Tucker June 28 2023 (High Quality and High UPT [10 GeV] Track Plots)
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  // end new plots
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  //Lucas Faria de Sa Tucker June 28 2023 (Unconstrained and Dxy plots)
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  //end new plots
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  constexpr int singleMuPT = 22;
change to constexpr float

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  constexpr int singleMuPT = 22;
and 22.0

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +  constexpr int singleMuUPT = 10;
change to constexpr float and 10.0

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +    emtfTrackDxy->Fill(Track->GMT_dxy());             //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +    emtfTrackUnconstrainedPt->Fill(Track->Pt_dxy());  //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +      emtfTrackUnconstrainedPtHighQuality->Fill(Track->Pt_dxy());  //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +      if (Track->Pt_dxy() >= singleMuUPT) {  //High UPT plots by Lucas Faria de Sa Tucker
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +      emtfMuonhwPtUnconstrained->Fill(Muon->hwPtUnconstrained());  //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 13:49 UTC, emanueleusai commented on DQM/L1TMonitor/src/L1TStage2EMTF.cc
> +      emtfMuonhwDxy->Fill(Muon->hwDXY());                          //Lucas Faria de Sa Tucker June 28 2023
remove comment

2023-08-15 14:04 UTC, lutuck commented
@emanueleusai  Yes, I will make these changes now! Would you like singleMuPT and singleMuUPT to still be constexpr float, or just float?

2023-08-15 14:47 UTC, emanueleusai commented
constexpr float is fine

2023-08-16 02:34 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36597

- This PR adds an extra 28KB to repository

2023-08-16 02:34 UTC, cmsbuild commented
Pull request #42155 was updated. @nothingface0, @emanueleusai, @cmsbuild, @pmandrik, @syuvivida, @tjavaid, @micsucmed, @rvenditti can you please check and sign again.

2023-08-16 22:40 UTC, emanueleusai commented
please test

2023-08-17 03:17 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/34330/summary.html
**COMMIT**: 3f09a503a47d0973e8d5bed7b23b5b88873c7fa5
**CMSSW**: CMSSW_13_3_X_2023-08-16-1100/el8_amd64_gcc11
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/42155/34330/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially removed 3 lines from the logs
 - Reco comparison results: 6 differences found in the comparisons
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3152915
 - DQMHistoTests: Total failures: 3
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3152890
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1129.1800000000005 KiB( 47 files compared)
 - DQMHistoSizes: changed ( 10024.0,... ): 56.459 KiB       L1T/L1TStage2EMTF
 - Checked 207 log files, 159 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-16-1100+3f4d2d/58469/triggerResults): no differences found

2023-08-17 07:01 UTC, perrotta commented
unhold
@lutuck there are still a few comments from @emanueleusai to be implemented, see https://github.com/cms-sw/cmssw/pull/42155#pullrequestreview-1578585475 (I'll let Emanuele decide whether they are relevant or not)

2023-08-18 02:22 UTC, emanueleusai commented
Yes, @lutuck please remove the comments with your name and date from the code. Functionally speaking the PR is ok now, but it is a matter of code cleanliness and readability.
I do not think each line you change should be commented with the date and name of the author. This is tracked by github already.

2023-08-18 03:48 UTC, lutuck commented
@emanueleusai I believe I updated the PR to have the comments removed for the reasons you stated. Please let me know if you're still seeing this issue and I can take another look, or if there are any other modifications you'd like me to make.

2023-08-18 06:27 UTC, perrotta commented
> @emanueleusai I believe I updated the PR to have the comments removed for the reasons you stated. Please let me know if you're still seeing this issue and I can take another look, or if there are any other modifications you'd like me to make.

@lutuck please have a look at all comments listed in https://github.com/cms-sw/cmssw/pull/42155#pullrequestreview-1578585475 that you have not yet implemented

2023-08-18 12:34 UTC, lutuck commented
@perrotta the most recent commit (2 days ago) removed the comments and changed ints to constexpr floats. Please let me know if you're not seeing that on your end, and I can try to update the PR again. Please let me know as well if there are any other changes you would like me to implement.

2023-08-18 12:48 UTC, perrotta commented
@lutuck please open the "Files changed" tab in this PR in github and go through the several other comments of @emanueleusai that you did not apply yet

2023-08-19 02:11 UTC, lutuck commented
@perrotta I apologize for the confusion, I have now resolved the other comments for the header file. Please let me know if there are any other changes you'd like to make for this PR.

2023-08-19 02:12 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36658

- This PR adds an extra 28KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36658/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36658/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2023-08-19 02:36 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-42155/36659

- This PR adds an extra 28KB to repository

2023-08-19 02:37 UTC, cmsbuild commented
Pull request #42155 was updated. @nothingface0, @emanueleusai, @cmsbuild, @pmandrik, @syuvivida, @tjavaid, @micsucmed, @rvenditti can you please check and sign again.

2023-08-19 06:02 UTC, perrotta commented
@lutuck I still see some unanswered comment in https://github.com/cms-sw/cmssw/pull/42155/files
Can't you also see them?

2023-08-19 12:58 UTC, cmsbuild commented
Pull request #42155 was updated. @nothingface0, @emanueleusai, @cmsbuild, @pmandrik, @syuvivida, @tjavaid, @micsucmed, @rvenditti can you please check and sign again.

2023-08-21 08:43 UTC, syuvivida commented
+1

2023-08-21 08:44 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs after it passes the integration tests. This pull request will now be reviewed by the release team before it's merged. @perrotta, @dpiparo, @antoniovilela, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2023-08-21 14:07 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3f4d2d/34372/summary.html
**COMMIT**: 1961347a396bcf057b41acebd318cb9604976a33
**CMSSW**: CMSSW_13_3_X_2023-08-20-2300/el8_amd64_gcc11
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/42155/34372/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially added 11 lines to the logs
 - Reco comparison results: 7 differences found in the comparisons
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3152915
 - DQMHistoTests: Total failures: 6
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3152887
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 1129.1800000000005 KiB( 47 files compared)
 - DQMHistoSizes: changed ( 10024.0,... ): 56.459 KiB       L1T/L1TStage2EMTF
 - Checked 207 log files, 159 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-20-2300+3f4d2d/58510/triggerResults): no differences found

2023-08-21 15:38 UTC, merged

2023-09-19 20:56 UTC, syuvivida commented
@lutuck 
 We don't seem to find the 13_2_X version of this PR. Could you create a backport to 13_2_X? For the time being, we are adding this PR on top of 13_2_3 and 13_2_4 but it would be easier for DQM if this PR is merged in one of the 13_2_X releases in the coming future. Thanks!!

2023-09-21 16:41 UTC, eyigitba commented
@syuvivida , I think @lutuck won't be able to help with this. I can handle the backport to 13_2_X tomorrow.