Emulator cluster firmware style
cms-sw/cmssw pull request #43363
Opened 2023-11-22 15:50 UTC by SClarkPhysics

This PR changes the TrackJet Emulation Clustering algorithm to more closely match what is done in firmware. Specifically, it changes the way the binning is done in the ηφ plane. We also change the python config file so that the max eta is appropriately set, which is used in the APx workflow

This has already been merged to cms-l1t-offline:phase2-l1t-integration-13_3_0_pre3 via [PR 1170](https://github.com/cms-l1t-offline/cmssw/pull/1170) . See discussion there

2023-11-22 15:57 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43363/37834

- This PR adds an extra 32KB to repository

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43363/37834/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43363/37834/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2023-11-22 16:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43363/37835

- This PR adds an extra 32KB to repository

2023-11-22 16:18 UTC, epalencia commented
Please test

2023-11-22 18:54 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36005/summary.html
**COMMIT**: 717b912931234472d672303daff6834ecb813b1c
**CMSSW**: CMSSW_14_0_X_2023-11-22-1100/el8_amd64_gcc12
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/43363/36005/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [removed 21 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-22-1100+e84fd7/59892/validateJR/logRootQA-events.log) from the logs
 - [Reco comparison results: 137 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-22-1100+e84fd7/59892/validateJR.html)
 - DQMHistoTests: Total files compared: 50
 - DQMHistoTests: Total histograms compared: 3363868
 - DQMHistoTests: [Total failures: 1804](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-22-1100+e84fd7/59892/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3362042
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 49 files compared)
 - Checked 214 log files, 167 edm output root files, 50 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-22-1100+e84fd7/59892/triggerResults): no differences found

2023-11-27 10:07 UTC, aloeliger commented
+l1
- reviewed by L1 here: https://github.com/cms-l1t-offline/cmssw/pull/1170

2023-11-27 17:44 UTC, srimanob commented
+Upgrade

2023-11-28 16:54 UTC, rappoccio requested changes

2023-11-28 16:54 UTC, rappoccio commented on L1Trigger/L1TTrackMatch/plugins/L1TrackJetClustering.h
> +  static constexpr int kThirteenBitMask = 8191;  // 0001111111111111 (bin) = 8191 (dec)
Could these be made into binary literals? Then you don't need the comment and it's clearer for all of the cases.

2023-11-29 12:27 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43363/37963

- This PR adds an extra 32KB to repository

2023-11-29 14:42 UTC, epalencia commented
Please test

2023-11-29 21:07 UTC, epalencia commented
Please test

2023-11-29 23:39 UTC, cmsbuild commented
-1

**Failed Tests**: UnitTests 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36184/summary.html
**COMMIT**: a3ea23be982f8875843a5d7ecdc982bef02474e3
**CMSSW**: CMSSW_14_0_X_2023-11-29-1100/el8_amd64_gcc12
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36184/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Unit Tests

I found 1 errors in the following unit tests:

<pre>---> test test-das-selected-lumis had ERRORS
</pre>

## Comparison Summary



**Summary**:
 - You potentially [removed 11 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-29-1100+e84fd7/60042/validateJR/logRootQA-events.log) from the logs
 - [Reco comparison results: 24 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-29-1100+e84fd7/60042/validateJR.html)
 - DQMHistoTests: Total files compared: 50
 - DQMHistoTests: Total histograms compared: 3372451
 - DQMHistoTests: [Total failures: 1184](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-29-1100+e84fd7/60042/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3371245
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 49 files compared)
 - Checked 214 log files, 167 edm output root files, 50 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-29-1100+e84fd7/60042/triggerResults): no differences found

2023-11-30 10:13 UTC, aloeliger commented
please test

The quoted error is with an x509 proxy, which this PR should have no way of affecting. I would imagine/hope the error is temporary

2023-11-30 11:32 UTC, cmsbuild commented
-1

**Failed Tests**: RelVals RelVals-INPUT AddOn 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36193/summary.html
**COMMIT**: a3ea23be982f8875843a5d7ecdc982bef02474e3
**CMSSW**: CMSSW_14_0_X_2023-11-29-2300/el8_amd64_gcc12
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/install.sh` to create a dev area with all the needed externals and cmssw changes.


## RelVals

- [5.1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36193/runTheMatrix-results/5.1_TTbarFS)
```
----- Begin Fatal Exception 30-Nov-2023 11:35:38 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named TTbar_8TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_VALIDATION_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoTracker/FinalTrackSelectors/data/TrackTfClassifier/MkFitDisplacedRegionalOnly_Run3_12_5_0_pre5.pb anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/matrix-results/5.1_TTbarFS


At:
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Types.py(881): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(381): insertContentsInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(516): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1216): _insertManyInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1502): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
- [135.4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36193/runTheMatrix-results/135.4_ZEEFS_13)
```
----- Begin Fatal Exception 30-Nov-2023 11:35:38 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ZEE_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_VALIDATION_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoTracker/FinalTrackSelectors/data/TrackTfClassifier/MkFitDisplacedRegionalOnly_Run3_12_5_0_pre5.pb anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/matrix-results/135.4_ZEEFS_13


At:
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Types.py(881): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(381): insertContentsInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(516): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1216): _insertManyInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1502): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
- [138.4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36193/runTheMatrix-results/138.4_PromptCollisions2021)
```
----- Begin Fatal Exception 30-Nov-2023 11:35:51 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_RAW2DIGI_L1Reco_RECO_ALCA_DQM.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file RecoTracker/FinalTrackSelectors/data/TrackTfClassifier/MkFitDisplacedRegionalOnly_Run3_12_5_0_pre5.pb anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36193/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/poison:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/external/el8_amd64_gcc12/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-relvals/matrix-results/138.4_PromptCollisions2021


At:
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Types.py(881): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(381): insertContentsInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Mixins.py(516): insertInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1216): _insertManyInto
  /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-29-2300/src/FWCore/ParameterSet/python/Config.py(1502): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```
<details>
<summary>Expand to see more relval errors ...</summ [...]

2023-11-30 16:11 UTC, epalencia commented
Please test

2023-11-30 19:27 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e84fd7/36211/summary.html
**COMMIT**: a3ea23be982f8875843a5d7ecdc982bef02474e3
**CMSSW**: CMSSW_14_0_X_2023-11-30-1100/el8_amd64_gcc12
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43363/36211/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [removed 50 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-30-1100+e84fd7/60059/validateJR/logRootQA-events.log) from the logs
 - [Reco comparison results: 32 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-30-1100+e84fd7/60059/validateJR.html)
 - DQMHistoTests: Total files compared: 50
 - DQMHistoTests: Total histograms compared: 3370032
 - DQMHistoTests: [Total failures: 1219](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-30-1100+e84fd7/60059/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3368791
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 49 files compared)
 - Checked 214 log files, 167 edm output root files, 50 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-30-1100+e84fd7/60059/triggerResults): no differences found

2023-12-04 15:54 UTC, aloeliger commented
+l1

- Good from the L1 side, already reviewed in https://github.com/cms-l1t-offline/cmssw/pull/1170
- Bit pattern changes done.

2023-12-05 20:53 UTC, srimanob commented
Hi @SClarkPhysics @aloeliger @rappoccio 
I see a request change by @rappoccio but I can't find what is the quest. When I click on request change button, it just point to the code, but I have no clue what is a request.

2023-12-06 17:20 UTC, SClarkPhysics commented
Hi @srimanob , the request was to change the variables from decimal to binary literals. I implemented these changes in this commit: https://github.com/cms-sw/cmssw/pull/43363/commits/a3ea23be982f8875843a5d7ecdc982bef02474e3 

I had to expand a box that said "24 hidden items" in this thread to see the original request

2023-12-06 19:21 UTC, srimanob commented
+Upgrade

2023-12-06 19:21 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @antoniovilela, @sextonkennedy, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2023-12-08 17:23 UTC, merged