Nano branches from ValueMap of elaborated types [WIP]
cms-sw/cmssw pull request #43916
Opened 2024-02-08 14:33 UTC by vlimant

#### PR description:

in order to enable table extension, using elaborated types (other than int, float, ...) some specific templated producer need to be added.

#### PR validation:

code does not compile because of r-value arguments I am unable to solve ATM

2024-02-08 14:33 UTC, cmsbuild commented
cms-bot internal usage<!-- bot cache: {"commits":{"b9de1e079981ed1e667ff603aa02c2ed9a693e6d":{"files":["PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h","PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc"],"squashed":false,"time":1707399062}},"emoji":{},"last_seen_sha":"b9de1e079981ed1e667ff603aa02c2ed9a693e6d","signatures":{}} -->

2024-02-08 14:34 UTC, vlimant commented on PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
> +      : ValueMapVariable<ObjType, VarType, ValType>(aname, cfg, cc, skipNonExistingSrc),
it failes on passing `cc` around ; any clue anyone ?

2024-02-08 14:35 UTC, vlimant commented
meant to help with #43525

2024-02-08 14:41 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38766

ERROR: Build errors found during clang-tidy run.
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/unique_ptr.h:1065:34: note: in instantiation of member function 'TypedValueMapVariable<reco::Candidate, reco::Candidate, StringObjectFunction<reco::Candidate>, int>::TypedValueMapVariable' requested here
--
PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:125:9: error: no matching constructor for initialization of 'ValueMapVariable<Candidate, int, short>' [clang-diagnostic-error]
  125 |       : ValueMapVariable<ObjType, VarType, ValType>(aname, cfg, cc, skipNonExistingSrc),
      |         ^                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/unique_ptr.h:1065:34: note: in instantiation of member function 'TypedValueMapVariable<reco::Candidate, reco::Candidate, StringObjectFunction<reco::Candidate>, int, short>::TypedValueMapVariable' requested here
--
PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:125:9: error: no matching constructor for initialization of 'ValueMapVariable<Candidate, int, unsigned char>' [clang-diagnostic-error]
  125 |       : ValueMapVariable<ObjType, VarType, ValType>(aname, cfg, cc, skipNonExistingSrc),
      |         ^                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/unique_ptr.h:1065:34: note: in instantiation of member function 'TypedValueMapVariable<reco::Candidate, reco::Candidate, StringObjectFunction<reco::Candidate>, int, unsigned char>::TypedValueMapVariable' requested here
--
PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:125:9: error: no matching constructor for initialization of 'ValueMapVariable<Candidate, int, unsigned short>' [clang-diagnostic-error]
  125 |       : ValueMapVariable<ObjType, VarType, ValType>(aname, cfg, cc, skipNonExistingSrc),
      |         ^                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/unique_ptr.h:1065:34: note: in instantiation of member function 'TypedValueMapVariable<reco::Candidate, reco::Candidate, StringObjectFunction<reco::Candidate>, int, unsigned short>::TypedValueMapVariable' requested here
--
PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h:125:9: error: no matching constructor for initialization of 'ValueMapVariable<Candidate, unsigned int, unsigned int>' [clang-diagnostic-error]
  125 |       : ValueMapVariable<ObjType, VarType, ValType>(aname, cfg, cc, skipNonExistingSrc),
      |         ^                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02823/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/unique_ptr.h:1065:34: note: in instantiation of member function 'TypedValueMapVariable<reco::Candidate, reco::Candidate, StringObjectFunction<reco::Candidate>, unsigned int>::TypedValueMapVariable' requested here
--
gmake: *** [config/SCRAM/GMake/Makefile.coderules:129: code-checks] Error 2
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```

2024-02-08 15:05 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38767

- This PR adds an extra 24KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h  modified in PR(s): #43525
  - File  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc  modified in PR(s): #43525

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38767/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38767/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2024-02-09 11:32 UTC, vlimant commented
enable nano

2024-02-09 11:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38781

- This PR adds an extra 24KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h  modified in PR(s): #43525
  - File  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc  modified in PR(s): #43525

2024-02-09 11:39 UTC, cmsbuild commented
A new Pull Request was created by  @vlimant (vlimant) for master.

It involves the following packages:

- PhysicsTools/NanoAOD (**xpog**)


@cmsbuild, @hqucms, @vlimant can you please review it and eventually sign? Thanks.
@AnnikaStein, @gpetruc this is something you requested to watch as well.
@sextonkennedy, @rappoccio, @antoniovilela you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2024-02-09 11:40 UTC, vlimant commented
please test

2024-02-09 11:50 UTC, cmsbuild commented
-1

**Failed Tests**:   ClangBuild 
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e7e804/37324/summary.html
**COMMIT**: 00c69786fea005c1f08c5324aacd0c9461be7d35
**CMSSW**: CMSSW_14_1_X_2024-02-09-1100/el8_amd64_gcc12
**Additional Tests**: NANO
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/43916/37324/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Clang Build

I found compilation warning while trying to compile with clang. Command used:
```
USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

```
 See details on the summary page.

2024-02-12 10:52 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38806

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h  modified in PR(s): #43525
  - File  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc  modified in PR(s): #43525

2024-02-12 10:59 UTC, vlimant commented
please test

2024-02-12 11:10 UTC, mbluj requested changes
@vlimant Thank you for this development. I tested it with my setup and it works fine after implementing a few fixes here and there (see directly in code & one below).
How I should proceed? Should I introduce those changes into my PR or this one is added and then my development branch is rebased on top of it? The former is simpler for me.

L345 & L352:
`if (!extvars_.empty())` => `if (!extvars_.empty() || !typedextvars_.empty())`

2024-02-12 11:15 UTC, mbluj commented
@vlimant Hi my comments are partly outdated as were given to previous version of the development, but some are still valid.

2024-02-12 13:24 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38809

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h  modified in PR(s): #43525
  - File  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc  modified in PR(s): #43525

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38809/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38809/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

2024-02-12 13:30 UTC, vlimant commented on PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
> +    extvariable.add<edm::InputTag>("src")->setComment("valuemap input collection to fill the flat table");
thanks indeed

2024-02-12 13:30 UTC, vlimant commented on PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
> +  typedef TypedValueMapVariable<T, V, StringObjectFunction<V>, int, uint16_t> UInt16TypedExtVar;
the intermediate template type is actually not necessary

2024-02-12 13:36 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-43916/38810

- This PR adds an extra 20KB to repository

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h  modified in PR(s): #43525
  - File  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc  modified in PR(s): #43525

2024-02-12 13:36 UTC, cmsbuild commented
Pull request #43916 was updated. @hqucms, @cmsbuild, @vlimant can you please check and sign again.

2024-02-12 13:36 UTC, vlimant commented
please test

2024-02-12 13:38 UTC, vlimant commented
@mbluj : I think that the best way is to merge this, and you rebase #43525 to pick up and use the feature (removing `SimpleCandidate2CandidateFlatTableProducer`) along the way

2024-02-12 14:03 UTC, mbluj commented
> @mbluj : I think that the best way is to merge this, and you rebase #43525 to pick up and use the feature (removing `SimpleCandidate2CandidateFlatTableProducer`) along the way

OK, so I am waiting until this is merged. Could it be also backported to 14_0?

2024-02-12 19:57 UTC, cmsbuild commented
+1

**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e7e804/37371/summary.html
**COMMIT**: 20f3d137843b970ef0c1372261765963ed78198c
**CMSSW**: CMSSW_14_1_X_2024-02-12-1100/el8_amd64_gcc12
**Additional Tests**: NANO
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/43916/37371/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [removed 92 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-12-1100+e7e804/61015/validateJR/logRootQA-events.log) from the logs
 - [Reco comparison results: 37 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-12-1100+e7e804/61015/validateJR.html)
 - DQMHistoTests: Total files compared: 48
 - DQMHistoTests: Total histograms compared: 3248626
 - DQMHistoTests: [Total failures: 0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-12-1100+e7e804/61015/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3248604
 - DQMHistoTests: Total skipped: 22
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 47 files compared)
 - Checked 200 log files, 161 edm output root files, 48 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-12-1100+e7e804/61015/triggerResults): no differences found


## NANO Comparison Summary



**Summary**:
 - You potentially [added 4 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-02-12-1100+e7e804/61012/validateJR/logRootQA-events.log) to the logs
 - [Reco comparison results: 0 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-02-12-1100+e7e804/61012/validateJR.html)
 - DQMHistoTests: Total files compared: 15
 - DQMHistoTests: Total histograms compared: 16524
 - DQMHistoTests: [Total failures: 0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-02-12-1100+e7e804/61012/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 16524
 - DQMHistoTests: Total skipped: 0
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 14 files compared)
 - Checked 38 log files, 18 edm output root files, 15 DQM output files

**Nano size comparison Summary**:

| Sample | kb/ev | ref kb/ev | diff kb/ev | ev/s/thd | ref ev/s/thd | diff rate | mem/thd | ref mem/thd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2500.0 | 2.545 | 2.545 | 0.000 ( +0.0% ) | 5.23 | 5.16 | +1.3% | 2.135 | 2.152 |
| 2500.001 | 2.692 | 2.692 | 0.000 ( +0.0% ) | 4.68 | 4.75 | -1.6% | 2.561 | 2.581 |
| 2500.002 | 2.631 | 2.631 | 0.000 ( +0.0% ) | 4.91 | 4.93 | -0.4% | 2.571 | 2.583 |
| 2500.01 | 1.315 | 1.315 | 0.000 ( +0.0% ) | 9.58 | 9.53 | +0.6% | 2.258 | 2.304 |
| 2500.011 | 1.732 | 1.732 | 0.000 ( +0.0% ) | 5.15 | 5.30 | -2.9% | 2.361 | 2.437 |
| 2500.012 | 1.578 | 1.578 | 0.000 ( +0.0% ) | 7.43 | 7.52 | -1.1% | 2.287 | 2.321 |
| 2500.1 | 2.193 | 2.193 | 0.000 ( +0.0% ) | 5.30 | 5.32 | -0.3% | 1.976 | 2.045 |
| 2500.2 | 2.307 | 2.307 | 0.000 ( +0.0% ) | 6.05 | 6.06 | -0.3% | 1.873 | 1.961 |
| 2500.21 | 1.183 | 1.183 | 0.000 ( +0.0% ) | 4.30 | 4.36 | -1.5% | 2.144 | 2.245 |
| 2500.211 | 1.547 | 1.547 | 0.000 ( +0.0% ) | 3.78 | 3.74 | +1.1% | 2.159 | 2.326 |
| 2500.3 | 2.063 | 2.063 | 0.000 ( +0.0% ) | 12.55 | 12.71 | -1.3% | 1.878 | 1.945 |
| 2500.31 | 1.258 | 1.258 | 0.000 ( +0.0% ) | 19.65 | 20.42 | -3.8% | 2.225 | 2.335 |
| 2500.311 | 1.646 | 1.646 | 0.000 ( +0.0% ) | 13.51 | 13.70 | -1.4% | 2.276 | 2.394 |
| 2500.312 | 7.159 | 7.159 | 0.000 ( +0.0% ) | 1.43 | 1.41 | +0.8% | 1.675 | 1.676 |
| 2500.313 | 1.564 | 1.564 | 0.000 ( +0.0% ) | 6.67 | 6.53 | +2.1% | 1.023 | 1.030 |
| 2500.4 | 2.063 | 2.063 | 0.000 ( +0.0% ) | 12.65 | 12.67 | -0.2% | 1.877 | 1.955 |
| 2500.5 | 19.575 | 19.575 | 0.000 ( +0.0% ) | 1.19 | 1.22 | -2.7% | 1.071 | 1.116 |

2024-02-13 10:33 UTC, vlimant commented
+1

2024-02-13 10:33 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @sextonkennedy, @antoniovilela, @rappoccio (and backports should be raised in the release meeting by the corresponding L2)

2024-02-13 10:36 UTC, mbluj commented
Many thanks @vlimant! I am moving my development on top of it.
Could this development be also backported to 14_0 series, please?

2024-02-13 13:59 UTC, antoniovilela commented
+1

2024-02-13 13:59 UTC, merged

2024-02-21 12:16 UTC, mbluj commented
For reference: backported to 14_0_X in #44040.