Decrease error threshold for BadCapIDThreshold QTest
cms-sw/cmssw pull request #45602
Opened 2024-07-31 08:21 UTC by nothingface0

#### PR description:

As discussed with @DennRoy, This PR decreases the `error` threshold of the Hcal `BadCapIDThreshold` QTest, i.e., makes the test more tolerant to errors, allowing the up to any 3 bins to fail the test for the whole plot (which translates to ~99.9% error threshold for 60x42 bins that the plot contains). 

A backport will also be created, to patch the DQM production CMSSW deployment.

2024-07-31 08:22 UTC, cmsbuild commented
cms-bot internal usage<!-- bot cache: {"commits":{"3acbc092e17fec9ca0a8fe5c39402463c4cf8771":{"files":["DQM/HcalTasks/data/HcalQualityTests.xml"],"squashed":false,"time":1722406514}},"emoji":{},"last_seen_sha":"3acbc092e17fec9ca0a8fe5c39402463c4cf8771","signatures":{}} -->

2024-07-31 08:27 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45602/41095

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQM/HcalTasks/data/HcalQualityTests.xml  modified in PR(s): #45571

2024-07-31 21:23 UTC, DryRun requested changes
Thanks for preparing the PR! I have one request: the tuned threshold only applied to the 60*42 bin histogram, "Hcal/DigiTask/CapID/CapID_BadvsLSmod60", but the LINK wildcard also matches "Hcal/DigiTask/CapID/CapID_BadvsLS". The test should only be run on the former histogram, so the wildcard should be changed to `*CapID_BadvsLSmod60*`.

2024-08-01 09:29 UTC, nothingface0 commented
> Thanks for preparing the PR! I have one request: the tuned threshold is only valid for the 60*42 bin histogram, "Hcal/DigiTask/CapID/CapID_BadvsLSmod60", but the LINK wildcard also matches "Hcal/DigiTask/CapID/CapID_BadvsLS" (4000*42 bins; the mod60 histogram was created so that the alarm condition goes away after 60 LSes and stops sounding the alarm). The test should only be run on the former histogram, so the wildcard should be changed to `*CapID_BadvsLSmod60*`.

Thanks for the catch, I updated the PR

2024-08-01 09:31 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45602/41115

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQM/HcalTasks/data/HcalQualityTests.xml  modified in PR(s): #45571

2024-08-01 09:31 UTC, cmsbuild commented
Pull request #45602 was updated. @antoniovagnerini, @cmsbuild, @nothingface0, @rvenditti, @syuvivida, @tjavaid can you please check and sign again.

2024-08-07 12:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45602/41201

- There are other open Pull requests which might conflict with changes you have proposed:
  - File  DQM/HcalTasks/data/HcalQualityTests.xml  modified in PR(s): #45571

2024-08-07 12:51 UTC, cmsbuild commented
Pull request #45602 was updated. @antoniovagnerini, @cmsbuild, @nothingface0, @rvenditti, @syuvivida, @tjavaid can you please check and sign again.

2024-08-08 07:42 UTC, tjavaid commented
please test

2024-08-08 11:05 UTC, cmsbuild commented
+1

**Size**: This PR adds an extra 12KB to repository
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f6560b/40827/summary.html
**COMMIT**: 6e1f4e555329827fb92ba1ab076f3dac32a3e807
**CMSSW**: CMSSW_14_1_X_2024-08-07-2300/el8_amd64_gcc12
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/45602/40827/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [removed 1 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-07-2300+f6560b/63930/validateJR/logRootQA-events.log) from the logs
 - [Reco comparison results: 94 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-07-2300+f6560b/63930/validateJR.html)
 - DQMHistoTests: Total files compared: 45
 - DQMHistoTests: Total histograms compared: 3423977
 - DQMHistoTests: [Total failures: 2463](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-07-2300+f6560b/63930/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3421494
 - DQMHistoTests: Total skipped: 20
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 44 files compared)
 - Checked 196 log files, 165 edm output root files, 45 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-07-2300+f6560b/63930/triggerResults): no differences found

2024-08-13 09:40 UTC, closed without merging

2024-08-13 09:41 UTC, nothingface0 commented
Closing in favor of #45571