[Do not merge] Testing Python formatting workflow with cmsbot
cms-sw/cmssw pull request #45616
Opened 2024-08-01 13:52 UTC by Benedikttk

As previously discussed at the CoreSoftware meeting at 30/Jul,2024: [indico link](https://indico.cern.ch/event/1442038/) . This PR aims to test python code quality checks in the CMSSW infrastructure and is not meant to be merged: testing of Python formatting workflow with cmsbot is being implemented.

2024-08-01 13:52 UTC, cmsbuild commented
cms-bot internal usage<!-- bot cache: {"commits":{"b554b6f13e5013d7c572ca41c8984bf5aa53cc9a":{"files":["FWCore/Framework/python/test/cmsExceptionsFatalOption_cff.py","FWCore/Framework/python/test/cmsExceptionsFatal_cff.py"],"squashed":false,"time":1722512533}},"emoji":{},"last_seen_sha":"b554b6f13e5013d7c572ca41c8984bf5aa53cc9a","signatures":{}} -->

2024-08-01 13:56 UTC, cmsbuild commented
A new Pull Request was created by  @Benedikttk for master.

It involves the following packages:

- FWCore/Framework (**core**)


@Dr15Jones, @cmsbuild, @makortel, @smuzaffar can you please review it and eventually sign? Thanks.
@makortel, @missirol, @wddgit this is something you requested to watch as well.
@antoniovilela, @mandrenguyen, @rappoccio, @sextonkennedy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2024-08-06 10:09 UTC, aandvalenzuela commented
code-checks

2024-08-07 08:25 UTC, aandvalenzuela commented
code-checks

2024-08-07 08:36 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41189

2024-08-07 08:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41190

2024-08-07 08:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41191

2024-08-07 08:49 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41194

2024-08-07 08:54 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41195

2024-08-07 09:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41197

2024-08-07 09:28 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41198

2024-08-07 10:27 UTC, cmsbuild commented
-python-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41200

ERROR: Ruff found formatting errors on the python files.
```
diff --git a/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py b/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
index bb24a02020c..6be187332b0 100644
--- a/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
+++ b/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
@@ -3,5 +3,5 @@ import FWCore.ParameterSet.Config as cms
 import FWCore.Framework.test.cmsExceptionsFatalOption_cff
 
 options = cms.untracked.PSet(
-  Rethrow = FWCore.Framework.test.cmsExceptionsFatalOption_cff.Rethrow
+    Rethrow=FWCore.Framework.test.cmsExceptionsFatalOption_cff.Rethrow
 )
```

2024-08-13 10:29 UTC, cmsbuild commented
-python-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41261

ERROR: Ruff found formatting errors on the python files.
```
diff --git a/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py b/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
index bb24a02020c..6be187332b0 100644
--- a/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
+++ b/FWCore/Framework/python/test/cmsExceptionsFatal_cff.py
@@ -3,5 +3,5 @@ import FWCore.ParameterSet.Config as cms
 import FWCore.Framework.test.cmsExceptionsFatalOption_cff
 
 options = cms.untracked.PSet(
-  Rethrow = FWCore.Framework.test.cmsExceptionsFatalOption_cff.Rethrow
+    Rethrow=FWCore.Framework.test.cmsExceptionsFatalOption_cff.Rethrow
 )
```

2024-08-14 08:47 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41303

2024-08-14 08:57 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41304

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41304/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41304/python-code-format.patch | patch -p1`
You can also run `python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-14 09:16 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41305

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41305/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41305/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41305/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41305/python-code-format.patch | patch -p1`
You can also run `python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-14 09:28 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41306

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41306/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41306/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

2024-08-14 09:35 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41307

2024-08-14 10:10 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41308

2024-08-14 10:17 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41309

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41309/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41309/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

2024-08-14 14:27 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41316

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41316/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41316/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

2024-08-14 14:43 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41318

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41318/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41318/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

2024-08-14 15:19 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41321/python-code-format.patch

2024-08-14 15:19 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41321

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41321/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41321/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

2024-08-14 15:28 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322/python-code-format.patch

2024-08-14 15:28 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41322/python-code-format.patch | patch -p1`
You can also run `python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-15 08:58 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327/python-code-format.patch

2024-08-15 08:59 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-checks**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327/code-checks.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327/code-checks.patch | patch -p1`
You can also run `scram build code-checks` to apply code checks directly

- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41327/python-code-format.patch | patch -p1`
You can also run `python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-15 09:25 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328/python-code-format.patch

2024-08-15 09:25 UTC, cmsbuild commented
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328

Code check has found code style and quality issues which could be resolved by applying following patch(s)

- **code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328/code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328/code-format.patch | patch -p1`
You can also run `scram build code-format` to apply code format directly

- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41328/python-code-format.patch | patch -p1`
You can also run `python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-15 09:30 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41329/python-code-format.patch

2024-08-15 09:30 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41329

2024-08-15 10:41 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41334/python-code-format.patch

2024-08-15 10:41 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41334

2024-08-15 10:52 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41335/python-code-format.patch

2024-08-15 10:52 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41335

2024-08-15 11:10 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41336/python-code-format.patch

2024-08-15 11:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41336

2024-08-15 14:34 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41342

2024-08-15 14:34 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41342/python-code-format.patch

2024-08-15 14:58 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41343

2024-08-15 14:58 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41343/python-code-format.patch

2024-08-15 15:10 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41344

2024-08-15 15:16 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41345

2024-08-15 15:16 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:

 https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41345/python-code-format.patch


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41345/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41345/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-16 08:37 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41351

2024-08-16 08:37 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41351/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41351/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-16 08:38 UTC, Benedikttk commented
code-checks

2024-08-16 08:41 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41352

2024-08-16 08:41 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41352/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41352/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-16 09:46 UTC, aandvalenzuela requested changes
*

2024-08-16 09:48 UTC, aandvalenzuela requested changes

2024-08-16 09:48 UTC, aandvalenzuela commented on FWCore/Framework/python/test/cmsExceptionsFatalOption_cff.py
> +    "CommandLineProcessing",
```suggestion
    "CommandLineProcessing2",
```

2024-08-16 09:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41354

2024-08-16 09:51 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41354/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41354/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-16 09:51 UTC, cmsbuild commented
Pull request #45616 was updated. @Dr15Jones, @cmsbuild, @makortel, @smuzaffar can you please check and sign again.

2024-08-19 08:55 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41391

2024-08-19 08:55 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41391/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41391/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:01 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41393

2024-08-19 09:01 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41393/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41393/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:04 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41394

2024-08-19 09:04 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41394/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41394/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:23 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41398/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41398/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41399

2024-08-19 09:39 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41399/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41399/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:54 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41400

2024-08-19 09:54 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41400/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41400/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 09:58 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41401

2024-08-19 09:58 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41401/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41401/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 10:01 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41402

2024-08-19 10:01 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41402/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41402/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 11:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41403

2024-08-19 11:13 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41403/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41403/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 11:17 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41404

2024-08-19 11:17 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41404/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41404/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 11:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41407

2024-08-19 11:25 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41407/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41407/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 11:33 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41408

2024-08-19 11:33 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41408/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41408/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 11:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41409

2024-08-19 11:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41410

2024-08-19 12:07 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41411

2024-08-19 12:07 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41411/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41411/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly

2024-08-19 12:13 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41412

2024-08-19 12:17 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41413

2024-08-19 12:17 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41413/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41413/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly
  - Status: All checks passed!  😊

2024-08-19 12:18 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41414

2024-08-19 12:18 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41414/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41414/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly
  - Status: All checks passed!  😊

2024-08-19 12:25 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41415

2024-08-19 12:25 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41415/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41415/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: All checks passed!  😊

2024-08-19 12:33 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41416

2024-08-19 12:33 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41416/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41416/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: All linting checks passed!  😊

2024-08-19 12:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41418

2024-08-19 12:57 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41418/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41418/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: All linting checks passed!  😊

2024-08-19 14:00 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41419

2024-08-19 14:00 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41419/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41419/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. Please check the file 'python-linting.txt' for details. 😢
You can also use the run 'ruff check <file.py> --fix' to automatically apply fixes.

2024-08-19 14:00 UTC, cmsbuild commented
Pull request #45616 was updated. @Dr15Jones, @antoniovagnerini, @cmsbuild, @consuegs, @makortel, @nothingface0, @perrotta, @rvenditti, @saumyaphor4252, @smuzaffar, @syuvivida, @tjavaid can you please check and sign again.

2024-08-19 14:23 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41423

2024-08-19 14:23 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41423/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41423/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. Please check the file 'python-linting.txt' for details. 😢
You can also use the run 'ruff check <file.py> --fix' to automatically apply fixes.

2024-08-19 14:30 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41424

2024-08-19 14:30 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41424/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41424/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41424/python-linting.txt
You can also use the run 'ruff check <file.py> --fix' to automatically apply fixes.

2024-08-19 14:36 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41425

2024-08-19 14:36 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41425/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41425/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41425/python-linting.txt
You can also run run \'ruff check <file.py> --fix\' to automatically apply fixes.

2024-08-19 14:39 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41426

2024-08-19 14:39 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41426/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41426/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41426/python-linting.txt
You can also run run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to automatically apply fixes.

2024-08-19 14:42 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41427/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41427/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41427/python-linting.txt
You can also run run `ruff check --fix` to automatically apply fixes.

2024-08-19 14:50 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41428

2024-08-19 14:50 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41428/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41428/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41428/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-19 14:57 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41429

2024-08-19 14:57 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41429/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41429/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41429/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-19 15:02 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41430

2024-08-19 15:02 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41430/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41430/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41430/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-19 15:14 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41436

2024-08-19 15:14 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41436/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41436/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41436/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-20 08:02 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41442

2024-08-20 08:02 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41442/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41442/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41442/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-20 12:45 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41448

2024-08-20 12:45 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41448/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41448/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41448/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-20 12:53 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41450

2024-08-20 12:53 UTC, cmsbuild commented
INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. 

 Ruff found formatting errors on the python files in this PR.

 We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.

 This is a non-blocking check, but feel free to contribute and apply the following formatting patch:


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41450/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41450/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41450/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-20 13:08 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41451

2024-08-20 13:14 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41452

2024-08-20 13:27 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41454

2024-08-20 13:35 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41456

2024-08-20 13:43 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41457

2024-08-20 13:43 UTC, cmsbuild commented
INFO: We're applying PEP8 formatting to CMSSW using Ruff; while Ruff found formatting errors in the PR's Python files, this non-blocking check may flag untouched lines, so feel free to contribute by applying the suggested patch.


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41457/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-23 08:51 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41507

2024-08-23 08:51 UTC, cmsbuild commented
INFO: We're applying PEP8 formatting to CMSSW using Ruff; while Ruff found formatting errors in the PR's Python files, this non-blocking check may flag untouched lines, so feel free to contribute by applying the suggested patch.


- **python-code-format**:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41507/python-code-format.patch
e.g. `curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41507/python-code-format.patch | patch -p1`
You can also run `python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>` to apply Python code formatting directly


- **python-code-linting**:
Status: There are some linting recommendations that need your attention. 😢
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45616/41507/python-linting.txt
You can also run `ruff check --fix` to automatically apply fixes.

2024-08-23 08:51 UTC, cmsbuild commented
Pull request #45616 was updated. @Dr15Jones, @antoniovagnerini, @cmsbuild, @consuegs, @makortel, @nothingface0, @perrotta, @rvenditti, @saumyaphor4252, @smuzaffar, @syuvivida, @tjavaid can you please check and sign again.

2024-08-27 08:10 UTC, cmsbuild commented
Milestone for this pull request has been moved to CMSSW_14_2_X. Please open a backport if it should also go in to CMSSW_14_1_X.

2024-09-03 09:32 UTC, antoniovilela commented
ping (to make bot change milestone)

2024-11-22 13:11 UTC, cmsbuild commented
Milestone for this pull request has been moved to CMSSW_15_0_X. Please open a backport if it should also go in to CMSSW_14_2_X.

2025-02-07 08:32 UTC, cmsbuild commented
Milestone for this pull request has been moved to CMSSW_15_1_X. Please open a backport if it should also go in to CMSSW_15_0_X.

2025-08-28 21:05 UTC, makortel commented
@smuzaffar Do we still need this PR open?

2025-09-01 09:59 UTC, smuzaffar commented
no, we do not need this

2025-09-01 09:59 UTC, closed without merging