Updates and Bug Fixes for NanoAOD related to muon
cms-sw/cmssw pull request #45635
Opened 2024-08-05 09:08 UTC by rbhattacharya04

- Implementation of missing 2 Mu trigger bit for 2017B
- Added TuneP_Pt_Err for standard NanoAODs and omit it from custom muon POG NanoAOD
- Fix of a bug for IsoMu24 trigger bit for custom muon POG NanoAOD

2024-08-05 09:11 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45635/41147

2024-08-05 09:11 UTC, cmsbuild commented
A new Pull Request was created by  @rbhattacharya04 for master.

It involves the following packages:

- PhysicsTools/NanoAOD (**xpog**)


@cmsbuild, @ftorrresd, @hqucms, @vlimant can you please review it and eventually sign? Thanks.
@AnnikaStein, @gpetruc this is something you requested to watch as well.
@antoniovilela, @mandrenguyen, @rappoccio, @sextonkennedy you are the release manager for this.

cms-bot commands are listed <a href="http://cms-sw.github.io/cms-bot-cmssw-cmds.html">here</a>

2024-08-05 09:43 UTC, hqucms commented
enable nano

2024-08-05 09:43 UTC, hqucms commented
please test

2024-08-05 13:36 UTC, cmsbuild commented
+1

**Size**: This PR adds an extra 32KB to repository
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9801df/40759/summary.html
**COMMIT**: 338779529b4f06053a42aeef53087b13916ba22e
**CMSSW**: CMSSW_14_1_X_2024-08-04-2300/el8_amd64_gcc12
**Additional Tests**: NANO
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/45635/40759/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [added 1 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-04-2300+9801df/63877/validateJR/logRootQA-events.log) to the logs
 - ROOTFileChecks: Some differences in event products or their sizes found
 - [Reco comparison results: 105 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-04-2300+9801df/63877/validateJR.html)
 - DQMHistoTests: Total files compared: 45
 - DQMHistoTests: Total histograms compared: 3423977
 - DQMHistoTests: [Total failures: 2470](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-04-2300+9801df/63877/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3421487
 - DQMHistoTests: Total skipped: 20
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 44 files compared)
 - Checked 196 log files, 165 edm output root files, 45 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-04-2300+9801df/63877/triggerResults): no differences found


## NANO Comparison Summary



**Summary**:
 - You potentially [added 1480 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-08-04-2300+9801df/63876/validateJR/logRootQA-events.log) to the logs
 - ROOTFileChecks: Some differences in event products or their sizes found
 - [Reco comparison results: 0 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-08-04-2300+9801df/63876/validateJR.html)
 - DQMHistoTests: Total files compared: 21
 - DQMHistoTests: Total histograms compared: 54913
 - DQMHistoTests: [Total failures: 0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-08-04-2300+9801df/63876/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 54913
 - DQMHistoTests: Total skipped: 0
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 20 files compared)
 - Checked 102 log files, 58 edm output root files, 21 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_1_X_2024-08-04-2300+9801df/63876/triggerResults): no differences found

**Nano size comparison Summary**:

| Sample | kb/ev | ref kb/ev | diff kb/ev | ev/s/thd | ref ev/s/thd | diff rate | mem/thd | ref mem/thd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2500.001 | 2.787 | 2.785 | 0.002 ( +0.1% ) | 3.32 | 3.26 | +1.9% | 6.030 | 6.051 |
| 2500.002 | 2.900 | 2.898 | 0.002 ( +0.1% ) | 2.99 | 2.90 | +2.9% | 6.431 | 6.395 |
| 2500.003 | 2.847 | 2.844 | 0.002 ( +0.1% ) | 3.09 | 3.03 | +2.0% | 6.354 | 6.362 |
| 2500.011 | 1.451 | 1.447 | 0.004 ( +0.3% ) | 5.78 | 5.58 | +3.8% | 2.151 | 2.409 |
| 2500.012 | 1.909 | 1.907 | 0.003 ( +0.1% ) | 3.17 | 3.09 | +2.4% | 2.185 | 2.218 |
| 2500.013 | 1.765 | 1.762 | 0.003 ( +0.2% ) | 4.56 | 4.46 | +2.2% | 2.199 | 2.203 |
| 2500.021 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 1.01 | 0.95 | +6.7% | 2.386 | 2.382 |
| 2500.022 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.98 | 0.92 | +7.1% | 2.387 | 2.375 |
| 2500.023 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.97 | 0.90 | +7.5% | 2.246 | 2.242 |
| 2500.024 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.72 | 0.68 | +6.7% | 2.477 | 2.462 |
| 2500.031 | 0.035 | 0.035 | 0.000 ( +0.0% ) | 0.91 | 0.85 | +7.3% | 2.442 | 2.429 |
| 2500.032 | 0.036 | 0.036 | 0.000 ( +0.0% ) | 0.92 | 0.86 | +7.1% | 2.414 | 2.403 |
| 2500.033 | 0.037 | 0.037 | 0.000 ( +0.0% ) | 0.83 | 0.78 | +7.1% | 2.493 | 2.482 |
| 2500.034 | 0.036 | 0.036 | 0.000 ( +0.0% ) | 0.84 | 0.78 | +7.2% | 2.474 | 2.470 |
| 2500.101 | 2.645 | 2.643 | 0.002 ( +0.1% ) | 9.13 | 8.48 | +7.7% | 6.289 | 6.328 |
| 2500.111 | 1.330 | 1.327 | 0.003 ( +0.2% ) | 20.40 | 18.95 | +7.7% | 2.229 | 2.233 |
| 2500.112 | 1.735 | 1.732 | 0.003 ( +0.2% ) | 15.37 | 14.44 | +6.4% | 2.309 | 2.311 |
| 2500.131 | 5.194 | 5.194 | 0.000 ( +0.0% ) | 15.91 | 15.05 | +5.7% | 1.545 | 1.540 |
| 2500.201 | 2.477 | 2.475 | 0.001 ( +0.1% ) | 7.47 | 7.20 | +3.8% | 5.609 | 5.635 |
| 2500.211 | 1.593 | 1.589 | 0.003 ( +0.2% ) | 18.08 | 17.01 | +6.3% | 2.302 | 2.299 |
| 2500.212 | 2.034 | 2.030 | 0.003 ( +0.2% ) | 14.62 | 13.42 | +8.9% | 2.386 | 2.385 |
| 2500.221 | 2.004 | 2.006 | -0.002 ( -0.1% ) | 7.81 | 7.51 | +4.0% | 2.439 | 2.437 |
| 2500.222 | 3.074 | 3.072 | 0.002 ( +0.1% ) | 7.73 | 7.32 | +5.7% | 2.523 | 2.522 |
| 2500.223 | 8.887 | 8.885 | 0.002 ( +0.0% ) | 2.82 | 2.70 | +4.5% | 2.382 | 2.390 |
| 2500.224 | 5.514 | 5.512 | 0.002 ( +0.0% ) | 1.11 | 1.07 | +4.1% | 2.146 | 2.138 |
| 2500.225 | 5.532 | 5.530 | 0.002 ( +0.0% ) | 1.03 | 0.98 | +5.1% | 2.152 | 2.150 |
| 2500.226 | 2.972 | 2.970 | 0.002 ( +0.1% ) | 7.74 | 7.23 | +7.0% | 2.396 | 2.342 |
| 2500.227 | 8.972 | 8.972 | 0.000 ( +0.0% ) | 10.14 | 9.68 | +4.7% | 1.517 | 1.519 |
| 2500.231 | 1.404 | 1.407 | -0.004 ( -0.3% ) | 14.29 | 13.72 | +4.1% | 1.930 | 2.203 |
| 2500.232 | 2.149 | 2.145 | 0.003 ( +0.2% ) | 14.37 | 13.54 | +6.1% | 2.264 | 2.284 |
| 2500.233 | 4.671 | 4.668 | 0.003 ( +0.1% ) | 5.01 | 4.77 | +4.9% | 2.036 | 2.306 |
| 2500.234 | 3.308 | 3.304 | 0.003 ( +0.1% ) | 1.53 | 1.44 | +5.7% | 1.843 | 2.331 |
| 2500.235 | 3.318 | 3.315 | 0.003 ( +0.1% ) | 1.40 | 1.35 | +3.6% | 1.851 | 2.356 |
| 2500.236 | 2.086 | 2.082 | 0.003 ( +0.2% ) | 13.98 | 13.44 | +4.0% | 2.085 | 2.293 |
| 2500.237 | 7.977 | 7.977 | 0.000 ( +0.0% ) | 14.76 | 13.99 | +5.5% | 1.501 | 1.568 |
| 2500.241 | 9.405 | 9.405 | 0.000 ( +0.0% ) | 3.73 | 3.78 | -1.3% | 1.833 | 1.961 |
| 2500.242 | 10.331 | 10.331 | 0.000 ( +0.0% ) | 0.92 | 0.86 | +6.9% | 1.701 | 1.728 |
| 2500.243 | 2.712 | 2.712 | 0.000 ( +0.0% ) | 7.27 | 7.82 | -7.0% | 1.070 | 1.058 |
| 2500.244 | 485.976 | 485.976 | 0.000 ( +0.0% ) | 0.58 | 0.54 | +6.5% | 1.680 | 1.687 |
| 2500.245 | 823.224 | 823.224 | 0.000 ( +0.0% ) | 0.76 | 0.71 | +7.8% | 1.672 | 1.668 |
| 2500.901 | 1.749 | 1.749 | 0.000 ( +0.0% ) | 18.13 | 20.06 | -9.6% | 1.834 | 1.833 |
| 2500.902 | 1.598 | 1.598 | 0.000 ( +0.0% ) | 22.21 | 20.47 | +8.5% | 1.762 | 1.764 |
| 2500.911 | 13.931 | 13.931 | 0.000 ( +0.0% ) | 3.05 | 2.21 | +37.8% | 1.079 | 1.078 |
| 2500.912 | 0.171 | 0.199 | -0.028 ( -14.1% ) | 1.05 | 1.26 | -16.7% | 0.967 | 0.968 |
| 2500.913 | 0.110 | 0.110 | 0.000 ( +0.0% ) | 1.10 | 1.13 | -2.1% | 0.972 | 0.975 |

2024-08-05 15:58 UTC, hqucms requested changes

2024-08-05 15:58 UTC, hqucms commented on PhysicsTools/NanoAOD/python/triggerObjects_cff.py
> +_run2_2017_muon_filters = triggerObjectTable.selections.Muon.qualityBits
It needs a deepcopy here, otherwise `triggerObjectTable.selections.Muon.qualityBits` will also be modified.

2024-08-26 08:50 UTC, hqucms commented on PhysicsTools/NanoAOD/python/triggerObjects_cff.py
> +_run2_2017_muon_filters = triggerObjectTable.selections.Muon.qualityBits
@rbhattacharya04 A gentle reminder.

2024-08-27 08:10 UTC, cmsbuild commented
Milestone for this pull request has been moved to CMSSW_14_2_X. Please open a backport if it should also go in to CMSSW_14_1_X.

2024-09-03 09:32 UTC, antoniovilela commented
ping (to make bot change milestone)

2024-09-04 16:18 UTC, cmsbuild commented
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-45635/41636

2024-09-04 16:18 UTC, cmsbuild commented
Pull request #45635 was updated. @cmsbuild, @ftorrresd, @hqucms, @vlimant can you please check and sign again.

2024-09-04 16:19 UTC, rbhattacharya04 commented on PhysicsTools/NanoAOD/python/triggerObjects_cff.py
> +_run2_2017_muon_filters = triggerObjectTable.selections.Muon.qualityBits
Hi @hqucms, I have added the change.

2024-09-04 16:20 UTC, rbhattacharya04 commented on PhysicsTools/NanoAOD/python/muons_cff.py
> +        tuneP_pterr = Var("tunePMuonBestTrack().ptError()", float, doc = "pTerr from tunePMuonBestTrack", precision=6),
Hi @hqucms, we have discussed among muon pog and we think precision=6 is sufficient.

2024-09-04 16:26 UTC, rbhattacharya04 commented
Added a change in the definition of tkRelIso in the last commit and updated the header.

2024-09-04 16:51 UTC, hqucms commented
please test

2024-09-04 19:55 UTC, cmsbuild commented
+1

**Size**: This PR adds an extra 28KB to repository
**Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9801df/41300/summary.html
**COMMIT**: eee33fc1cb4f3f8e8303f95abd938edecfc04474
**CMSSW**: CMSSW_14_2_X_2024-09-04-1100/el8_amd64_gcc12
**Additional Tests**: NANO
**User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/45635/41300/install.sh` to create a dev area with all the needed externals and cmssw changes.


## Comparison Summary



**Summary**:
 - You potentially [added 4 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-09-04-1100+9801df/64350/validateJR/logRootQA-events.log) to the logs
 - ROOTFileChecks: Some differences in event products or their sizes found
 - [Reco comparison results: 10 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-09-04-1100+9801df/64350/validateJR.html)
 - DQMHistoTests: Total files compared: 44
 - DQMHistoTests: Total histograms compared: 3328501
 - DQMHistoTests: [Total failures: 1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-09-04-1100+9801df/64350/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 3328480
 - DQMHistoTests: Total skipped: 20
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 43 files compared)
 - Checked 193 log files, 163 edm output root files, 44 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-09-04-1100+9801df/64350/triggerResults): no differences found


## NANO Comparison Summary



**Summary**:
 - You potentially [added 845 lines](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_2_X_2024-09-04-1100+9801df/64345/validateJR/logRootQA-events.log) to the logs
 - ROOTFileChecks: Some differences in event products or their sizes found
 - [Reco comparison results: 11 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_2_X_2024-09-04-1100+9801df/64345/validateJR.html)
 - DQMHistoTests: Total files compared: 21
 - DQMHistoTests: Total histograms compared: 55059
 - DQMHistoTests: [Total failures: 15](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_2_X_2024-09-04-1100+9801df/64345/validateJR.html)
 - DQMHistoTests: Total nulls: 0
 - DQMHistoTests: Total successes: 55044
 - DQMHistoTests: Total skipped: 0
 - DQMHistoTests: Total Missing objects: 0
 - DQMHistoSizes: Histogram memory added: 0.0 KiB( 20 files compared)
 - Checked 102 log files, 58 edm output root files, 21 DQM output files
 - [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_2_X_2024-09-04-1100+9801df/64345/triggerResults): no differences found

**Nano size comparison Summary**:

| Sample | kb/ev | ref kb/ev | diff kb/ev | ev/s/thd | ref ev/s/thd | diff rate | mem/thd | ref mem/thd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2500.001 | 2.831 | 2.828 | 0.002 ( +0.1% ) | 3.34 | 3.34 | -0.1% | 6.666 | 6.661 |
| 2500.002 | 2.946 | 2.944 | 0.002 ( +0.1% ) | 2.95 | 2.96 | -0.2% | 7.009 | 7.110 |
| 2500.003 | 2.892 | 2.890 | 0.003 ( +0.1% ) | 3.09 | 3.07 | +0.7% | 6.990 | 6.980 |
| 2500.011 | 1.483 | 1.480 | 0.003 ( +0.2% ) | 5.74 | 5.80 | -1.1% | 2.404 | 2.402 |
| 2500.012 | 1.950 | 1.947 | 0.003 ( +0.2% ) | 3.14 | 3.16 | -0.5% | 2.594 | 2.592 |
| 2500.013 | 1.800 | 1.797 | 0.004 ( +0.2% ) | 4.59 | 4.59 | -0.0% | 2.492 | 2.480 |
| 2500.021 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.99 | 0.99 | +0.1% | 2.219 | 2.207 |
| 2500.022 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.95 | 0.94 | +0.7% | 2.224 | 2.200 |
| 2500.023 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.96 | 0.95 | +0.7% | 2.174 | 2.173 |
| 2500.024 | 0.022 | 0.022 | 0.000 ( +0.0% ) | 0.72 | 0.72 | -0.5% | 2.317 | 2.314 |
| 2500.031 | 0.035 | 0.035 | 0.000 ( +0.0% ) | 0.88 | 0.89 | -1.4% | 2.322 | 2.306 |
| 2500.032 | 0.036 | 0.036 | 0.000 ( +0.0% ) | 0.90 | 0.92 | -2.0% | 2.254 | 2.251 |
| 2500.033 | 0.037 | 0.037 | 0.000 ( +0.0% ) | 0.82 | 0.81 | +0.3% | 2.375 | 2.347 |
| 2500.034 | 0.036 | 0.036 | 0.000 ( +0.0% ) | 0.83 | 0.82 | +1.4% | 2.342 | 2.331 |
| 2500.101 | 2.652 | 2.650 | 0.002 ( +0.1% ) | 9.07 | 9.00 | +0.7% | 6.891 | 6.891 |
| 2500.111 | 1.335 | 1.332 | 0.003 ( +0.2% ) | 20.31 | 20.59 | -1.4% | 2.224 | 2.213 |
| 2500.112 | 1.741 | 1.738 | 0.003 ( +0.2% ) | 15.25 | 15.78 | -3.4% | 2.109 | 2.124 |
| 2500.131 | 5.194 | 5.194 | 0.000 ( +0.0% ) | 16.01 | 16.01 | +0.0% | 1.547 | 1.539 |
| 2500.201 | 2.484 | 2.482 | 0.003 ( +0.1% ) | 7.75 | 7.75 | -0.0% | 6.123 | 6.113 |
| 2500.211 | 1.605 | 1.602 | 0.003 ( +0.2% ) | 17.40 | 17.56 | -0.9% | 2.111 | 2.089 |
| 2500.212 | 2.047 | 2.044 | 0.003 ( +0.2% ) | 13.95 | 13.87 | +0.6% | 2.145 | 2.123 |
| 2500.221 | 2.004 | 2.006 | -0.002 ( -0.1% ) | 7.81 | 7.85 | -0.6% | 2.267 | 2.252 |
| 2500.222 | 3.213 | 3.210 | 0.002 ( +0.1% ) | 7.58 | 7.57 | +0.1% | 2.328 | 2.306 |
| 2500.223 | 8.895 | 8.893 | 0.002 ( +0.0% ) | 2.81 | 2.66 | +5.6% | 2.317 | 2.310 |
| 2500.224 | 5.563 | 5.561 | 0.002 ( +0.0% ) | 1.11 | 1.11 | +0.0% | 2.407 | 2.559 |
| 2500.225 | 5.583 | 5.580 | 0.002 ( +0.0% ) | 1.01 | 1.02 | -0.2% | 2.409 | 2.409 |
| 2500.226 | 2.980 | 2.978 | 0.002 ( +0.1% ) | 7.58 | 7.62 | -0.4% | 2.304 | 2.289 |
| 2500.227 | 8.972 | 8.972 | 0.000 ( +0.0% ) | 10.25 | 10.24 | +0.1% | 1.396 | 1.383 |
| 2500.231 | 1.404 | 1.407 | -0.004 ( -0.3% ) | 13.77 | 13.73 | +0.3% | 1.938 | 1.939 |
| 2500.232 | 2.251 | 2.248 | 0.003 ( +0.2% ) | 13.52 | 13.65 | -1.0% | 2.004 | 2.010 |
| 2500.233 | 4.684 | 4.681 | 0.003 ( +0.1% ) | 4.92 | 4.88 | +0.8% | 2.040 | 2.018 |
| 2500.234 | 3.340 | 3.336 | 0.003 ( +0.1% ) | 1.49 | 1.53 | -2.5% | 2.054 | 2.061 |
| 2500.235 | 3.350 | 3.347 | 0.003 ( +0.1% ) | 1.41 | 1.41 | -0.4% | 2.080 | 2.087 |
| 2500.236 | 2.099 | 2.096 | 0.003 ( +0.2% ) | 14.05 | 13.92 | +0.9% | 1.998 | 1.998 |
| 2500.237 | 7.977 | 7.977 | 0.000 ( +0.0% ) | 14.62 | 14.59 | +0.2% | 1.435 | 1.431 |
| 2500.241 | 9.405 | 9.405 | 0.000 ( +0.0% ) | 4.08 | 3.96 | +3.1% | 1.761 | 1.762 |
| 2500.242 | 10.331 | 10.331 | 0.000 ( +0.0% ) | 0.91 | 0.91 | +0.3% | 1.646 | 1.685 |
| 2500.243 | 2.712 | 2.712 | 0.000 ( +0.0% ) | 8.45 | 8.44 | +0.2% | 1.060 | 1.062 |
| 2500.244 | 485.976 | 485.976 | 0.000 ( +0.0% ) | 0.58 | 0.57 | +0.3% | 1.628 | 1.596 |
| 2500.245 | 823.224 | 823.224 | 0.000 ( +0.0% ) | 0.76 | 0.76 | +0.1% | 1.606 | 1.581 |
| 2500.901 | 1.749 | 1.749 | 0.000 ( +0.0% ) | 21.37 | 21.41 | -0.2% | 1.756 | 1.799 |
| 2500.902 | 1.598 | 1.598 | 0.000 ( +0.0% ) | 20.51 | 21.62 | -5.1% | 1.762 | 1.740 |
| 2500.911 | 13.931 | 13.931 | 0.000 ( +0.0% ) | 3.00 | 3.16 | -5.0% | 1.079 | 1.075 |
| 2500.912 | 0.240 | 0.199 | 0.041 ( +20.3% ) | 1.15 | 1.06 | +8.0% | 0.965 | 0.966 |
| 2500.913 | 0.110 | 0.110 | 0.000 ( +0.0% ) | 1.18 | 1.14 | +3.4% | 0.970 | 0.975 |

2024-09-04 20:49 UTC, hqucms commented
+1

2024-09-04 20:50 UTC, cmsbuild commented
This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @mandrenguyen, @rappoccio, @sextonkennedy, @antoniovilela (and backports should be raised in the release meeting by the corresponding L2)

2024-09-06 08:34 UTC, merged